### ISSUE TITLE
TypeVector<T>::operator== Documentation is lying

### ISSUE THREAD

**Issue by pbauman** [libMesh/libmesh#1004]
<pre>
/**
   * @returns \p true iff two vectors occupy approximately the same
   * physical location in space, to within an absolute tolerance of \p TOLERANCE.
   */
  bool operator == (const TypeVector<T> & rhs) const;
</pre>

<pre>
bool TypeVector<T>::operator == (const TypeVector<T> & rhs) const
{
#if LIBMESH_DIM == 1
  return (_coords[0] == rhs._coords[0]);
#endif

#if LIBMESH_DIM == 2
  return (_coords[0] == rhs._coords[0] &&
          _coords[1] == rhs._coords[1]);
#endif

#if LIBMESH_DIM == 3
  return (_coords[0] == rhs._coords[0] &&
          _coords[1] == rhs._coords[1] &&
          _coords[2] == rhs._coords[2]);
#endif
}
</pre>

Should we internally call `absolute_fuzzy_equals`? Or change the documentation?

**Comment by roystgnr** [comment]
Definitely change the documentation.
