### ISSUE TITLE
macOS Sierra (beta) issues

### ISSUE THREAD

**Issue by dschwen** [libMesh/libmesh#1024]
I'm builiding libmesh with clang on macOS Sierra. It builds mostly fine. Some observations
- ./include/libmesh/threads_pthread.h:86:18: warning: '`OSSpinLockLock`' is deprecated: first deprecated in OS X 10.12 - Use `os_unfair_lock_lock()` from `<os/lock.h>` instead [-Wdeprecated-declarations]
- ./include/libmesh/threads_pthread.h:87:20: warning: '`OSSpinLockUnlock`' is deprecated: first deprecated in OS X 10.12 - Use `os_unfair_lock_unlock()` from `<os/lock.h>` instead [-Wdeprecated-declarations]

I'll expand on this while I test further.

**Comment by jwpeterson** [comment]
Did you hear there was a Pokemon in the macOS Sierra or something?

**Comment by dschwen** [comment]
![screen shot 2016-07-14 at 9 27 09 am 2](https://cloud.githubusercontent.com/assets/202302/16845476/431950da-49a6-11e6-84db-8f3bbc9d58d5.png)

**Comment by friedmud** [comment]
Fixing those locks is no big deal... but since they're just deprecations this isn't super high priority...

**Comment by jwpeterson** [comment]
The issue above was addressed in c71a4fe27bf9706f22713ced421f0a1ad80ba5ca.
