### ISSUE TITLE
Maybe wrong instructions in install.html

### ISSUE THREAD

**Issue by juan42** [libMesh/libmesh#1027]
I'm not sure, but shouldn't the line at the bottom be

> libmesh-config --cxx -o foo foo.C `libmesh-config --cxxflags --include --ldflags --libs

instead of

> libmesh-config --cxx -o foo foo.C libmesh-config --cxxflags --include --ldflags

(mind the missing ticks because of markdown)

**Comment by jwpeterson** [comment]
Fixed in repo and update the website, thanks!
