### ISSUE TITLE
problem with `allgather_packed_range` at scale

### ISSUE THREAD

**Issue by permcody** [libMesh/libmesh#1039]
I'm having a problem with the `allgather_packed_range` routine in libMesh at scale. The specific line that's failing is here: https://github.com/idaholab/moose/blob/devel/modules/phase_field/src/postprocessors/FeatureFloodCount.C#L272-L273

# What I know:
* The line referenced above is indeed where the failure occurs. I added parallel barriers before and after that line with print statements and verified it's failure at that location. 
* The run is large but not that large. I successfully ran several large 3D runs with around 100 total dofs on several hundred processors without incident. I was working my way up to the size of run I did late last fall since I haven't run a large run with the rewrite of this object. The parallel packed range exchange is among the features added in the rewrite.
* It is currently failing on 576 processors. I `gather`ed the buffer sizes on the root process that was being prepared to be sent and they were all around 150K on all 576 processors.
* I believe the failure is always on the root process

# What I don't know
* I can't figure out what's failing. I get an exit code 9 on MVAPICH on our Falcon cluster every time. I attempted to add additional checks but everything appears OK.
* I can't get the debug problem to run for some reason. It just seems to hang forever on the problem this size. Instead I went into libMesh and turned all of the assertions in the affected "pack" routines into real checks. I also removed the `#ifndef NDEBUG` lines to fire the checks, no problems.

I wish I had more information as to why this fails. If anyone has any ideas, let me know. Otherwise, I'll work on making a toy problem that builds buffers of this size and attempt to run on several hundred processors to replicate on a simpler problem.

**Comment by roystgnr** [comment]
Can you get a devel mode problem to run?  devel adds a ton of O(1) assertions, which can make large problems painful, but dbg actually turns on glibc libstdc++ options which change the asymptotic complexity of some container operations, which can make large problems effectively impossible.

**Comment by friedmud** [comment]
Do you mean your buffer sizes are 150KB or 150,000 entries?

**Comment by friedmud** [comment]
The reason I ask is because `Parallel::pack_range()` has a maximum size that defaults to: `1000000` bytes (1MB) ( https://github.com/libMesh/libmesh/blob/master/include/parallel/parallel.h#L588 ).  150,000 doubles would be over that size (1.2MB).  At that size the buffer would be split into two chunks and two communications would happen.

I'm not sure how much testing there has been of that code path.

I actually am not a fan of this.  This idea goes back to "old lore" that MPI gets inefficient when trying to send message sizes of more than 1-2 MB.  In practice, I haven't seen it on modern hardware (but that doesn't mean it doesn't exist).

When I did my new non-blocking packed range implementation I always send only one buffer (pretty much impossible to do it any other way because of the way non-blocking works).  The blocking version could be made much simpler by doing the same thing.

If you want to investigate if this is indeed the problem you can either go change the default (which I pointed to up there) or you could go just into the `allgather_packed_range()` routine here: ( https://github.com/libMesh/libmesh/blob/master/include/parallel/parallel_implementation.h#L3712 ) and override the default of the `maximum_buffer_size` argument.

You can look at how I do it in the non-blocking version here: https://github.com/libMesh/libmesh/blob/master/include/parallel/parallel_implementation.h#L2401

**Comment by friedmud** [comment]
BTW: I don't see why doing it in two messages would cause an error like this.  It's just the first thing that popped into my head for a buffer of that size...

**Comment by permcody** [comment]
Roy, I ran devel the other day and it worked on the slightly smaller problem (still quite large). I'll run it on this test case to see if it will give me any additional information now that I've narrowed the problem down to this specific line.

Derek, 150K entries (i.e. string.size()). I noticed that max buffer size default as well when I was poking around in `parallel.h`. Even if it goes over, it should still work, but yeah that's something that should probably be explicitly tested if it hasn't already. I'll look at that a bit more carefully too.

**Comment by friedmud** [comment]
After re-reading my comments I think I was overly negative.  Just one of those days (chasing some of my own tails over here!).

Scratch most of what I said - I don't have good data either way.

Just try taking the buffer size out of the way to make sure it's not that...

**Comment by permcody** [comment]
devel mode also fails with no error messages

**Comment by roystgnr** [comment]
Don't feel bad about being negative; just be accurate!

"This is a stupid idea because MPI can handle big message sizes" is a non-sequitur; streaming is not an attempt to work around message size limitations.

"This is a stupid idea because overlapping work with communication is not worth creating a second codepath that is almost impossible to test properly", OTOH, would have been devastating.  It would definitely be a good idea to just crank that buffer size upward and see if it fixes the problem.

**Comment by permcody** [comment]
I cranked up buffer size (10x) and it still failed in the same way - still no assertions (with devel mode).

**Comment by friedmud** [comment]
Well - at least we've eliminated that possibility...

No idea about what could be wrong really...

**Comment by pbauman** [comment]
Does this happen on a stand alone call with some dummy data of the same size, independent of MOOSE/libMesh/whatever? Maybe you're exposing a bug in the MPI stack?

**Comment by permcody** [comment]
Good question Paul, I'll put together a test that attempts to recreate the
problem in a simple libMesh example. If it works with the same number of
processors, data, on the same machine, that'll tell us something.

**Comment by permcody** [comment]
Just made a very small stand-alone test code to exercise this routine and it was able to successfully communicate much larger data sets then I'm currently sending. I tried to mimic my usage as much as possible by randomizing the individual buffer sizes a bit and also using all ascii characters (not just printable types) in the character strings. Everything appeared to work just fine...

I might try doing *n* `gather` operations instead to see if I can get that to work. I really can't see why this is failing.

**Comment by permcody** [comment]
I don't believe there is a problem with the parallel communication. I have now narrowed the crash to the unpack routine called from the all gather routine. It's likely an issue in user code but still may be some failed allocation or other assumption in the unpack code or my code 😦. I'll leave the ticket open a little longer so that when I do figure this out I can status you all.

**Comment by permcody** [comment]
OK, I've convinced myself that I'm simply running out of memory with this problem. I want to record my findings here in case they are useful to anyone else. I was able to successfully run a problem on a mesh with 150^3 elements on 72 nodes of our Falcon cluster using 8 ranks per node (128GB). Last year I was able to run a larger problem which is why I really didn't think I was running out of memory here (180^3). I'll probably need to be a little more careful about cleaning up the temporaries and deleting unneeded objects during the unpacking because this problem "should" be more efficient in terms of memory usage (and CPU usage) than my previous implementation. What's really annoying and troubling is that I am unable to find a way to avoid getting axed by the OOM process on the cluster. I attempted to wrap my memory hogging code in a suitable `try/catch` block but it only gets triggered sometimes. Other times OOM kills my processes before they have an opportunity to handle the exception. I've created a small test problem that people can run if they are interested here:
https://gist.github.com/permcody/99e79a228ac507aeba189f04cfa0d862 

Note the actual output of the program at the top of that gist. Depending on the number of ranks you can get different behavior on the cluster.

I guess I need to come up with a different deserialization method on these buffers to avoid copies or other problems causing me to blow memory. Ideas are appreciated.

**Comment by roystgnr** [comment]
I'm afraid that Linux routinely oversubscribes memory, and last I checked there are technical reasons why you can't just tell it to deny mallocs like it really ought to instead.

Restricting how much memory we allocate at once was actually one of the two motivations for using a limited buffer size in the packed_range code.  You could try cranking down the buffer size (we should probably make that run-time configurable...) and see if it helps you squeak under your RAM limit.

If you're using DistributedMesh then you might also try libMesh from after my last PR, and see if the reduced ghosting saves you a few bytes.

**Comment by roystgnr** [comment]
Oh, but don't bother unless you're using DistributedMesh with mesh refinement; on a one-level grid the old code wasn't doing any overghosting.

**Comment by permcody** [comment]
Thanks for the suggestions. I'm going to start profiling the actual memory usage (very difficult) to see how much I need to squeeze this down. I have several populated data structures that can be cleared before doing the `allgather` and other ways to save bytes. I'll keep you posted.

**Comment by permcody** [comment]
UPDATE: I'm a little embarrassed to report that the problem was actually quite simple. I was right about running out of memory but not in the way that I expected at all. My process was being killed by PBS (not the Unix OOM directly) because I failed to specify that I either required all of the CPUs on the node (which I didn't) or all of the memory on the node. In the past, memory limits have *not* been enforced on our cluster nodes but apparently they are now (with no notification or documentation that this is the case on our HPC help pages!!!). I'm a good citizen, I was using the "scatter:excl" option to make sure that I wouldn't land on a node with another job on it but that didn't matter. PBS was killing my job for taking more than _node_per_proc_ / _nodes_i_requested_ * total_memory.
