### ISSUE TITLE
Nemesis Named Mesh Entities

### ISSUE THREAD

**Issue by friedmud** [libMesh/libmesh#1094]
Named mesh entities (blocks, sidesets, etc.) don't seem to be getting written to Nemesis files...

**Comment by jwpeterson** [comment]
I thought that would be handled already  by Exodus... I'll take a look.

**Comment by friedmud** [comment]
I just double checked: the block names definitely aren't getting written out.

**Comment by jwpeterson** [comment]
We definitely weren't writing the sideset and nodeset names in Nemesis.  The Nemesis IO helper overrides the `write_nodesets()` and `write_sidesets()` functions from the Exodus IO helper, but whenever the Exodus helper functions were updated to write names, the Nemesis helper functions were not.  

I have a branch with a fix for this part, still working on writing the element block names too.
