### ISSUE TITLE
Fix deprecation messages in adaptivity examples

### ISSUE THREAD

**Issue by jwpeterson** [libMesh/libmesh#1095]
Currently all of the examples which do adaptivity print two deprecation warnings:
```
*** Warning, This code is deprecated, and likely to be removed in future library versions!
../src/mesh/mesh_refinement.C, line 880, compiled Sep 14 2016 at 14:24:19 ***
../src/mesh/mesh_refinement.C, line 1225, compiled Sep 14 2016 at 14:24:19 ***
```
which stem from this code in `EquationSystems::reinit()`:
```
// Don't override any user refinement settings
MeshRefinement mesh_refine(_mesh);
mesh_refine.face_level_mismatch_limit() = 0; // unlimited
mesh_refine.overrefined_boundary_limit() = -1; // unlimited
mesh_refine.underrefined_boundary_limit() = -1; // unlimited
```
that changes the value `face_level_mismatch_limit` to 0 instead of its default value of 1.  These lines were added in 5b98cbd0 by @roystgnr to avoid *relaxing* restrictions set by the user, but would it not be better to deprecate the current `EquationSystems::reinit()` interface in favor of one which can be passed a `MeshRefinement` object for internal use?  

If that's not a good idea, then I'd like to come up with some other way to avoid all of our adaptivity examples throwing deprecation warnings...

**Comment by roystgnr** [comment]
Those warnings aren't consequences of anything in EquationSystems; they stem from internal calls in MeshRefinement.  What we ought to be doing is fixing the ~8 internal calls to make_foo_compatible(_internal_limit_we_will_use_anyway) which are confusing those if tests into thinking someone's still on the old API.  I'll take a crack at it now.
