### ISSUE TITLE
Keep mesh elements on refinement

### ISSUE THREAD

**Issue by neosimsim** [libMesh/libmesh#1104]
Is there a way to refine a mesh keeping current mesh elements? I tried

``` cpp
libMesh::MeshRefinement mesh_refinement(*mesh);
mesh_refinement.uniformly_refine();
```

but this seems to throw away nodes.

Thank you very much.

**Comment by roystgnr** [comment]
If you have a Node which isn't attached to any Elem then it's at risk of being thrown away any time you sneeze; create a NodeElem object if you have a Node that really shouldn't be attached to anything else.

If you have a Node which is attached to an Elem then it shouldn't be thrown away upon refinement.  (At least not with any Elem type I can think of...)  If you're using a DistributedMesh then a Node or Elem may move to a different processor and be deleted on its previous processor, but it'll still exist in the abstract sense.

Even on a ReplicatedMesh a Node or Elem may be renumbered, though, so if you need to refer to the same node post refinement then you'll need to keep a pointer to it or search for its unique_id.

If you have a Node or Elem actually being removed by uniform refinement then that sounds like a bug; I'd appreciate a test code reproducing it.

**Comment by jwpeterson** [comment]
Closing as this is more of a mailing list question than a specific issue to be addressed... also Roy did a pretty good job of answering it.
