### ISSUE TITLE
Add const_casts to new "scatter" implementations in parallel_implementation.h

### ISSUE THREAD

**Issue by permcody** [libMesh/libmesh#1118]
We need a few const casts around the raw buffers to support MPI-1 standards which apparently is still in use on the version of OpenMPI that you receive with Ubuntu.

**Comment by friedmud** [comment]
Really?  With a current version of Ubuntu?

That seems HIGHLY unlikely...

**Comment by permcody** [comment]
Yeah, He's using OpenMPI 1.6.5 which should be version 2.0 compliant
(Thanks OpenMPI guys for the confusing numbering scheme). I'm not entirely
sure what's going on and I don't have his exact environment but take a look
at those errors.

**Comment by dschwen** [comment]
@friedmud see here: https://launchpad.net/ubuntu/+source/openmpi
1.6.5 was shipped with Ubuntu versions as recent as Wily (15.10).

**Comment by friedmud** [comment]
I was doubting that it was shipping with "MPI-1"... which it is not.

OpenMPI 1.6.5 is compliant with MPI-2.

MPI-2 was published in the late 90s. There is no way that any modern Ubuntu
shipped with an MPI that only supported MPI-1!!

**Comment by dschwen** [comment]
Ugh, ok, now I feel dumb.

**Comment by permcody** [comment]
Right, but then this doesn't explain why we need the const casts then.

**Comment by roystgnr** [comment]
OpenMPI 1.6.5 "should be" 2.0 compliant, maybe, but that doesn't mean it is.  From mpi.h.in, line 1374:

```C
OMPI_DECLSPEC  int MPI_Scatter(void *sendbuf, int sendcount, MPI_Datatype sendtype,
                               void *recvbuf, int recvcount, MPI_Datatype recvtype,
                               int root, MPI_Comm comm);
```

Nothing else is properly const'ed either.  Maybe they added the MPI 2.0 Fortran functions and C hooks to them but hadn't yet fixed up the C API correctness?

**Comment by jwpeterson** [comment]
Ugh, this means that you can't do a simple `MPI_VERSION` check either.  Is this worth writing configure tests for all the functions that we use and are affected by the const issue?

**Comment by roystgnr** [comment]
They do ```#define MPI_VERSION 2``` but that doesn't mean they're telling the truth...

That does mean we might have subsequent problems even after the const_casts, though; we've got a few places where we just test MPI_VERSION to pick a code path, and if there are significant MPI implementations that claim to be MPI 2 but are not actually correct MPI 2 then we might need to be more paranoid.

**Comment by roystgnr** [comment]
We should just put the const_casts in place, IMHO; having an inelegant code path is nasty but having two code paths for every effected function would be even worse IMHO.  It's annoying enough to have to remember the !LIBMESH_HAVE_MPI code path every time we add a new parallel.h function.

**Comment by friedmud** [comment]
Another option is simply to not support OpenMPI 1.6.5.  Just throw a configure error.

BTW: I believe this is just an implementation bug.  OpenMPI 1.6.5 was definitely MPI-2.  OpenMPI was using MPI-2 since OpenMPI 1.2:

https://www.open-mpi.org/doc/v1.6/man3/MPI.3.php

> The outcome, known as the MPI Standard, was first published in 1993; its most recent version (MPI-2) was published in July 1997. Open MPI 1.2 includes all MPI 1.2-compliant and MPI 2-compliant routines.

So: it's just a plain old bug.  We either try to work around it... or just throw an error.  The 1.6 branch is officially retired now... although it did receive it's last patch just this last July...

**Comment by roystgnr** [comment]
If the MPI_VERSION>2 code paths aren't supported by 1.6.5 then I'm not interested in fixing that.

But the const_cast is needed to support any systems that actually are still on MPI-1, so we ought to add them anyway; if that is also sufficient to support MPI-2-but-not-really systems then that's a free bonus.

**Comment by friedmud** [comment]
I guess that's kind of my question.  Do we really care about supporting
MPI-1?  MPI-2 has been the standard now for _20_ years!  Surely it won't be
a problem to drop support for MPI-1...

**Comment by roystgnr** [comment]
That's what I'd have hoped, too, but here we are, with a popular operating system distribution less than a year old, triggering a bug in a not-fully-MPI-2-compliant stack.  If we didn't already have 99% of the MPI-1 support in place I'd happily say "here's a nickel, kid, go get yourself a real OS", but we're just talking about adding a couple more casts to get that last 1% of our support fixed.  I'll put up the PR myself this week if @permcody doesn't beat me to it; writing the patch would have taken less time than I've already spent talking about the patch.  :-D

**Comment by friedmud** [comment]
Agree: definitely not worth the time we've spent on it... but I always like
a good deprecation discussion :-)
