### ISSUE TITLE
Add transpose nullspace interface in petsc_nonlinear_solver

### ISSUE THREAD

**Issue by snschune** [libMesh/libmesh#1121]
@fdkong 

To ensure that `A x = b` has a solution the nullspace of A^T must be removed from `b`.
PETSc does that here

http://www.mcs.anl.gov/petsc/petsc-current/src/ksp/ksp/interface/itfunc.c.html#KSPSolve

lines 644 and following but libmesh does not have an interface so far.

**Comment by jwpeterson** [comment]
The code that you linked to is in `KSPSolve`, but you are wanting to do this for the `PetscNonlinearSolver`, i.e. `SNES`.  Any idea how it should be done for that?

**Comment by snschune** [comment]
Hmmm, I am not sure. My thought process ended with handing over the transpose nullspace tp PETSc
similar to `build_mat_null_space` and then in `PetscNonlinearSolver<T>::solve` call 
`MatSetTransposeNullSpace`. I was under the assumption that PETSc does the right thing 
with it.

**Comment by jwpeterson** [comment]
I think you are right, @fdkong just pointed out where we already have this interface for "regular" and "near" null spaces.  It would be good to have a test that uses the new feature (test could be in MOOSE or libmesh, I don't care) to aid in development, do you have anything simple in mind?

**Comment by snschune** [comment]
there is a test here 

idaholab/moose#7790

the first test ensures that b has not A^T contrib, while the second adds it and currently fails to converge.

**Comment by jwpeterson** [comment]
> there is a test here
> 
> idaholab/moose#7790

This looks like it's ready to be merged?  Are you waiting for anything else on that PR?

**Comment by fdkong** [comment]
> there is a test here
> 
>     idaholab/moose#7790
> 
> This looks like it's ready to be merged? Are you waiting for anything else on that PR?

The second example needs to pass a transpose null space to make it correct, and it now does not converge. 
Need to add a new interface in libmesh to support MatSetTransposeNullSpace.

**Comment by snschune** [comment]
@fdkong let's wait with the MOOSE PR idaholab/moose#7790. I'll make the b with transpose nullspace an example that will show that stuff coming here soon works.

**Comment by jwpeterson** [comment]
Closing because this was completed.
