### ISSUE TITLE
Add initial guess for eigenproblems

### ISSUE THREAD

**Issue by juan42** [libMesh/libmesh#1130]
As discussed on the libmesh-users mailinglist, there is a demand for setting the initial guess in the EigenSystem / EigenSolver interface. This has to be done via a SLEPc call to EPSSetInitialSpace.

My questions for the enhancement are:

- Should the option be available in EigenSystem or EigenSolver interface? I don't use the EigenSystem class at all, because i have no use for _just_ solving an eigenproblem.

- Should the option, if set, assume that the last solution is always the next initial space for further solves? (Could be irritating, but beneficial if explicitly documented)

**Comment by jwpeterson** [comment]
> Should the option be available in EigenSystem or EigenSolver interface? I don't use the EigenSystem class at all, because i have no use for just solving an eigenproblem.

I think it would make more sense on the `EigenSystem`.  The `System` base class already provides the following API for setting initial conditions that should probably be used for this as well:
```
  /**
   * Register a user function to use in initializing the system.
   */
  void attach_init_function (void fptr(EquationSystems & es,
                                       const std::string & name));

  /**
   * Register a user class to use to initialize the system.
   * Note this is exclusive with the \p attach_init_function.
   */
  void attach_init_object (Initialization & init);
```

If you are currently just using `EigenSolver` objects directly, it shouldn't be too hard to use it from within an `EigenSystem` object, which also gives you convenient access to things like the `Mesh`, variables, vector projection APIs, etc.



> Should the option, if set, assume that the last solution is always the next initial space for further solves? (Could be irritating, but beneficial if explicitly documented)

We do this for time-dependent problems (the solution from the previous timestep is the initial guess for the current timestep) so there is certainly precedent for it.  I'd say go ahead unless you think there is genuine potential for confusion/bad results.

**Comment by roystgnr** [comment]
If we were designing from scratch, I'd say it was a mistake to use system.solution for eigenfunctions in the first place.  Eigensolves of nonlinear systems are a very useful thing, and you don't want to overwrite the current state of the system just to examine an eigenfunction.

It's too late to change that decision now, but I wonder if using the initial solution as an eigensolve initial guess would make things worse.  0 is a pretty decent initial guess, and the nonlinear system's solution may not be, so this would be a potential regression for some users.

I don't there's one correct answer here, but my vote would be to put the option into EigenSolver.
