### ISSUE TITLE
optional filename argument to --redirect-stdout

### ISSUE THREAD

**Issue by permcody** [libMesh/libmesh#1159]
In an attempt to make MOOSE RunException testing more robust, we need the ability to write output from a parallel run that cannot be interleaved. To accomplish this, we plan to use the `--redirect-stdout` flag when running these types of test through the TestHarness. We'll concatenate the resulting files written to the filesystem scanning for our error message. 

In order to do this efficiently though, we need the ability to control the names of these files so that we can run multiple instances of test programs in the same directory at the same time without them stomping on each other.

Tag @jwpeterson, @milljm

**Comment by jwpeterson** [comment]
While we're at it, it would probably be good to deprecate the `--redirect-stdout` flag, since it actually redirects both stdout and stderr now.  We could add a new flag
```
--redirect-output filebase
```
that takes an optional argument for specifying the base filename to which libmesh would append the processor id when writing.

**Comment by jwpeterson** [comment]
Added in #1163.
