### ISSUE TITLE
Connection of finite and infinite element region

### ISSUE THREAD

**Issue by BalticPinguin** [libMesh/libmesh#1197]
Hi,
I have a quite unspecific error, but I have the impression that it still might be related to some error or unconsistency in libmesh:
I try to compute some Coulomb functions (mainly some spherical oscillations which may have a few angular nodes)
In the figures below, the finite elements are in a spherical region (exactly there, where the cuts are) where the box size and order of the radial polynomial in infinite region are varied.
The figures are obtained from computing the solution on a uniform grid for each point as
```
    Point map_point=FEInterface::inverse_map(3, fe_type, elem, q_point, TOLERANCE, true);
    FEComputeData data(es, map_point);
    FEInterface::compute_data(3, fe_type, elem, data);

     unsigned int n_sf= cfe->n_shape_functions();
     for (unsigned int i=0; i<n_sf; i++){-                         
              soln+=(*solution_vect)(dof_indices[i])*data.shape[i];  
      }
```

Here the interface shows strong irregularity
![snapshot](https://cloud.githubusercontent.com/assets/2708704/21401972/b5b768aa-c7b6-11e6-8990-be0d42530ebc.png)

Besides the the fact that the solution is almost 0 in the finite region, the oscillations in the infinite part (which are also present in the absolute value, so its not a change in phase) are far too stiff: The edge is 8 units and the wavelength should be ~6 units...
![re0](https://cloud.githubusercontent.com/assets/2708704/21401919/6bdbf4e4-c7b6-11e6-9b8f-53992728855b.png)

So long explanation, now my real question: Could it be that the DOFs of finite and infinite region are more or less independent? 
Do you have some other idea what to check?
Thank you very much,
Hubert

**Comment by BalticPinguin** [comment]
Ok, after some more investigation, this behaviour shows up only in a certain region for parameters so it doesn't seem to be a bug in libmesh, probably.
I'll close this issue respectively.

**Comment by jwpeterson** [comment]
OK, sorry we could not be more helpful...
