### ISSUE TITLE
HDF5 >1.8.12 support for bundled netCDF library

### ISSUE THREAD

**Issue by barnabecsek** [libMesh/libmesh#1199]
Hello,

I was wondering whether it would be possible to update the netcdf version that comes with libmesh. For HDF5 libraries newer than 1.8.12 the function 'H5Pset_fapl_mpiposix' has been removed and consequently I get a linker error. I know this issue has been resolved in newer netcdf libraries:

https://github.com/Unidata/netcdf-c/commit/435d8a03ed28bb5ad63aff12cbc6ab91531b6bc8

I am working on a project that uses libmesh and unfortunately I do not have access to older HDF5 libraries than 1.8.16 on the system that I am using.
Thank you,

Barna

**Comment by jwpeterson** [comment]
We are definitely planning to do this.  Just hasn't been a high priority since not many of us use hdf5, and i'm not really sure exactly how to do the netcdf upgrade since I have not done one before.

**Comment by jwpeterson** [comment]
This should be fixed as of #1326.
