### ISSUE TITLE
Fix path search for inline Trilinos build support

### ISSUE THREAD

**Issue by rppawlo** [libMesh/libmesh#1201]
The CASL project builds libmesh inline with Trilinos. This means that we don't install a Trilinos build prior to configuring libmesh. Recent changes to libmesh have broken the detection process for ifpack, epetra and epetraext during casl builds. An extra search path needs to be added to the trilinos.m4 to allow for casl builds. Will submit a pull request with the changes shortly.

**Comment by jwpeterson** [comment]
Hmm.. I recently also added a test for the `Epetra_CombineMode.h` header file.  If the `Ifpack_config.h` test is not working for you, this one probably is not either...

**Comment by rppawlo** [comment]
yes. had to change that slightly. epetra, ifpack and epetraext stopped working in casl builds. pull request #1202 fixes this for us. I did change the file checked in epetra to one that is pregenerated in the build directory tree as opposed to the source directory tree. For installed trilinos all files are in the same place but before installation, the generated headers and source headers are in separate locations. Hope this is ok.

**Comment by jwpeterson** [comment]
Fixed by #1202.
