### ISSUE TITLE
Can I compute Stiffness Matrix for Solid Elements using this package ? Is the source code available ?

### ISSUE THREAD

**Issue by Karthi1626** [libMesh/libmesh#1253]

**Comment by pbauman** [comment]
It certainly is possible to solve finite element formulations for solid
mechanics, many do. libMesh provides the infrastructure, but not
"physics-specific" kernels. Packages based on libMesh such as GRINS (
http://grinsfem.github.io) and MOOSE (http://mooseframework.org) provide
more "turn-key" solutions.

**Comment by jwpeterson** [comment]
Closing because this isn't an issue, if you have general questions please mail the mailing list, 
libmesh-users@lists.sourceforge.net.
