### ISSUE TITLE
Regression in ExactSolution?

### ISSUE THREAD

**Issue by dknez** [libMesh/libmesh#1273]
After updating to the HEAD I'm now getting NaNs from ExactSolution::l2_error. I'll look into this further... if anyone has any suggestions about what commit may have caused this, please let me know.

**Comment by jwpeterson** [comment]
No idea...  what test are you running? I wonder if we could get you guys up and running with CIVET.  That way we can at least know when your stuff breaks, the tests themselves can remain internal.

**Comment by dknez** [comment]
I'm using attach_reference_solution, which means that this is using a MeshFunction. As a result, I suspect this issue is related to the PointLocator/bounding box changes. I'll keep investigating.

Re CIVET: That sounds good. I don't have time to look into that right now, but it'd be a good thing to do, for sure.

**Comment by jwpeterson** [comment]
> As a result, I suspect this issue is related to the PointLocator/bounding box changes

That's a good bet.  @roystgnr hinted to me that he found some further issues with the new loose_bounding_box stuff, but I don't know the details.

**Comment by dknez** [comment]
The error is indeed due to the MeshFunction not finding an element. This is most likely caused by a bug in Cell::loose_bounding_box () (Roy and I discussed this bug too; we need to create the union of the bounding boxes in that function which is not what it does currently).

**Comment by roystgnr** [comment]
Try it with https://github.com/libMesh/libmesh/pull/1275 and see if that fixes it for you?

Sorry about the hassle.

**Comment by roystgnr** [comment]
Sorry, not 1275, I mean #1274

**Comment by dknez** [comment]
#1274 fixes this issue for me, thanks! Please merge when ready.

**Comment by jwpeterson** [comment]
#1274 is merged.
