### ISSUE TITLE
Lock error in PetscDiffSolver

### ISSUE THREAD

**Issue by canesin** [libMesh/libmesh#1294]
When changing the solver on the fem_system_ex1 from DiffSolver to a PetscDiffSolver there is a problem with a lock on PETSc vec.

The error is copied bellow and attached is the diff from master code and modified.

0]PETSC ERROR: --------------------- Error Message --------------------------------------------------------------
[0]PETSC ERROR: Object is in wrong state
[0]PETSC ERROR:  Vec is locked read only, argument # 1
[0]PETSC ERROR: See http://www.mcs.anl.gov/petsc/documentation/faq.html for trouble shooting.
[0]PETSC ERROR: Petsc Release Version 3.7.5, Jan, 01, 2017 
[0]PETSC ERROR: ./test on a linux-gnu-dbg named office by fcanesin Fri Mar 31 02:03:41 2017
[0]PETSC ERROR: Configure options PETSC_ARCH=linux-gnu-dbg --with-cc=clang --with-cxx=clang++ --with-fc=0 --prefix=/home/fcanesin/libs/petsc --download-metis --download-parmetis --download-openmpi --download-f2cblaslapack --with-debugging=1
[0]PETSC ERROR: #1 VecGetArray() line 1647 in /home/fcanesin/libs/petsc-clang/src/vec/vec/interface/rvector.c
[0]PETSC ERROR: #2 VecSetValues_MPI() line 876 in /home/fcanesin/libs/petsc-clang/src/vec/vec/impls/mpi/pdvec.c
[0]PETSC ERROR: #3 VecSetValues() line 892 in /home/fcanesin/libs/petsc-clang/src/vec/vec/interface/rvector.c

Example with diff:
[fem_system_ex1.zip](https://github.com/libMesh/libmesh/files/892091/fem_system_ex1.zip)

**Comment by jwpeterson** [comment]
On Mon, Apr 3, 2017 at 11:11 PM, Fabio C. Canesin <notifications@github.com>
wrote:

> When changing the solver on the fem_system_ex1 from DiffSolver to a
> PetscDiffSolver there is a problem with a lock on PETSc vec.
>
> The error is copied bellow and attached is the diff from master code and
> modified.
>
> 0]PETSC ERROR: --------------------- Error Message
> --------------------------------------------------------------
> [0]PETSC ERROR: Object is in wrong state
> [0]PETSC ERROR: Vec is locked read only, argument # 1
> [0]PETSC ERROR: See http://www.mcs.anl.gov/petsc/documentation/faq.html
> for trouble shooting.
> [0]PETSC ERROR: Petsc Release Version 3.7.5, Jan, 01, 2017
> [0]PETSC ERROR: ./test on a linux-gnu-dbg named office by fcanesin Fri Mar
> 31 02:03:41 2017
> [0]PETSC ERROR: Configure options PETSC_ARCH=linux-gnu-dbg --with-cc=clang
> --with-cxx=clang++ --with-fc=0 --prefix=/home/fcanesin/libs/petsc
> --download-metis --download-parmetis --download-openmpi
> --download-f2cblaslapack --with-debugging=1
> [0]PETSC ERROR: #1 <https://github.com/libMesh/libmesh/issues/1>
> VecGetArray() line 1647 in /home/fcanesin/libs/petsc-
> clang/src/vec/vec/interface/rvector.c
> [0]PETSC ERROR: #2 <https://github.com/libMesh/libmesh/issues/2>
> VecSetValues_MPI() line 876 in /home/fcanesin/libs/petsc-
> clang/src/vec/vec/impls/mpi/pdvec.c
> [0]PETSC ERROR: #3 <https://github.com/libMesh/libmesh/issues/3>
> VecSetValues() line 892 in /home/fcanesin/libs/petsc-
> clang/src/vec/vec/interface/rvector.c
>
> Example with diff:
> fem_system_ex1.zip
> <https://github.com/libMesh/libmesh/files/892091/fem_system_ex1.zip>
>

Hmm... I think I fixed this issue for the PetscNonlinearSolver back in
45241afe (2015 time frame). A similar fix probably needs to be done
for PetscDiffSolver.

The problem is that the solution vector is locked read only by PETSc during
the nonlinear solve, so we can't directly modify it by calling
enforce_constraints_exactly() in the middle of the residual computation
callback.

The fix I did at the time was to impose the constraints
on sys.current_local_solution instead, and finally impose them on the
parallel solution vector after the solve is done.  The same thing could
probably be done for PetscDiffSolver.

-- 
John

**Comment by canesin** [comment]
@jwpeterson I saw that in the PR history, I tried something similar before submitting the issue (and posted in the users mail list)... The problem is that the traceout just warns that the error was on the petsc_diff_solver solve method, not where the last lock was requested - making debugging a little harder. I will give a second try this afternoon and update this.
