### ISSUE TITLE
Memory leak detected when there appears to be no leak?

### ISSUE THREAD

**Issue by dknez** [libMesh/libmesh#1316]
I ran a job which printed the reference count info below. As you can see, it reports a memory leak, but all the Creation/Destruction counts match up. I added a print statement
```
std::cout << "n_objects: " << ReferenceCounter::n_objects() << std::endl;
```
and that printed 4294967264, as you can see below.

```
 ---------------------------------------------------------------------------- 
| Reference count information                                                |
 ---------------------------------------------------------------------------- 
| 14RBRefComponent reference count information:
|  Creations:    2
|  Destructions: 2
| 20RBComponentDofObject reference count information:
|  Creations:    3
|  Destructions: 3
| 23RBComponentConnectivity reference count information:
|  Creations:    1
|  Destructions: 1
| N7libMesh10FEAbstractE reference count information:
|  Creations:    290
|  Destructions: 290
| N7libMesh10Parameters5ValueE reference count information:
|  Creations:    2
|  Destructions: 2
| N7libMesh12LinearSolverIdEE reference count information:
|  Creations:    1
|  Destructions: 1
| N7libMesh12SparseMatrixIdEE reference count information:
|  Creations:    2
|  Destructions: 2
| N7libMesh13NumericVectorIdEE reference count information:
|  Creations:    8
|  Destructions: 8
| N7libMesh15EquationSystemsE reference count information:
|  Creations:    1
|  Destructions: 1
| N7libMesh15GhostingFunctorE reference count information:
|  Creations:    5
|  Destructions: 5
| N7libMesh19SolverConfigurationE reference count information:
|  Creations:    1
|  Destructions: 1
| N7libMesh4ElemE reference count information:
|  Creations:    6932
|  Destructions: 6932
| N7libMesh4NodeE reference count information:
|  Creations:    1587
|  Destructions: 1587
| N7libMesh5QBaseE reference count information:
|  Creations:    279
|  Destructions: 279
| N7libMesh6DofMapE reference count information:
|  Creations:    1
|  Destructions: 1
| N7libMesh6SystemE reference count information:
|  Creations:    1
|  Destructions: 1
| N7libMesh9DofObjectE reference count information:
|  Creations:    8519
|  Destructions: 8519
 ---------------------------------------------------------------------------- 
n_objects: 4294967264
Memory leak detected!
```

**Comment by permcody** [comment]
Well that's some sort of overflow. That number is unsigned max!

**Comment by jwpeterson** [comment]
Is this really the correct way to initialize the static member `_n_objects`? 
```
Threads::atomic<unsigned int> ReferenceCounter::_n_objects;
```
Seems like it should have an `= 0` or something...

**Comment by jwpeterson** [comment]
Actually it looks like the Threads::atomic<T> type should be correctly zero-initialized, except for possibly the TBB implementation?

```
template <typename T>
class atomic : public tbb::atomic<T> {};
```

What do you have in your libmesh_config.h file for the various thread-related defines (`USING_THREADS`, `HAVE_PTHREAD`, `HAVE_TBB_API`, `HAVE_OPENMP`, etc...)?

**Comment by dknez** [comment]
I checked my libmesh_config.h and I have the entries below:

```
/* Define if you have POSIX threads libraries and header files. */
#ifndef LIBMESH_HAVE_PTHREAD
#define LIBMESH_HAVE_PTHREAD 1
#endif

/* Define if OpenMP is enabled */
#ifndef LIBMESH_HAVE_OPENMP
#define LIBMESH_HAVE_OPENMP 1
#endif
```

I use --enable-everything when I configure, which I guess is why I have these enabled.

**Comment by jwpeterson** [comment]
OK, thanks for the info. Since you are using the pthreads threading model, `Threads::atomic<T>` is just our hand-rolled, mutex-guarded atomic class. It should definitely be zero-initialized. But I bet the entire point is moot because you are not using threads anyway...

Have you tried printing `ReferenceCounter::n_objects()` at various times during the simulation? Is it always wrong?

**Comment by dknez** [comment]
I printed that value out in each call to increment_constructor_count and increment_destructor_count. The count looks fine intiially, and it gets up to over 6000. I've pasted the last part of the count printing below. It looks like it gets decremented past zero into negative values, and we then see the result of casting small negative numbers to unsigned ints.

```
ReferenceCounter::n_objects() = 53
ReferenceCounter::n_objects() = 52
ReferenceCounter::n_objects() = 51
ReferenceCounter::n_objects() = 50
ReferenceCounter::n_objects() = 49
ReferenceCounter::n_objects() = 48
ReferenceCounter::n_objects() = 47
ReferenceCounter::n_objects() = 46
ReferenceCounter::n_objects() = 45
ReferenceCounter::n_objects() = 44
ReferenceCounter::n_objects() = 43
ReferenceCounter::n_objects() = 42
ReferenceCounter::n_objects() = 41
ReferenceCounter::n_objects() = 40
ReferenceCounter::n_objects() = 39
ReferenceCounter::n_objects() = 38
ReferenceCounter::n_objects() = 37
ReferenceCounter::n_objects() = 36
ReferenceCounter::n_objects() = 35
ReferenceCounter::n_objects() = 34
ReferenceCounter::n_objects() = 33
ReferenceCounter::n_objects() = 32
ReferenceCounter::n_objects() = 31
ReferenceCounter::n_objects() = 30
ReferenceCounter::n_objects() = 29
ReferenceCounter::n_objects() = 28
ReferenceCounter::n_objects() = 27
ReferenceCounter::n_objects() = 26
ReferenceCounter::n_objects() = 25
ReferenceCounter::n_objects() = 24
ReferenceCounter::n_objects() = 23
ReferenceCounter::n_objects() = 22
ReferenceCounter::n_objects() = 21
ReferenceCounter::n_objects() = 20
ReferenceCounter::n_objects() = 19
ReferenceCounter::n_objects() = 18
ReferenceCounter::n_objects() = 17
ReferenceCounter::n_objects() = 16
ReferenceCounter::n_objects() = 15
ReferenceCounter::n_objects() = 14
ReferenceCounter::n_objects() = 13
ReferenceCounter::n_objects() = 12
ReferenceCounter::n_objects() = 11
ReferenceCounter::n_objects() = 10
ReferenceCounter::n_objects() = 9
ReferenceCounter::n_objects() = 8
ReferenceCounter::n_objects() = 7
ReferenceCounter::n_objects() = 6
ReferenceCounter::n_objects() = 5
ReferenceCounter::n_objects() = 4
ReferenceCounter::n_objects() = 3
ReferenceCounter::n_objects() = 2
ReferenceCounter::n_objects() = 1
ReferenceCounter::n_objects() = 0
ReferenceCounter::n_objects() = 4294967295
ReferenceCounter::n_objects() = 4294967294
ReferenceCounter::n_objects() = 4294967293
ReferenceCounter::n_objects() = 4294967292
ReferenceCounter::n_objects() = 4294967291
ReferenceCounter::n_objects() = 4294967290
ReferenceCounter::n_objects() = 4294967289
ReferenceCounter::n_objects() = 4294967288
ReferenceCounter::n_objects() = 4294967287
ReferenceCounter::n_objects() = 4294967286
ReferenceCounter::n_objects() = 4294967285
ReferenceCounter::n_objects() = 4294967284
ReferenceCounter::n_objects() = 4294967283
ReferenceCounter::n_objects() = 4294967282
ReferenceCounter::n_objects() = 4294967281
ReferenceCounter::n_objects() = 4294967280
ReferenceCounter::n_objects() = 4294967279
ReferenceCounter::n_objects() = 4294967278
ReferenceCounter::n_objects() = 4294967277
ReferenceCounter::n_objects() = 4294967276
ReferenceCounter::n_objects() = 4294967275
ReferenceCounter::n_objects() = 4294967274
ReferenceCounter::n_objects() = 4294967273
ReferenceCounter::n_objects() = 4294967272
ReferenceCounter::n_objects() = 4294967271
ReferenceCounter::n_objects() = 4294967270
ReferenceCounter::n_objects() = 4294967269
ReferenceCounter::n_objects() = 4294967268
ReferenceCounter::n_objects() = 4294967267
ReferenceCounter::n_objects() = 4294967266
ReferenceCounter::n_objects() = 4294967265

 ---------------------------------------------------------------------------- 
| Reference count information                                                |
 ---------------------------------------------------------------------------- 
| 14RBRefComponent reference count information:
```

**Comment by jwpeterson** [comment]
And yet somehow, the information in the `_counts` container is still correct... I'll see if I can reproduce this when I get a second. Can you reproduce this with one of the normal libmesh examples, or is it only happening for your app code?


One thing I've wondered about in the past is whether the `ReferenceCountedObject` always works correctly for multiply-inherited class like [Elem](http://libmesh.github.io/doxygen/classlibMesh_1_1Elem.html). Technically this produces a diamond inheritance pattern, but it never seemed to be an issue before so I never really followed up to investigate it further...

**Comment by dknez** [comment]
I haven't been able to reproduce this in the normal libmesh examples (I didn't run all of them yet though...). It only happens in one of my app codes. Note that the app code uses "reference_elem", so I was wondering if that may be the cause of the issue, since IIRC those use singleton classes. Just a thought.

Let me know if there's anything I can help with in your testing.

**Comment by jwpeterson** [comment]
I added your same print statements and unsurprisingly for all the libmesh examples it prints what you would expect at the end of the simulation:
```
ReferenceCounter::n_objects() = 13
ReferenceCounter::n_objects() = 12
ReferenceCounter::n_objects() = 11
ReferenceCounter::n_objects() = 10
ReferenceCounter::n_objects() = 9
ReferenceCounter::n_objects() = 8
ReferenceCounter::n_objects() = 7
ReferenceCounter::n_objects() = 6
ReferenceCounter::n_objects() = 5
ReferenceCounter::n_objects() = 4
ReferenceCounter::n_objects() = 3
ReferenceCounter::n_objects() = 2
ReferenceCounter::n_objects() = 1
```
I don't think I have any example code that uses the `ReferenceElem::get()` stuff. If it would be possible for you to write a simplified app that calls this in a similar way as your real app that might help us narrow down the problem. 

Are you by any chance on a new or recently-upgraded machine, or maybe on a cluster somewhere and this is just a bad build?

**Comment by dknez** [comment]
I believe I found the issue. I had a function that took a QGauss as a pass-by-value argument, and calling that apparently caused the "negative" ref count. Switching it to pass-by-reference fixes the issue.

So my guess is that we do not increment the ref counter when the copy constructor is called.

**Comment by jwpeterson** [comment]
It looks like you're right. BTW, this can be verified with the simple test code below:
```
#include "libmesh/quadrature_gauss.h"

using namespace libMesh;

// Run this example in dbg mode with reference counting enabled to
// ensure that the number of QGauss creations match the number of
// deletions.
int main (int argc, char ** argv)
{
  LibMeshInit init(argc, argv);

  QGauss qgauss(/*dim=*/3, /*order=*/THIRD);

  // The more copies we make, the further off the refcount gets.
  for (unsigned i=0; i<10; ++i)
    QGauss qgauss_copy(qgauss);

  return 0;
}
```

**Comment by jwpeterson** [comment]
I think the issue is that the other class, `ReferenceCounter` does not have a copy constructor that increments `_n_objects`. This would explain why some of the counts are correct but `_n_objects` is wrong.

I'm trying a fix now... nice bug find by the way. That one must be about 15+ years old by now...

**Comment by dknez** [comment]
Award for finding the oldest bug! :1st_place_medal:

**Comment by jwpeterson** [comment]
> Award for finding the oldest bug!

Definitely. It's there in the oldest surviving revision of the class:
```
git show 8e96ad9:trunk/libmesh/include/reference_counter.h
```
Commit 8e96ad9 is from Jan, 2003 but it definitely existed before that in a local CVS repo.

**Comment by dknez** [comment]
I tested this with @jwpeterson's PR, and that fixes this for me. Thanks John!
