### ISSUE TITLE
Eigenmodes are incorrect when we have hanging nodes

### ISSUE THREAD

**Issue by dknez** [libMesh/libmesh#1327]
I was curious if we can use mesh refinement with the eigensolver, so I added the following code into eigenproblems_ex1.C in order to introduce some hanging nodes:

```
  {
    MeshBase::element_iterator       el     = mesh.active_local_elements_begin();
    const MeshBase::element_iterator end_el = mesh.active_local_elements_end();

    for ( ; el != end_el; ++el)
      {
        Elem * elem = *el;

        if(elem->centroid()(0) < 0.)
        {
          elem->set_refinement_flag(Elem::REFINE);
        }
      }
  }

  MeshRefinement mesh_refinement(mesh);
  mesh_refinement.refine_and_coarsen_elements();
```

This gives incorrect results, presumably due to how we handle dof constraints on hanging nodes.

**Comment by dknez** [comment]
I think eigenproblems_ex3 is actually a better test case for this. If you introduce hanging nodes (e.g. using the same sort of code as above) you'll see that the eigenmode is forced to zero on those hanging nodes. This also means that our eigenvalues are incorrect (as can be verified by comparing to the reference eigenvalues in eigenproblems_ex3.C).

**Comment by dknez** [comment]
Ah, I realized that we do not call "constrain_element_matrix" in these examples. Adding

```
      dof_map.constrain_element_matrix (Ke, dof_indices);
      dof_map.constrain_element_matrix (Me, dof_indices);
```
in eigenproblems_ex3 fixes it.

**Comment by jwpeterson** [comment]
Would you mind adding the constrain calls to this example? It shouldn't have any effect in the non-refined case and would help someone avoid the same issue in the future...

**Comment by dknez** [comment]
Good idea. See #1328.
