### ISSUE TITLE
Would like erf function in contrib/fparser

### ISSUE THREAD

**Issue by lindsayad** [libMesh/libmesh#1333]
Going to try implementing this myself...

**Comment by jwpeterson** [comment]
I will generalize the existing `LIBMESH_TEST_CXX11_INVERSE_HYPERBOLIC_FUNCS` configure test in cxx11.m4 to test for `std::erf`. You can just assume that `std::erf` is available while you are doing the Fparser development.

**Comment by pbauman** [comment]
Thanks @jwpeterson you read my mind.

**Comment by lindsayad** [comment]
Great. Thanks!

**Comment by lindsayad** [comment]
Closed by #1336
