### ISSUE TITLE
Investigate loop logic in systems_of_equations_ex8

### ISSUE THREAD

**Issue by jwpeterson** [libMesh/libmesh#1335]
I either haven't been paying close enough attention, or a newer version of the compiler triggers a warning for me in systems_of_equations_ex8 (see below). @dknez would you mind taking a look at this?

```
systems_of_equations_ex8.C:235:7: warning: variable 'outer_iteration' is incremented both in the loop header and in the loop body [-Wfor-loop-analysis]
      outer_iteration++;
```
```
systems_of_equations_ex8.C:205:51: note: incremented here
       outer_iteration != max_outer_iterations; ++outer_iteration)
```

**Comment by dknez** [comment]
Yep, that's a bug. The "outer_iteration++;" at the bottom of the loop should be removed. I probably switched the code from a while-loop to a for-loop at some point, but forgot to remove that final counter increment... oops.

**Comment by jwpeterson** [comment]
OK, I will just drop an extra commit onto the branch I'm working on.

**Comment by dknez** [comment]
Thanks!
