### ISSUE TITLE
Potential FParser cache race on NFS

### ISSUE THREAD

**Issue by dschwen** [libMesh/libmesh#1341]
There are reports about failing autodiff runs with high MPI rank counts where the JIT/autodiff cache is mounted on NFS volumes. I need to investigate this further, but my theory is that the

* open/create temporary file
* populate file
* close and move to the final name

scheme, which ensures that whenever a cache file with the final name exists it is fully written and valid, does not work on NFS. It looks like there is a time window during the move/rename where the file can be opened and is empty.

**Comment by dschwen** [comment]
http://stackoverflow.com/questions/41362016/rename-atomicity-and-nfs

**Comment by dschwen** [comment]
Same issue on Panasas (observed on ILN's Falcon cluster). This is pretty bad... 
I can add a MOOSE side workaround by doing AD and JIT on rank 0 first and then doing it in the remaining ranks, which would then only read the caches. To move this into FParser, I'd have to make this code MPI aware. I'm not sure there is a safe way to perform locking using the filesystem only.

**Comment by permcody** [comment]
Excuse my ignorance, how often do we hit the caches? Is it like once per time step, once per simulation? If you are hitting disk often at scale, you are already losing tons of performance. I think making the code MPI aware might be reasonable, not only for writing the cache, but perhaps even reading from it (e.g. read on rank one and distribute).

**Comment by dschwen** [comment]
These caches are hit only during setup. This is not a performance issue.
The race condition causes the simulation to crash if the caches are not
populated by a prior run.

**Comment by dschwen** [comment]
Ok, I think I have found a fix for this. I will do some further testing, but runs on Falcon look very promising.

The new strategy is not to run rename (which has implementation dependent behavior in case the target already exists), but run link instead (which will fail and do nothing if the target exists) and run unlink on the source in either case.

With this the target stays untouched and does not get constantly overwritten by all ranks.

**Comment by dschwen** [comment]
I think this is good to go.

**Comment by jwpeterson** [comment]
You haven't made a PR, though right? Also you mentioned something about `unlink` in your comments but are still calling `std::remove`, is that correct?

**Comment by jwpeterson** [comment]
Also did you want to check for nonzero return codes from `link` and `std::remove`?

**Comment by dschwen** [comment]
If link fails it is ok, no need to check the return code. If remove fails it is not fatal either (just junk remaining in the execution directory). I'll make a PR momentarily.

**Comment by dschwen** [comment]
remove and unlink are the same thing for files
