### ISSUE TITLE
Need configure flag for hard failure if VTK is missing

### ISSUE THREAD

**Issue by permcody** [libMesh/libmesh#1363]
More and more MOOSE users are relying on VTK as an input capability and we have the need to test for failure in a sane way if VTK isn't there. Currently libMesh is perfectly happy to move on if it can't find a working VTK installation that it can build against. We'd like to change that.

tag @jwpeterson

**Comment by jwpeterson** [comment]
I'll just do the same thing here that we do for PETSc, add an `--enable-vtk-required` flag that stops configure if VTK is not found...
