### ISSUE TITLE
TransientSystem::init_data() is not necessary?

### ISSUE THREAD

**Issue by YaqiWang** [libMesh/libmesh#1376]
If the template class is a `System`, `Base::init_data()` should have initialized the old and older vectors. Thus https://github.com/libMesh/libmesh/blob/master/src/systems/transient_system.C#L106 is really not needed, right?

Similarly, why is `ExplicitSystem::add_system_rhs()` not called in constructor? If so, its `init_data` will also not be needed. I see a commented line in constructor https://github.com/libMesh/libmesh/blob/master/src/systems/explicit_system.C#L39 maybe somebody have thought about this?

**Comment by roystgnr** [comment]
I think you're right about old/older vectors; that code looks like a very old atavism from before we started including those vectors in the System vectors container.  I'll put up a PR and see.  We'll also need to change clear() to make sure that the vectors remain of the appropriate type if users clear and then reuse a TransientSystem object.

For the "why wait until init_data to add the system RHS" question, I'm afraid I don't know.  The most likely answer is also "that wouldn't have worked before the RHS was managed by the System vectors container, but now it would", but in this case there's no double-initialization, so there's no obvious bug, so I'm disinclined to change the behavior unless there's some reason to do so (do you have one?) and there's no better reason not to do so (@benkirk, @jwpeterson, recall anything?)

**Comment by YaqiWang** [comment]
I was thinking to use `System::set_basic_system_only ()` in MOOSE in order to let MOOSE decide if the system matrix will be constructed or not. The vectors will be still handled by `Base::init_data()`. To do this, some minor changes in `ImplicitSystem::init_data` need to be made: to move `add_system_matrix()` into constructor, and to move the three line above it for clearing existing matrices into `init_matrices`, which will be made as a public function.

In MOOSE JFNK solve type, matrix is not needed but right now we have to hack the coupling matrix (put all zeros) to avoid the memory allocation in the matrix.

**Comment by permcody** [comment]
> In MOOSE JFNK solve type, matrix is not needed but right now we have to hack the coupling matrix (put all zeros) to avoid the memory allocation in the matrix.

Just to clarify, do you mean JFNK (No preconditioning)? I want to make sure because if that's the case you are correct, but do you really run without preconditioning? Or are you talking about the real Jacobian matrix?

**Comment by roystgnr** [comment]
That actually does sound like a good reason to change our behavior; some sparse matrix formats are O(1) for the empty case but I believe the linear algebra packages we use are all still O(N), and this does seem like the least hackish way to avoid that allocation entirely.  You really don't even need a Jacobian diagonal for -pc_type jacobi?

In that case, I'd be surprised if there's any equally compelling reason not to change.  You want to put together the PR with the ExplicitSystem and ImplicitSystem changes?

**Comment by YaqiWang** [comment]
@permcody JFNK means user does not let MOOSE to do the preconditioning. They may still provide their own preconditioner like physics-based preconditioning in MOOSE. Thus, system matrix should not be assembled.

Yes, for -pc_type jacobi, we do not need the full Jacobian. We can give user enough flexiability to let them decide how to construct the preconditioning matrix.

Yes, I will do this PR.
