### ISSUE TITLE
Unclosed filehandle build-up in FParser JIT compile

### ISSUE THREAD

**Issue by dschwen** [libMesh/libmesh#1386]
I'm using `mkstemp` to create temporary files. However that function actually opens the newly created fiIe. I don't store the returned handle, nor do I close the file (instead I open it again with `std::ofstream`).
This can cause failure if the maximum number of open file handles allowed by the OS is exhausted.

See https://github.com/idaholab/moose/issues/9549

**Comment by dschwen** [comment]
@tophmatthews would you mind checking out this libmesh hash and confirm that it fixes your issue?

**Comment by dschwen** [comment]
argh, stop, halt, not yet

**Comment by dschwen** [comment]
Ok, 	7f34446, should work... 🤞

**Comment by tophmatthews** [comment]
Ran into problems, I'll have to check it out next week...
