### ISSUE TITLE
Error building eigen

### ISSUE THREAD

**Issue by SimonDeRidder** [libMesh/libmesh#1411]
I get following error during the make step:
`In file included from ./contrib/eigen/eigen/Eigen/Core:257,
                 from ./include/libmesh/dense_vector.h:32,
                 from ./include/libmesh/fem_function_base.h:30,
                 from ./include/libmesh/system.h:31,
                 from src/mesh/exodusII_io_helper.C:33:
./contrib/eigen/eigen/Eigen/src/Core/util/Memory.h: In function ‘void* Eigen::internal::generic_aligned_realloc(void*, size_t, size_t)’:
./contrib/eigen/eigen/Eigen/src/Core/util/Memory.h:167: error: ‘__errno_location’ was not declared in this scope
In file included from ./include/libmesh/dense_vector.h:33,
                 from ./include/libmesh/fem_function_base.h:30,
                 from ./include/libmesh/system.h:31,
                 from src/mesh/exodusII_io_helper.C:33:
./include/libmesh/restore_warnings.h: At global scope:
./include/libmesh/restore_warnings.h:39: warning: unknown option after ‘#pragma GCC diagnostic’ kind
make[1]: *** [src/mesh/libmesh_dbg_la-exodusII_io_helper.lo] Error 1
make[1]: Leaving directory `/root/libmesh'
make: *** [all-recursive] Error 1
less `
I'm running CentOS 6.8

**Comment by jwpeterson** [comment]
We've seen this error
```
error: ‘__errno_location’ was not declared in this scope
```
a few times before, and I think it is caused when some compilers versions of `<errno.h>` (and apparently also `<string.h>`) are included from within a C++ namespace. I tried to make a configure test for this scenario that sets the `LIBMESH_COMPILER_HAS_BROKEN_ERRNO_T` define appropriately, but it may not be working on your system...

Can you look in your `build/include/libmesh_config.h` file and see if the define above is set for you?

**Comment by SimonDeRidder** [comment]
Hi, I only find this:
`/* define if errno.h cannot be included in a namespace */
/* #undef COMPILER_HAS_BROKEN_ERRNO_T */`
but if I define it make still gives the same error

**Comment by jwpeterson** [comment]
> but if I define it make still gives the same error

OK, it's possible that we need the same workaround but in a different place. In `include/numerics/dense_vector.h`, would you try adding 
```
#include <errno.h>
``` 
just before the 
```
#include <Eigen/Core>
```
line? Looks like line 32 in your version of libmesh, but in master it's on line 31.

Also, for future reference, can you let us know what compiler you are using on CentOS 6.8?

**Comment by jwpeterson** [comment]
Oh, and what version of libmesh are you using? `contrib/eigen/eigen/Eigen/Core:257` is a blank line in the libmesh master version of this file, and the last time we updated Eigen was in August of last year, so you may also be using a fairly old version of libmesh...

**Comment by jwpeterson** [comment]
Just to add one more data point: I was able to compile libmesh successfully on a CentOS 7 virtual machine with the compiler `g++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-11)`. This could be interpreted as bad news (since I can't replicate the problem locally) or good news (you might be able to fix the problem if you can upgrade OS's). 

FYI, from what I'm reading, the GCC on CentOS 6.x is 4.4.7 and probably won't support many C++11 things, which we are planning to start requiring for libmesh in the near future... so unless this build is for a system that will be around for a long time, I don't know how much effort you really want to spend on it...

**Comment by roystgnr** [comment]
I do most of my work on CentOS7, but with a hand-built gcc 6.2 to support some C++14 features.  I'd normally recommend "just build a better compiler" to others, as well, but in this case I'm not sure it would work - errno.h is part of glibc, not gcc, so the problem may be with the header itself and the header is unlikely to be so easy to upgrade.

**Comment by SimonDeRidder** [comment]
With both the git master version and the 1.2.1 release I still got the error with the include in dense_vector.h.
I was using the OS's default g++ 4.4.7.
In the past I did install an alternative g++ 6.2.0 I had forgotten about, however, and with that the compilation works fine.
I guess this fixes the issue for me. Thank you for your time.

**Comment by jwpeterson** [comment]
> With both the git master version and the 1.2.1 release I still got the error with the include in dense_vector.h.

Bummer, I was hoping that would have helped. Glad you were able to get a newer compiler to work for you.
