### ISSUE TITLE
osx compilation issue

### ISSUE THREAD

**Issue by dmebane** [libMesh/libmesh#1417]
Hi,

Trying to compile in OSX (10.12.6). Any particular suggestions? I can't do a user-level 'make' with default config options -- have to do 'sudo make'. Building seems to go fine until it gets to 'tests', which eventually fails with

  CXX      src/utils/libmesh_devel_la-xdr_cxx.lo
  CXXLD    libmesh_devel.la
  CXXLD    unit_tests-devel
libtool:   error: cannot find the library '/opt/local/lib/libidn.la' or unhandled argument '/opt/local/lib/libidn.la'
make[1]: *** [unit_tests-devel] Error 1
make: *** [all-recursive] Error 1

Thanks

**Comment by jwpeterson** [comment]
What is your toolchain on OSX? I'd recommend getting Xcode command line utils and building with the clang they provide. Other compilers (e.g. from homebrew) should also work, though.

I have no idea what `libidn.la` is, or why libmesh would be trying to link against it, but `/opt` is where local software is typically installed, so maybe you know what it is?

**Comment by dmebane** [comment]
I'm using Macports gcc 4.8, which is installed in /opt/local, mostly because there's no parallel debugging in clang. But if it would be easier to build with that I can specify the compiler.

Maybe I'll try that & see how it goes -- will report back. Thanks.

On Sep 5, 2017, at 5:56 PM, John W. Peterson <notifications@github.com<mailto:notifications@github.com>> wrote:


What is your toolchain on OSX? I'd recommend getting Xcode command line utils and building with the clang they provide. Other compilers (e.g. from homebrew) should also work, though.

I have no idea what libidn.la<http://libidn.la> is, or why libmesh would be trying to link against it, but /opt is where local software is typically installed, so maybe you know what it is?

**Comment by dmebane** [comment]
I use macports gcc, since llvm can't be parallel debugged. I reran configure to specify the clang compilers:

./configure --disable-fortran --with-cxx=/usr/bin/g++ --with-cc=/usr/bin/gcc
...
-------------------------------------------------------------------------------
Configure complete, now type 'make' and then 'make install'.

---------------------------------------------
--------- Done Configuring libMesh ----------
---------------------------------------------

make
...
  CXX      src/utils/libmesh_dbg_la-tree_node.lo
  CXX      src/utils/libmesh_dbg_la-utility.lo
  CXX      src/utils/libmesh_dbg_la-xdr_cxx.lo
  CXXLD    libmesh_dbg.la
Undefined symbols for architecture x86_64:
  "_MPI_Abort", referenced from:
      MPI::Comm::Abort(int) in libmesh_dbg_la-default_coupling.o
      MPI::Comm::Abort(int) in libmesh_dbg_la-dirichlet_boundary.o
      MPI::Comm::Abort(int) in libmesh_dbg_la-dof_map.o
      MPI::Comm::Abort(int) in libmesh_dbg_la-dof_map_constraints.o
      MPI::Comm::Abort(int) in libmesh_dbg_la-dof_object.o
      MPI::Comm::Abort(int) in libmesh_dbg_la-ghost_point_neighbors.o
      libMesh::libmesh_terminate_handler() in libmesh_dbg_la-libmesh.o
      ... 

[many, many similar messages]

ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [libmesh_dbg.la] Error 1
make: *** [all-recursive] Error 1

Now the permissions issue seems to be gone, but still having trouble.

**Comment by jwpeterson** [comment]
Hm... I think we need to update the build instructions in our README.md file. They should be directing people to do an out-of-tree build by default (in-tree builds should also work, but none of the main developers really use them, so we wouldn't know if they regressed).

Anyway, that doesn't seem to be your issue here. The compilers in /usr/bin on OSX 10.12.6 should be fine, but just to be sure, what does `/usr/bin/g++ --version` say for you?

It seems like what happened is that libmesh configured itself to use MPI, but doesn't have all the correct linker flags needed to successfully link against MPI on your system. This is usually taken care of either by PETSc, or by using the `mpicxx` compiler script that comes with your MPI distribution, but you may not fall into either of those cases. We'll probably need to see your config.log file to know exactly what's going on with your system...

**Comment by dmebane** [comment]
Davids-iMac:libmesh-master dsmebane$ /usr/bin/g++ --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.1.0 (clang-802.0.42)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

Davids-iMac:libmesh-master dsmebane$ g++ --version
g++ (MacPorts gcc48 4.8.5_2) 4.8.5
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Davids-iMac:libmesh-master dsmebane$ mpicxx --version
g++ (MacPorts gcc48 4.8.5_2) 4.8.5
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

so my MPI was also a macports thing

**Comment by jwpeterson** [comment]
> so my MPI was also a macports thing

Yes, but we still need to know how/why/if libmesh detected MPI. Since you are not using the macports compilers, it should not pick up macports MPI unless there is *another* MPI on your system. We still need to see the config.log file.

**Comment by dmebane** [comment]
[config.log.txt](https://github.com/libMesh/libmesh/files/1288016/config.log.txt)

Had to append .txt extension so it would upload. The help here is much appreciated.

**Comment by dmebane** [comment]
Yes, I don't have PETSc, since I typically write my own solvers. (Multidimensional adaptive mesh is something I decided not to take on.) But maybe that will change -- I can install PETSc first if that will also fix the problem.

**Comment by permcody** [comment]
Another option if you are tired of dealing with dependencies is to grab the
prebuilt package we maintain through MOOSE (A framework built on top of
libMesh and many other packages):
http://mooseframework.org/getting-started/

It'll give you everything you need on OS X: Better compilers, MPI, PETSc,
SLEPC, Hyper, SuperLU, Mumps and more. It also comes with modules so you
can load and unload various packages. It's easy to remove if you don't want
it, etc.

Cody

**Comment by jwpeterson** [comment]
> I can install PETSc first if that will also fix the problem.

Having a libmesh+PETSc+MPI installation will ultimately be more useful to you in the long run. If you decide to go that route, I would recommend using the MOOSE package as @permcody suggests.

**Comment by dmebane** [comment]
Will give it a shot guys, thanks

**Comment by jwpeterson** [comment]
> You may have some environment variable set that somehow allows this test to pass, but does not subsequently get used by libmesh for linking. I'm not really sure how this could happen, though...

After giving it a few seconds more thought, this error makes perfect sense. The mpi.m4 file is doing an `AC_TRY_COMPILE` test, and it (correctly) passes because you have the MPI headers in /usr/include. This should be an `AC_TRY_LINK` test, however, to avoid the problem you ran into.

**Comment by dmebane** [comment]
Hey glad I could help! Going the MOOSE route -- it's building libmesh now. I'll let you know how that goes.

**Comment by dmebane** [comment]
Ran 1394 tests in 109.9 seconds
1394 passed, 58 skipped, 0 failed

Looks pretty positive. Thanks again guys

**Comment by jwpeterson** [comment]
I'm going to close this for now, but feel free to reopen/comment again if necessary.
