### ISSUE TITLE
L2_LAGRANGE output appears to be incorrect

### ISSUE THREAD

**Issue by permcody** [libMesh/libmesh#1420]
See the discussion in https://github.com/idaholab/moose/issues/8635.

**Comment by roystgnr** [comment]
It looked like @jwpeterson correctly identified the bug.  It looks like it would affect XYZ elements too.

**Comment by jwpeterson** [comment]
Closing as I think this has been fixed for a while now...

**Comment by GiudGiud** [comment]
This might be in nemesis actually.
