### ISSUE TITLE
eigenproblems_ex3 error with SLEPc 3.8

### ISSUE THREAD

**Issue by dknez** [libMesh/libmesh#1486]
We get this error:
"Must select a target sorting criterion if using shift-and-invert"

This is explained on the PETSc mailing list here:
https://lists.mcs.anl.gov/mailman/htdig/petsc-users/2017-October/033649.html

**Comment by jwpeterson** [comment]
Thanks for the info. SLEPc is suddenly a hot topic in our PRs/Issues this week.

**Comment by jwpeterson** [comment]
By the way, @dknez are you already working on fixing this? 

@fdkong you were on the email thread, can you take a crack at it?

**Comment by jwpeterson** [comment]
I can look at it but I need to get PETSc/SLEPc 3.8 builds going first.

**Comment by dknez** [comment]
I don't have to work on it right now, so if someone else wants to do it first that would be welcome.

I think the fix just requires us to change the call to set_position_of_spectrum(SMALLEST_MAGNITUDE) so that we set a target value of 0 instead. Note that according to the PETSc thread, this fix applies to earlier versions of SLEPc as well, and it is considered a common mistake to use EPS_SMALLEST_MAGNITUDE along with shift-and-invert.

**Comment by dknez** [comment]
Fixed with PR #1555.
