### ISSUE TITLE
git bisect fem_system_ex2

### ISSUE THREAD

**Issue by pbauman** [libMesh/libmesh#1559]
I went to a year ago and b36673c is passing. So will start `git bisect` there.

**Comment by pbauman** [comment]
So it's all the way back to 0ef555e so far, without about 4 bisect steps to go. Any running bets on how close my git bisect good is the to offending commit?

**Comment by pbauman** [comment]
For posterity, here's my script that was fed to `git bisect run`

<pre>
#!/bin/bash

MYTEST_LIBMESH_BUILD_DIR=/fry1/data/users/pbauman/research/libmesh/build/test-femsystemex2-fail
MYTEST_LIBMESH_INSTALL_DIR=/fry1/data/users/pbauman/research/libmesh/install/test-femsystemex2-fail

# Go to libMesh build directory, configure, make, make install
mkdir -p $MYTEST_LIBMESH_BUILD_DIR
cd $MYTEST_LIBMESH_BUILD_DIR
module load gcc mpich openblas petsc vtk boost hdf5 cppunit
rm -rf ./*
../../libMesh/configure --enable-everything --with-metis=PETSc --with-methods=devel --prefix=$MYTEST_LIBMESH_INSTALL_DIR
make -j 32
cd examples/fem_system/fem_system_ex2/
make -j 16 check
</pre>

**Comment by jwpeterson** [comment]
This thread finally jogged my memory. I believe the error is coming from a TypeVector::inverse() call on a matrix of all zeros. At some point I changed this to throw an exception, whereas before it would just divide by zero...

**Comment by jwpeterson** [comment]
Sorry for not commenting before. This test's VTK requirement means that it doesn't get run as much as it should... we should probably consider writing multiple output files so the test can be turned on in more configurations...

**Comment by pbauman** [comment]
So.... git bisect said ec5c76f8 was the offending commit... which is exactly one after the one I randomly chose (and thought I tested...). I'm very suspicious, will report back.

**Comment by jwpeterson** [comment]
You might test ae45822a81687b54202f902543058457b74c3a91. That was the commit where we first started throwing exceptions from `TypeVector::inverse()`.

**Comment by jwpeterson** [comment]
> On the other hand, I don't think that explains this bug, because it's dying in the first assembly of the second time step, not in the middle of a solve.

IIRC the error was from this line:

https://github.com/libMesh/libmesh/blob/c8452da98200235081f8976734e29fdb2c98b36d/examples/fem_system/fem_system_ex2/nonlinear_neohooke_cc.C#L39

is that not the case? I haven't seen a stack trace, sorry if it was already posted by someone!

**Comment by roystgnr** [comment]
That's where it's dying; it's definitely a failure to invert a zero matrix.

But what I'm saying is that, if that was previously a *recoverable* failure, it would have had to have been in the assembly of a proposed step that would (upon discovery of NaN instead of a thrown exception) have been retracted.  If the assembly of the solution at the beginning of a time step throws NaN, there's no way for the solver to converge after that.

**Comment by jwpeterson** [comment]
> if that was previously a recoverable failure

Maybe it previously computed a NaN, nothing used/depended on it, and the simulation just kept chugging along?

**Comment by pbauman** [comment]
Sorry, had meetings, am back at this. I'm currently retesting my original starting commit for the sake of my sanity. I haven't even tried to get a stack trace because I'm lazy and `git bisect` was easier.

**Comment by pbauman** [comment]
I had a bug in my bisect script (was using source tree that wasn't being used in bisect). FML.

**Comment by pbauman** [comment]
OK, original good commit is still good, bad is still bad, so trying bisect again with fixed script...

**Comment by pbauman** [comment]
OK, git bisect reports 3b4b2fbce7aae208974132ec033b9df137439a7f as the offending commit

**Comment by roystgnr** [comment]
Definitely my fault, then, huh?  I was trying to get some redundancy out of EquationSystems::reinit(), but didn't notice that the removed code was *not* redundant if codes (like fem_system_ex2) used reinit() on a single System.

This is going to take a bit of thought.

**Comment by jwpeterson** [comment]
Any ETA on when fem_system_ex2 might be fixed? I think we should probably temporarily disable the test if it's going to be a while...

**Comment by roystgnr** [comment]
Not soon enough, I fear.  Let's have the shell script return XFAIL like @pbauman suggested on the list?

**Comment by jwpeterson** [comment]
Is that the same thing as `return 77;`?

**Comment by roystgnr** [comment]
Yeah.

**Comment by jwpeterson** [comment]
OK, I can take care of it then.

**Comment by roystgnr** [comment]
Sorry, I'm being an idiot.  SKIP is "return 77;" and is what I had in mind, but XFAIL is set up in Makefile.am and is I believe what Paul was suggesting.  I think SKIP would be preferable but either would be fine temporarily.

**Comment by pbauman** [comment]
Not quite. You just need to add `XFAIL_TESTS = <test_name>` in the Makefile.am where all the `TESTS` are listed. See [here](https://github.com/grinsfem/grins/blob/master/test/Makefile.am#L224) for example.

**Comment by jwpeterson** [comment]
Hmm... it looks like we don't use `TESTS` in *any* of our Makefile.am files, maybe we just aren't using this feature of automake. For the time being, I think I'll just `SKIP` it.

**Comment by roystgnr** [comment]
Resolved by #1592
