### ISSUE TITLE
Exodus file from steady-state problem is written out with non-zero "time_whole"

### ISSUE THREAD

**Issue by dknez** [libMesh/libmesh#1573]
This issue is minor, but it's a bit annoying. When I write out an exodus file using the code below:

```
ExodusII_IO exo_out(mesh, /*single_precision*/ true);
exo_out.write_equation_systems("filename.exo", es);
```

in some cases (I haven't been able to identify exactly when it will happen), the exodus file will be written out with a non-zero value of "time_whole" (which I can see via ncdump), e.g.:

`
time_whole = 1.205117e-43 ;
`

This is an issue for me since our visualization tool interprets this exo file as a time-dependent solution since time_whole is non-zero.

If I explicitly call ex_put_time in ExodusII_IO_Helper to set the time to zero, then this issue goes away, so I'm wondering if it's due to an uninitialized time, or something?

**Comment by jwpeterson** [comment]
> This is an issue for me since our visualization tool interprets this exo file as a time-dependent solution since time_whole is non-zero.

You may want to use a floating point tolerance comparison in your viz tool!

> If I explicitly call ex_put_time in ExodusII_IO_Helper to set the time to zero, then this issue goes away, so I'm wondering if it's due to an uninitialized time, or something?

Looks like `exII::ex_put_time()` is currently only called from `ExodusII_IO_Helper::write_timestep()`, but `write_equation_systems()` only calls `ExodusII_IO::write_nodal_data()`. So yeah I'm guessing it's an uninitialized variable issue.

I don't know if we can just add a "dummy" call to `ex_put_time(ex_id, 0, 0.0)` in `ExodusII_IO::write_nodal_data_common()` at the library level. This might be an issue if the first timestep starts at a negative time for some reason (I think this is supported, haven't tested it recently). My preferred workaround would probably be to add and `ExodusII_IO` interface that the user could employ to manually call `ex_put_time()` and work around the issue. Would that work for your case?

**Comment by dknez** [comment]
> You may want to use a floating point tolerance comparison in your viz tool!

Yeah, that's an easy fix, but I thought it was worth bringing up since it may be an unintialized variable issue that is worth fixing in a more thorough way.

Your preferred workaround sounds good to me. If I could call ex_put_time() from app code to set the time to zero, I think that'd fix the issue for me.

**Comment by dknez** [comment]
I may make a PR with John's fix later on if I need that, but for now I will just close this since it's a minor issue.
