### ISSUE TITLE
Don't automatically enable HDF5

### ISSUE THREAD

**Issue by jwpeterson** [libMesh/libmesh#1585]
There may be [compatibility issues](https://groups.google.com/d/msg/moose-users/S8Wq7-Ep3bs/X2_CZf6ECQAJ) with our vendored NetCDF and system HDF5 installs, and our configure script is apparently not sophisticated enough to catch them at configure time. So I'd like to stop enabling HDF5 support by default in hdf5.m4...

**Comment by roystgnr** [comment]
Doesn't ExodusII rely on HDF5?

**Comment by jwpeterson** [comment]
No. As I understand it, NetCDF4 *can* use of HDF5 if it's available (the error message in the link above comes from a NetCDF file that is trying to call and HDF5 function) but it doesn't require it. ExodusII has no relationship to HDF5 that I am aware of except for the optional connection in NetCDF.
