### ISSUE TITLE
Support for Petsc 3.4.5

### ISSUE THREAD

**Issue by kevindugan** [libMesh/libmesh#1596]
Some of the recent updates to Libmesh do not account for older versions of Petsc. 

I'm proposing adding more checks on the Petsc version, specifically in the PetscNonlinearSolver::solve method.

**Comment by jwpeterson** [comment]
@kevindugan sorry about this, we definitely try to maintain backwards compatibility for older versions of PETSc. There have been some recent changes in petsc_nonlinear_solver.C, but note that some of them were removed in #1587, so if you are using the libmesh version currently in MOOSE's submodule (cdeee5648) the problem may already be fixed?

**Comment by kevindugan** [comment]
@jwpeterson I completely understand the difficulty in keeping backward compatibility. I'm actually pulling a fresh version of MOOSE with the new submodule. When I build with my older version of Petsc, I get segmentation faults while running the MOOSE test suite inside of the SNESSetUp routine (which made an appearance in petsc_nonlinear_solver.C). 

My initial thought was that this routine didn't exist in v3.4.5 of Petsc, but now that I dig deeper I see that it does exist. Do you think this may be a MOOSE issue instead of a LibMesh issue?

**Comment by lindsayad** [comment]
@kevindugan Can you pull libmesh/master? The most recent changes in `PetscNonlinearSolver::solve` post-date the submodule update. You should still be able to build MOOSE with libmesh/master

**Comment by kevindugan** [comment]
@lindsayad Yes. I'll report what happens.

**Comment by lindsayad** [comment]
The last commit that touched the SNESSetUp interface was in 2010, so I'm thinking it was probably another change in that method

**Comment by jwpeterson** [comment]
> My initial thought was that this routine didn't exist in v3.4.5 of Petsc, but now that I dig deeper I see that it does exist.

Right... you would have had a compilation issue if the routine didn't exist!

> so if you are using the libmesh version currently in MOOSE's submodule (cdeee56) the problem may already be fixed?

Sorry, this sentence was confusing. What I meant was what Alex said: the problem may be fixed in libmesh master, although I see now that libmesh master still has a call to `SNESSetUp`. If you are being forced to rebuild anyway, you might consider building a debug-enabled version of PETSc to help you track down the segfault.

**Comment by kevindugan** [comment]
> Right... you would have had a compilation issue if the routine didn't exist!

Fair point!

I've rebuilt everything in debug mode, and I've checked out the master branch of Libmesh. I'm actually failing in a Petsc routine that is checking for pointer aliasing. Here's the error message below (I removed the configure options for compactness)

```
[0]PETSC ERROR: --------------------- Error Message ------------------------------------
[0]PETSC ERROR: Argument aliasing not permitted!
[0]PETSC ERROR: Solution vector cannot be right hand side vector!
[0]PETSC ERROR: ------------------------------------------------------------------------
[0]PETSC ERROR: Petsc Release Version 3.4.5, unknown
[0]PETSC ERROR: See docs/changes/index.html for recent updates.
[0]PETSC ERROR: See docs/faq.html for hints about trouble shooting.
[0]PETSC ERROR: See docs/index.html for manual pages.
[0]PETSC ERROR: ------------------------------------------------------------------------
[0]PETSC ERROR: /home/pqd/moose/test/moose_test-dbg on a arch-warthog named hts-ci-pc by pqd Mon Feb 19 13:28:57 2018
[0]PETSC ERROR: Libraries linked from /home/pqd/.warthogDependencies/petsc-debug/lib
[0]PETSC ERROR: Configure run at Mon Feb 19 11:43:44 2018
[0]PETSC ERROR: Configure options ...
[0]PETSC ERROR: ------------------------------------------------------------------------
[0]PETSC ERROR: SNESSetUp() line 2506 in src/snes/interface/snes.c
```

I'm not really sure how to resolve this issue. It looks like the constraint on pointer aliasing is lifted in later versions of Petsc.

**Comment by jwpeterson** [comment]
> Here's the error message below

Is there any way you could also give us the stack trace leading up to this error (off-issue if necessary)? We only call `SNESSolve` in one place in `petsc_nonlinear_solver.C`, but I'm curious how you might have gotten into a state where the rhs and solution vectors were identical...

> It looks like the constraint on pointer aliasing is lifted in later versions of Petsc.

In the PETSc master version of snes.c, line 4183, I still see:
```
    if (snes->vec_rhs  == snes->vec_sol) SETERRQ(PETSC_COMM_SELF,PETSC_ERR_ARG_IDN,"Solution vector cannot be right hand side vector");
```
in `SNESSolve`, so I don't think it has gone away completely...

**Comment by jwpeterson** [comment]
Looks like the check in question was first added to SNESSetUp in petsc/petsc@58c9b8173 (v3.2), and then moved to SNESSolve() in petsc/petsc@154060b52 (v3.5), which is at least consistent with your use of v3.4.5. 

I don't know of a reason that `snes->vec_rhs` should *ever* be equal to `snes->vec_sol`. Is it possible they are both `NULL`? In the stack trace you emailed me, the memory addresses of `x_in` and and `r_in` aren't shown in the backtrace.

**Comment by jwpeterson** [comment]
It looks like we don't call [`SNESSetSolution`](http://www.mcs.anl.gov/petsc/petsc-current/docs/manualpages/SNES/SNESSetSolution.html) at all in `PetscNonlinearSolver`, although we do call [`SNESSetFunction`](http://www.mcs.anl.gov/petsc/petsc-current/docs/manualpages/SNES/SNESSetFunction.html).  

This isn't necessary because you pass in the solution vector when you call `SNESSolve`, but it might help satisfy this early error check in SNESSetUp...

@fdkong may also be able to help with this issue.

**Comment by kevindugan** [comment]
Looks like they are both `NULL`:

```
2506	  if (snes->vec_rhs  == snes->vec_sol) SETERRQ(PETSC_COMM_SELF,PETSC_ERR_ARG_IDN,"Solution vector cannot be right hand side vector");
(gdb) p snes->vec_rhs
$1 = (Vec) 0x0
(gdb) p snes->vec_sol
$2 = (Vec) 0x0
```

**Comment by jwpeterson** [comment]
Hah, OK then my advice would be to call
```
SNESSetSolution(_snes, x->vec());
```
somewhere before `SNESSetUp` and see if that fixes the problem.

**Comment by kevindugan** [comment]
It looks like 3.4.5 doesn't include the `SNESSetSolution` method. I haven't seen a way to access the SNES solution vector in 3.4.5. Do you know of any other ways to set this vector?

I think I may have to defer the `SNESSetUp` to be handled in `SNESSolve`, like the documentation for `SNESSetUp` indicates for basic usage. What are your thoughts?

**Comment by jwpeterson** [comment]
> It looks like 3.4.5 doesn't include the SNESSetSolution method.

You're right, according to [this](https://github.com/petsc/petsc/blob/7835e463ee341cac5868e1c07c7d1c153f3a31ef/src/docs/website/documentation/changes/300.html#L299)  
```
SNESSetRhs() and SNESSetSolution() were removed. Use instead
SNESSolve(snes, b, x) to pass right hand side (optional, can be
PETSC_NULL) and solution (required).
```
it was removed for a while, then it came back in petsc/petsc@3cd8a7ca861cb485d39fa06ce4d184c90e995f2f (v3.6).

> I think I may have to defer the SNESSetUp to be handled in SNESSolve, like the documentation for SNESSetUp indicates for basic usage. What are your thoughts?

@lindsayad and @fdkong: Presumably we now need to explicitly call `SNESSetup` (71ea1191810f) in order to call `MatMFFDSetFunction`, `MatSNESMFSetReuseBase`, `SNESLineSearchSetType` stuff, but this breaks older versions of PETSc (at least 3.4.5) because of a (in my opinion, incorrect) check that the solution and rhs vectors not be the same (at the time they are both `NULL`). Is there a known workaround for this issue?

**Comment by jwpeterson** [comment]
It's pretty ugly, but as a workaround you might be able to
```
#if PETSC_VERSION_LESS_THAN(3,5,0)
#include <petsc-private/petscimpl.h>
#endif
```
and then manually set `vec_sol` before `SNESSetup()` happens, i.e. something like:
```
#if PETSC_VERSION_LESS_THAN(3,5,0)
_snes->vec_sol = x->vec();
#endif
```
just to get past the check. If something like this works, we could get it merged into libmesh upstream.

**Comment by fdkong** [comment]
@jwpeterson  Don't you like to use `PETSC_VERSION_LESS_THAN` to disable `SNESSetup`?  We fall back to old style when using old PETSc. If people want to the new capability, they have to use new petsc because of new API.

**Comment by kevindugan** [comment]
@fdkong I have tested disabling only `SNESSetup` with preprocessor directives, and have a few tests failing because of NULL arguments being passed into PetSc. You may be able to make this work, but I'm having trouble while making minimal changes to `petsc_nonlinear_solver.c`.

**Comment by jwpeterson** [comment]
> @fdkong I have tested disabling only SNESSetup with preprocessor directives, and have a few tests failing because of NULL arguments being passed into PetSc.

It's likely that we will have to restrict some of our newer MOOSE tests (which depend on the ability to set different MFFD functions) to only run with newer versions of PETSc.  It would be helpful if you could give us a list of the tests which are still failing if we finally succeed in working around the `NULL` pointer check...

**Comment by kevindugan** [comment]
After removing `SNESSetUp` by preprocessor directives, the following tests fail:

```
misc/jacobian.inf_nan ..................................................... FAILED (EXPECTED OUTPUT NOT FOUND)
preconditioners/pbp.check_petsc_options_test ................................ FAILED (EXPECTED OUTPUT MISSING)
dampers/min_damping.min_general_damping ...................................... FAILED (EXPECTED ERROR MISSING)
dampers/bounding_value_element_damper.bounding_value_max ..................... FAILED (EXPECTED ERROR MISSING)
dampers/bounding_value_nodal_damper.bounding_value_min ....................... FAILED (EXPECTED ERROR MISSING)
dampers/bounding_value_nodal_damper.bounding_value_max ....................... FAILED (EXPECTED ERROR MISSING)
dampers/interactions.interacting_node_elem1 .................................. FAILED (EXPECTED ERROR MISSING)
dampers/interactions.interacting_node_elem2 .................................. FAILED (EXPECTED ERROR MISSING)
materials/material_dependency.dont_reinit_mat_for_aux ....................................... FAILED (EXODIFF)
parser/parser_dependency.testpbp ............................................................. FAILED (ERRMSG)
misc/check_error.nan_no_trap_fpe_test ........................................................ FAILED (ERRMSG)
postprocessors/scalar_coupled_postprocessor.test ............................................. FAILED (ERRMSG)
preconditioners/pbp.pbp_adapt_test ........................................................... FAILED (ERRMSG)
preconditioners/pbp.test ..................................................................... FAILED (ERRMSG)
materials/material.throw_material ............................................................ FAILED (ERRMSG)
restart/restart.test_xda_restart_part_2 ...................................................... FAILED (ERRMSG)
dampers/min_damping.min_nodal_damping ............................. [min_threads=2,min_cpus=2] FAILED (ERRMSG)
dampers/min_damping.min_elem_damping .............................. [min_threads=2,min_cpus=2] FAILED (ERRMSG)
outputs/iterative.csv ....................................................................... FAILED (CSVDIFF)
postprocessors/all_print_pps.test .............................................. [min_cpus=2] FAILED (CSVDIFF)
```

@jwpeterson I had tried accessing the SNES solution vector by including `snesimpl.h`, but ended up getting errors from `VecGetSize`. I thought it would be more expedient to remove `SNESSetUp` and filter out the failing tests, instead of trying to resolve the `NULL` pointer check.

**Comment by jwpeterson** [comment]
Hmm... these tests aren't new, so if they are failing due to your changes, I don't think you can just remove the `SNESSetUp()` line like that.

Could you also try `#ifdef`ing out the other lines that were added in 71ea119 which required the `SNESSetUp()` line in the first place, like in this [commit](https://github.com/jwpeterson/libmesh/commit/e7d122caa583211f526f12f3eee6be7a174bd78a)?

**Comment by jwpeterson** [comment]
Oops, change that check to `!PETSC_VERSION_LESS_THAN` of course!

**Comment by kevindugan** [comment]
I'm still having several tests failing with my modifications to `petsc_nonlinear_solver.c`. A significant difference I can see between the previous version is that the `SNESSetJacobian` routine was used with different arguments based on the `_solver_type`, which is no longer present. Is there a way that I could mimic switching on `_solver_type`? Do you think this could be why some of the older tests are still failing?

**Comment by jwpeterson** [comment]
If you are referring to the `_solve_type` parameter, that code was already removed in a subsequent commit (e4e5962) in upstream which is not yet in the version of libmesh used by MOOSE. If we are going to debug this issue, you'll need to be applying your patches to libmesh master, not the version currently used in MOOSE. 

I suggest you just try pulling my "ifdef_attempt" branch (which I have now fixed the logic on!) and seeing how that goes. If there are still tests failing, we can see about trying to replicate the issue here with the old version of PETSc. 

BTW, PETSc 3.4.5 will turn 4 years old this year, so I'd try to upgrade if you can. There are bound to be even more incompatibilities with older versions as time goes on.

**Comment by kevindugan** [comment]
@jwpeterson I hadn't realized you created a branch that I could pull from. I'm building and testing with my version of PetSc now.

Unfortunately, upgrading to a newer Petsc version is not really an option for me. I'm using a code from ANL called Proteus, and the developers don't seem to want to upgrade Petsc versions. It's one of the issues we've raised with them.

**Comment by jwpeterson** [comment]
> Unfortunately, upgrading to a newer Petsc version is not really an option for me.

I see... yeah sometimes these things are out of our control :-/

**Comment by kevindugan** [comment]
Building with your fork of libmesh gives me the following tests failing:

```
misc/jacobian.inf_nan ..................................................... FAILED (EXPECTED OUTPUT NOT FOUND)
dampers/min_damping.min_general_damping ...................................... FAILED (EXPECTED ERROR MISSING)
dampers/bounding_value_element_damper.bounding_value_max ..................... FAILED (EXPECTED ERROR MISSING)
dampers/bounding_value_nodal_damper.bounding_value_min ....................... FAILED (EXPECTED ERROR MISSING)
dampers/bounding_value_nodal_damper.bounding_value_max ....................... FAILED (EXPECTED ERROR MISSING)
dampers/interactions.interacting_node_elem2 .................................. FAILED (EXPECTED ERROR MISSING)
dampers/interactions.interacting_node_elem1 .................................. FAILED (EXPECTED ERROR MISSING)
materials/material_dependency.dont_reinit_mat_for_aux ....................................... FAILED (EXODIFF)
misc/check_error.nan_no_trap_fpe_test ........................................................ FAILED (ERRMSG)
materials/material.throw_material ............................................................ FAILED (ERRMSG)
dampers/min_damping.min_nodal_damping ............................. [min_threads=2,min_cpus=2] FAILED (ERRMSG)
dampers/min_damping.min_elem_damping .............................. [min_threads=2,min_cpus=2] FAILED (ERRMSG)
outputs/iterative.csv ....................................................................... FAILED (CSVDIFF)
postprocessors/all_print_pps.test .............................................. [min_cpus=2] FAILED (CSVDIFF)
```

It seems like a lot of the tests are failing due to floating point exceptions being caught by Petsc. For example:

```
dampers/min_damping.min_general_damping: From damper: 'limit' damping below min_damping: 0.25 Cutting timestep.
dampers/min_damping.min_general_damping: [0]PETSC ERROR: --------------------- Error Message ------------------------------------
dampers/min_damping.min_general_damping: [0]PETSC ERROR: Floating point exception!
dampers/min_damping.min_general_damping: [0]PETSC ERROR: Vec entry at local location 0 is not-a-number or infinite at end of function: Parameter number 3!
dampers/min_damping.min_general_damping: [0]PETSC ERROR: ------------------------------------------------------------------------
dampers/min_damping.min_general_damping: [0]PETSC ERROR: Petsc Release Version 3.4.5, unknown
dampers/min_damping.min_general_damping: [0]PETSC ERROR: See docs/changes/index.html for recent updates.
dampers/min_damping.min_general_damping: [0]PETSC ERROR: See docs/faq.html for hints about trouble shooting.
dampers/min_damping.min_general_damping: [0]PETSC ERROR: See docs/index.html for manual pages.
dampers/min_damping.min_general_damping: [0]PETSC ERROR: ------------------------------------------------------------------------
dampers/min_damping.min_general_damping: [0]PETSC ERROR: /home/pqd/Playground/petscLibmeshTest/moose/test/moose_test-dbg on a arch-warthog named node22.ornl.gov by pqd Thu Feb 22 12:13:56 2018
dampers/min_damping.min_general_damping: [0]PETSC ERROR: Libraries linked from /home/pqd/.warthog_dependencies/petsc-3.4.5-debug/lib
dampers/min_damping.min_general_damping: [0]PETSC ERROR: Configure run at Mon Feb 19 15:05:20 2018
dampers/min_damping.min_general_damping: [0]PETSC ERROR: Configure options --prefix=/home/pqd/.warthog_dependencies/petsc-3.4.5-debug --with-petsc-arch=arch-warthog --download-hypre=1 --with-ssl=0 --with-c2html=0 --with-debugging=1 --with-pic=1 --with-shared-libraries=1 --with-cc=mpicc --with-cxx=mpicxx --with-fc=mpif90 --download-f-blas-lapack=1 --download-metis=1 --download-parmetis=1 --download-superlu_dist=1 --download-scalapack=1 --download-mumps=1 CC=mpicc CXX=mpicxx FC=mpif90 F77=mpif77 F90=mpif90 CFLAGS="-fPIC -fopenmp" CXXFLAGS="-fPIC -fopenmp" FFLAGS="-fPIC -fopenmp" FCFLAGS="-fPIC -fopenmp" F90FLAGS="-fPIC -fopenmp" F77FLAGS="-fPIC -fopenmp" PETSC_DIR=/home/pqd/Playground/petscLibmeshTest/warthog/tpls/petsc-v3.4.5
dampers/min_damping.min_general_damping: [0]PETSC ERROR: ------------------------------------------------------------------------
dampers/min_damping.min_general_damping: [0]PETSC ERROR: VecValidValues() line 30 in src/vec/vec/interface/rvector.c
dampers/min_damping.min_general_damping: [0]PETSC ERROR: SNESComputeFunction() line 1998 in src/snes/interface/snes.c
dampers/min_damping.min_general_damping: [0]PETSC ERROR: SNESLineSearchApply_Basic() line 40 in src/snes/linesearch/impls/basic/linesearchbasic.c
dampers/min_damping.min_general_damping: [0]PETSC ERROR: SNESLineSearchApply() line 525 in src/snes/linesearch/interface/linesearch.c
dampers/min_damping.min_general_damping: [0]PETSC ERROR: SNESSolve_NEWTONLS() line 242 in src/snes/impls/ls/ls.c
dampers/min_damping.min_general_damping: [0]PETSC ERROR: SNESSolve() line 3636 in src/snes/interface/snes.c
dampers/min_damping.min_general_damping: application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0
dampers/min_damping.min_general_damping: [unset]: write_line error; fd=-1 buf=:cmd=abort exitcode=1
dampers/min_damping.min_general_damping: :
dampers/min_damping.min_general_damping: system msg for write_line failure : Bad file descriptor
dampers/min_damping.min_general_damping: ################################################################################
dampers/min_damping.min_general_damping:
dampers/min_damping.min_general_damping: Unable to match the following pattern against the program's output:
dampers/min_damping.min_general_damping:
dampers/min_damping.min_general_damping: Solve failed and timestep already at or below dtmin
dampers/min_damping.min_general_damping:
dampers/min_damping.min_general_damping: ################################################################################
dampers/min_damping.min_general_damping: Tester failed, reason: EXPECTED ERROR MISSING
```

**Comment by lindsayad** [comment]
A lot of damper stuff. Wonder if at least part of the failures could be
rooted in computePostCheck

**Comment by jwpeterson** [comment]
I think I know what (at least one of) the issues is. Older versions PETSc used to not allow NaNs in the solution vector (would throw a floating point exception) but later versions, I think >=3.5, explicitly allow this to make it easier to "recover" from failed solves. I bet at least some of these failed tests are relying on that NaN-in-the-solution-vector approach, and therefore need to be restricted to only run for PETSc >= 3.5...

**Comment by kevindugan** [comment]
@jwpeterson Were you going to incorporate the changes in your "ifdef_attempt" branch into the Libmesh master, or should I create a merge request for the changes?

Also, would you be able to deactivate the failing tests in the MOOSE repo like you had suggested?

> and therefore need to be restricted to only run for PETSc >= 3.5...

**Comment by jwpeterson** [comment]
> Were you going to incorporate the changes in your "ifdef_attempt" branch into the Libmesh master, or should I create a merge request for the changes?

I'll open a PR since the fix seems to adequately work around the issue in that old version of PETSc.

> Also, would you be able to deactivate the failing tests in the MOOSE repo like you had suggested?

I would need to dig into *exactly* why each test is failing before I'd feel comfortable with blanket disabling them. Since I don't currently have a working PETSc 3.4.5 stack, it would be helpful if you could open an initial MOOSE PR (tag me on it) that adds
```
petsc_version = '>=3.6.0'
```
to the test specs of the tests in question (I was wrong earlier when I guessed 3.5). Then I can take a closer look into exactly why each one is failing once I get everything built with old PETSc.

**Comment by kevindugan** [comment]
I'll take care of the initial pull request in MOOSE.

**Comment by jwpeterson** [comment]
This was fixed through a combination of ifdefs and disabling various tests. We still have some MOOSE tests that will fail if run with a debug-enabled version of PETSc 3.4.5, but aren't going to worry about maintaining that particular configuration perfectly.
