### ISSUE TITLE
No Unique Indices Compile Issue (--disable-unique-id)

### ISSUE THREAD

**Issue by benkirk** [libMesh/libmesh#1610]
@roystgnr, I think this line is in error because the corresponding #ifdef lives inside the get_hilbert_index method?  I'm a little hesitant to submit the fix because I don't have anything to test it.  Can you confirm or deny my suspicion?

https://github.com/libMesh/libmesh/blob/ed3dc66c224a59f03bc4d23dffc3512bfc79a51f/src/mesh/mesh_communication_global_indices.C#L676

Specifically, there's no 3-argument implementation of get_hilbert_index required.
```
Parallel::DofObjectKey
get_hilbert_index (const Elem * e,
                   const libMesh::BoundingBox & bbox)
{
  static const unsigned int sizeof_inttype = sizeof(Hilbert::inttype);

  Hilbert::HilbertIndices index;
  CFixBitVec icoords[3];
  Hilbert::BitVecType bv;
  get_hilbert_coords (e->centroid(), bbox, icoords);
  Hilbert::coordsToIndex (icoords, 8*sizeof_inttype, 3, bv);
  index = bv;

#ifdef LIBMESH_ENABLE_UNIQUE_ID
  return std::make_pair(index, e->unique_id());
#else
  return index;
#endif
}



// Compute the hilbert index
Parallel::DofObjectKey
get_hilbert_index (const Node * n,
                   const libMesh::BoundingBox & bbox)
{
  static const unsigned int sizeof_inttype = sizeof(Hilbert::inttype);

  Hilbert::HilbertIndices index;
  CFixBitVec icoords[3];
  Hilbert::BitVecType bv;
  get_hilbert_coords (*n, bbox, icoords);
  Hilbert::coordsToIndex (icoords, 8*sizeof_inttype, 3, bv);
  index = bv;

#ifdef LIBMESH_ENABLE_UNIQUE_ID
  return std::make_pair(index, n->unique_id());
#else
  return index;
#endif
}
```

**Comment by jwpeterson** [comment]
Hmmm... should the `#else` branch of this just be deleted? The logic doesn't seem correct to me anyway... if `!LIBMESH_ENABLE_UNIQUE_ID` then we access `unique_id()`??

**Comment by roystgnr** [comment]
Did I seriously switch those two branches of the #ifdef?

**Comment by benkirk** [comment]
That’s the change I made to get it to compile again, but like I said can’t test it in any meaningful way!

On Mar 6, 2018, at 1:44 PM, John W. Peterson <notifications@github.com<mailto:notifications@github.com>> wrote:


Hmmm... should the #else branch of this just be deleted? The logic doesn't seem correct to me anyway... if !LIBMESH_ENABLE_UNIQUE_ID then we access unique_id()??

**Comment by jwpeterson** [comment]
Am I blind, I don't even see a three argument version of `get_hilbert_index()`...

**Comment by jwpeterson** [comment]
Oh, I see now it is a nested constructor call.

**Comment by roystgnr** [comment]
An invalid nested constructor call, even in the --enable-unique-id case.

I really need to get the old BuildBot umpteen-different-configure-option tests reenabled, if only as a manual script...

**Comment by jwpeterson** [comment]
I'll add a `--disable-unique-id` recipe on the CIVET side.

**Comment by benkirk** [comment]
To be clear, I got this just with a vanilla master ./configure.  Which I think defaults to —disable-uniquie-id

Thanks all!

**Comment by roystgnr** [comment]
> Thanks all!

![Simpsons meme](https://frinkiac.com/meme/S08E17/274123.jpg?b64lines=IEFORCBUSEFOSyBZT1UgRk9SIFNFTkRJTkcKIExJU0EgVE8gUFJPVEVDVCBVUyBGUk9NCiBUSEUgQlVHIFlPVSBTRU5ULg==)

"And thank you for sending a PR to fix the bug you sent!"
