### ISSUE TITLE
PointLocatorTree may not be thread safe at all

### ISSUE THREAD

**Issue by dschwen** [libMesh/libmesh#1612]
Servant point locators of the `PointLocatorTree` type share the `Tree` allocated by the master point locator. `TreeNode` contains a `mutable std::vector<bool> searched_child;` member which is set and resized (!) in `TreeNode<N>::find_element_in_children`, which in turn is called by the point locator `operator ()` (which obviously can be called from parallel threads).

This looks bad, but maybe it means that I am not "full of shit" after all @friedmud ...

**Comment by jwpeterson** [comment]
Hmm... looks like the `searched_child` member went from being a local variable to a class member farily recently in 84b1df9c, so maybe we can just revert that commit to fix the thread safety issue.

**Comment by roystgnr** [comment]
> maybe it means that I am not "full of shit" after all @friedmud

> @friedmud committed on Feb 12, 2017

:open_mouth:

:popcorn:

**Comment by jwpeterson** [comment]
https://github.com/libMesh/libmesh/pull/1238#issuecomment-279722823

**Comment by jwpeterson** [comment]
I like the `std::array<int,N>` like @roystgnr suggested in the original thread.

Once it's in, this fix should also be cherry-picked onto v1.3.0...

**Comment by dschwen** [comment]
Wait, guys, the vector is sized by `children.size()`, that seems to be a runtime thing. For `std::array` we'd have to know the size at compile time. Or is the number of children a property that we can know at compile time (octree?)
