### ISSUE TITLE
Compilation Libmesh with another code

### ISSUE THREAD

**Issue by aziznasri** [libMesh/libmesh#1614]
Hello

I have recently installed Libmesh and i try to use it. 
In fact, I have my C++ code working on a single Gauss point. Is it possible to use Libmesh with my code in order to obtain my finite element code (like Moose framework). Unfortunately there isn't a user manual for that. Is there someone who has already doing this?

Best regards,
Aziz

**Comment by jwpeterson** [comment]
You should probably be using MOOSE directly. MOOSE has lots of documentation at http://mooseframework.org/moose/.

**Comment by jwpeterson** [comment]
BTW, I'm going to close this since it's not a specific issue about code. You can send mail to libmesh-users@lists.sourceforge.net for questions like this.
