### ISSUE TITLE
Cannot use adjacent periodic boundary conditions

### ISSUE THREAD

**Issue by dknez** [libMesh/libmesh#1639]
When I was debugging systems_of_equations_ex9, one test I did was to create a new mesh that is "two copies" of the current mesh, with one rotated by 30 degrees so that we had two distinct segments of the periodic domain. I then impose a separated periodic condition on each segment, with the goal of checking that the overall solution was continuous. However, this failed with the error below:

```
Assertion `s_neigh != libMesh::invalid_uint' failed.
s_neigh = 4294967295
libMesh::invalid_uint = 4294967295


Stack frames: 23
0: libMesh::print_trace(std::ostream&)
1: libMesh::MacroFunctions::report_error(char const*, int, char const*, char const*)
2: libMesh::FEAbstract::compute_periodic_node_constraints(libMesh::NodeConstraints&, libMesh::PeriodicBoundaries const&, libMesh::MeshBase const&, libMesh::PointLocatorBase const*, libMesh::Elem const*)
3: /home/dknez/software/libmesh_install/dbg_real/libmesh/lib/libmesh_dbg.so.0(+0x1678384) [0x7fffee8d7384]
4: /home/dknez/software/libmesh_install/dbg_real/libmesh/lib/libmesh_dbg.so.0(+0x16a9b63) [0x7fffee908b63]
5: libMesh::DofMap::create_dof_constraints(libMesh::MeshBase const&, double)
6: libMesh::System::reinit_constraints()
7: libMesh::System::init_data()
8: libMesh::ImplicitSystem::init_data()
9: libMesh::LinearImplicitSystem::init_data()
10: libMesh::System::init()
11: libMesh::EquationSystems::init()
12: FeSystem::try_equation_systems_init(libMesh::EquationSystems&)
13: FeSolverFunctions::call_linear_elasticity_fe_solver(libMesh::MeshBase&, TypeMaps&, FeSolverInit const&, FeSolverSolve const&, SolveInfo<FeSolverResponse>&, unsigned int, AppOutputHelper&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, std::__debug::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, ComponentVisualizationSummary, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, ComponentVisualizationSummary> > >*)
14: /home/dknez/akselos-dev/scrbe/build/bin/fe_solver-dbg_real() [0x4a1fe5]
15: MessageHandler::dispatch_message(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Json::Value const&, std::unique_ptr<MessageHandler, std::default_delete<MessageHandler> >&)
16: MessageHandler::extract_message(Json::Value&, std::unique_ptr<MessageHandler, std::default_delete<MessageHandler> >&)
17: MessageHandler::parse_message(char const*, char const*, std::unique_ptr<MessageHandler, std::default_delete<MessageHandler> >&)
18: /home/dknez/akselos-dev/scrbe/build/bin/fe_solver-dbg_real() [0x4a41f7]
19: /home/dknez/akselos-dev/scrbe/build/bin/fe_solver-dbg_real() [0x4a3c85]
20: /home/dknez/akselos-dev/scrbe/build/bin/fe_solver-dbg_real() [0x4a3c43]
21: __libc_start_main
22: /home/dknez/akselos-dev/scrbe/build/bin/fe_solver-dbg_real() [0x49fa29]
[0] /home/dknez/software/libmesh-src/src/fe/fe_abstract.C, line 986, compiled Mar 22 2018 at 13:18:15
```

I gather that the issue is that the point locator that we use fails because we have two overlapping periodic surfaces from the two different segments.

It'd be nice if we could handle this case more gracefully, IMO.

**Comment by roystgnr** [comment]
I'm still failing to understand the problem, I think.  IIRC I've used adjacent periodic boundary conditions for *years* - a box where the pair of horizontal sides are periodic and so are the pair (or pairs in 3D) of vertical sides is pretty much the default use case, no?  And those are all adjacent at the nodes (or edges in 3D) where different pairs of sides meet?

If anything like *that* is causing problems, then I'd fear that #1640 is at best a workaround rather than a solution.

But your description here is of two meshes which are overlapping, so that the same physical point is in multiple different elements?  ... even in that case, it seems like we shouldn't have to force users to manually tag subdomain ids, when we *already* have boundary ids to disambiguate overlap.  Would it be possible to, instead of getting a single element back from the point locator, use the method which returns a set of elements, then test those elements to see which has the necessary bcid?

**Comment by dknez** [comment]
Hi Roy,

You can reproduce the issue yourself with #1640: use the changes from that PR to systems_of_equations_ex9.C and systems_of_equations_ex9.exo, and omit the other changes (and also omit the changes to systems_of_equations_ex9.C that are based on the other changes, but they'll be easy to find since they'll give compilation errors). For me, that fails with the error reported in this issue.

The alternative fix that you suggested also sounds fine to me. I don't really mind either way, as long as it fixes my updated version of systems_of_equations_ex9.
