### ISSUE TITLE
Regression in MOOSE XFEM module test

### ISSUE THREAD

**Issue by jwpeterson** [libMesh/libmesh#1688]
@roystgnr, we seem to have picked up a regression in the `init_solution_propagation` test in MOOSE's xfem module due to commit 9844a86206005266ed1bb690f8fc9aefca00b43c. To reproduce with master, build everything up to the xfem module and run
```
cd $MOOSE_DIR/modules/xfem/test/tests/init_solution_propagation
mpiexec -n 4 ../../../xfem-opt -i init_solution_propagation.i
```
This happened because we previously weren't running the MOOSE modules tests on libmesh PRs, although @brianmoose has subsequently rectified that situation.

Before this commit, the code runs fine, after this commit, the test code hangs with some processes in `MPI_Probe` as best as I can tell. Based on the comment in the offending commit, I'd say some logic error is causing us to be in an infinite loop... In other words, instead of quitting syncing "too soon" we are now never quitting 😄 

@bwspenc I'm not sure exactly what the test in question is doing, but if you could briefly describe it, it might shed some light on what the problem is.

**Comment by jwpeterson** [comment]
The failures can also be seen (they appear as timeouts) over on idaholab/moose#11469.

**Comment by bwspenc** [comment]
When we cut the mesh with XFEM, we have to be careful to copy the solution (current, old, and older as applicable) from the original nodes of the duplicated elements to the newly created nodes at those locations. This test is making sure that happens correctly both in serial and parallel.

**Comment by bwspenc** [comment]
The code that is being tested is in `XFEM::initSolution()` in `moose/modules/xfem/src/base/XFEM.C`. If you comment out all the code in that method, my guess is that it won't hang (but you'll also break a lot of tests because they run incorrectly).

**Comment by jwpeterson** [comment]
OK, thanks for the info @bwspenc!

**Comment by roystgnr** [comment]
Thanks!  I'll try to replicate it this morning.

**Comment by roystgnr** [comment]
This is easy enough to replicate, and it's definitely a libMesh bug.  The trouble is that the offending commit isn't actually a bug; it just triggers the bug.  I think I'll have a real fix soon.

**Comment by roystgnr** [comment]
Well, maybe not as soon as I'd hoped, and maybe not a libMesh bug after all.  But I think I finally understand *why* the bug - the XFEM code may be be giving a node a processor_id that doesn't match any of the elements touching it?  That used to be (maybe still is?) invalid for a mesh getting numbered by DofMap, so I've taken care to make sure that the library doesn't do that internally, but I've also needed to rely on that same limitation in other code.  In the specific failures I'm triggering I could add a workaround at the libMesh level, but I fear that would hide silent failures in other cases.

@bwspenc, is there a chance my theory is accurate?  I'm afraid I don't understand the XFEM code well enough to verify it.  There's a parent node processor id getting copied onto new nodes, but I can't trace exactly where that comes from.

**Comment by roystgnr** [comment]
It looks like https://github.com/idaholab/moose/pull/11511 finally resolved this for goot.

**Comment by jwpeterson** [comment]
> resolved this for goot.

![groot](https://user-images.githubusercontent.com/1775907/40076443-206f1a46-583c-11e8-913d-f9c6f8a16ab9.jpg)
