### ISSUE TITLE
libmesh_static is not set correct with "--enable-static --enable-all-static --disable-shared"

### ISSUE THREAD

**Issue by fdkong** [libMesh/libmesh#1692]
MOOSE relies on this variable, `libmesh_static`, to determine whether or not to link the lib statically. 

`libmesh_static` is empty when configure `libmesh` with `--enable-static --enable-all-static --disable-shared`.  I found this issue on `theta`, and I did not try my laptop yet. 

@friedmud

**Comment by jwpeterson** [comment]
This is a Makefile variable, right? I think this is a new dependency assumed by @rwcarlsen for his registry stuff? As far as I know it has not been used for anything before. Do you know when it *does* get set?

**Comment by rwcarlsen** [comment]
using `--disable-shared` sets makefile var `libmesh_shared=no`.  using `--enable=static` sets `libmesh_static=yes`.  using `--enable-all-static` sets `libmesh_all_static=yes` but doesn't set `libmesh_static=yes`.  We an deal with this in the MOOSE makefile, but it might be cleaner to do in libmesh.

**Comment by jwpeterson** [comment]
The only reference to `libmesh_static` that I see in installed libmesh appears in `contrib/utils/Make.common.in`, 
```
libmesh_static   := $(shell $(libmesh_LIBTOOL) --config | grep build_old_libs | cut -d'=' -f2)
```
but we don't seem to include Make.common in any of the MOOSE Makefiles? So I'm not sure where you are actually picking it up, but presumably the line of shell code above is not sufficient in the --enable-all-static case.
