### ISSUE TITLE
PETSc sparsity pattern error in libMesh examples in parallel

### ISSUE THREAD

**Issue by dknez** [libMesh/libmesh#1697]
If I run introduction_ex4 with "mpirun -np 2" I get a PETSc sparsity pattern error:

```
[0]PETSC ERROR: --------------------- Error Message --------------------------------------------------------------
[0]PETSC ERROR: Argument out of range
[0]PETSC ERROR: New nonzero at (0,409) caused a malloc
Use MatSetOption(A, MAT_NEW_NONZERO_ALLOCATION_ERR, PETSC_FALSE) to turn off this check
[0]PETSC ERROR: See http://www.mcs.anl.gov/petsc/documentation/faq.html for trouble shooting.
[0]PETSC ERROR: Petsc Release Version 3.8.0, unknown 
[0]PETSC ERROR: ./example-opt on a arch-linux2-c-opt named david-Lenovo by dknez Wed May 16 09:51:58 2018
[0]PETSC ERROR: Configure options --with-shared-libraries=1 --with-debugging=0 --download-suitesparse --download-blacs --download-ptscotch=yes --with-blaslapack-dir=/opt/intel/compilers_and_libraries_2018.1.163/linux/mkl --CXXFLAGS=-Wl,--no-as-needed --download-scalapack --download-mumps --download-metis --prefix=/home/dknez/software/libmesh_install/opt_real/petsc --download-hypre --download-ml
[0]PETSC ERROR: #1 MatSetValues_MPIAIJ() line 610 in /home/dknez/software/petsc-src/src/mat/impls/aij/mpi/mpiaij.c
[0]PETSC ERROR: #2 MatAssemblyEnd_MPIAIJ() line 712 in /home/dknez/software/petsc-src/src/mat/impls/aij/mpi/mpiaij.c
[0]PETSC ERROR: #3 MatAssemblyEnd() line 5213 in /home/dknez/software/petsc-src/src/mat/interface/matrix.c
```

I'm on the libMesh HEAD, and using PETSc 3.8. I'll git bisect to figure out what triggers this.

**Comment by friedmud** [comment]
This could be related to the parallel_sync changes. I’m not sure if I’ll
have time to take a look today...

**Comment by roystgnr** [comment]
I'll at least see if I can replicate and see if reverting #1686 has any effect.

**Comment by dknez** [comment]
Reverting to c7933d3 works for me, which is the commit right before #1686, so I think #1686 is the issue.

**Comment by jwpeterson** [comment]
Should we open a PR with `git revert -m 1 b676c94`? This seems like a major regression, so how the f did it pass all the libmesh PR testing *and* the libmesh update testing on idaholab/moose#11469???

**Comment by jwpeterson** [comment]
I suspect reverting just a555464 would also do the trick, instead of reverting the entire merge.

**Comment by dknez** [comment]
Yes, I think we should revert this. It's causing me lots of errors in our test suite (I should really get our test suite onto the PR testing system...)

**Comment by dknez** [comment]
I tested b676c9 and that fails, so #1686 is definitely the issue.

**Comment by jwpeterson** [comment]
@dknez are you on Linux or MacOS?

**Comment by permcody** [comment]
CIVET is also working on this:
https://civet.inl.gov/pr/6123/

**Comment by jwpeterson** [comment]
Hmm... so not just that one commit then? If you revert the entire merge (`git revert -m 1 b676c94`) does it work?

I'm not able to reproduce the problem currently on libmesh master, MacOS, PETSc 3.8.0, clang 3.9. BTW, intro_ex4 runs a 1D, 2D, and 3D case, which one is giving you the failure?

**Comment by dknez** [comment]
I was testing by running "mpirun -np 1 ./example-opt -n 10 -d 3" vs "mpirun -np 2 ./example-opt -n 10 -d 3", and I only get the sparsity pattern error in the "-np 2" case.

I'll try "git revert -m 1 b676c94" and let you know.

**Comment by roystgnr** [comment]
Wait, the whole PR fails but that specific commit isn't the cause?  That's great!  If that's the case then it's likely that the failure is coming from somewhere like 2d9377d, which we haven't had any suspicion in, rather than from a555464, which I've been tearing my hair out staring at to no avail.

**Comment by jwpeterson** [comment]
> mpirun -np 2 ./example-opt -n 10 -d 3

I cannot reproduce the `intro_ex4` failure with these command line options on a Ubuntu 16.04.4, Intel-17, PETSc 3.7.6 build either...

@roystgnr have you had any luck reproducing this?
@dknez can you post the exact flags you use to configure libmesh?

**Comment by roystgnr** [comment]
Could you also try reverting just 2d9377d, and then if that works try reverting the combination of 2d9377d with a555464?

Sorry to be a beggar with the requests, but I still can't replicate this myself.

**Comment by dknez** [comment]
Regarding configure options, here's the top of my config.log:

```
This file contains any messages produced by compilers while
running configure, to aid debugging if configure makes a mistake.

It was created by libmesh configure 1.4.0-pre, which was
generated by GNU Autoconf 2.69.  Invocation command line was

  $ /home/dknez/software/libmesh-src/configure --enable-everything --enable-slepc --with-metis=PETSc --with-subdomain-id-bytes=4 --with-boundary-id-bytes=4 --disable-glpk --enable-unique-id --with-unique-id-bytes=4 --with-nlopt-include=/home/dknez/software/libmesh_install/nlopt/include --with-nlopt-lib=/home/dknez/software/libmesh_install/nlopt/lib --with-capnproto=/home/dknez/software/libmesh_install/capnp --disable-parmetis --disable-ifem --prefix=/home/dknez/software/libmesh_install/opt_real/libmesh --with-methods=opt --enable-shared PETSC_DIR=/home/dknez/software/libmesh_install/opt_real/petsc SLEPC_DIR=/home/dknez/software/libmesh_install/opt_real/slepc CPPFLAGS=  LIBS= -ldl  CPPFLAGS=   LIBS=  -ldl  CPPFLAGS=    LIBS=   -ldl  CPPFLAGS=     LIBS=    -ldl  CPPFLAGS=      LIBS=     -ldl  CPPFLAGS=       LIBS=      -ldl  CPPFLAGS=        LIBS=       -ldl  CPPFLAGS=         LIBS=        -ldl  CPPFLAGS=          LIBS=         -ldl  CPPFLAGS=           LIBS=          -ldl  CPPFLAGS=            LIBS=           -ldl  CPPFLAGS=             LIBS=            -ldl  --disable-netcdf-4 --disable-testsets CXX=mpicxx CC=mpicc F77=mpif77 FC=mpif90 CPPFLAGS=              LIBS=             -ldl  --disable-netcdf-4 --disable-testsets CXX=mpicxx CC=mpicc F77=mpif77 FC=mpif90 CPPFLAGS=               LIBS=              -ldl  --no-create --no-recursion
```

Also, introduction_ex4 works for me with "git revert -m 1 b676c94". One issue is that I had merge conflicts with that, but I think I resolved them appropriately.

I'll try reverting just 2d9377d next.

**Comment by dknez** [comment]
Reverting 2d9377d has merge conflicts, and it doesn't compile after I resolved them.

**Comment by roystgnr** [comment]
That'll get rid of a ton of later commits, of course, but if c7933d3 worked for you and b676c94 failed then the later commits are irrelevant.

**Comment by dknez** [comment]
Checking out 79aa160 works for me.

**Comment by jwpeterson** [comment]
Your configure options look mostly benign to me except for maybe:
```
--with-subdomain-id-bytes=4 \
--with-boundary-id-bytes=4 \
--with-unique-id-bytes=4 \
```
which are all non-default options that we don't test with regularly or at all.

@roystgnr do you think this would be a factor in us not being able to reproduce David's issue? If you think it's worthwhile, I can test out a build with these different size ids.

**Comment by dknez** [comment]
I then checked out 2d9377 and the example failed in that case.

**Comment by jwpeterson** [comment]
@dknez did you by chance recently update either MPI or PETSc or some other part of your software stack other than libmesh, or is this an environment you've been using successfully for a while?

**Comment by dknez** [comment]
I haven't changed MPI or PETSc for a long while.

**Comment by dknez** [comment]
In any case, it seems to me that the issue is due to 2d9377d since 79aa160 works and 2d9377d doesn't. Is that plausible?

I'd like to try to revert that commit if possible, but as I said above I tried "git revert 2d9377d" and that didn't work cleanly for me.

**Comment by dknez** [comment]
Yeah, I guess later commits depend on it, which is why there are compilation errors once the conflicts are resolved.

**Comment by roystgnr** [comment]
It's definitely plausible that 2d9377d is broken.  MPI_Pack and MPI_Unpack might be the "right" way to do things, but that doesn't mean I understand them well enough to use them properly.

If that's the only thing that's broken, though, we're in good shape - I can prepare a PR that just reverts that particular implementation of the vec_of_vec communications, and falls back on the more hackish implementation, which should *still* be enough to allow Derek's communication optimizations to work without being reverted.

**Comment by roystgnr** [comment]
@jwpeterson I can't see how the id sizes could cause this problem but honestly I can't see how anything *else* could either, so I'd say give it a shot!

**Comment by dknez** [comment]
I use openmpi, so maybe that's the issue?

**Comment by jwpeterson** [comment]
> I use openmpi, so maybe that's the issue?

I'm leaning towards it, unless @roystgnr comes back saying he's using openmpi.

**Comment by jwpeterson** [comment]
So, on the MOOSE side we have stopped including an OpenMPI software stack in our binary redistributable package... we basically have no test coverage for that at the moment, but I can see how it would be useful when writing new/refactoring old MPI code to make sure it works with all the popular implementations. OpenMPI is the default on Ubuntu, which is probably the biggest part of our Linux userbase.

**Comment by roystgnr** [comment]
With OpenMPI I get an MPI error rather than an unexpected allocation error, but I *DO* get an error!  I'll see if I can figure out why.
