### ISSUE TITLE
Improve exception safety with smart pointers

### ISSUE THREAD

**Issue by elfring** [libMesh/libmesh#170]
Would you like to wrap any pointer data members with the template class "[std::unique_ptr](http://en.wikipedia.org/wiki/Smart_pointer#unique_ptr "a smart pointer")"?

Update candidate: [DofMap](https://github.com/libMesh/libmesh/blob/46ff3ed791b9c9ae8ce5292c124d95f02c8327d3/include/base/dof_map.h#L135 "DofMap class")

**Comment by jwpeterson** [comment]
As of #357, you can configure libmesh with `--enable-unique-ptr` and libmesh will use a non-deprecated smart pointer type appropriate to your compiler.
