### ISSUE TITLE
MessageTag copies should be attached to Requests using them

### ISSUE THREAD

**Issue by roystgnr** [libMesh/libmesh#1709]
We haven't actually triggered this issue yet, but with parallel communications that return Request objects for later completion it's now a risk.  The current lifetime of a unique tag ends when the MessageTag object is destructed, so if we create a local MessageTag, use it for non-blocking Parallel method, then exit the scope without a wait() on all corresponding Request(s), it is possible for a subsequent MessageTag creation to allocate the same tag number.

Non-blocking Parallel:: methods should probably copy the MessageTag they're given and only delete the copy when they're done with a wait(), so the reference counting will let the Communicator know not to reuse the same tag value.

We should also have a unit test that makes sure this is true.

**Comment by friedmud** [comment]
Nice catch!  Hadn’t thought of that.

In my own code I create the tags in a global scope actually (or at least class scope) so they live during the whole execution of the program.

**Comment by roystgnr** [comment]
I can't take too much credit; I investigated this while tracking down a refactoring bug.  Tag reuse wasn't the cause of that bug, but I looked into it closely enough to realize that we were bug-free in this respect only by luck and timidity, not by design.

**Comment by roystgnr** [comment]
Resolved by #1741
