### ISSUE TITLE
Problems configuring with PGI

### ISSUE THREAD

**Issue by RonRahaman** [libMesh/libmesh#1730]
I've got some problems configuring libmesh with new-ish versions of the PGI compilers (v17.10) and was wondering if you had any pointers.  

## Compiler identification 
I think I've got this fixed (see below).  Looks like the issue is that, with the `-V` flag, newer versions call themselves the "PGI Compilers and Tools"  instead of "Portland Group Something Something".   
``` Diff
--- a/m4/compiler.m4
+++ b/m4/compiler.m4
@@ -274,7 +274,7 @@ AC_DEFUN([DETERMINE_CXX_BRAND],
   dnl Portland Group C++?
   AS_IF([test "x$compiler_brand_detected" = "xno"],
         [
-          is_pgcc="`($CXX -V 2>&1) | grep 'Portland Group'`"
+          is_pgcc="`($CXX -V 2>&1) | grep 'Portland Group\|PGI'`"
           AS_IF([test "x$is_pgcc" != "x"],
           [
             AC_MSG_RESULT(<<< C++ compiler is Portland Group C++ >>>)
```

## Enabling C++ 11 for conftests
I'm stuck on this issue.  The conftest for `unordered_multimap` fails because I need to add the `-std=c++11` flag.  However, if i set `CXXFLAGS='-std=c++11`, it doesn't seem to get passed along to the conftest.  See the error from config.log below.  Note the compile line doesn't include the `-std` flag.  
```
configure:29427: checking whether the compiler supports std::unordered_multimap
configure:29455: mpicxx -c -g --no_using_std     conftest.cpp >&5
"/usr/include/c++/4.8.5/bits/c++0x_warning.h", line 32: catastrophic error:
          #error directive: This file requires compiler and library support for
          the ISO C++ 2011 standard. This support is currently experimental,
          and must be enabled with the -std=c++11 or -std=gnu++11 compiler
          options.
  #error This file requires compiler and library support for the \
   ^

1 catastrophic error detected in the compilation of "conftest.cpp".
Compilation terminated.
```

**Comment by jwpeterson** [comment]
The configure tests should definitely detect and use the `-std=c++11` flag, I'm not sure why it's missing for you... it would probably be helpful if you could send me your entire config.log file.

I will also say that we have been unable to use the Portland Group C++ compiler for many years, so it would be nice if it is finally working!

The change to compiler.m4 looks like a good one.

**Comment by RonRahaman** [comment]
Here's my config.log.  Let me know if you have trouble viewing it:
https://www.dropbox.com/s/nb0azypwoyxtlzm/config.log?dl=0

**Comment by RonRahaman** [comment]
I started a PR with my fixes so far (PR #1731)  I've marked it WIP, since the build process is proceeding much further but now gets stuck at the link stage.  I think the linker errors might be particular to my setup.  I will keep you posted.

**Comment by jwpeterson** [comment]
I'm closing this, since I think @RonRahaman got this working.

**Comment by RonRahaman** [comment]
If I put a phrase like "Fixes #some_issue" in the commit message or PR, and then the PR is merged, will it automagically close the respective issue?

**Comment by jwpeterson** [comment]
Yes, that is a [GitHub feature](https://help.github.com/articles/closing-issues-using-keywords/).
