### ISSUE TITLE
Regression with --use-petsc-dm

### ISSUE THREAD

**Issue by roystgnr** [libMesh/libmesh#1752]
This was reported by Ata Mesgarnejad last month but I didn't find time to look into it until now.

> The new implementation of the libMeshDM unfortunately fails when using variational inequality solvers VINEWTONRSLS or VINEWTONSSLS (for example miscellaneous/ex7). This happens when PETSc tries to VecDuplicate the solution vector for lower bound in src/snes/impls/vi/vi.c: 383 ?! 

To replicate, in miscellaneous_ex7, run
```
./example-opt --verbose dim=1 N=1024 initial_state=strip initial_center=0.5 initial_width=0.1 dt=1e-10 max_time=.5e-8 -snes_type vinewtonssls --use-petsc-dm
```

> This generates a seg fault on my mac with the PETSc and libMesh revisions I provided before.
>
> My guess is the seg fault happens probably because the solution vector is not initiated correctly.

The failure in misc ex7 was triggered by #1572

@fdkong, any ideas?  Any other takers?  I'm afraid I'm not familiar with either the code that's breaking *or* the code that broke it.

**Comment by fdkong** [comment]
I think I know what is going on here. We encountered the same issue when using SNESVI in moose.  Does not cause a big concern in MOOSE because we do not use VI at all at this point.  

But I will fix it with a PR soon.

**Comment by pbauman** [comment]
OK, I didn't respond to this originally because I assumed it wasn't related to (unmarked) #1568. However, I noticed you've included the command line flag that I wanted to introduce in #1568. I wanted to confirm that you really need that. Specifically `--use-petsc-dm`. If so, then I need to reconcile.

**Comment by roystgnr** [comment]
Huh, now I'm more confused.  I'm just using what Ata emailed us, but I didn't think #1568 was involved.

Anyway, #1568 isn't critical.  Adding ```--use-petsc-dm``` isn't necessary to get the segfault; ```-snes_type vinewtonssls``` is enough to trigger the breakage.

71ea119 segfaults with the above test even with ```--use-petsc-dm``` stripped so long as ```-snes_type vinewtonssls``` is still specified, and b3bf5cd completes regardless.

**Comment by BobBobbins** [comment]
This is causing some of my MOOSE apps to core dump when using bounded variables with -snes_type vinewtonssls and -snes_type vinewtonrsls

**Comment by jwpeterson** [comment]
@fdkong's commit message closed this issue automatically; if it is still not resolved, please reopen.

**Comment by roystgnr** [comment]
Fixed it for me, at least.

**Comment by BobBobbins** [comment]
Yep thanks for fixing this. Appreciate it.
