### ISSUE TITLE
Outdated Makefile.in

### ISSUE THREAD

**Issue by mquevill** [libMesh/libmesh#1754]
The file located at contrib/utils/Makefile.in is out of date. It includes a nonexistent `$(LIBMESH_DIR)/Make.common` and uses the `make_dependencies.pl` script that was removed in #1318 (commit 9dcd46b).

Excerpt from contrib/utils/Makefile.in:
```
.depend: $(srcfiles) $(LIBMESH_DIR)/include/libmesh/*.h
    @$(perl) $(LIBMESH_DIR)/contrib/bin/make_dependencies.pl
```

**Comment by jwpeterson** [comment]
Thanks for reporting this. In my `$(LIBMESH_DIR)` I do have a Make.common file, it is symbolically linked to a file in `$LIBMESH_DIR/etc/libmesh`. $LIBMESH_DIR here refers to the *installation* dir, not the source tree. 

The .depend target is definitely out of date and there is some other weird stuff (the `gmv` target refers to `$(LIBMESH_DIR)/roy`, for example) that could definitely be cleaned up.
