### ISSUE TITLE
Make.common missing references to METHOD=prof

### ISSUE THREAD

**Issue by bboutkov** [libMesh/libmesh#1776]
Hi all, after building the library with `--enable-everything --with-methods="devel prof oprof"` I was trying to build / profile some examples and noticed that my Make.common didn't seem to have any reference to prof/pro/profiling builds:
```
/install/examples/introduction/ex1$ METHOD=prof make
/bender1/data/users/borisbou/software/master/libmesh/install/Make.common:115: *** Invalid environment variable METHOD=prof specified.
```
For now as a quick workaround I drop in the following snippet directly into the installed Make.common and things build as expected, but since I wasn't sure of the proper fix, I thought I'd log this issue for later. Thanks!

```# If METHOD=prof, compile in profile mode.                                                                                                                                                                                                     
ifeq ($(METHOD),prof)
  prof-mode := on
  mode       := "prof"
endif
```

**Comment by roystgnr** [comment]
Huh.  It looks like we had the same problem with oprof, and @permcody fixed it in 2013, and nobody noticed that prof support there was incomplete too.  I'll make a PR.
