### ISSUE TITLE
Compiler Warning parmetis_partitioner.C

### ISSUE THREAD

**Issue by pbauman** [libMesh/libmesh#1793]
Saw this while compiling from scratch. Don't have time ATM to cook up PR, sorry.

<pre>
../../pbauman/src/partitioning/parmetis_partitioner.C: In member function ‘virtual void libMesh::ParmetisPartitioner::_do_repartition(libMesh::MeshBase&, unsigned int)’:
../../pbauman/src/partitioning/parmetis_partitioner.C:194:95: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
   this->assign_partitioning (mesh, reinterpret_cast<std::vector<dof_id_type> &> (_pmetis->part));
</pre>

<pre>
[10:57:01][pbauman@fry:~]$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/fry1/data/shared/software/apps/gcc/7.2.0/libexec/gcc/x86_64-pc-linux-gnu/7.2.0/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /fry1/data/shared/software/sourcesdir/gcc/gcc-7.2.0-src/configure --prefix=/fry1/data/shared/software/apps/gcc/7.2.0 --with-gmp=/fry1/data/shared/software/libs/gmp/6.1.1 --with-mpfr=/fry1/data/shared/software/libs/mpfr/3.1.5 --with-mpc=/fry1/data/shared/software/libs/mpc/1.0.3 --disable-multilib --enable-languages=c,c++,fortran --enable-lto
Thread model: posix
gcc version 7.2.0 (GCC) 
</pre>

**Comment by jwpeterson** [comment]
That's... annoying. We should be able to see this on CIVET as well, since I believe we have GCC 7.x targets. Do you see this warning in opt, dbg, and devel modes?

**Comment by roystgnr** [comment]
I get this too, only in devel mode.  I'm looking at warnings in another branch already; let me see if I can find a fix for this to slip in there.
