### ISSUE TITLE
DTK_MeshContainer.hpp: No such file or directory

### ISSUE THREAD

**Issue by yw5aj** [libMesh/libmesh#1849]
Dear all, 

Sorry for bothering. Could you please help me install libmesh?

I am using Windows 10 64 bit, Windows Subsystem Linux, Ubuntu 18.04. I have done:

```
git clone git://github.com/libMesh/libmesh.git 
cd libmesh
./configure
make
```

The process went on perfect until this happened:

```
In file included from ./include/libmesh/dtk_adapter.h:27:0,
                 from src/solution_transfer/dtk_adapter.C:24:
./include/libmesh/dtk_evaluator.h:31:10: fatal error: DTK_MeshContainer.hpp: No such file or directory
 #include <DTK_MeshContainer.hpp>
          ^~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
Makefile:16028: recipe for target 'src/solution_transfer/libmesh_dbg_la-dtk_adapter.lo' failed
make[1]: *** [src/solution_transfer/libmesh_dbg_la-dtk_adapter.lo] Error 1
make[1]: Leaving directory '/mnt/x/libmesh/libmesh'
Makefile:29399: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
```

And I checked that `DTK_MeshContainer.hpp` is not in the source code.

Was I doing something wrong? Any hint would be greatly appreciated.

Best,
Shawn

**Comment by pbauman** [comment]
> And I checked that DTK_MeshContainer.hpp is not in the source code.

That's an external header, part of DTK package in Trillions.

Please post your config.log file? It looks like configure thinks you have Trilinos and DTK, but it's not finding it when you build. Or that particular part of Trilinos has changed up their header files. Or something along those lines.
