### ISSUE TITLE
configure: Disable Trilinos when configuring --with-dof-id-bytes=8

### ISSUE THREAD

**Issue by jwpeterson** [libMesh/libmesh#1851]
I'm not sure if this is our fault or Trilinos' (surely they don't have all indices hard-coded to `int`?) but our `numeric_trilinos_cast` helper function assumes this:
```
int * numeric_trilinos_cast(const numeric_index_type * p)
{
  return reinterpret_cast<int *>(const_cast<numeric_index_type *>(p));
}
```
and we also assert it in a few places, e.g.
```
libmesh_assert_equal_to (sizeof(numeric_index_type), sizeof(int));
```

The right solution is probably to just disable Trilinos at configure time if the user configures with `--with-dof-id-bytes=8`.

**Comment by roystgnr** [comment]
Neither our fault nor theirs, I think; they didn't add a "long long" option until Trilinos 11, so it's reasonable that we hardcoded int too, but they do have it working now and we should eventually upgrade.

But in the meantime, simply disabling Trilinos when our type sizes don't match is the right workaround.
