### ISSUE TITLE
Vary order of a variable on different subdomains

### ISSUE THREAD

**Issue by dknez** [libMesh/libmesh#1861]
An issue that I'm currently running into is that I'd like to be able to change the variable order for a variable on different subdomains. The main use-case for this is in structural analysis where you have beams and shells, and you want, say, second-order variables on beams but first order on shells (this is a very typical case). For both element types we use the same 6 variables (u,v,w,theta_x,theta_y,theta_z).

I started some discussion on this in a libmesh-users thread, where I wondered if p-refinement could be used for this, but it didn't seem like a good fit (primarily because we use LAGRANGE variables, which are not compatible with p-refinement).

So I'm wondering if there's any reasonable way to address this issue? One thing I wondered about was enabling an option for per-subdomain variable orders (similar to how we can have variables that are active or inactive on subdomains).

I'll be happy to work on this issue, but I wanted to brainstorm a bit on whether there is a reasonable way to proceed here.

**Comment by roystgnr** [comment]
Lagrange variables don't handle constraints for adaptive p refinement, and I don't think they handle projection after p refinement/coarsening... but neither of those applies in your case, right?  You'll be starting the quadratic elements at extra_p=1 from the get-go, so no projections, and if you'll only be connecting each beam to a shell at only one node then there's no constraints either.

On the other hand I like the per-subdomain variable order idea and if you want to implement it I'm definitely not going to object.  Create ```System::add_variable(s)``` overloads where instead of an optional ```set<subdomain_id_type>``` we have a ```map<subdomain_id_type, unsigned char>```?  Then add a corresponding map member to ```Variable```?

**Comment by dknez** [comment]
OK, thanks very much for this info.

> Lagrange variables don't handle constraints for adaptive p refinement, and I don't think they handle projection after p refinement/coarsening... but neither of those applies in your case, right? You'll be starting the quadratic elements at extra_p=1 from the get-go, so no projections, and if you'll only be connecting each beam to a shell at only one node then there's no constraints either.

Yes, you're right. So it sounds like I could define the variables as first order, and set extra_p=1 everywhere that I need it. I agree, that should work! (I think I fell victim to your favorite XY-problem in my original question on the email list, I should have described what I was trying to achieve, rather than ask a more general question about p-refinement.)

> On the other hand I like the per-subdomain variable order idea and if you want to implement it I'm definitely not going to object. Create System::add_variable(s) overloads where instead of an optional set<subdomain_id_type> we have a map<subdomain_id_type, unsigned char>? Then add a corresponding map member to Variable?

I agree that this would be a nice feature. I'll look into this too, thanks.

**Comment by dknez** [comment]
I will use Roy's first suggestion, i.e. use the p-level functionality. As a result, no change in libMesh is needed and I'll close this issue.
