### ISSUE TITLE
issue with example reduced_basis_7: PETSc >= 3.9 / no MUMPs

### ISSUE THREAD

**Issue by BalticPinguin** [libMesh/libmesh#1890]
I am compiling against the git-branch (3.10.1) from PETSc and saw that
the option ``-pc_factor_mat_solver_package`` is deprecated (since 3.9.) and is replaced by ``-pc_factor_mat_solver_type``.
Moreover, when Petsc is configured without Mumps, this option should not be used.

As I see it, the 'run.sh'-files are not touched by any configure-step. Is there some other (easy) way to switch between the name of arguments? 
The more important issue is: If PETSc is configured without Mumps, this should not be used at all.
One can of course skip this example, but it runs with just 
``options="-online_mode 0 -ksp_type preonly -pc_type lu"``.
Would you still skip it or do you have some standard way to run examples differently depending on the configuration?

**Comment by jwpeterson** [comment]
Hmm... the right way to handle this might be programmatically instead of as a command line option, which as you pointed out is more difficult to configure for.

**Comment by BalticPinguin** [comment]
As I see it, forcing the use of MUMPS is rather new (2 jears old).
Depending on what the actual reason for this was, one can either run the example without mumps or do not use this option from command line but from within the code, depending on the configuration.

**Comment by roystgnr** [comment]
The original behavior was "just break unless the user manually specified a direct solver", acc4cc5b added "but with a nice message", and #955 added the automatic call to MUMPS (which just didn't break).

run_unit_tests.sh is generated by configure from run_unit_tests.sh.in, and we could do the same for this run.sh if we needed to.  I know automake gives test scripts a bunch of standard environment variables like ```$srcdir``` but I don't know of any well-supported way to add to that environment.  Programmatic selection sounds like a good idea, if we make sure to return skip rather than fail when we're in parallel without MUMPS.

**Comment by BalticPinguin** [comment]
ah; ok.
In other words: one can just add a `` libmesh_example_requires(mumps)``-flag to the example because it will break without it in some cases? (In my case, it doesn't break without specification of a solver).
But now I understand at least why things are that way and where to look for configure-options; I will have a look at the configure-options; maybe I can find something nice. Thanks for these infos so far.

**Comment by BalticPinguin** [comment]
I am trying to fix this issue; but it is not so easy, since I don't see an option to obtain the PETSc-object in the reduced_basis_ex7.C which one would need to set the solver-type programmatically.

But I'd like to open up @jwpeterson s question
[> I take it this does it not work with just straight -pc_type lu?](https://github.com/libMesh/libmesh/pull/955#issuecomment-221900655)
What is the reason to explicitly use Mumps for solving? According to the discussion, it is somewhat related to parallelisation, but probably you can explain me the issue briefly?

I currently have the impression that it might be best to avoid this option in some way: There seems to be no variable indicating whether mumps is enabled (also not in petsc). If it fails without this option, probably it is ok to let it fail if mumps is disabled and in addition ignore the deprecated name? This seems to have no easy solution as well...
