### ISSUE TITLE
Scaling for 2D problems

### ISSUE THREAD

**Issue by manavbhatia** [libMesh/libmesh#1897]
Hi, 
  
  I am doing some scaling studies for my 2D plate bending analysis built on libMesh. I am using MUMPS for the linear solve. This is on a machine with 20 CPUs per node and an FDR infiniband interconnect. 
 
  For a mesh with 400x400 elements (~965K dofs) an analysis with DistributedMesh scales near linearly till about 40 processes. After this the cost of MeshCommunication (::find_global_indices(), ::compute_hilbert_indices(), ::parallel_sort()) starts to overshadow the total active time (greater than 50%). 

   Running the same problem with ReplicatedMesh then causes Parallel::allgather() to be the largest chunk of the active time, which is ~2.5-4 times higher than the same case with DistributedMesh. 

   I am writing to check if this is expected. Note that this is only a single linear solve on this mesh. So, if this is a one time problem setup cost then it may be a relatively smaller overhead for nonlinear or transient simulations.  

   Any guidance will be appreciated. 

Thanks,
Manav

**Comment by jwpeterson** [comment]
> scales near linearly till about 40 processes.

Are those 40 processes running on two nodes (since you mentioned 20 cores/node)? Are you using libMesh master? @roystgnr has done some parallel optimizations recently in these functions so it would be good to know what version of the code you are using.

**Comment by manavbhatia** [comment]
Yes, these were running on 2 nodes. 
My libmesh version, I just realized, is over a year old: commit `f83f92ecc9f789b31912d37e07753ff78c20308a` from Aug 16, 2017. 

I will update and try the same.

**Comment by jwpeterson** [comment]
That commit is from August 2018, but yeah, it wouldn't hurt to still update.

**Comment by manavbhatia** [comment]
You are correct. I misread the log. 
Will try updating.

**Comment by roystgnr** [comment]
Hmmm... my parallel optimization work actually mostly went in shortly *before* that commit.... there was some subsequent optimization in MeshCommunication::redistribute(), and some more w.r.t. ghosting that might have helped, but I fear your new results won't differ enough from your previous.

I'd love to get a perf tree of your results or even just the PerfLog output to start with.
