### ISSUE TITLE
Partitioning a 0 element mesh throws an assert

### ISSUE THREAD

**Issue by jwpeterson** [libMesh/libmesh#1905]
Currently, if someone calls `prepare_for_use()` on an empty (zero element) mesh, the number of partitions gets set to 0 by this line:

https://github.com/libMesh/libmesh/blob/5e3620b01bc1ab478de8ae8c6786714095f2148a/src/partitioning/partitioner.C#L69-L71

Then we end up calling `_do_partition` with `n_parts==0`,

https://github.com/libMesh/libmesh/blob/5e3620b01bc1ab478de8ae8c6786714095f2148a/src/partitioning/partitioner.C#L86

and this eventually triggers an assert in `MetisPartitioner`:

https://github.com/libMesh/libmesh/blob/5e3620b01bc1ab478de8ae8c6786714095f2148a/src/partitioning/metis_partitioner.C#L61

It seems to me, however, that this doesn't need to be an error, but simply an early return. @leorachapuis ran into this while working on some mesh generation stuff...

**Comment by roystgnr** [comment]
This should be easy to fix.  I'll add some unit tests while I'm at it.
