### ISSUE TITLE
Hardwired return type of norm methods

### ISSUE THREAD

**Issue by lindsayad** [libMesh/libmesh#1923]
Methods like `norm` on `TypeTensor` and `TypeVector` are hard-wired to return a `Real`. This is problematic for automatic differentiation calculations where `T = DualNumber<>`

**Comment by roystgnr** [comment]
Yeah, that's a problem.  We don't just want to return T, because that's not right when ```T==std::complex<U>```, but we ought to be able to do a trailing return type (using std::norm?) now.

**Comment by lindsayad** [comment]
We don't yet have a `std::complex` overload for `DualNumber`. Are `DualNumbers` intended to be able to work with complex numbers? Currently all the unary operators defined for `DualNumber<T,D>` return a `DualNumber<T,D>`. If we intend to support complex numbers, then it seems right that the function `norm(DualNumber<std::complex<T>>)` should return a `DualNumber<T>`.

**Comment by roystgnr** [comment]
> Are DualNumbers intended to be able to work with complex numbers?

Only in the sense that they're intended to be able to work with anything else that can act like a scalar; you'll need more than that for this level of use.  In particular, the DualNumber implementation for abs is broken in the complex case, and there's no DualNumber implementation at all for norm (or real, imag, arg, conj...), and I'd want to double check the other derivative calculations to make sure none of them are broken in a more subtle way than abs (which would at least scream and die at compile time rather than undermining you at runtime).

**Comment by lindsayad** [comment]
> there's no DualNumber implementation at all for norm (or real, imag, arg, conj...)

Moreover, the real, imaginary, conjugate, and norm operators are not complex differentiable (had to brush up on my complex calculus). Given that, I'm not sure about a trailing return type with `std::norm` since an `std::norm` overload doesn't make sense for `DualNumber` in general (e.g. df/dz does not exist for f = norm operator).

**Comment by lindsayad** [comment]
I was thinking that we could go ahead and write a general `std::norm` for `DualNumber` and then produce a compilation error if someone attempts to call `std::norm(DualNumber<std::complex>)`. Then we could go ahead and use `std::norm(T())` as the trailing return type. (`std::abs(T())` would also do the job)

**Comment by roystgnr** [comment]
We'd have to set the derivatives to NaN for those functions in the complex case.  But that's what we'd want to do anyway, right?  And then once that was done then we'd get the right answers from the trailing return type, right?  real for Real or Complex, real-with-real-derivative for ```DualNumber<Real>```, real-with-NaN-derivative for ```DualNumber<complex>```?

**Comment by roystgnr** [comment]
I'm generally of the opinion that compile-time errors are better than run-time errors, I'm just not sure this qualifies as an error.  Anyone using DualNumber ought to be prepared to hit cases where the derivative isn't uniquely defined; that doesn't mean we disallow users from calling such functions, it just means that their code has to be robust there.  Admittedly, complex functions where no derivative makes sense take this philosophy further than I'd originally imagined it going...

**Comment by lindsayad** [comment]
I like your reasoning. I can submit the metaphysicl PR (tomorrow) if you don’t get there first.

**Comment by lindsayad** [comment]
Closed by #1946
