### ISSUE TITLE
UnstructuredMesh::contract() Clearing Point Locators

### ISSUE THREAD

**Issue by friedmud** [libMesh/libmesh#1927]
I'm running into an issue where `UnstructuredMesh::contract()` is clearing the PointLocator from the Mesh... but then it's needed by `DefaultCoupling` during a threaded loop - which causes an error in debug:

![screen shot 2018-10-30 at 11 05 36 am](https://user-images.githubusercontent.com/870705/47863582-360a4400-ddbd-11e8-91a1-535b5194b2b0.png)

I've tracked it down to this `contract()` call:

![screen shot 2018-10-31 at 12 19 06 pm](https://user-images.githubusercontent.com/870705/47863567-2ab71880-ddbd-11e8-95ed-ed4aae776acf.png)

The issue is that there is no way for me to fix this.  It all happens within the same call to `EquationSystems::reinit()`.  If I add a `mesh.sub_point_locator()` call to `DofMap::build_sparsity()` just before the threaded call... then it works fine.

One thing we could do is actually do a doubly-checked lock (with memory fencing) in `MeshBase::sub_point_locator()` so that it is actually thread safe... then we could remove the restriction.

**Comment by roystgnr** [comment]
> If I add a mesh.sub_point_locator() call to DofMap::build_sparsity() just before the threaded call... then it works fine.

Hmm... that's our "standard" way to handle this, but I don't think it's appropriate here.  DefaultCoupling doesn't even need a PointLocator unless there are periodic BCs in play, and I'd hate to construct one unnecessarily!

> One thing we could do is actually do a doubly-checked lock (with memory fencing) in MeshBase::sub_point_locator() so that it is actually thread safe... then we could remove the restriction.

Like what we do in PetscVector::_get_array?  That sounds great to me!  Would you be up to writing this instance too?  Or better yet, encapsulate the idiom so it's more accessible to mortals?  The details of C++11 memory fence APIs aren't *too* awful, but boy the failure mode is.  Runtime errors that might only happen one time in a million occupy the lowest circle in runtime error hell.

**Comment by friedmud** [comment]
Yeah - I can write this one up.  I'm not sure about abstracting it though - but I'll think about it while I do it.

It will be easier now for sure though: because now that we officially support C++11 we can just write it in pure C++11 and avoid all the C++03 compatible hacks I had to do back in the day for `PetscVector::_get_array()`

**Comment by friedmud** [comment]
Well crap.  I put in a doubly-checked lock... but ran into the next problem:

`PointLocatorTree::init()` calls `MeshTools::create_bounding_box()` which calls `Threads::parallel_reduce()`.  Unfortunately - since this is already happening inside of a `Threads::parallel_reduce()` (from `DofMap::build_sparsity()`)... the `Threads::BoolAcquire()` fails...

Basically - the pthreads implementation of `parallel_reduce()` is set up to not allow multiple nested `parallel_reduce()` calls (which is probably a good thing... because pthreads don't have a thread pool - so you would just trash your CPUs with `n_threads*n_threads` threads).

But what's the fix here?  We know that `PointLocator::init()` is NOT being called on multiple threads (because of the doubly-checked lock)... would it be ok if I set `Threads::in_threads = false;` before initializing the `PointLocator`?  Then returning it to it's previous state after finishing that?

**Comment by friedmud** [comment]
Or maybe make `create_bounding_box()` just fall back to serial if it finds that it's running within threads?

Also: for both OpenMP and TBB this type of check is overzealous... because two threaded loops running inside of eachother won't create n_threads*n_threads threads... they will just happily pull from the thread pool.

**Comment by roystgnr** [comment]
> for both OpenMP and TBB this type of check is overzealous... because two threaded loops running inside of eachother won't create n_threads*n_threads threads... they will just happily pull from the thread pool.

Regardless of threading model, we'll end up with no more than a spike to 2*n_threads, right?  Because even if every entry on the outer threaded loop hits the point locator request, you're wrapping the point locator request in a mutex, and only one of the outer threads will spawn the inner threaded loop.

**Comment by friedmud** [comment]
Closing this as irrelevant now - it just wasn't a great idea.
