### ISSUE TITLE
Infinite elements don't find their finite neighbors

### ISSUE THREAD

**Issue by BalticPinguin** [libMesh/libmesh#1949]
Dear all,
after my recent update, the infinite elements miss their neighbors at side 0 (the interfacing finite element): ``elem->neighbor(0)`` is ``0``.
In my case, these are second-order ``Tets`` and ``InfPrism``, respectively.

According to my understanding, the problem is introduced by the change of the used ``side_ptr``-function in called by ``UnstructuredMesh::find_neighbors``:
   * The previously used  ``side_ptr(const unsigned int i)`` always puts a first-order side element; in the ``Tet``-class, the function ``me->side_ptr(i)`` should always give a ``TRI3``; in the ``InfPrism``-class, this is put explicitly.
   * using the respective  ``side_ptr  (std::unique_ptr< Elem > & side, const unsigned int i)``, the ``InfPrism``-version ensures that afterwards the side is of type ``TRI3`` while the ``Tet``-version calls ``build_side_ptr``, which should either be ``TRI3`` or ``TRI6``, depending on the order being used.
 
Without understanding the  ``key``-based part,  I could imagine that the keys don't match and the function ``find_neighbors`` does not work anymore, leaving the neighbor nr. 0 to be the null-pointer.

Do you agree with this argumentation or would you rather see the problem somewhere else? (I came to this because the only recent change related to the problem seems to be 7f7e62ea).
If you do, the is to make "The ``side`` is always the first-order" or " is always the real order" scheme consistent. Which one is preferable in this case?

Best,
Hubert

**Comment by BalticPinguin** [comment]
Ok, I have played with this and found that indeed, making side_ptr() and build_side_ptr()-calls consistent fixes this issue.
I would like to make a PR with this respect, but would like to hear some oppinion about which one to use? (I would assume that the side_ptr()-function is faster, but I would like to avoid breaking something due to wrong order).

Thanks in advance

**Comment by BalticPinguin** [comment]
Since my initial fix was not very good, I am working further on this. However, I came across a behaviour that I don't understand: The function
```Elem::simple_build_side_ptr (std::unique_ptr<Elem> & side, const unsigned int i,  ElemType sidetype) ``` (in `include/libmesh/elem.h:2254`) just ignores the sidetype given.
I would consider this as unexpected.
Probably @roystgnr or @jwpeterson could comment on this?

For the context: In the find_neighbor()-function, the side_ptr()-function is called which, for Tet10, calls the above-mentioned function, obtaining the second-order side (and not, as the side_ptr() functions usually do, the first-order counterpart).

**Comment by roystgnr** [comment]
On Wed, 12 Dec 2018, Hubert Weißmann wrote:

> Since my initial fix was not very good, I am working further on
> this. However, I came across a behaviour that I don't understand:
> The function Elem::simple_build_side_ptr (std::unique_ptr<Elem> &
> side, const unsigned int i, ElemType sidetype) (in
> include/libmesh/elem.h:2254) just ignores the sidetype given.

No, it uses the sidetype to determine when it needs to build a new
side from scratch rather than just altering values in an existing side
object.

> I would consider this as unexpected.
> Probably @roystgnr or @jwpeterson could comment on this?
> 
> For the context: In the find_neighbor()-function, the
> side_ptr()-function is called which, for Tet10, calls the
> above-mentioned function, obtaining the second-order side (and not,
> as the side_ptr() functions usually do, the first-order
> counterpart).

Ah, I think I see what's going wrong.  That's embarrassing.  I call
simple_build_side_ptr<Tet4>(), expecting it to act like a Tet4, but it
only does so for the Tet4::side_nodes_map, *not* when making the
virtual function call to this->build_side_ptr(), which still
dispatches to the Tet10 implementation.

Let me see if I can fix that and add some unit tests.

Thanks for pointing this out.  I'm guessing that you're using a hybrid
mesh with tets alongside pyramids or prisms, and that we don't have
any such meshes in our CI runs?
---
Roy

**Comment by BalticPinguin** [comment]
> Thanks for pointing this out. I'm guessing that you're using a hybrid
> mesh with tets alongside pyramids or prisms, and that we don't have 
>any such meshes in our CI runs?

Yes: I use a mesh made of `Tet10` and `InfPrism12`. Probably we can just change the `misc_ex1` or `misc_ex14` to use the second-order elements.

**Comment by roystgnr** [comment]
Huh.  How is this not already showing up on misc ex14?  We do the same "all sides are the same so optimize" trick on Hex elements, and the Hex27 elements we build there should trigger the same "builds a high order face when we expected a low order face" bug when we do so, and then find_neighbors should fail to keep the infinite elements connected.

**Comment by BalticPinguin** [comment]
Fixed by #1977.

**Comment by BalticPinguin** [comment]
Closing now.
