### ISSUE TITLE
const functions in FEMap

### ISSUE THREAD

**Issue by BalticPinguin** [libMesh/libmesh#1976]
Dear all,
This must be rather a problem of my understanding than a problem of libMesh, but since google didn't help, I'd still like to ask the experts themselves:
In the FEMap()-class, there are several functions `get_whatever()` which are declared as const functions, but they set the variables `calculate_(d)xyz=true`.
According to my understanding, this should even not compile; but why is this working? Should not be a 'const' function be forbidden to change any variables?

Best regards and many thanks in advance,
Hubert

**Comment by jwpeterson** [comment]
Those flags are marked mutable, so they can be changed even in const functions..

**Comment by BalticPinguin** [comment]
Ok, that makes sense. This is one of the points of mutable I didn't know. 
Thanks for the explanation!
