### ISSUE TITLE
DG with libmesh

### ISSUE THREAD

**Issue by manavbhatia** [libMesh/libmesh#1978]
I am interested in doing high order DG with Legendre basis functions. I see that libMesh has Legendre and Jacobi basis support but it seems to be tied into the infinite elements. 

Outside of this, there seems to be support for DG with Lagrange and monomials  (#1437 ). 

I am curious if it may be possible to use the existing Legendre basis implementation for DG. If currently this is only available for infinite FE, what would be needed to make this happen?

**Comment by roystgnr** [comment]
It would be easy enough for you to pull the legendre_eval stuff out of inf_fe_legendre_eval; then you'd implement the fe_l2_legendre*.C code by starting from fe_monomial*.C and replacing the simpler shape functions with tensor products of eval_legendre() outputs.  Likewise with either of the jacobi_*_eval functions.

This would give you cross-terms in the bases, though, which might be less efficient than you'd want for high p.
