### ISSUE TITLE
Resolution of hanging-node constraints incorrect for matrix-free/finite difference formation of Jacobian

### ISSUE THREAD

**Issue by lindsayad** [libMesh/libmesh#1985]
My understanding of the current set-up for a Newton solve (with PETSc at least) *with user-provided Jacobian and preconditioner*:

1. `SNESComputeFunction` gets called -> callback to libMesh
2. Enforce constraints on `current_local_solution`
3. Call the residual function or functor
    1. While computing the residual, make sure to call `constrain_element_vector` during assembly. This zeros the residual of the constrained dof (and modifies the residuals of the un-constrained dofs which determine the constrained dof)
4. `SNESComputeJacobian` gets called -> callback to libMesh
5. Enforce constraints on `current_local_solution`
6. Call the Jacobian function or functor
    1. While computing the Jacobian, make sure to call `constrain_element_matrix` during assembly. This puts a 1 on the diagonal for the constrained dofs and zeros elsewhere. In conjunction with 3i) this enforces delta_u_constrained_dof = 0
7. `SNESSolve` finishes and then we enforce the constraints exactly on the parallel solution vector

So this works great. The problems occur when we approximate the action of the Jacobian with a matrix-free method **or** any time the preconditioner/Jacobian is computed using finite differences. In that case if one is using the same function for computing the "nonlinear" residual and either the "linear" residual (for matrix-free) or columns of the Jacobian matrix/preconditioner (for a finite-differenced matrix), then it will appear to the linear operator as if the constrained dof depends on **nothing**. 

Consider this mesh:

![mesh](https://user-images.githubusercontent.com/10248304/50662625-4dec7880-0f64-11e9-8eb1-c1e6a9160dbc.png)

The resulting hand-coded Jacobian row for the hanging-node using `constrain_element_matrix` (note that the diagonal is doubled because two elements contribute to it):
row 6: (1, 0.)  (2, 0.)  (4, 0.)  (5, 0.)  (6, 2.)  (9, 0.) 

And the resulting finite-differenced Jacobian row for the hanging-node:
row 6: (1, 0.)  (2, 0.)  (4, 0.)  (5, 0.)  (6, 0.)  (9, 0.) 

So our operator is now singular because we zero this dof's residual every time we call our function! My suggestion to fix this:

- Don't enforce constraints exactly
- Form an actual residual for the "constrained" dof, e.g. .5 * u1 + .5 * u2 - u6 = 0
- And subsequently also form an actual Jacobian as well, e.g. J61 = 0.5, J62 = 0.5, J66 = -1
- These would override the residuals that would fall out of the pde discretizations, so they might be called from the exact same places in assembly as they're currently called.

This would be a fairly large conceptual change. Thoughts? I'm certain there are use cases where the current approach may be better and/or even necessary.

**Comment by roystgnr** [comment]
Sorry for being dumb, but could you walk me through this?  I avoided this problem in FEMSystem by doing all the finite differencing pre-constraint-application, but it seems like post-constraint-application would work just fine too:

PETSc has a solution candidate ```x```.  We enforce constraints on it, getting ```u := C x```.  We evaluate a residual, say ```r(u) := f - K u``` for a linear problem to be simple.  We ```constrain_element_vector``` during assembly of that, getting ```C^T r = C^T f - C^T K u = C^T f - C^T K C x```, so when we take dr/dx we should still get ```C^T K C```, and the effective pre- and post- multiplication there is exactly what we *would* have done in ```constrain_element_matrix```.

You can definitely form an actual residual for constrained dofs, though - that's the original and still the default behavior, even, with asymmetric_constraint_rows = true!  IIRC the only troubles with it were that it breaks iterative solvers that expect a symmetric matrix, and that it can allow constraint values to "drift" in some circumstances with repeated use of inexact solvers, forcing you to ```enforce_constraints_exactly``` anyways, at which point you might as well not bother making the solver worry about the constraint equation in the first place.

**Comment by lindsayad** [comment]
@roystgnr #1986 shows my idea for constraint application... It's currently only failing (by a very small exodiff) a periodic boundary condition test in MOOSE. Periodic BCs are another area aside from hanging node constraints where our function evaluation (at least as done from MOOSE) is wrong according to @fdkong so the fact that this test has been hit is a good sign from my perspective...

**Comment by roystgnr** [comment]
x contains both constrained and unconstrained dofs, but the constrained dofs get ignored and we put some "filler" in their place to keep the solver happy.

So I guess the trouble with FDM is that we don't get the proper filler.

Imagine we're solving -2u''=f on a single EDGE2 from 0 to 1, with a homogeneous Dirichlet constraint at x=0 and a homogeneous Neumann constraint at x=1.  Then ```K=[2 -2; -2 2]```, ```f=[.5 .5]'```, and under our restriction where we have to keep constrained dofs around to maintain the original sparsity pattern,  ```C=[0 0; 0 1]```.  So ```C'*K*C = [0 0; 0 2]```, ```C'*f = [0 .5]'```, but in libMesh with the symmetric option on we use ```[1 0; 0 2]``` to keep the system SPD and we correct the constrained dof afterward.  If we define ```r = Ku-f``` then we have ```C'*r = [0; -.5-2*u1+2*u2]``` and FDM of that gives ```[0 0; -2 2]``` and we've got nothing in the constrained row.  The problem is that the system is still consistent but it's underspecified?

Ok, I think this is starting to make sense now.  And #1986 looks pretty clean.  I'll manually run the GRINS tests if femputer is down for too long.

**Comment by lindsayad** [comment]
Closed by #1986
