### ISSUE TITLE
RAII for perf_log

### ISSUE THREAD

**Issue by benkirk** [libMesh/libmesh#199]
OK, START_LOG(.,.) / STOP_LOG(.,.) pairs are annoying.

@roystgnr, we've talked about this a few times, and I think I have a good solution I'd like to run by you. The basic problem is one of scope & unique names.

What we'd like is something like

``` c++
PerfItem foo(.,.,perf_log);
...
```

where the constructor begins the logging, and the destructor stops the logging.

But requiring unique names seems like a hassle and a pain to go back and drop in existing code.

What if we used the compiler **LINE** macro to create something automatic along the lines of

http://stackoverflow.com/questions/1597007/creating-c-macro-with-and-line-token-concatenation-with-positioning-macr

So then behind the scenes

``` c++
START_LOG("action A", "Group");
START_LOG("action B", "Group");
```

would expand to 

``` c++
PerfItem perf_item_1("action A", "Group",perf_log);
PerfItem perf_item_2("action B", "Group",perf_log);
```

and then STOP_LOG(.,.) would be a no-op, and implemented in the PerfItem (or better class name...) destructor?

@permcody - thoughts?

**Comment by jwpeterson** [comment]
Not closing this yet, since we still have not implemented:

- [ ] static PerfLookup objects
- [ ] The ability to specify a PerfLog other than libMesh::PerfLog when creating `LOG_SCOPE` objects.
