### ISSUE TITLE
Gmsh Mesh Format 4.0 supersedes 2.2 but is not supported

### ISSUE THREAD

**Issue by dschwen** [libMesh/libmesh#2016]
Gmsh has a new version of its native mesh format 
Version 4: http://gmsh.info/doc/texinfo/gmsh.html#MSH-file-format-_0028version-4_0029
which supersedes 
Version 2: http://gmsh.info/doc/texinfo/gmsh.html#MSH-file-format-version-2
Would be nice to get support for it in libMesh as Gmsh is probably the most capable and accessible open mesh generator.

**Comment by jwpeterson** [comment]
Fixed in #2082.
