### ISSUE TITLE
ExodusIO: Reading subdomain restricted elemental variable

### ISSUE THREAD

**Issue by lindsayad** [libMesh/libmesh#2040]
Maybe @jwpeterson has an idea for this since he seems to have been around in `ExodusIO` recently. Is there a good way to query whether an elemental variable being read with `ExodusII_IO::read_elemental_variable` -> `ExdosuII_IO_Helper::read_elemental_var_values` actually exists for a given `block_id` before we try to read it? Right now we have a MOOSE user getting an error from [here](https://github.com/libMesh/libmesh/blob/master/src/mesh/exodusII_io_helper.C#L1059) when restarting a simulation and the problem is that the variable doesn't exist on one of the subdomains.

**Comment by jwpeterson** [comment]
According to the ExodusII [manual](https://github.com/libMesh/libmesh/blob/master/contrib/exodusii/5.22b/exodus/doc/exodus.pdf), `ex_get_elem_var()` returns a nonzero error code when "variable does not exist for the desired element block". We currently treat all such errors as fatal, but we could instead keep going in the case of subdomain-restricted variables.

**Comment by lindsayad** [comment]
Closed by #2041
