### ISSUE TITLE
Don't use mesh.partition(1) in split_mesh

### ISSUE THREAD

**Issue by fdkong** [libMesh/libmesh#2058]
```
std::unique_ptr<CheckpointIO> split_mesh(MeshBase & mesh, processor_id_type nsplits)
{
  // There is currently an issue with DofObjects not being properly
  // reset if the mesh is not first repartitioned onto 1 processor
  // *before* being repartitioned onto the desired number of
  // processors. So, this is a workaround, but not a particularly
  // onerous one.
  mesh.partition(1);
  mesh.partition(nsplits);

  processor_id_type my_num_chunks = 0;
  processor_id_type my_first_chunk = 0;
  chunking(mesh.comm().size(), mesh.comm().rank(), nsplits, my_num_chunks, my_first_chunk);

  auto cpr = libmesh_make_unique<CheckpointIO>(mesh);
  cpr->current_processor_ids().clear();
  for (processor_id_type i = my_first_chunk; i < my_first_chunk + my_num_chunks; i++)
    cpr->current_processor_ids().push_back(i);
  cpr->current_n_processors() = nsplits;
  cpr->parallel() = true;
  return cpr;
}
```

`mesh.partition(1)` stops us from using a parallel partitioner during mesh splitting since we can not construct a distributed graph. The distributed graph is constructed based on the right PID assignments.

I understand there are some issues so that we are hacking here using `mesh.partition(1)`.

Roy, could you come up the actual fix? @roystgnr 

Ping @friedmud  as well.

**Comment by fdkong** [comment]
@jwpeterson  Do you have any thoughts on this?

**Comment by friedmud** [comment]
The comment that's there is true... we have to reset the partitioning back to `1` each time through the routine if we're partitioning for multiple different processor sets.

**Comment by roystgnr** [comment]
The later swath of commits in #1965 is part of the actual fix.  It's likely at the "necessary but not sufficient" stage, though.

**Comment by fdkong** [comment]
I think the right fix should be to cache the actual partition.  Every time, we set it back to the actual partition and then have a distributed graph.  

Or looks like we do not set it to 1 at the first time, and then we should have a parallel partitioner since the distributed is created at the very begin.

**Comment by friedmud** [comment]
I don't understand what this has to do with your stuff though... it shouldn't effect your partitioner.  Your partitioner shouldn't be "reading" the partitioning at all... just setting it.

**Comment by fdkong** [comment]
OK, let me explain using an example.

Suppose you have a two-element mesh: element 0 and element 1.

Run the code with 2 mpi ranks using the presplit capability  in a replicated mesh mode.

libMesh will have an automatic linear partitioner at the beginning. After partitioning,

rank 0: element 0 with pid 1, element 1 with pid 0
rank 1: element 0 with pid 1, element 1 with pid 0

Moose will call a partitioner that will be based on a  parallel graph constructed  using the thing above. After partitioning,

rank 0: element 0 with pid 0, element 1 with pid 1
rank 1: element 0 with pid 0, element 1 with pid 1

Now we are going to do the actual presplitting.

call mesh.partition(1);

rank 0: element 0 with pid 0, element 0 with pid 0
rank 1: element 0 with pid 0, element 0 with pid 0

And then 
mesh.partition(nsplits) have to use a  fake distributed graph (the whole graph is on rank 0). 

And then I am going to partition this graph that is empty everywhere except on rank 0. ParMETIS does not allow empty graph, and we are going to create subcomm for the graph. The subcomm contains one mpi rank only (mpi rank 0). Now ParMETIS just a wrapper of METIS, and it is a serial partitioner. That is, I can not do parallel partitioning in the first level.

**Comment by fdkong** [comment]
The code definitely is working. But I want an actual parallel partitioner at first step.

**Comment by friedmud** [comment]
Why do you think libMesh uses a linear partitioning up front?  That's not coded anywhere.  If you're getting that then it's just luck.  You shouldn't depend on that.

If you want that - then do your own linear partitioning in your partitioner before calling out to PETSc.

**Comment by friedmud** [comment]
BTW: This is the reason why there are two functions on `Partitioner`: `partition()` and `repartition()`.

`partition()` shouldn't assume _anything_ about how the elements are currently partitioned.  `repartition()` can assume that the elements are currently partitioned properly.

**Comment by fdkong** [comment]
Do we  call the linear partitioner before we call parmetis in libmesh? If yes, I think I should do the same way. Suppose all parallel partitioners should be setup as what we are doing for parmetis in libMesh (parmetis_partitioner.C)

**Comment by fdkong** [comment]
Just talked to @friedmud, and I think I understand the whole thing now.  I am going to add a linear partitioner before I call my parallel partitioner.

So closed this issue.
