### ISSUE TITLE
Tensor structure of dphi for vector finite elements

### ISSUE THREAD

**Issue by lindsayad** [libMesh/libmesh#2062]
Wikipedia states that the gradient of a vector is the transpose of the Jacobian matrix. However, from looking in `h1_fe_transformation.C` it appears to me like we structure our vector gradients as if we were storing the Jacobian matrix, **not** the **transpose**  of the jacobian matrix:
```c++
        for (auto i : index_range(dphi))
          for (auto p : index_range(dphi[i]))
            {
              // dphi/dx    = (dphi/dxi)*(dxi/dx)
              dphi[i][p].slice(0) = dphidx[i][p] = dphidxi[i][p]*dxidx_map[p];

#if LIBMESH_DIM>1
              dphi[i][p].slice(1)  = dphidy[i][p] = dphidxi[i][p]*dxidy_map[p];
#endif
#if LIBMESH_DIM>2
              dphi[i][p].slice(2) = dphidz[i][p] = dphidxi[i][p]*dxidz_map[p];
#endif
            }

        break;
      }
```
This has bad consequences...this math

![image](https://user-images.githubusercontent.com/10248304/53980475-a8719480-40cd-11e9-8442-f1052542b1ce.png)

for example won't yield the expected vector. Instead the user would have to perform the right multiply of the vector to get the result they probably expected.

**Comment by jwpeterson** [comment]
> Wikipedia states that the gradient of a vector is the transpose of the Jacobian matrix.

This is just a convention, and personally I prefer grad(v) = dv_i/ dx_j.

> This has bad consequences...this math

This isn't an identity as far as I know. It's why they invented the (u.grad) form of writing it...

**Comment by lindsayad** [comment]
So in code do I just have to know to perform the right multiplication? Or is there an easy way I'm missing

**Comment by pbauman** [comment]
> This is just a convention, and personally I prefer grad(v) = dv_i/ dx_j.

Yes, this convention is the one used pretty much throughout mechanics.

And the "identity" you listed at the end is not valid. One of the reasons I don't like that notation and never use it when I teach/write the Navier-Stokes equations - it causes confusion.

**Comment by pbauman** [comment]
> So in code do I just have to know to perform the right multiplication? Or is there an easy way I'm missing

What are you trying to do? The tensor that is formed there will do the correct thing if you have "A \times b" (A tensor, b vector).

**Comment by jwpeterson** [comment]
The NS equation term you want is "\grad(\vec{u}) \vec{u}", where matrix multiplication is implied. In other words, right multiply the grad(u) matrix (in our convention) with the u vector.

**Comment by jwpeterson** [comment]
I would also caution that authors (e.g. Hughes) use "A \cdot x" to mean right multiplication by transpose, e.g. "A^T x", so don't get tripped up by that either!

**Comment by pbauman** [comment]
It get even more fun in some papers (like the one I'm looking at this very second) with "\grad \lambda \cdot \grad \varphi" with the \cdot is actually a tensor inner product (instead of the usual ":" notation). Good times.

**Comment by lindsayad** [comment]
Alright I think I'm satisfied
