### ISSUE TITLE
BoundaryInfo::boundary_ids() Segfaulting

### ISSUE THREAD

**Issue by friedmud** [libMesh/libmesh#2075]
Not quite sure what the issue is here.  Tough to get a good backtrace because this is only happening when I'm running with 50M+ elements.

Here is part of what I'm seeing:

```
*** Error in `../../../../../mocodile-opt': malloc(): memory corruption (fast): 0x00000000072c6270 ***
*** Error in `../../../../../mocodile-opt': munmap_chunk(): invalid pointer: 0x0000000007502180 ***
/home/gastdr/projects/lemhi_nomarch/moose/framework/libmoose-opt.so.0(_ZNSt10_HashtableIsSt4pairIKsbESaIS2_ENSt8__detail10_Select1stESt8equal_toIsESt4hashIsENS4_18_Mod_range_hashingENS4_20_Default_ranged_hashENS4_20_Prime_rehash_policyENS4_17_Hashtable_traitsILb0ELb0ELb1EEEE9_M_rehashEmRKm+0x9e)[0x2aaaaba1bdde]
/home/gastdr/projects/lemhi_nomarch/libmesh/install/lib/libmesh_opt.so.0(_ZNK7libMesh12BoundaryInfo12boundary_idsEPKNS_4ElemEtRSt6vectorIsSaIsEE+0x170)[0x2aaaac8e18f0]
```

What I think is happening is that we're overwhelming the hash table in BoundaryInfo::boundary_ids().  The other possibility is that we're reading in some corrupt junk from a really big Exodus file.

Sorry for sketchy info so far.  I'm going to continue to investigate this tonight.

**Comment by roystgnr** [comment]
Oh, hell.  How much RAM does this take to replicate?

> What I think is happening is that we're overwhelming the hash table in BoundaryInfo::boundary_ids().

C++ hash-tables do the standard thin, keeping linked lists for hash collisions and auto-resize when collisions get too common, right?  A bad hash function should be able to trash performance but not to trash malloc metadata.

> The other possibility is that we're reading in some corrupt junk from a really big Exodus file.

Can you try reading in the same file from a utility program and see if you get an error?  That's not a perfect test for what looks like it might be manifesting as a dangling pointer write, but at least it would pin the problem down to "bad Exodus file" or "bad Exodus code" if you can get it to trigger again.

I'd like to reiterate my ages-old suggestion that we create a libmesh_always_assert (or libmesh_opt_assert or whatever) to encourage people to do sanity-checking in opt mode "whenever appropriate", which IMHO means "when reading data from files".  The testing overhead ought to be inconsequential compared to the I/O overhead, and it would let us catch file corruption, and it would let us gradually move away from the current status of completely-100%-insecure when reading files from untrustworthy sources.

**Comment by friedmud** [comment]
I dunno - I've been able to replicate this problem with two very different meshes (and the failure is in the same place).  Doesn't mean that it's _not_ because of reading the file... but it really feels odd that it would manifest the same way with both meshes.

I'm thinking about changing the storage for `boundary_ids()` to being a `std::map<std::vector>` intsead of being a multimap.  This will have the added benefit that `boundary_ids()` can simply return a const vector - instead of having to do equal_range and fill up the vector.

**Comment by friedmud** [comment]
Ok - I was able to replicate this problem even going directly from generation to split `cpr` files (i.e. without the Exodus middleman)... so there's no Exodus corruption going on here...

I'm going to go reimplement boundary_ids as a `std::map<std::vector>` to see if that helps... it's something I've wanted to do for a while anyway.

**Comment by roystgnr** [comment]
> I'm going to go reimplement boundary_ids as a std::map<std::vector> to see if that helps... it's something I've wanted to do for a while anyway.

I don't see any way the container choice could be leading to the bug, but you might find and fix it along the way, and I can definitely see how this might end up improving performance, so good luck!

**Comment by friedmud** [comment]
This didn't end up being my problem.  As suspected... it was memory corruption elsewhere.  I was able to run valgrind on the cluster to get to the bottom of it.

That said - this process did uncover quite a bit of inefficiency in MOOSE related to boundary_ids().  I hope to be able to dig into that stuff more later.  But I don't have time right now.  I'll close this issue for now though.

Thanks for your help!
