### ISSUE TITLE
left/right multiply in DenseMatrix has wrong code docs

### ISSUE THREAD

**Issue by dschwen** [libMesh/libmesh#2087]
https://github.com/libMesh/libmesh/blob/master/include/numerics/dense_matrix_impl.h#L46
```
void DenseMatrix<T>::left_multiply (const DenseMatrixBase<T2> & M2)
{
  // (*this) <- M2 * (*this)
```

https://github.com/libMesh/libmesh/blob/master/include/numerics/dense_matrix_impl.h#L213
```
void DenseMatrix<T>::right_multiply (const DenseMatrixBase<T2> & M3)
{
  // (*this) <- M3 * (*this)
```

One of those is wrong. I think the `right_multiply` should be `(*this) * M3`.

**Comment by jwpeterson** [comment]
:+1: I think the doco in dense_matrix_base.h is correct, so I'll fix it to match that one.
