### ISSUE TITLE
Add DualNumber explicit instantiations to libmesh numerical types if MetaPhysicL is enabled

### ISSUE THREAD

**Issue by dschwen** [libMesh/libmesh#2089]
I stumbled across this when I was unable to use `DenseMatrix<ADReal>` in MOOSE. I'll try to figure out a solution for this. Ping @lindsayad

**Comment by dschwen** [comment]
argh, of course that does not work because the proper type is only known in MOOSE

**Comment by dschwen** [comment]
maybe we can factor out a `dense_matrix_base_impl.h` file...

**Comment by jwpeterson** [comment]
Closing because we do now have a dense_matrix_base_impl.h file, and I think there are more recent open PRs/issues on the same topic.

**Comment by roystgnr** [comment]
Yeah; MOOSE now has the explicit instantiations in src/utils/DenseMatrixDualReal.C, which is probably the optimal way to do things until/unless we have other users clamoring to move the instantiations to libMesh proper to (slightly) reduce their own compile times.
