### ISSUE TITLE
visualizing transient data with exodusII and paraview

### ISSUE THREAD

**Issue by manavbhatia** [libMesh/libmesh#2094]
@jwpeterson I am facing a similar situation with .e-s.* file naming situation as you have described in the example [here](https://gist.github.com/jwpeterson/6795229#file-modified_transient_ex1-c-L248)  . Preview is unable to show the transient evolution of the data with naming scheme. 

I am using AMR and need to visualize transient data in Paraview. Does the "append" approach remain the workaround?

**Comment by manavbhatia** [comment]
Using the same approach I am tripping the following error [here](https://github.com/libMesh/libmesh/blob/e9baf16da2b10310348becffb2058a738db3d2c6/src/mesh/exodusII_io_helper.C#L362): 
```
Exodus Library Error: [ex_open]
	Error: failed to open output_optim.exo write only
    exerrval = -101
Error opening ExodusII mesh file: output_optim.exo

```

Any advice on this? 

I am wondering if there is anyone else on the list who has been successfully visualizing transient data with AMR in Paraview.

**Comment by pbauman** [comment]
> successfully visualizing transient data with AMR in Paraview.

We do this all the time. If you're doing AMR, you can't append to the file. Paraview assumes that all datasets in the same file have the same mesh topology. What we do is just write a new file for each time step and everything works fine.

**Comment by manavbhatia** [comment]
Thanks. 
What naming scheme do you use for the files? 

Do you write using the write_equation_systems() method?

**Comment by pbauman** [comment]
ExodusIO.write_timestep() and we just stick the timestep number at the end fo the filename, e.g. foo.e-s.5 for tilmestep number 5.

**Comment by pbauman** [comment]
https://github.com/grinsfem/grins/blob/master/src/visualization/src/visualization.C#L214

**Comment by manavbhatia** [comment]
I did try the .e-s.xx approach yesterday and it did not work. Seems like it was because I was setting the "N" as the time-step number in calling this method, as opposed to the number of time-steps in the file. 

I will give it another shot.

**Comment by manavbhatia** [comment]
Setting the value to "1" in the call to write_timestep() did the trick. 

Thanks for your help!
