### ISSUE TITLE
Add a member function sub_matrix in DenseMatrix

### ISSUE THREAD

**Issue by YaqiWang** [libMesh/libmesh#2118]
I am motivated to do it because I will probably need it for the array kernel stuff that I am working on. I plan to have an interface like
```
DenseMatrix<T> DenseMatrix<T>::sub_matrix(
                                       unsigned int row_id, unsigned int row_size,
                                       unsigned int col_id, unsigned int col_size) const;
```
Even I might not be using it (highly unlikely), it does not hurt to have such a function.

**Comment by pbauman** [comment]
Are you aware of `DenseSubMatrix<T>`? [Documentation](https://libmesh.github.io/doxygen/classlibMesh_1_1DenseSubMatrix.html)

What functionality does that not provide?

**Comment by YaqiWang** [comment]
Oh, I am not aware of `DenseSubMatrix`. Eventually I want to add the submatrix into a global matrix by calling `PetscMatrix::add_matrix`. But looks like `add_matrix` can only accept `DenseMatrix`. I can definitely use `add` method directly.

**Comment by pbauman** [comment]
The usual mode is to create the `DenseMatrix`, use `DenseSubMatrix` objects to populate since populating the `DenseSubMatrix` directly populates the `DenseMatrix` (this is mainly used for coupled problems (see [example](https://github.com/libMesh/libmesh/blob/master/examples/systems_of_equations/systems_of_equations_ex1/systems_of_equations_ex1.C#L289)) and then you add then `DenseMatrix` to the `SparseMatrix`.

**Comment by YaqiWang** [comment]
Assembling the whole `DenseMatrix` is not a problem to me. But I only have DoF indices of one sub-matrix of the `DenseMatrix`. Each submatrix corresponds to a component of an array variable (a standard variable) and may or may not get assembled to the global matrix depending on how user setup the coupling of variables. So I basically need something like
```
if (component i and component j needed in the global matrix)
{
   auto sub = full_dense_matrix.sub_matrix(i, j);
   global_matrix.add_matrix(sub, modified dof_indices based on i and j);
}
```
The usual mode does not apply here.

**Comment by roystgnr** [comment]
Yeah; if we didn't add a sub_matrix function then the only alternative would be to add a ```SparseMatrix::add_matrix(const DenseSubMatrix &)``` function.

... and in the PETSc case, it doesn't look like that alternative will save us anything?  Creating an actual temporary DenseMatrix from the submatrix is going to involve a bunch of copying, which I'd *hope* we could avoid somehow, but the MatSetValues method assumes you have a contiguous array of values to hand it, and I don't see any way to tell it (or any other PETSc method) to use a stride.
