### ISSUE TITLE
Need MPI_Comm_Split routine that takes a type

### ISSUE THREAD

**Issue by permcody** [libMesh/libmesh#2128]
The existing Communicator split routine in libMesh doesn't honor all of the parameters that the MPI Communicator split can take. It would be nice to extend this API to support additional arguments:

MOOSE Needs this version:
```
  MPI_Comm_split_type(
	      _mur_communicator.get(), MPI_COMM_TYPE_SHARED, 0, MPI_INFO_NULL, &shmem_raw_comm);
```

**Comment by roystgnr** [comment]
Looks straightforward enough.  I'll want to make a Parallel::Info shim to MPI_Info too, I think, albeit non-functioning in the --disable-mpi case, to reduce the ifdef mess.  No shim for MPI_COMM_TYPE_SHARED (or any of the zillion OpenMPI extensions) for now.
