### ISSUE TITLE
Add --disable-openmp configure option

### ISSUE THREAD

**Issue by jwpeterson** [libMesh/libmesh#2131]
We currently "enable" OpenMP (i.e. set the define `LIBMESH_HAVE_OPENMP` and pass the corresponding flags) any time the compiler supports one of the possible OpenMP flags. Basically in threads.m4, we call
```
AX_OPENMP([],[enableopenmp=no])
```
no matter what without any option to disable it. When using helgrind for debugging, it is apparently necessary to have pthreads support turned on but *not* be using OpenMP (@lindsayad made a thread about this on libmesh-devel). So, we need to be able to control these two things independently.

There might also be an even more subtle middle ground where one would want to pass the `-fopenmp` flags to the compiler, but not actually use any OpenMP pragmas in the code... that should also be possible to support if necessary, but I think for now the ability to simply turn off OpenMP is all that's needed.

**Comment by lindsayad** [comment]
This would be great. Thanks @jwpeterson

**Comment by permcody** [comment]
What about having the existing thread model flag actually work? We have the
three thread models but apparently we can’t run pure pthreads even when we
select that model if openMP is available? I understand that we want to
generally detect and enable openMP for downstream libraries so maybe having
the disable flag is still a good idea but getting the thread model flag
sane would also be good.

**Comment by jwpeterson** [comment]
I think the point is that pthreads/openmp are not really separable things/you don’t want to separate them in general? I think this mixture of pthreads/openmp is how Derek wants it to be anyway, unless his thinking on it has changed.

**Comment by permcody** [comment]
We’ll sort of
1) Pure Pthreads: good for debugging and anything that requires static
scheduling
2) Pthreads+OpenMP but we causally call it OpenMP. It uses the pthreads
base implementation but that’s because the threading is done with compiler
directives on top of an existing class
3) TBB

What I’m saying is that 1) is inaccessible right now if your compiler
supports OpenMP. The mixture isn’t the problem and is fine.

**Comment by permcody** [comment]
Thinking about this more... Actually we really don’t want to solve this
with a —disable-OpenMP flag. That would turn off OpenMP in downstream
libraries too. What If we want the case where we want to use pure Pthreads
in libmesh but still compile in the OpenMP for other libraries (hypre)? I
think we just need the thread model flag to pick the choice we select.

**Comment by jwpeterson** [comment]
> That would turn off OpenMP in downstream libraries too.

Presumably this is what you want when debugging with helgrind.

Anyway, I understand what you are saying and this is the reason for the last sentence in my original post "There might also be an even more subtle middle ground where one would want to pass the -fopenmp flags to the compiler, but not actually use any OpenMP pragmas in the code..."

**Comment by permcody** [comment]
On Tue, May 14, 2019 at 7:00 AM John W. Peterson <notifications@github.com>
wrote:

> That would turn off OpenMP in downstream libraries too.
>
> Presumably this is what you want when debugging with helgrind.
>

Probably, but with Alex's latest debugging effort, he didn't go back and
try to remove the -fopenmp flag. He was able to workaround the issue but
simply changing the libmesh_config.h flag manually. So apparently he was
able to figure it out without turning it all the way off. That being said,
completely disabling it makes a lot more sense.
