### ISSUE TITLE
NaN in result when vector variables are restricted to a subdomain

### ISSUE THREAD

**Issue by cticenhour** [libMesh/libmesh#2141]
When creating idaholab/moose#13359, I experienced some unexpected errors using libmesh (as of c4c9fd5) with PetSc 3.8.3 for a 3D test.

In those MOOSE tests (see [`vector_3d.i`](https://github.com/cticenhour/moose/blob/4290733582c25cd2e07ca7bd9db7a471becc5aca/test/tests/interfacekernels/3d_interface/vector_3d.i)), I have two vector variables, `u` and `v`, with `u` being active in subdomain 0 and `v` being active in subdomain 1. `u` has kernels active only in subdomain 0, while `v` only has kernels in subdomain 1. I am applying a vector penalty interface condition (my MOOSE contribution in the PR is to enable VectorInterfaceKernels in general) to ensure `u = v` along the interface between the subdomains, with natural conditions along all external boundaries.

In practice, I would receive good results in 2D and 3D using libMesh and PetSc 3.9.4, but during testing with 3.8.3, NaNs would occur in the solution for `v` in subdomain 0, but **only** in the Y and Z components of the vector. Fande and I tracked this down to a divide by zero that occurs in `equation_systems.C:819`. The difference between PetSc versions is that the `/=` operator is able to catch divide-by-zero in 3.9.4, but doesn't in 3.8.3. 

I did find a fix for this. It seems as though `repeat_count` zero entries were not being set to 1 consistently for variables that do not exist on a particular subdomain. The expression used to calculate the proper vector index in `equation_systems.C:784` differed from that in other parts of the code just before. Specifically, the `var_inc+d` term was `var+d` here. `var` didn't seem to be tied to the number of components of the vectors in the problem, rather, the number of variables in the problem (via `nv_sys`). This change both improved my test solutions and removed the NaNs for those components it was affecting. So I will be submitting a PR with this fix in a few minutes. 

My question for ya'll - was there some specific intention that you might/might not remember for having `var+d` over `var_inc+d` on Line 784? Just want to make sure I am fixing up the right thing  in the right way and not just making a new problem later. :-)

**Comment by roystgnr** [comment]
Looking through git logs it appears that @lindsayad made a bunch of those var->var_inc fixes in #1458 but didn't touch the currently broken line, so I'm guessing it was just an oversight.

**Comment by cticenhour** [comment]
Ok - thanks Roy!
