### ISSUE TITLE
Adding a variable to an existing FParser object is slow

### ISSUE THREAD

**Issue by dschwen** [libMesh/libmesh#2161]
Adding a variable to an existing FParser object (required for derivatives of MOOSE material properties used in functions) is way too slow (consuming >60% of the derivative parsed material setup time). Currently the new variable has to be appended to a comma-separated string of all variables, and that string will be will re-parsed each time a variable is added.

**Comment by roystgnr** [comment]
This is one of those "we have N=10,000 variables but you guys wrote O(N^2) algorithms when you were expecting N=20" situations, huh?

But in this case, is it an O(N^2) algorithm?  It sounds like an O(N) algorithm that you're calling N times, in which case we need to figure out how to change the calling sequence.

What's the exact mechanism being used here?  You're calling ParsedFEMFunction::reparse() after each variable add?  ParsedFunction::reparse() with new _additional_vars?

**Comment by dschwen** [comment]
This is used in derivative parsed materials. I think the internal design of FParser does not allow me to speed this up any further. The variables names are stored internally in a map of objects that contain pointers to the passed in comma-separated string of variable names. Changing that string invalidates all pointers, which cannot be updated in the map (as they are the keys). So the map has to be rebuilt from scratch always. 

I think the right approach is to add the new variables in bulk instead of one by one. I think I can do that with a MOOSE change only. I'll close this for now.
