### ISSUE TITLE
Diagonal PETSc matrix

### ISSUE THREAD

**Issue by lindsayad** [libMesh/libmesh#2168]
We've recently been doing some automatic scaling of our residuals and Jacobians in MOOSE (see idaholab/moose#12601 and idaholab/moose#13547) in order to improve the condition  number of the linear system, and we've seen some pretty awesome improvements. Take this Jacobian-free non-linear solve without scaling:
```
 0 Nonlinear |R| = 1.326650e+04
      0 Linear |R| = 1.326650e+04
      1 Linear |R| = 2.944220e-05
 1 Nonlinear |R| = 1.864784e+00
      0 Linear |R| = 1.864784e+00
      1 Linear |R| = 3.385636e-06
 2 Nonlinear |R| = 6.259735e-04
      0 Linear |R| = 6.259735e-04
      1 Linear |R| = 9.361485e-07
      2 Linear |R| = 1.749268e-08
      3 Linear |R| = 9.788406e-10
 3 Nonlinear |R| = 1.039767e-04
      0 Linear |R| = 1.039767e-04
      1 Linear |R| = 1.515572e-10
 4 Nonlinear |R| = 3.621991e-07
      0 Linear |R| = 3.621991e-07
      1 Linear |R| = 3.113164e-11
      2 Linear |R| = 1.267239e-12
 5 Nonlinear |R| = 1.073857e-08
```
vs with scaling:
```
 0 Nonlinear |R| = 1.326650e+04
      0 Linear |R| = 1.326650e+04
      1 Linear |R| = 7.073560e+01
      2 Linear |R| = 2.495484e+00
      3 Linear |R| = 8.710280e-02
 1 Nonlinear |R| = 1.866817e+00
      0 Linear |R| = 1.866817e+00
      1 Linear |R| = 2.314249e-02
      2 Linear |R| = 8.128605e-04
      3 Linear |R| = 4.823874e-05
      4 Linear |R| = 2.617779e-06
 2 Nonlinear |R| = 7.210617e-05
      0 Linear |R| = 7.210617e-05
      1 Linear |R| = 7.244895e-07
      2 Linear |R| = 4.770732e-08
      3 Linear |R| = 2.199447e-09
      4 Linear |R| = 1.075420e-10
 3 Nonlinear |R| = 1.609251e-09
```
However, with the way we're implementing this scaling, we end up doing mallocs in `MatSetValues` if we're using discontinuous Galerkin calculations for example because the non-zero structure is different between the matrix computed for scaling purposes and the true matrix. In truth we only care about the diagonal for scaling (eventually we want other scaling choices for say saddle-point problems). So I'm proposing a `PetscDiagonalMatrix` that inherits from `SparseMatrix` but actually uses a `Vec` to store the data. Calls to things like `PetscDiagonalMatrix::add(i, j, value)` would simply return if `i` doesn't equal `j`. Implementing this new class is definitely the simplest option for accomplishing what we want, and in general I think that simplest is best :smile:

**Comment by lindsayad** [comment]
@fdkong

**Comment by fdkong** [comment]
@lindsayad I just realize we might have another even better way. I added one API a while ago to  PETSc, and it can get the original sparsity pattern back. https://www.mcs.anl.gov/petsc/petsc-current/docs/manualpages/Mat/MatResetPreallocation.html

``better" here means you need one single line code change.  The vector matrix idea may be faster since we drop off off-diagonal part.  We could ignore the off-diagonal as well at moose side

**Comment by lindsayad** [comment]
Oooh, I do like that. Well for the scaling calculation I only call to the diagonal parts of our Jacobian function, so probably shouldn't bee too much slower

**Comment by fdkong** [comment]
> Oooh, I do like that. Well for the scaling calculation I only call to the diagonal parts of our Jacobian function, so probably shouldn't bee too much slower

Cool

**Comment by roystgnr** [comment]
Would this need to be PETSc specific?  If PETSc shell matrix support makes it super easy to call some MatCreateWithDiagonalVec() and be done then I guess "yes", but if we have to write the shims ourselves then it seems like we could use NumericVector as the underlying storage, or even template around underlying NumericVector subclass type if the extra virtual function call overhead is a concern.
