### ISSUE TITLE
Warning: binding reference member to stack allocated parameter

### ISSUE THREAD

**Issue by dschwen** [libMesh/libmesh#2199]
In the constructor 
```
Build::Build (const MeshBase & mesh_in,
              const DofMap & dof_map_in,
              const CouplingMatrix * dof_coupling_in,
              std::set<GhostingFunctor *> coupling_functors_in,
              const bool implicit_neighbor_dofs_in,
              const bool need_full_sparsity_pattern_in);
```
the set `coupling_functors_in` is passed in by copy, but is then bound to a reference:
```
const std::set<GhostingFunctor *> & coupling_functors;
```
That seems very wrong (as the reference points to the stack allocated (temporary) copy. Hence the warning:

```
../src/base/sparsity_pattern.C:48:21: warning: binding reference member 'coupling_functors' to stack allocated parameter 'coupling_functors_in' [-Wdangling-field]
  coupling_functors(coupling_functors_in),
                    ^~~~~~~~~~~~~~~~~~~~
./include/libmesh/sparsity_pattern.h:86:39: note: reference member declared here
  const std::set<GhostingFunctor *> & coupling_functors;
```

**Comment by jwpeterson** [comment]
Looks like this line was added in 0d50454d03 as part of the huge PR #1064. I'd say we could just fix it by not storing a reference in the class, but I'll let @roystgnr comment since maybe the intent was to allow that `std::set` to be updated from outside the class.

**Comment by roystgnr** [comment]
That's a horrible bug.  How on Earth are our --enable-werror --enable-paranoid-warnings builds not seeing that?  Tell me what compiler version you are using, I want to switch to it.

And how is that not giving us all kinds of segfault or worse errors?

The intent was to allow that set to be updated from outside; the right fix ought to be to pass by reference.  Give me a sec.

**Comment by dschwen** [comment]
Clang 8.0.0 from the latest MOOSE redistributable package issued that warning.
