### ISSUE TITLE
Add MONOMIAL_VEC family type

### ISSUE THREAD

**Issue by lindsayad** [libMesh/libmesh#2211]
Like LAGRANGE_VEC but with monomials. In MOOSE this would be very useful for our auxiliary system for computing auxiliary quantities on element interiors, e.g. in places where coupled lagrange variables have defined gradients. 

Specific example: we want to compute an auxiliary velocity from the gradient of a pressure variable that uses a Lagrange basis. The easiest family type to use for the velocity variable would be a MONOMIAL_VEC

**Comment by lindsayad** [comment]
An L2_LAGRANGE_VEC may also serve this purpose, but a MONOMIAL_VEC may be more appropriate for DG simulations...?

**Comment by roystgnr** [comment]
Both'd be fine for DG IMHO, but a MONOMIAL_VEC would let you go to zeroth order, which is exactly what you want if you're caching gradients of first order solutions on simplices.  L2_LAGRANGE_VEC would have 2x to 4x too many DoFs in that use case.
