### ISSUE TITLE
libmesh_config --libs returns `readlink` paths

### ISSUE THREAD

**Issue by milljm** [libMesh/libmesh#2218]
I have been experimenting with releasing a build of libMesh via Homebrew. Homebrew, creates symlinks from a centralized location (/usr/local/opt) to an actual path. The actual path, contains version information on the formula used to create said resource, like so:

  /usr/local/Cellar/gcc/9.0.0-1 (-1 being the formula version)

The symlink'd common location libraries are supposed to use:

  /usr/local/opt/gcc

The issue, is that when Homebrew updates gcc, `libmesh_config` reports the target location of the symlink. Example:

/usr/local/Cellar/gcc/9.0.0-1 (which no longer exists due to an update), instead of /usr/local/opt/gcc (which still exists, and points to: /usr/local/Cellar/9.0.0-2 due to Homebrew updates).

Is there a way to instruct configure, not to follow symlinks? I can 'hack' my way through the libmesh_config script to print the symlink path if there is no alternative.

Thanks!

**Comment by jwpeterson** [comment]
> I have been experimenting with releasing a build of libMesh via Homebrew.

That sounds cool!

So if I understand correctly, it sounds like the compiler is being "changed" out from under `libmesh_config`, but the actual compiler is not being changed, it's just a symlink that is now gone? And therefore if we could have `libmesh_config` record the location of the real compiler (follow the symlink) at configure time, that would fix the problem?

**Comment by roystgnr** [comment]
I got the opposite understanding: we're *supposed* to be recording the symlink so that we're still okay if and when the underlying target gets changed.

If that's the case then manually setting CXX, CC, FC at configure time ought to fix it.

Actually, either way I'd hope that manually setting the environment variable (as opposed to our usual "just look around our path for some good compilers or their MPI wrappers depending") would cause it to stick.

**Comment by milljm** [comment]
>`libmesh_config`, but the actual compiler is not being changed, it's just a symlink that is now gone? 

The exact opposite actually...

The actual compiler path _did_ change (Homebrew calls this the Cellar path), but the location of the symlink remains the same (Homebrew calls this the 'opt_prefix' path), and points to the new 'actual compiler path'.

```pre
[milljm][~]> ll /usr/local/opt | grep gcc
lrwxr-xr-x   1 milljm  admin    19B Aug 15 11:50 gcc -> ../Cellar/gcc/9.2.0
```
libmesh_config now reports a path no longer available (Homebrew deleted my ../Cellar/gcc/9.1.0 for example).

Additional examples of how moose-based stuff is installed currently on Homebrew. Might make things more clear:

```pre
[milljm][~]> ll /usr/local/opt | grep moose
lrwxr-xr-x   1 milljm  admin    31B Aug 14 10:56 moose-vtklite -> ../Cellar/moose-vtklite/8.2.0_1
lrwxr-xr-x   1 milljm  admin    27B Aug 14 10:57 moose-vtk -> ../Cellar/moose-vtk/8.2.0_5
lrwxr-xr-x   1 milljm  admin    33B Aug 14 10:57 moose-peacock -> ../Cellar/moose-peacock/peacock_1
lrwxr-xr-x   1 milljm  admin    34B Aug 14 10:57 moose-peacock3 -> ../Cellar/moose-peacock3/peacock_1
lrwxr-xr-x   1 milljm  admin    25B Aug 14 11:08 moose -> ../Cellar/moose/modules_6
lrwxr-xr-x   1 milljm  admin    30B Aug 19 09:10 moose-petsc -> ../Cellar/moose-petsc/3.11.3-2
lrwxr-xr-x   1 milljm  admin    33B Aug 19 09:10 moose-libmesh -> ../Cellar/moose-libmesh/da98c01-3
```

LIBMESH_DIR=/usr/local/opt/moose-libmesh
PETSC_DIR=/usr/local/opt/moose-petsc

This allows us to update these two libraries, but not the PATHs.

Now... before anyone actually performs work on this, there are additional issues that I have no way of solving, currently. The libmesh_config script reports the gcc toolchain path several subdirectories deep:

```pre
/usr/local/Cellar/gcc/9.2.0/lib/gcc/9/gcc/x86_64-apple-darwin18/9.2.0
```
I foresee no way of solving this. You guys might be able to solve the path to /usr/local/opt/gcc. But because there are no symlinks available other than the top-level 'gcc'... I have no idea how to fix libmesh_config's output of that entire subdirectory path containing specific versions.

**Comment by milljm** [comment]
And, if anyone is interested/curious, to obtain all of the above to poke around:
```pre
brew tap idaholab/moose
brew install moose
```

**Comment by jwpeterson** [comment]
> The exact opposite actually...

I can put you on a flight coming *back* from Chicago... would that help?

**Comment by milljm** [comment]
Homebrew doesn't update GCC very often. I suppose I'll just have to watch it, and update accordingly. Admittedly I am still very new to Homebrew formula-fu. I think this Homebrew PR describes my woes best: 

https://github.com/Homebrew/brew/issues/60
