### ISSUE TITLE
PointLocatorTree 

### ISSUE THREAD

**Issue by manavbhatia** [libMesh/libmesh#2235]
I have a need to identify nodes within a certain distance of a given point. This is currently implemented in PointLocatorTree [here](https://github.com/libMesh/libmesh/blob/ca543b0a6d9af487d4b7d1e64b890aa777a3bb9c/src/utils/point_locator_tree.C#L308) using a linear search. 

I have to perform this search on potentially all nodes in a mesh, which could be cost prohibitive with a linear search. 

I am wondering if it may be possible to extend the octree search to include this feature. Any thoughts will be welcome.

**Comment by jwpeterson** [comment]
I would use nanoflann to accomplish this, as it is probably going to be more well-suited to the task of "identify nodes within a certain distance of a given point." For examples of using nanoflann, see e.g. the `VectorOfNodesAdaptor` in replicated_mesh.C or this [utility for detecting duplicate nodes](https://gist.github.com/jwpeterson/7a36f9f794df67d51126).

**Comment by manavbhatia** [comment]
Very cool! Thanks!
