### ISSUE TITLE
File stream error when read Gmsh mesh file

### ISSUE THREAD

**Issue by Laphet** [libMesh/libmesh#2242]
Hi guys, I am a newbie in libMesh. I test the examples/introductions/ex1 with my .msh (created from Gmsh). However, something wrong:

/* messages from console
Stream is bad! Perhaps the file does not exist?
Stack frames: 9
0: libMesh::print_trace(std::ostream&)
1: libMesh::MacroFunctions::report_error(char const*, int, char const*, char const*)
2: libMesh::GmshIO::read_mesh(std::istream&)
3: libMesh::GmshIO::read(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
4: libMesh::NameBasedIO::read(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
5: libMesh::UnstructuredMesh::read(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, void*, bool, bool)
6: ./example-opt(+0x9f41) [0x7fe970209f41]
7: __libc_start_main
8: ./example-opt(+0xa2da) [0x7fe97020a2da]
[0] src/mesh/gmsh_io.C, line 834, compiled Sep  5 2019 at 17:07:51
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0
[unset]: write_line error; fd=-1 buf=:cmd=abort exitcode=1
:
system msg for write_line failure : Bad file descriptor
*/

I enclose the mesh file for your testing.
[Cell01.msh.txt](https://github.com/libMesh/libmesh/files/3590302/Cell01.msh.txt)

Thanks.

**Comment by Laphet** [comment]
This mesh file describes a ball embedded in a cube, and three periodic relations are imposed on all opposite faces.

**Comment by jwpeterson** [comment]
Hi, 

I didn't test your file yet, but it looks like it is using Gmsh version 4. So just FYI you will need to be using a libmesh newer than March 21st of this year to read it, since we did not support version 4 before then. In particular the latest libmesh release series (1.4.x) does not support reading Gmsh version 4.

**Comment by Laphet** [comment]
Hi,

bin/libmesh-config tells the version is 1.5.0-pre, and the Gmsh version is 4.0.4.

It means I need to use a old version Gmsh?

**Comment by Laphet** [comment]
Another question, if I choose libMesh, which mesh tool I should consider as the top priority?

**Comment by permcody** [comment]
Cubit/Trellis have the best support but aren't free. Gmsh is still probably
your best free option.

**Comment by jwpeterson** [comment]
> bin/libmesh-config tells the version is 1.5.0-pre, and the Gmsh version is 4.0.4.
> 
> Dose it means I need to use an old version Gmsh?

No, "1.5.0-pre" just means "some revision after the 1.4.x release series" so it's at least possible you have a new enough version, especially if you downloaded it recently. Just look up the git hash that you cloned, or if you downloaded a zip file from Github, just check the date on one of the files like README.md to figure out when it is from...

**Comment by Laphet** [comment]
Hi guys, did you test my mesh file?
I used the ex1 program test the mesh file generated from Gmsh/tutorial/t4.geo, which is a 2-d mesh and the program worked fine. However, the mesh file generated from Gmsh/tutorial/t3.geo, which is a 3-d mesh shew the same "Stream error".

**Comment by Laphet** [comment]
BTW, I noticed the command "bin/libmesh-config --libs" prints the optimized libMesh library, is there a suggested way to retrieve libs for debug usage?

**Comment by roystgnr** [comment]
Try ```METHOD=dbg libmesh-config --libs```

**Comment by Laphet** [comment]
Hi, I think this message may be useful for your future developments...

I exported ".inp" mesh fie by Gmsh, and this time, the "ex1" program can successfully read the mesh file.

I guess there do exist some bugs in reading newest version 3-d ".msh" files.

Another question, which mesh format will be preferred?

**Comment by Laphet** [comment]
It seems the new pre-version fixed this issue.

Good job! bros
