### ISSUE TITLE
FEMap::map() fails for infinite elements

### ISSUE THREAD

**Issue by BalticPinguin** [libMesh/libmesh#2272]
I found out, that the map() function (most probably some others as well?) fail when called on infinite elements. The reason is that the ``FEInterface::shape_function(dim, fe_type)`` function cannot handle infinite elements: having only ``dim`` and ``fe_type`` available, we cannot distinguish finite from infiite elements.
I currently don't see an easy fix for the FEInterface-function, I would fix this on the level of ``FEMap``.

Or does someone have a more elegant idea? I think, one of the reasons for the FEInterface-class is to provide a uniform interface for finite and infinite elements...

**Comment by BalticPinguin** [comment]
I just saw that this issue is introduced only recently by commit 920691ef0f by @roystgnr ...

**Comment by roystgnr** [comment]
Yeah, it looks like I need to be testing for infinite elements when getting the function pointer there.

Would you mind adding a unit test that replicates the problem so I can make sure the fix works?

Thanks, and sorry for the regression.

**Comment by BalticPinguin** [comment]
unfortunately, in my local version I reversed the changes, but I think the following patch should do the trick:
````
git diff examples/miscellaneous/miscellaneous_ex1/miscellaneous_ex1.C
diff --git a/examples/miscellaneous/miscellaneous_ex1/miscellaneous_ex1.C b/examples/miscellaneous/miscellaneous_ex1/miscellaneous_ex1.C
index 87dfaf5d3..89c8fee09 100644
--- a/examples/miscellaneous/miscellaneous_ex1/miscellaneous_ex1.C
+++ b/examples/miscellaneous/miscellaneous_ex1/miscellaneous_ex1.C
@@ -327,6 +327,8 @@ void assemble_wave(EquationSystems & es,
       // have.  Aske the element of what type it is:
       if (elem->infinite())
         {
+           Point tmp_pt(0.,0.,0.);
+           FEMap::map(3,elem,tmp_pt);
           // We have an infinite element.  Let cfe point
           // to our InfFE object.  This is handled through
           // a std::unique_ptr.  Through the std::unique_ptr::get() we "borrow"
````
I hope, this helps?

**Comment by BalticPinguin** [comment]
... it is even worse: The whole function does not work with infinite elements: I just reversed the changes locally but get completely different results:
```
     FEMap::map does not agree with FEInterface::map:
      (x,y,z)=(1.85872e-06, 7.30991e-06, 9.98231e-06)
      (x,y,z)=(-3.31972e+09, -1.2288e+10, -1.65163e+10)
```
The infinite elements are not of Lagrange-type with this respect,since the radial order (and polynomial being used) is still free...

**Comment by roystgnr** [comment]
> I just saw that this issue is introduced only recently by commit 920691e by @roystgnr ...

I finally took a look at this more closely (got to get it fixed before the next release branch at least, right?) - it looks like the problem is simply that I was promoting (and in at least one case internally using...) the new FEMap::map() as a replacement for FEInterface::map(), but in fact only **InfFEMap::map()** supports infinite elements?  I can easily have FEMap::map() farm off to InfFEMap when elem->infinite(), and after doing that I can verify that FEMap and InfFEMap and FEInterface and InfFE all give the same result with your misc ex1 patch, but maybe that means I just haven't replicated the problem you're seeing on your last comment there.

**Comment by roystgnr** [comment]
@BalticPinguin, test out #2380 and see if it works for your apps too?  If not then I'll need some other test case to trigger any remaining problem(s).
