### ISSUE TITLE
CONFIGURE_CURL & CONFIGURE NETCDF in m4/libmesh_optional_packages.m4

### ISSUE THREAD

**Issue by YinkaiLei** [libMesh/libmesh#2313]
Hi,

I found that the macro CONFIGURE_CURL has been put after the macro CONFIGURE_NETCDF in m4/libmesh_optional_packages.m4.
This results in --enable-curl not be passed to NETCDF while configuring, which causes issue in calling NETCDF4 API in application.
I'm new to libMesh, so is this a bug or is this intended?

**Comment by jwpeterson** [comment]
Hi, 

Sorry for not responding sooner. I don't think this is intended, the ordering of tests in libmesh_optional_packages.m4 is a bit haphazard. In m4/netcdf.m4, it appears that we do assume the `CONFIGURE_CURL` test has already been run:
```
  dnl allow opt-out for nested subpackages
  AS_IF([test "x$enablenested" = "xyes"],
        [
          dnl ensure that the configuration is consistent
          AS_IF([test "x$enablecurl" = "xyes"],
                [libmesh_subpackage_arguments="$libmesh_subpackage_arguments --enable-dap" ],
                [libmesh_subpackage_arguments="$libmesh_subpackage_arguments --disable-dap --disable-curl"])
          dnl pass --disable-testsets to the netcdf subpackage to disable the most rigorous tests
          libmesh_subpackage_arguments="$libmesh_subpackage_arguments --disable-testsets"
          AC_CONFIG_SUBDIRS([contrib/netcdf/v4])
        ])
```
Have you tried simply the `CONFIGURE_CURL` test to before `CONFIGURE_NETCDF` and seeing if that fixes the problem? There's some relevant info on working with autoconf files [here](https://github.com/libMesh/libmesh/wiki/Updating-configure-tests%2C-Makefiles%2C-etc.).

**Comment by YinkaiLei** [comment]
Yes, I have tried to put the CONFIGURE_CURL before CONFIGURE_NETCDF and it worked.
Actually I think CONFIGURE_CURL should be put before CONFIGURE_HDF5 as HDF5 might also need curl. Do I need to push the modification I made to the repo?

**Comment by jwpeterson** [comment]
I don't think you'll be able to push directly to the repo but if you'd like to fork it and make a PR with your tested changes, that would be very helpful, thanks.

**Comment by YinkaiLei** [comment]
Submitted, I'll close this issue.
