### ISSUE TITLE
Need `--with-metis=external` option

### ISSUE THREAD

**Issue by dschwen** [libMesh/libmesh#2331]
Currently two option values are allowed, `internal` (uses the contrib metis), and `PETSc` (uses the metis bundled with PETSc). I propose adding a third option for using a metis supplied by a package manager. 

For example the current Ubuntu 19.10 has come to a point where we can build libmesh (and ultimately MOOSE) with stock compilers, and stock packages (for PETSc, SLEPc, VTK, etc.). The main holdup is this metis option. I can build a MOOSE that passes most of the tests by supplying `--disable-metis`, however some tests error out because metis is explicitly needed (DistributedGeneratedMesh for example).

**Comment by jwpeterson** [comment]
Presumably the stock PETSc uses the stock METIS, so `--with-metis=PETSc` is close to being the right thing, but we need to include metis.h from wherever PETSc includes it from (/usr/include ?) instead of whatever we are doing now? I still think this is related to the change in bcf8df72742aad48b892bd70f9af94d8725fc99d, it seems like things would just work if metis.h from our contrib was just not installed.

**Comment by dschwen** [comment]
Yes, agreed, It does look like no matter what the setting is the contrib metis headers get used.

I think the reason is that `petsc_have_metis` is not set. In `petsc.m4` it gets set through

```
            petsc_have_metis=`cat ${PETSC_DIR}/include/petscconf.h ${PETSC_DIR}/${PETSC_ARCH}/include/petscconf.h 2>/dev/null | grep -c PETSC_HAVE_METIS`
```

But `petscconf.h` does not have that line. Shouldn't we still be able to use the system metis regardless to partition the meshes?!

**Comment by jwpeterson** [comment]
Interesting... I guess it means that the stock PETSc is not built with METIS support as I had assumed. This indeed seems like a 3rd case then, where we can theoretically use METIS for the libmesh internal partitioners, but not for anything in PETSc. I suspect this won't be useful to you in MOOSE, however, as I believe it requires a PETSc with METIS support for its tests.

**Comment by dschwen** [comment]
I can at least build libmesh with metis support with this change:

https://github.com/libMesh/libmesh/compare/master...dschwen:metis_configure?expand=1

building and testing MOOSE now...

**Comment by dschwen** [comment]
Ok, a lot more tests pass with libmesh built that way (previously a bunch of partitioning tests errored out because no partitioning library was working - I couldn't get sfcurves enabled either, but that's a separate issue!). 5/6 failures are contact related. The 6th one is a levelset advection exodiff. (that's in modules).

In framework tests some relationship manager stuff fails, but I think this might be because I built without parmetis! Testing now

**Comment by dschwen** [comment]
Again there is too-smart-for-me logic in `parmetis.m4` that I need to rip out to convince libmesh to build the way I ask it to...

**Comment by dschwen** [comment]
In this third case (package manager parmetis) there is a missing `-lparmetis` in the linker stage :-/ (also I had to nuke some stuff in the m4 to "convince" libmesh to use the external parmetis)

**Comment by dschwen** [comment]
Ok, now that MOOSE thinks parmetis is available I get a bunch or PETSc errors:

```
PETSC ERROR: Unknown partitioning type parmetis
```

I guess because libmesh reports parmetis as present despite it not being enabled in PETSc. `PetscExternalPartitioner` would need betetr checks (or libmesh needs multiple variables for petsc-level (par)metis vs. libmesh-level (par)metis).

Anyhow, I think having the option of an easy libmesh build with only stock packages for dependencies would be really neat.

**Comment by jwpeterson** [comment]
> Anyhow, I think having the option of an easy libmesh build with only stock packages for dependencies would be really neat.

I agree but unfortunately don't want to install Ubuntu MPI/PETSc/METIS on my currently working system in order to test this out. 

I would recommend you use the MOOSE package :rofl:

**Comment by dschwen** [comment]
> I would recommend you use the MOOSE package :rofl: 

:neutral_face:
