### ISSUE TITLE
Error flushing buffers to file

### ISSUE THREAD

**Issue by arswalid** [libMesh/libmesh#2332]
I am writing an exodus file in an iterative manner. 
It goes through for the first couple of iterations but then I get this error.  
Error flushing buffers to file.
[0] src/mesh/exodusII_io_helper.C, line 2257, compiled Jun 19 2019 at 22:54:20

**Comment by roystgnr** [comment]
What release or git hash are you using?

The error is probably coming from the ex_update() call in write_timestep()?

You might but a break point in there and see if you can step down into ex_update.c ... I don't actually see how you'd have gotten that error message from libMesh without getting an error message from an ExodusII ex_err() call there first.
