### ISSUE TITLE
Refactor FParser code generation and just in time compilation

### ISSUE THREAD

**Issue by dschwen** [libMesh/libmesh#2345]
I need this to be more flexible to support JIT with dual numbers and batch compilation. In batch compilation multiple functions will be compiled in a single pass. This should reduce overhead from multiple compiler launches. This functionality will require a global storage (or material object level management of batches) for function objects, which will most likely be implemented on the MOOSE side.

**Comment by roystgnr** [comment]
Sounds great, but I'm kind of surprised this is a problem.  How many function objects per executable are you guys playing with?

**Comment by dschwen** [comment]
Potentially hundreds! In a multiphase system with many components you need derivatives and second derivatives (with cross derivatives) of free energies for multiple phases, in certain scenarios you also need third order derivatives...

**Comment by roystgnr** [comment]
That'd do it, then!

Would it be possible to make batch compilation available to everyone, and avoid the global management problem, by doing some sort of registration when parsers are instantiated but postponing compilation until the first evaluation call?  Typically apps (including MOOSE) build all their ParsedFunction+ParsedFEMFunction objects during a "setup" phase, right?  So by the time an evaluation gets called, every object would be registered and we'd be able to do all the compilation in one sweep then.

**Comment by dschwen** [comment]
Hm, this would have to be thought out carefully. Eval can be called in threaded regions, and the cache files are named based on a hash of the function. In moose JIT is triggered in the non-threaded setup phase, which allows me for threads >0 to copy construct functions from thread zero versions. 

It sounds worthwhile to at least think about it. My current refactoring should make an implementation of a libmesh batch JIT compilation easier.

**Comment by roystgnr** [comment]
> Hm, this would have to be thought out carefully.

I would be offended by your implication that I'm not thinking carefully, if it hadn't been followed by undeniable proof that I'm not thinking carefully...

> Eval can be called in threaded regions, and the cache files are named based on a hash of the function.

Yeah, I see now.  That's easy to fix with an extra lock, but then we trash eval performance.  I guess that since we know the "cache_exists" bool would only ever be changing from false to true, though, we would be able to trust a "true" and we'd only have to worry about locking *after* we saw a "false"?
