### ISSUE TITLE
Allow MPI_NULL_PROC broadcast

### ISSUE THREAD

**Issue by loganharbour** [libMesh/libmesh#2353]
Currently, `root_id` in the `Communicator::broadcast` methods is checked to see if its within range of the size of the `Communicator`. I'd like to modify the assertions to allow `MPI_NULL_PROC` so that we can allow broadcasts where we don't need to know the root ahead of time as long as only one proc does the broadcast.

Thoughts?

**Comment by roystgnr** [comment]
Well, of course we should allow that.  (although by weakening the assertion, not eliminating it entirely)

Probably would be a good idea to add a unit test for the capability too, assuming this came up because you're planning to take advantage of it.
