### ISSUE TITLE
ExodusII_IO: Make writing complex magnitudes optional

### ISSUE THREAD

**Issue by jwpeterson** [libMesh/libmesh#2403]
Currently we write three Real-valued fields per complex field in Exodus files: real part, imaginary part, and complex modulus. Since the third can be computed from the first two, it doesn't strictly need to be written, thereby saving some file space and I/O time. For backwards compatibility, we should make skipping the magnitude optional and default it to "on" for the time being.

**Comment by roystgnr** [comment]
We don't even read the magnitude when doing a restart from Exodus, do we?  It's just there for viz?

**Comment by jwpeterson** [comment]
That's correct, yes.

**Comment by jwpeterson** [comment]
Added in #2421.
