### ISSUE TITLE
FEInterface::shape_function() fails for infinite elements

### ISSUE THREAD

**Issue by BalticPinguin** [libMesh/libmesh#2404]
I mentioned this already in #2272: The ``FEInterface``-functions that return a ``FEInterface::shape_ptr`` cannot handle infinite elements and currently cannot be adapted easily.

Since this affects many places (currently I try to make the ``FEMap::init_reference_to_physical_map``-function compatible with inf elements) I'd prefer to adapt the interface of that function instead of circumventing it everywhere.

My suggestion would be to to write another set of functions, taking not only ``dim`` and ``FEType`` but also ``ElemType`` and deprecate the version with two arguments.
Any thoughts or better ideas?

Best regards

**Comment by roystgnr** [comment]
> My suggestion would be to to write another set of functions, taking not only dim and FEType but also ElemType and deprecate the version with two arguments.

This sounds like an ideal solution to me.  I wouldn't even waste effort deprecating the two argument version; just replace it.  That API is pretty new, and IIRC it hasn't made it into a release tarball yet, so anyone who's bleeding edge enough to be using it outside the library is bleeding edge enough to change their code along with the library.

I think the deeper problem we've got here is lack of quality infinite element test coverage, though.  I appreciate your patience with the current regressions, but I fear that even if we get them properly fixed we'll just see more breakage in the future, unless it stops being so easy for any breakage to get all the way through "make check" without anything screaming and dying.  We desperately need a tests/fe/inf_fe_test.h in the mold of our existing tests/fe/fe_test.h, or I fear I'm just going to end up breaking things again when I do my next FE refactor (to allow increased vectorization and caching).  That sounds like a hostile threat but I swear only I mean it as an apologetic plea!

**Comment by BalticPinguin** [comment]
> I wouldn't even waste effort deprecating the two argument version; just replace it.

Ok, if you think so, I'll replace it.

>I fear that even if we get them properly fixed we'll just see more breakage in the future, unless it stops being so easy for any breakage to get all the way through "make check" without anything screaming and dying. 

Well, I understand you point and more tests could definitely catch some problems, but they cannot possibly catch things that become problems during future development: If you create a new API, you will always have the possibility to break features not yet implemented (as is the case with the current issue).

Nonetheless, more tests would be helpfull and being the only one using inifinite elements, I might be the one who should actually set them up...

**Comment by roystgnr** [comment]
I hate to put you in this position, but although I've advocated for our infinite elements support in the past (they've been orphaned and inadequately maintained since before I started developing on libMesh), I haven't actually ever put my money where my mouth is and studied the code well enough to maintain it adequately myself.

I'm hoping something like the fe_test.h idea (do a projection or a solve with a known solution, then compare the numeric to the true solution at a bunch of points) will at least catch the most egregious problems.  In this case, it wouldn't have caught the new API when it was added, but *would* have caught the new API when it was introduced to a critical path.

The trouble is that in fe_test.h we can actually have simple (well, that RATIONAL_BERNSTEIN case is pushing it) exact solutions to compare to.  In inf_fe_test.h we'd need something that was piecewise analytic, wouldn't we?  Polynomial inside the finite elements but with decay matching the radial bases in the infinite elements?

**Comment by BalticPinguin** [comment]
>  In inf_fe_test.h we'd need something that was piecewise analytic, wouldn't we?

I'll have a look at this and try to think of some nice test to do there; also, the ``examples`` might be enriched by some features; I hope I manage to get back to this soon.

Back to the actual topic: It turns out that things are more complicated. Since the ``FEInterface::shape_ptr`` propagates the actually called ``shape``-function, now it becomes apparent that the interface fo ``fe``-shape differs compared to the ``inf_fe``-shape functions: The finite element functions have ``ElemType, Order`` as first arguments the latter have ``FEType , ElemType`` as first arguments.

Do you have any better idea to handle this than adding functions with the ``FEType , ElemType``-scheme to all finite elements? (in case of inf_elem, ``Order`` is not enough)
This means a lot of changes in APIs...

**Comment by BalticPinguin** [comment]
>Do you have any better idea to handle this than adding functions with the FEType , ElemType-scheme to all finite elements?

Never mind. Yes, there are better ways...

**Comment by roystgnr** [comment]
> Do you have any better idea to handle this than adding functions with the FEType , ElemType-scheme to all finite elements?

That sounds awful, but I wouldn't rule it out, at least not if adding a shim to support the previous API isn't too hard.

IIRC that shape_ptr version of the FE code was a significant performance savings over the previous "repeat the same nested switch statements over and over and over again" code.
