### ISSUE TITLE
Add SparseMarix::clone(), zero_clone() methods

### ISSUE THREAD

**Issue by jwpeterson** [libMesh/libmesh#2431]
Currently there is no way (that I am aware of) to make a copy of an existing `SparseMatrix`. The current approach is to cast to a more derived type e.g. `PetscMatrix` and then call `MatCopy` on the raw `Mat`, which definitely seems like it could be improved. The `clone()` and `zero_clone()` names are consistent with existing `NumericVector` interfaces.

**Comment by roystgnr** [comment]
Yeah, there's no good reason we don't have this interface already, other than "none of the main developers needed it before" and "users were willing to put up with a PetscMatrix-specific hack instead".

**Comment by jwpeterson** [comment]
Added in #2435
