### ISSUE TITLE
node_ptr_range vs local_node_ptr_range

### ISSUE THREAD

**Issue by bzjan** [libMesh/libmesh#2433]
While modifying a mesh with multiple processors, I noticed that nodes that are duplicated in the memory of different processors are modified differently when using local_node_ptr_range. However, when I use node_ptr_range everything there are no problems. I would like to understand why that is.

The critical lines in my code are:
```
for(auto & node_ptr : good_mesh->node_ptr_range()) (*node_ptr) /=  node_ptr->norm();
for(auto & node_ptr : bad_mesh->local_node_ptr_range()) (*node_ptr) /=  node_ptr->norm();
```

For visualization I attached two images showing the problem. Note: The fault lines are lines between nodes managed by different processors.

.
bad mesh:
![bad_mesh](https://user-images.githubusercontent.com/5402654/74276018-ee25dc80-4ce2-11ea-8459-565a615cefd4.png)

good mesh:
![good_mesh](https://user-images.githubusercontent.com/5402654/74278305-03046f00-4ce7-11ea-8a8a-dd91183d631e.png)

**Comment by jwpeterson** [comment]
Assuming you are using a ReplicatedMesh (which is the default) then there are separate copies of the Nodes and Elems on all processors. Therefore changes in Node position that you make on one processor will not be automatically reflected on the other procs, which could potentially lead to the first figure you showed, although I would expect more than just the processor "boundaries" to look wrong in that case.

Another possibility is that there are somehow nodes which are not owned by *any* procs, which would mean that they are not moved on any proc when you execute the `local_node_ptr_range()` loop... you might want to check if that's the case as it could indicate a deeper issue with your code.

**Comment by bzjan** [comment]
1) Since the same operation is applied to all nodes on all processors (dividing by norm of the position, so they end up on the unit sphere), I did not think it was necessary to update the node positions.
For testing: How would I update mesh across all processors?

2) I checked the processor id using paraview. All nodes seem to be owned by a processor. The nodes at the boundaries turned out to be duplicated for each processor.

Does the local_node_ptr_range exclude boundary nodes?

I have attached code for an MWE.

[mesh_fault_lines_MPI.zip](https://github.com/libMesh/libmesh/files/4189080/mesh_fault_lines_MPI.zip)

**Comment by roystgnr** [comment]
If each processor modifies its local nodes, then ghost nodes remain unmodified.  We do have routines to sync ghost node location changes from their owners, but we don't invoke them automatically, since it would be a pure waste of time in the very many cases where nodes aren't moving.  And, even in cases where nodes are moving, most of the time the "embarrassingly parallel" algorithm (calculating movement redundantly on each processor) is still faster than any communication algorithm.  It takes a lot of FLOPs to outweigh network latencies.

**Comment by bzjan** [comment]
So just for me to understand this correctly:
* `local_node_ptr_range()` acceses all local nodes of a processor. However, those nodes of the processor that lie on the boundary (= ghost nodes) to other processors' nodes are not accessed.
* `node_ptr_range()` accesses all local nodes of a processor including the boundary nodes (ghost nodes)
* This means in general that when when manipulating nodes, one should not forget including boundary nodes (ghost nodes). (I previously thought I would never need to care about them, but apparently the ghost nodes of one processor are the ghost nodes of another one - specifically those that share a "node boundary")

Is that right?
(I initially thought, that `node_ptr_range()` accesses all nodes in the mesh. So I was quite surprised when `node_ptr_range()` did not lead to a segfault in parallel execution but instead it gave the correct solution  )

**Comment by jwpeterson** [comment]
> * `node_ptr_range()` accesses all local nodes of a processor including the boundary nodes (ghost nodes)

For `ReplicatedMesh`, `node_ptr_range()` access *all* the nodes of the Mesh, not just local+ghost nodes. Duplicate copies of all nodes are stored on all procs, hence the name "Replicated". When you loop over `node_ptr_range()` in your case you are doing redundant calculations, i.e. moving different copies of a given Node to the same position in space, but as @roystgnr mentioned, this duplication of effort is typically faster (and simpler) than synchronizing node positions using a subsequent communication step. This latter approach is required for `DistributedMesh`, where the only the local nodes and elements are actually stored.
