### ISSUE TITLE
Edge3::volume failure for not-quite-linear edges

### ISSUE THREAD

**Issue by roystgnr** [libMesh/libmesh#2510]
Wen Jiang hit this case:

```
point(0) = (x,y,z)=(0.810213, 0, 0),
point(1) = (x,y,z)=(1.01, 0, 0),
point(2) = (x,y,z)=(0.910055, 0, 0)
a = 1.06426e-08
c = 0.00997871
2. * std::sqrt(c) = 0.199787
b = 2.06106e-05
ba = 1936.61
ca = 937619
s1 = 967.307
s2 = 969.307
log_term = nan
Assertion `!libmesh_isnan(log_term) && log_term > 0.' failed.
```

Round-off error in the point values prevents me from reproducing that exactly, but it turns out to be *easy* to reproduce the same effect: just tweak the middle point in a line far enough to avoid the ```TOLERANCE*TOLERANCE``` check but not much farther, and you get NaN in log_term.

**Comment by roystgnr** [comment]
Fixing log_term in the a->0 limit turns out to be simple enough:

```
  const Real root_a = std::sqrt(a);
  
  libmesh_assert (1.-ba+ca>0.);
  
  const Real r1 = std::sqrt(a - b + c); // sqrt(c) if linear
  const Real r2 = std::sqrt(a + b + c); // sqrt(c) if linear
  const Real r2_minus_r1 = 2*b/(r2+r1);
  
  Real log_term = // 1 if linear 
    (a - 0.5*b + r1*root_a) / (a - 0.5*b + r2*root_a);
  libmesh_assert(!libmesh_isnan(log_term) && log_term > 0.);

  return 0.5*(r1 + r2 + ba*b/(r2+r1) +
              root_a*(ca - 0.25*ba*ba)*std::log(log_term)
             );
```

But the astute reader will note that there are still four divisions by zero in that final expression the a->0 limit.  The particularly astute reader will notice that ```ba*b``` in the third term in the final answer isn't just a 0/0 case that itself approaches 0, it's a *path-dependent* limit that doesn't vanish in 2D or 3D.  This implies that either my math is wrong, the original formula was wrong, or we the fourth term must *also* be a path-dependent limit which exactly cancels out the path-dependence in the third term, despite the forms looking nothing alike.

Pinging @jwpeterson

**Comment by roystgnr** [comment]
[edge3.pdf](https://github.com/libMesh/libmesh/files/4506548/edge3.pdf)

John's derivation of the current formula.

**Comment by roystgnr** [comment]
His comment was "I don't think there's any errors in this derivation but it's certainly possible. Or maybe an error in the translation into code?" - but I can't find any errors in either.

**Comment by roystgnr** [comment]
Hmmm... except that the unmarked equation "8b" is a division by zero whenever A is zero.  Some of that's just formal nitpicking, but later the degenerate case changes the form of the integral; that "check for A within tolerance" hack in the code isn't just a sop to floating point arithmetic, it's almost demanded by the derivation.

**Comment by jwpeterson** [comment]
According to the man page, the output of `std::log(x)` is nan if either x is nan or x<0. So, can we check whether either of these is the case and then fall back on the straight line approximation? Likewise for any of the std::sqrt() terms. This way we could get rid of the tolerance completely (still checking for a==0.) and fall back on the straight line approximation in case any computation would return nan.

**Comment by jwpeterson** [comment]
@jiangwen84 PR #2514 was merged so you may want to try your case again after a libmesh update.

**Comment by jwpeterson** [comment]
We are leaving this issue open since @roystgnr is still planning to fix the scaling/cancellation/accuracy issues which remain in the formula, but at least it should not crash for typical cases now :-)

**Comment by roystgnr** [comment]
s/planning/hoping, since I still can't figure out what's up with that path-dependent term, but yeah, this is still an issue.

**Comment by vikramvgarg** [comment]
If we think about the area of a triangle, one can compute it in ways that include or avoid the use of ratios,
A = 1/2 ab sin(C) -> ratio of lengths involved in computing sin, or C itself
A = sqrt( s*(s-a)*(s-b)*(s-c) ), s = ( a + b + c )/2 -> no ratios involved

Perhaps we should try and find general expressions for these volumes that avoid ratios ? The volume should be totally determined by lengths, and we should always have an expression that avoids the use of angles, and hence ratios ?

**Comment by jwpeterson** [comment]
@vikramvgarg I think that's what @roystgnr is doing in his reformulation... getting rid of division by  "a". In the PDF he attached here, the ratio is first introduced due to the "shift" B/(2A) in the quadratic formula, so it may not be essential, however I think the main point is that in the analytical formula A is either 0 or it isn't, but things are quite so straightforward in floating point arithmetic land.

**Comment by roystgnr** [comment]
After playing around in octave (^ below is exponentiation, not xor), this is the most stable formula I've come up with:

```
b = -abs(b)
root_a = sqrt(a)
b_over_root_a = b/root_a
r1 = sqrt(a-b+c)
r2 = sqrt(a+b+c) 
log_term_2_num = (root_a - 0.5*b_over_root_a + r1)
log_term_2_den = (-root_a - 0.5*b_over_root_a + r2)
log_term_2 = (log_term_2_num / log_term_2_den)^(1/root_a)
log_val_2 = log(log_term_2)
log_coef_2 = (c-0.25*b_over_root_a*b_over_root_a)
length_2 = 0.5*(r1 + r2 + b_over_root_a*b_over_root_a/(r2+r1) + log_coef_2*log_val_2)
```

For most "real curve" cases this matches our existing length calculation to the last digit.  For perturbations approaching 0, our existing calculation starts to show error in the +x direction at around 2e-10, fails completely in the -x direction for *any* perturbation, and shows error in the +/-y direction at around 1e-5.  The new calculation has similar error in +/-y, but is now fine for any non-zero +/-x.

log_term_2 here, the 1^infinity limit, is the only remaining term showing unacceptable numeric error, but nothing I've tried yet to improve it works.

**Comment by jwpeterson** [comment]
Sounds like a definite improvement to me. Did you intentionally keep the exponentiation "inside" the log term rather than pulling `1/root_a` out in front as a multiple? When `1/root_a` is small it seems like exponentiation would be more likely to lead to overflow issues, plus we already divide to get `b_over_root_a`.

**Comment by roystgnr** [comment]
Oh, that was definitely intentional, but it was in the hopes that by bringing it in I could find some way to do cancellation inside the term.  I also tried the log(1)/0 limit with division by root_a outside, but that "length_3" calculation was matching length_2 to the last digit in all my tests.

Huh.  But if we give up on further analytic formula improvements, then keeping the root_a outside does let us use log1p instead of log(thing_really_near_one), and that seems to give me about an order of magnitude less error in the +/-y case.  I'd still like to get a really *robust* formula, and I'm still hopeful that I can step back for a while and rethink things and get one, but if after that I'm ready to give up for good then I'll just put the log1p version into a PR.

**Comment by roystgnr** [comment]
Oh wow we can go further with that.  There's still some disastrous r2-r1 cancellation error going on in the obvious expression for the log1p case, and if I fix that then I'm suddenly getting decent numbers on the y axis.

Now I have
```
log_term_3c = (2*root_a - 2*b/(r1+r2))/log_term_2_den
log_val_3c = log1p(log_term_3c)/root_a
length_3c = 0.5*(r1 + r2 + b_over_root_a*b_over_root_a/(r2+r1) + log_coef_2*log_val_3c)
```

And short of plugging in an *exactly* zero perturbation (which we can then safely use the exact FP test for), I cannot get this thing to break.  I'll set up a PR now.

**Comment by jwpeterson** [comment]
OK, sounds good! I hadn't been aware of log1p previously, that's a nice touch.
