### ISSUE TITLE
Add dual basis

### ISSUE THREAD

**Issue by dewenyushu** [libMesh/libmesh#2550]
The dual basis is often utilized in the dual Lagrange approach. Here, the shape functions for the Lagrange multipliers (LMs) satisfy the biorthogonal condition across the interface. The biorthogonal condition results in a diagonalized local mass matrix, which allows to condense out the LMs and transform the saddle point problem in to a positive definite one. 

- [x] Add `dual_phi`, `dual_dphi`, and `dual_d2phi` in the `fe_base` class
- [x] Add `compute_dual_shape_functions()` to compute the dual shape functions
- [x] Initialize dual shape functions in `fe` for `lowerD` element type

**Comment by dewenyushu** [comment]
Dual basis unit test fails with:

- First order, Lagrange, Hex8

- Second order, Lagrange, QUAD9

- All 3D second order elements

Issue reported by @jwpeterson 
https://github.com/libMesh/libmesh/pull/2552#issuecomment-627581010

**Comment by jwpeterson** [comment]
@dewenyushu I think this issue can be closed if you are happy with it, I don't have any other outstanding issues.
