### ISSUE TITLE
Preserve Ordering of Nodal Variables in Nemesis Output Files

### ISSUE THREAD

**Issue by frombs** [libMesh/libmesh#2581]
When nodal solutions are written to Nemesis output files, `EquationSystems::find_variable_numbers` is called [(see line 1384 here)](https://github.com/libMesh/libmesh/blob/6ce8af5b657b1df5905ef40729d64637c25f25c4/src/mesh/nemesis_io.C#L1384).

This function creates a vector pair that lists the position of each nodal variable and its assigned system.  However, the ordering of the vector pairs is not preserved during the call, causing nodal variables values to be written to the wrong variable name in the Nemesis output files.  This can be verified by viewing the nodal variables in Paraview.

It seems that the Nemesis format expects the variable positions to be arranged alphabetically by variable name.  Here is a printout of the variable names and positions from Exodus showing the correct alphabetical ordering:

![Exodus_var_position](https://user-images.githubusercontent.com/8171022/82717474-85db8500-9c59-11ea-8e84-c3d5ec8861c6.png)

Here is the same output from Nemesis showing that the variables are not being ordered alphabetically:

![Nemesis_var_position_wrong](https://user-images.githubusercontent.com/8171022/82717464-765c3c00-9c59-11ea-9176-25ea079f43b5.png)

I was able to resolve this issue by alphabetically sorting the `var_nums` vector pairs and  the `names` vector withing `es:find_variable_numbers` before they are output.  Below is an updated screenshot showing the correct ordering applied to the Nemesis Output file:

![Nemesis_var_position_fixed](https://user-images.githubusercontent.com/8171022/82717488-a3105380-9c59-11ea-9dad-8f1637bb0bd0.png)

The changes to `EquationSystems::find_variable_numbers` can be found in the referenced commit below.  Let me know your thoughts.  I can create a pull request if you think it is a reasonable solution.

**Comment by roystgnr** [comment]
The commit looks good to me, thanks!  Set up a PR?
