### ISSUE TITLE
error: static_assert failed due to requirement '__is_cpp17_move_insertable<std::__1::allocator<FunctionParserBase<double>>, false>::value' "The specified type does not meet the requirements of Cpp17MoveInsertable"

### ISSUE THREAD

**Issue by yurivict** [libMesh/libmesh#2710]
clang-11 fails to compile libmesh-1.4.1 on FreeBSD:

```
In file included from src/apps/calculator.C:24:
In file included from /usr/include/c++/v1/map:481:
In file included from /usr/include/c++/v1/__tree:15:
/usr/include/c++/v1/memory:1634:13: error: static_assert failed due to requirement '__is_cpp17_move_insertable<std::__1::allocator<FunctionParserBase<double>>, false>::value' "The specified type does not meet the requirements of Cpp17MoveInsertable"
            static_assert(__is_cpp17_move_insertable<allocator_type>::value,
            ^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/c++/v1/vector:954:21: note: in instantiation of function template specialization 'std::__1::allocator_traits<std::__1::allocator<FunctionParserBase<double>>>::__construct_backward_with_exception_guarantees<FunctionParserBase<double> *>' requested here
    __alloc_traits::__construct_backward_with_exception_guarantees(
                    ^
/usr/include/c++/v1/vector:1631:5: note: in instantiation of member function 'std::__1::vector<FunctionParserBase<double>, std::__1::allocator<FunctionParserBase<double>>>::__swap_out_circular_buffer' requested here
    __swap_out_circular_buffer(__v);
    ^
/usr/include/c++/v1/vector:1644:9: note: in instantiation of function template specialization 'std::__1::vector<FunctionParserBase<double>, std::__1::allocator<FunctionParserBase<double>>>::__push_back_slow_path<const FunctionParserBase<double> &>' requested here
        __push_back_slow_path(__x);
        ^
./include/libmesh/parsed_fem_function.h:632:15: note: in instantiation of member function 'std::__1::vector<FunctionParserBase<double>, std::__1::allocator<FunctionParserBase<double>>>::push_back' requested here
      parsers.push_back(fp);
              ^
./include/libmesh/parsed_fem_function.h:349:9: note: in instantiation of member function 'libMesh::ParsedFEMFunction<double>::partial_reparse' requested here
  this->partial_reparse(expression);
        ^
./include/libmesh/parsed_fem_function.h:219:9: note: in instantiation of member function 'libMesh::ParsedFEMFunction<double>::reparse' requested here
  this->reparse(expression);
        ^
src/apps/calculator.C:157:29: note: in instantiation of member function 'libMesh::ParsedFEMFunction<double>::ParsedFEMFunction' requested here
  ParsedFEMFunction<Number> goal_function(old_sys, calcfunc);
                            ^
4 warnings and 1 error generated.
```

Log: http://beefy18.nyi.freebsd.org/data/head-amd64-default/p549079_s365919/logs/errors/libmesh-1.4.1_3.log (IPv6 URL)

**Comment by jwpeterson** [comment]
From a brief analysis, the line which triggers the error:
```
parsers.push_back(fp);
```
where
```
FunctionParserBase<Output> fp;
```
We have explicitly deleted the move assignment operator and move constructor for this class (see: contrib/fparser/fparser.hh)
```
    // This class manages its own memory via reference counting, so the
    // compiler-generated move constructor and move assignment operator
    // are not safe to use. By explicitly deleting them we can prevent
    // users from assuming this class can be moved when it really can't.
    FunctionParserBase (FunctionParserBase &&) = delete;
    FunctionParserBase & operator= (FunctionParserBase &&) = delete;
```
so it does make sense to me that it would fail to meet the requirements of "Cpp17MoveInsertable", however what's not clear to me is why that's an issue... we are just calling `push_back()` so the compiler should just make a copy IMO.

I would be happy to patch 1.4.1 if a satisfactory resolution to this issue can be found, but I don't have ready access to either clang-11 or FreeBSD so I'm afraid I won't be able to do much testing myself.

**Comment by yurivict** [comment]
> I would be happy to patch 1.4.1 if a satisfactory resolution to this issue can be found, but I don't have ready access to either clang-11 or FreeBSD so I'm afraid I won't be able to do much testing myself.

Please install clang-11 on the OS of your choice and you should be able to reproduce this problem.

**Comment by roystgnr** [comment]
My apologies, but I vaguely recall getting a second-hand report of running into this problem months ago, and I hastily decided the solution must be "go find a better compiler" since obviously push_back() does a copy construction not a move construction ... but looking into it more deeply today [it seems like the new clang++ behavior here is still standards-compliant](https://stackoverflow.com/a/52953306/1120062).

I think the most broadly-compatible easy fix is for us to turn that parsers vector into a vector of unique_ptr ... but I also don't have a system handy with more than clang-10 in the repos, and my last few times trying to build clang++ from scratch did not go well, so I'll have no good way to test the patch.

**Comment by jwpeterson** [comment]
Out of curiosity, I made a list of classes in libmesh with deleted move constructors. As I understand it, these classes do not satisfy the "MoveInsertable" requirements and therefore cannot be inserted into a std::vector with push_back():
```
git grep "= delete" | grep "&&" | grep -v operator= | less
```

It came back with the following classes where the move constructor is deleted because it is not possible to default:
* FunctionParserBase
* FunctionParserADBase
* All Elem-derived classes
* LaspackMatrix, LaspackVector
* PetscMatrix, PetscVector
* EpetraMatrix, EpetraVector

And these in which the move constructor could probably be defaulted with a small amount of work:
* RBEIMConstruction (RBConstructionBase move ctor could possibly be implemented)
* MeshFunction (_point_locator could become std::unique_ptr)

So, I think we are for the most part OK, since those in the first list are not typically not stored by value in vectors (although we store vectors of Elem pointers quite often). I may take a crack at fixing the last two at some point.

**Comment by yurivict** [comment]
1.6.0-rc1 release asserts with all clang versions: 8,9, 10, 11.

**Comment by roystgnr** [comment]
8 through 10 too?  Now that I might be able to replicate; thanks!

**Comment by yurivict** [comment]
Yes, 1.6.0-rc1 fails with more compilers.

**Comment by jwpeterson** [comment]
> 8 through 10 too? Now that I might be able to replicate; thanks!

I don't see how this can be possible? MOOSE guys have been using these compilers, at least versions 8 and 9, and have not run into any issues as far as I know. Note also that the potential fix merged in #2720 is not in 1.6.0-rc1 yet. I felt we should wait to see if it would work before backporting it to any releases.

**Comment by yurivict** [comment]
1.6.0-rc1 fails too.

**Comment by jwpeterson** [comment]
@yurivict Can you let us know how libmesh is configured when it hits the static_assert? Maybe it's that you are using `-std=c++17` (or -std=c++17 is the default for your compiler), which is something that we don't really test. By the way, I tried to click on the link in your original post but it doesn't work for me...

**Comment by yurivict** [comment]
The log linked above has all command lines.

**Comment by yurivict** [comment]
It might be that the compiler defaults to -std=c++17. You need to set your level which you don't currently do,

**Comment by yurivict** [comment]
> I tried to click on the link in your original post but it doesn't work for me...

It's an IPv6 URL.

**Comment by yurivict** [comment]
Setting ```-std=c++11``` doesn't solve the problem in 1.6.0-rc1 with clang-10.

**Comment by yurivict** [comment]
In ```include/libmesh/fparser_ad.hh``` you have deleted move-constructors:
```
  FunctionParserADBase (FunctionParserADBase &&) = delete;
  FunctionParserADBase & operator= (const FunctionParserADBase &) = delete;
  FunctionParserADBase & operator= (FunctionParserADBase &&) = delete;
```

This directly causes the failure at ```include/libmesh/parsed_function.h:561``` - you can't use such type for ```vector<>::push_back()```.

Gcc doesn't catch basic modern C++ bugs any more.

**Comment by jwpeterson** [comment]
Yes, I understand the problem and we have already patched it in master... if you can try master on your system that would be very helpful.

> It's an IPv6 URL.

OK... well I click the link in my browser (Chrome) and it doesn't work. Is there something special I need to do to view IPv6 links?

**Comment by yurivict** [comment]
> OK... well I click the link in my browser (Chrome) and it doesn't work. Is there something special I need to do to view IPv6 links?


You obviously don't have IPv6. When I raised this issue with the people who support the servers they said that about everybody is supposed to have IPv6 addresses because they are the future.

Personally, I view these links through the Tor network. Tor exit nodes usually are IPv6-enabled.

**Comment by yurivict** [comment]
> Yes, I understand the problem and we have already patched it in master... if you can try master on your system that would be very helpful.

I tried the latest revision 2873a0e09 and it still fails the same way.

**Comment by yurivict** [comment]
gcc-9 also fails to build rc1:
```
tecsrc/arrlist.cpp: In function 'Boolean_t ArrayListIsValid(ArrayList_pa)':
tecsrc/arrlist.cpp:390:26: error: 'VALID_REF' was not declared in this scope; did you mean 'INVALID_REF'?
  390 |     Boolean_t IsValid = (VALID_REF(ArrayList) &&
      |                          ^~~~~~~~~
      |                          INVALID_REF
```

**Comment by jwpeterson** [comment]
> I tried the latest revision 2873a0e and it still fails the same way.

The code is different now (the vector stores unique_ptrs instead of objects) so while I believe it may still not be quite right, I don't think the error can be the *same* as it was before.

> tecsrc/arrlist.cpp: In function 'Boolean_t ArrayListIsValid(ArrayList_pa)':

This is an error in the Tecplot contrib code that hasn't been updated in ages, probably best to just configure with `--disable-tecplot` on your system and not worry about it for the moment.

**Comment by yurivict** [comment]
rev. 2873a0e fails like this:

```
/bin/sh ./libtool  --tag=CXX   --mode=compile c++ -DHAVE_CONFIG_H -I. -I./include  -DNDEBUG  -DLIBMESH_IS_COMPILING_ITSELF -I./contrib/metaphysicl/src/numerics/include -I./contrib/metaphysicl/src/core/include -I./contrib/metaphysicl/src/utilities/include -I./contrib/nanoflann/include -I./contrib/fparser -I./contrib/libHilbert/include -I./contrib/gmv -I./contrib/qhull/qhull/src -I./contrib/qhull/qhull/src/libqhullcpp -I./contrib/triangle -I./contrib/tetgen -I./contrib/metis/include -I./contrib/gzstream -I./contrib/sfcurves -I./contrib/laspack -I./contrib/timpi/src/utilities/include -I./contrib/timpi/src/utilities/include -I./contrib/timpi/src/parallel/include -I./contrib/timpi/src/algorithms/include  -I/usr/local/include/eigen3 -D_THREAD_SAFE -pthread -I/usr/local/include -I./include  -fno-omit-frame-pointer -O2 -felide-constructors -Qunused-arguments -Wunused-parameter -Wunused    -fopenmp   -O2 -pipe -fno-omit-frame-pointer -fstack-protector-strong -fno-strict-aliasing -fno-omit-frame-pointer   -MT src/base/libmesh_opt_la-dof_map.lo -MD -MP -MF src/base/.deps/libmesh_opt_la-dof_map.Tpo -c -o src/base/libmesh_opt_la-dof_map.lo `test -f 'src/base/dof_map.C' || echo './'`src/base/dof_map.C
libtool: compile:  c++ -DHAVE_CONFIG_H -I. -I./include -DNDEBUG -DLIBMESH_IS_COMPILING_ITSELF -I./contrib/metaphysicl/src/numerics/include -I./contrib/metaphysicl/src/core/include -I./contrib/metaphysicl/src/utilities/include -I./contrib/nanoflann/include -I./contrib/fparser -I./contrib/libHilbert/include -I./contrib/gmv -I./contrib/qhull/qhull/src -I./contrib/qhull/qhull/src/libqhullcpp -I./contrib/triangle -I./contrib/tetgen -I./contrib/metis/include -I./contrib/gzstream -I./contrib/sfcurves -I./contrib/laspack -I./contrib/timpi/src/utilities/include -I./contrib/timpi/src/utilities/include -I./contrib/timpi/src/parallel/include -I./contrib/timpi/src/algorithms/include -I/usr/local/include/eigen3 -D_THREAD_SAFE -pthread -I/usr/local/include -I./include -fno-omit-frame-pointer -O2 -felide-constructors -Qunused-arguments -Wunused-parameter -Wunused -fopenmp -O2 -pipe -fno-omit-frame-pointer -fstack-protector-strong -fno-strict-aliasing -fno-omit-frame-pointer -MT src/base/libmesh_opt_la-dof_map.lo -MD -MP -MF src/base/.deps/libmesh_opt_la-dof_map.Tpo -c src/base/dof_map.C  -fPIC -DPIC -o src/base/.libs/libmesh_opt_la-dof_map.o
In file included from src/apps/fparser_parse.C:23:
In file included from ./include/libmesh/parsed_function.h:22:
In file included from ./include/libmesh/function_base.h:24:
In file included from ./include/libmesh/libmesh_common.h:46:
In file included from /usr/include/c++/v1/complex:246:
In file included from /usr/include/c++/v1/sstream:173:
In file included from /usr/include/c++/v1/ostream:138:
In file included from /usr/include/c++/v1/ios:215:
In file included from /usr/include/c++/v1/__locale:14:
In file included from /usr/include/c++/v1/string:504:
In file included from /usr/include/c++/v1/string_view:175:
In file included from /usr/include/c++/v1/__string:57:
In file included from /usr/include/c++/v1/algorithm:643:
/usr/include/c++/v1/memory:1720:13: error: static_assert failed due to requirement '__is_cpp17_move_insertable<std::__1::allocator<FunctionParserADBase<double> >, false>::value' "The
      specified type does not meet the requirements of Cpp17MoveInsertable"
            static_assert(__is_cpp17_move_insertable<allocator_type>::value,
            ^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/c++/v1/vector:952:21: note: in instantiation of function template specialization 'std::__1::allocator_traits<std::__1::allocator<FunctionParserADBase<double> >
      >::__construct_backward_with_exception_guarantees<FunctionParserADBase<double> *>' requested here
    __alloc_traits::__construct_backward_with_exception_guarantees(
                    ^
/usr/include/c++/v1/vector:1627:5: note: in instantiation of member function 'std::__1::vector<FunctionParserADBase<double>, std::__1::allocator<FunctionParserADBase<double> >
      >::__swap_out_circular_buffer' requested here
    __swap_out_circular_buffer(__v);
    ^
/usr/include/c++/v1/vector:1640:9: note: in instantiation of function template specialization 'std::__1::vector<FunctionParserADBase<double>, std::__1::allocator<FunctionParserADBase<double>
      > >::__push_back_slow_path<const FunctionParserADBase<double> &>' requested here
        __push_back_slow_path(__x);
        ^
./include/libmesh/parsed_function.h:561:15: note: in instantiation of member function 'std::__1::vector<FunctionParserADBase<double>, std::__1::allocator<FunctionParserADBase<double> >
      >::push_back' requested here
      parsers.push_back(fp);
              ^
./include/libmesh/parsed_function.h:254:9: note: in instantiation of member function 'libMesh::ParsedFunction<double, libMesh::VectorValue<double> >::partial_reparse' requested here
  this->partial_reparse(expression);
        ^
./include/libmesh/parsed_function.h:223:9: note: in instantiation of member function 'libMesh::ParsedFunction<double, libMesh::VectorValue<double> >::reparse' requested here
  this->reparse(expression);
        ^
src/apps/fparser_parse.C:36:20: note: in instantiation of member function 'libMesh::ParsedFunction<double, libMesh::VectorValue<double> >::ParsedFunction' requested here
  ParsedFunction<> func(function_string);
                   ^
1 error generated.
gmake[3]: *** [Makefile:31329: src/apps/fparser_parse_opt-fparser_parse.o] Error 1
gmake[3]: *** Waiting for unfinished jobs....
```

**Comment by jwpeterson** [comment]
OK, I see, the issue is that we had the same type of code in both parsed_function.h and parsed_fem_function.h, and the fix in #2720 was only for the latter. I will go ahead and push the same fix for that one.

**Comment by jwpeterson** [comment]
@yurivict when you have some time, can you please try compiling master again? As of 746b48936, we've updated it with a fix for the most recent issue.

**Comment by yurivict** [comment]
The problem is fixed in rev. 746b489, thank you.

**Comment by jwpeterson** [comment]
OK, great, thanks for letting us know.

**Comment by roystgnr** [comment]
Thanks for the constant feedback!  I know debugging-via-chat is the most painful sort of debugging; I'm glad it worked out this time.  Here's hoping that just backporting these fixes will be sufficient for the release too.

**Comment by yurivict** [comment]
Thanks for fixing it!
