### ISSUE TITLE
Make vector projection code work for elements that don't have old dof objects

### ISSUE THREAD

**Issue by bwspenc** [libMesh/libmesh#272]
This is a follow-on to an earlier discussion in pull request #215.

I'm trying to add new nodes and elements to the mesh.  When I do this, and then call EquationSystems::reinit(), I run into errors in the calls to project_vector() in System::restrict_vectors() because my newly created elements don't have old dof objects.

If I uncomment these lines of code that appear in two places in system_projection.C: (line 825 and 1188)
```
      // if (!elem->old_dof_object || !elem->old_dof_object->has_dofs(system.number()))
      //  continue;
```
my problem runs fine.  However, the comments above these lines of code suggest that this is a bad idea because it will break for FE types for which the element stores no dofs.  I don't really understand that comment, because I'm using linear Lagrange elements, which have no dofs, and it seems to work fine.  However, a bunch of the adaptivity tests in MOOSE fail with those lines uncommented, so there's obviously a problem with that.

I'd like to figure out a solution for this so that I can build my code against the standard version of libmesh.  I'm just not sure what the preferred way to fix this is, hence I'm opening this issue to discuss it.  @roystgnr previously suggested that maybe we should skip the tests for old dof values only if a function was supplied, and set those dofs to the value of the function.  If that's the preferred solution, would we create some function that evaluates to 0, and pass that in to the two calls to project_vector within System::restrict_vectors()?  I personally don't care what the dofs get set to -- I go back after the solution reinit and set them to the correct values.

**Comment by roystgnr** [comment]
This should have been fixed by #559 too.
