### ISSUE TITLE
GhostPointNeighbors has unintended behavior

### ISSUE THREAD

**Issue by loganharbour** [libMesh/libmesh#2747]
For this case, where the node in question is the sphere in the middle, the two elements pictured are on different processors, and there are other pyramids filling the gaps between these two pyramids:

![Screen Shot 2020-10-12 at 4 20 03 PM](https://user-images.githubusercontent.com/22062133/96009656-247da380-0dfe-11eb-93e6-72176d858400.png)

The recent changes introduced to `GhostPointNeighbors` do not properly ghost these elems.

**Comment by roystgnr** [comment]
Stupid question that just came to me - is it possible that the weirdness with Pyramid::contains_point() could be responsible here?  Are any of the pyramids in the chain connecting those two failing to return true when asked if they contain their apex node?

**Comment by jwpeterson** [comment]
> is it possible that the weirdness with Pyramid::contains_point()

This is almost certainly what's happening. The Jacobian is singular at the apex node and therefore the generic `contains_point()` returns false. We could possibly override `Pyramid::contains_point()` to first check whether the given Point is on the apex and if not, then call the generic `contains_point()` routine?

**Comment by roystgnr** [comment]
> We could possibly override Pyramid::contains_point() to first check whether the given Point is on the apex and if not, then call the generic contains_point() routine?

That would at least be infinitely better than the current behavior.

If we use the user-specified tolerance properly to test for point==apex then we'd probably be correct in general, too.

Except ... I'd hope users who play with this stuff in detail have a sense of how safe or unsafe it is to reduce their specified tolerance based on the FP error in their particular application, but I'm not sure if that sense holds up if the tolerance is getting blown up by Jacobian ill-conditioning..

**Comment by loganharbour** [comment]
Wow - what a very specific use case. I'm surprised I managed to catch this.

I'll add this in per this discussion and come up with a test.

**Comment by loganharbour** [comment]
Just this worked like a charm:
```
bool Pyramid::contains_point (const Point & p, Real tol) const
{
  // At the Pyramid apex (node 4), the Jacobian is singular which will result
  // in a false return from Elem::point_test, therefore check this first
  if (node_ref(4).absolute_fuzzy_equals(p, tol))
    return true;

  return Elem::contains_point(p, tol);
}
```

Is this sufficient? I'm still a little iffy on taking the tolerance directly. 

Also, is a unit test for `contains_point` on all of the Pyramid types sufficient or do you guys have something better in mind?

**Comment by jwpeterson** [comment]
> Also, is a unit test for contains_point on all of the Pyramid types sufficient or do you guys have something better in mind?

In 8dc7b9db98aed4dfc2c89bed5dca175a6395d3a4 I skipped some of the Pyramid `build_cube()` tests because they were dying in the `--disable-exceptions` configuration. Presumably with this fix we could now turn those back on, and then turn on the "Test No Exceptions" test in CIVET to make sure it now works.

**Comment by loganharbour** [comment]
Will do - I’ll get this in. Thanks for the help.
