### ISSUE TITLE
Infinite DOF constraints

### ISSUE THREAD

**Issue by BalticPinguin** [libMesh/libmesh#2798]
Hi @roystgnr,
  
I'd like to discuss the issue with DOF restrictions from #2792 separately, because I fear this might get a longer side-discussion.

I didn't understand the mechanisms involved in this in detail yet, so I am lost without some further help on this.

First thing is that there are node-wise (`FEAbstract::compute_node_constraints()`) and element-wise (`FE::compute_constraints`) constraints, depending on configuration. Are these two different approaches to do the same thing?

For infinite elements, the shape functions have a 'tensorial basis', i.e. for a `InfPrism6` with `radial_order=2` we have 3 basis functions from the basis (`Tri3`) and two radial degrees of freedom, resulting in 6 DOFs.
(Note that `radial_order` is not a property of the element but is provided by `FEType`, not sure this is important here).
The `i`-th basis function is constructed by a product of the `b`-th base (2D shape function) and `r`-th radial polynomial. The particular indices `r` and `b` for a given `i` are looked-up by `InfFE::compute_shape_indices`.

Since this is not node-based, to my understanding one should make `FEAbstract::compute_node_constraints()` not valid for infinite elements at all?

Using the `FE::compute_constraints`, the proper way might be to check the nodes of the base face (i.e. scan over `b`) and if a certain `b` needs restriction one should find the corresponding `i` where respective constraints should be set?
Or do you see any other possible mechanisms?

Many thanks in advance,
Hubert

**Comment by roystgnr** [comment]
> Are these two different approaches to do the same thing?

Nope.  The compute_node_constraints() constrains what it says on the box: nodes.  It's for allowing user code to move nodes freely on a mesh with hanging nodes but then letting libMesh make the hanging node locations consistent again afterwards.  It's kind of a niche use case, and would be way more of a niche use case when combined with 3D infinite elements, so we could just libmesh_not_implemented() it, except that it's basically a special case of Lagrange constraints, so if we can properly constrain DoFs of arbitrary FE type then we ought to be able to easily properly constrain Nodes too.

> one should make FEAbstract::compute_node_constraints() not valid for infinite elements at all?

If there's hanging nodes (there are in 3D), and their location is important, then no, it's still valid.

> a 'tensorial basis'

Does this work with *any* non-infinite basis on the base elem?  E.g. could I use Hierarchic or even Hermite instead of Lagrange and still expect it to work?

> the proper way might be to check the nodes of the base face (i.e. scan over b) and if a certain b needs restriction one should find the corresponding i where respective constraints should be set?

That should work to find the infinite hanging node, yes, but you could more easily just ignore the base face and compare inf_elem->level() to inf_elem->neighbor(n)->level().  If the latter is smaller then one or both of the InfFE nodes on that side needs constraining.  To be safe it'd be a good idea to compute constraints for the base nodes on that side at the same time, though; I don't recall how we handle redundancy but it'd sure be a shame if a constraint didn't get computed because e.g. in parallel the base element was thinking "I don't own that node; someone else will get it" and the inf element was thinking "I own that node, but I'm an infinite element; someone else will get it".

**Comment by BalticPinguin** [comment]
>  and their location is important, 

That is a good point; I am not aware of any place where the location of the 'outer nodes' currently is used.
In fact, usually the outer nodes are used for construction of the mapping function. But for this, our implementation assumes that they are twice as far away from the `elem->origin()` as the corresponding base node. This is a restriction, but makes sense due to good properties of the mapping function (I don't know any work in the literature, where other mappings are used).

Thus, if you move the 'outer' points in radial direction, I don't know any point where this might appear to be important. If you move them parallel to the base node, there SHOULD be some dependence, but I think, currently the implementation would be blind to the changes (and we must be carefull allowing for this, because this can lead to problems when the 'radial rays' cross each other.

> Does this work with any non-infinite basis on the base elem?

Yes, in principle it should work with any basis (in this particular implementation there might be quite some problems, but maybe it is worth to check it out).

From how I understand it now, I think I should do the following:
  *  implement a  `InfFE::compute_node_constraints()` restricts both the base and the 'outer' nodes; with this we can be safe if I forgot some influence of these nodes and to future changes in the implementation. These 'additional' restrictions should anyway not harm, I guess.
   * Concerning the  `compute_constraints()` I am less certain how to do it properly: I understand that I need restriction if ` inf_elem->level() > inf_elem->neighbor(n)->level()` ; however, I think it should still be enough to restrict at the base's location (because DOFs are restricted even if they contribute with '0' at the considered position, right?). Than, however, it would not be sufficient to restrict the `base` element, (because with this we would miss many DOFs) but should restrict the 'Inf' elem evaluated at the base surface? (I hope I made the difference clear)...

Do you agree?

**Comment by BalticPinguin** [comment]
Hi @roystgnr,
after quite some time I am currently working on the re-implementation of these constraints. However, I still have problems understanding how to implement the `InfFE::compute_node_constraints()` function properly:
In the `FEAbstract::compute_node_constraint`-function, the constraints are set by
````
             NodeConstraintRow & constraint_row = constraints[my_node].first; 
              constraint_row.emplace(their_node, their_value);
````
 i.e. for each child node `my_node`, we add a constraint according to the parents node `their_node` and the value of the corresponding shape function `their_value`.
Now for infinite elements, we have two sets of nodes: one set at the base (where I can set the `constraints` just as in the `FEAbstract` case because only one radial function is non-zero) and a second set of nodes with twice the distance from the origin. There, however, we have many DOFs ( its number depends on `FEType.radial_order` and thus may vary between different variables) that must be constraint independently.
Is such a scheme even possible? From my limited understanding of these frameworks, this looks hopeless.

I hope that I expressed myself clearly and I am looking forward to get this finally done.
Best regards,
Hubert

**Comment by roystgnr** [comment]
Sorry I lost track of this.  Not sure how much of it has been obsoleted by subsequent edits to #2792.  IMHO you shouldn't worry about node constraints too much; unlike DoF constraints, it's a feature that may have no active users at the moment, and I'm sure it has no active users who are chomping at the bit to mix it with infinite elements.

**Comment by BalticPinguin** [comment]
> IMHO you shouldn't worry about node constraints too much; unlike DoF constraints, it's a feature that may have no active users at the moment, and I'm sure it has no active users who are chomping at the bit to mix it with infinite elements.

Okay, that sounds good.
Probably than it is good to adjust the configure such that not both infinite elements AND node-constraints are enabled.
Otherwise, `reinit()` will fail with infinite elements.

**Comment by BalticPinguin** [comment]
I'll close this; with merging #2792, I'd consider this as resolved.
