### ISSUE TITLE
error: use of deleted function Mesh, ReplicatedMesh 

### ISSUE THREAD

**Issue by FilLTP89** [libMesh/libmesh#2837]
Hello
I'm trying to recompile my code on a new cluster and with the last libmesh version 1.6.0 and I get a couple of errors when compiling, that I don't know how to fix. Here's the code:

 ```
 Mesh_Intersection(  libMesh::ReplicatedMesh & mesh, const libMesh::Mesh & mesh_A,
            const libMesh::Mesh & mesh_B, IntersectionMeshingMethod MeshingMethod = IntersectionMeshingMethod::CGAL,
            int map_preallocation = 1E6, long grid_n_min = static_cast<long>(1E9), bool debugOutput = false) :
    m_comm { mesh.comm() },
    m_nodes { m_comm.size() },
    m_rank { m_comm.rank() },
    m_global_comm { mesh_A.comm() },
    m_global_nodes { m_global_comm.size() },
    m_global_rank { m_global_comm.rank() },
    m_libMesh_Mesh { mesh },
    m_libMesh_PolyhedronMesh { libMesh::Mesh(m_comm) },
    m_TetGenInterface { libMesh::TetGenMeshInterface(m_libMesh_PolyhedronMesh) },
    m_nb_of_intersections { 0 },
    m_eps { -1 },
    m_GridN { std::vector<long >(3,-1) },
    m_dummy_discrete_point { std::vector<long >(3,-1) },
    m_Grid_MinPoint { libMesh::Point(0,0,0) },
    m_Grid_MaxPoint { libMesh::Point(1,1,1) },
    m_GridN_min { grid_n_min },
    m_nb_of_elements { 0 },
    m_nb_of_vertices { 0 },
    m_nb_of_points { 0 },
    m_bMeshFinalized { false },
    m_bPrintDebug { debugOutput },
    m_MeshingMethod { MeshingMethod }
  {
    m_discrete_vertices.reserve(map_preallocation);
    m_intersection_point_indexes.resize(24);

    set_grid_constraints(mesh_A,mesh_B);

    m_libMesh_Mesh.reserve_nodes(map_preallocation);
    m_libMesh_Mesh.reserve_elem(10*map_preallocation);

    m_intersection_pairs.reserve(map_preallocation);
    m_intersection_couplings.reserve(map_preallocation);
    m_intersection_element_range.reserve(map_preallocation);

    m_libMesh_Mesh.allow_renumbering(false);

    switch(m_MeshingMethod)
    {
    case IntersectionMeshingMethod::LIBMESH_TETGEN :
      std::cout << " -> Using TetGen to generate mesh" << std::endl;
      break;
    case IntersectionMeshingMethod::CGAL :
      std::cout << " -> Using CGAL to generate mesh" << std::endl;
      break;
    }
  };
```

the error I get is : 

>  error: use of deleted function 'libMesh::Mesh::Mesh(libMesh::Mesh&&)'
  164 |     m_MeshingMethod { MeshingMethod }

Same for another constructor:

```
Patch_construction(libMesh::Mesh & mesh, const libMesh::Parallel::Communicator& local_comm, bool debugOutput = false) :
    m_comm { mesh.comm() },
    m_nodes { m_comm.size() },
    m_rank { m_comm.rank() },
    m_local_comm {  local_comm },
    m_Mesh_parent { mesh },
    m_Mesh_patch { libMesh::ReplicatedMesh(m_local_comm) },

    m_bPrintDebug { debugOutput }
  {
    m_Parent_Point_Locator = m_Mesh_parent.sub_point_locator();

    //  Instruction needed to avoid the code from crashing if a query is outside the mesh
    m_Parent_Point_Locator->enable_out_of_mesh_mode();

    m_working_element_id = 0;
    m_bTestNeighsForNewPairs = true;

    m_Patch_Elem_indexes.reserve(m_Mesh_parent.n_elem());
    m_Patch_Node_indexes.reserve(m_Mesh_parent.n_nodes());
  };
```

> error: use of deleted function 'libMesh::ReplicatedMesh::ReplicatedMesh(libMesh::ReplicatedMesh&&)'
  150 |   m_bPrintDebug { debugOutput }

Is there a way to fix this in an elegant way?
Thanks!

**Comment by jwpeterson** [comment]
The compiler is correct that the move constructor for ReplicatedMesh is deleted (see, e.g. include/mesh/replicated_mesh.h)
```
  /**
   * Move-constructor - deleted because after a theoretical move-construction
   * and then destruction of the moved-from object, the moved \p BoundaryInfo
   * would hold an invalid reference to the moved-from mesh
   */
  MeshBase(MeshBase &&) = delete;
```
however I don't think the line you quoted:
```
m_MeshingMethod { MeshingMethod }
```
is the problem, instead I think it's probably this line:
```
m_libMesh_Mesh { mesh },
```
my guess is that the type of `m_libMesh_Mesh` is an object rather than a reference. If you really intend to make a full copy of the incoming Mesh, you will need to call the MeshBase `clone()` method instead.

**Comment by FilLTP89** [comment]
Thanks for this answer! `m_libMesh_Mesh` is declared as a reference though:

`libMesh::ReplicatedMesh& m_libMesh_Mesh;`

that is why I am a bit confused. Cloning the mesh entirely would largely impact the performances...
Do you think there's an alternative workaround? Thanks

**Comment by jwpeterson** [comment]
OK, must be the following line then?
```
m_libMesh_PolyhedronMesh { libMesh::Mesh(m_comm) },
```
I don't know the details of `m_libMesh_PolyhedronMesh` class, but maybe this line triggers the call to the move constructor?

**Comment by FilLTP89** [comment]
The `m_libMesh_PolyhedronMesh` is a  `Mesh` containing the _tetrahedrization_ of an intersection polyhedron (the polyhedron mesh). 

```
libMesh::Mesh  m_libMesh_PolyhedronMesh;
```

It triggers the constructor `Mesh` but apparently ([#2732](https://github.com/libMesh/libmesh/pull/2732)) every mesh-related move constructor has been removed :) 

I did not get the alternative use of `unique_ptr` though (I'm still a c++ beginner).

**Comment by jwpeterson** [comment]
OK, in that case your code was indeed previously calling the default MeshBase move constructor. We found that the default (compiler-generated) move constructor was wrong, due to the issue with `BoundaryInfo` that I quoted above, so it was deleted for safety. 

In the present case you are not actually move constructing a Mesh but creating one from scratch, so you would do:
```
m_libMesh_PolyhedronMesh { m_comm },
```
instead.

**Comment by FilLTP89** [comment]
Yeah that worked! although a little collateral effect occurred: when calling another move constructor `Intersection_Search`, containing `Patch_construction`, the compiler throw error:

> error: use of deleted function 'carl::Patch_construction::Patch_construction(carl::Patch_construction&&)'

> note: 'carl::Patch_construction::Patch_construction(carl::Patch_construction&&)' is implicitly deleted because the default definition would be ill-formed:
   42 | class Patch_construction
      |       ^~~~~~~~~~~~~~~~~~

Below the code to define the `Intersection_Search` constructor:
```
Intersection_Search(libMesh::Mesh & mesh_A,
            libMesh::Mesh & mesh_B,
            libMesh::Mesh & mesh_Coupling,
            libMesh::Mesh & mesh_I,
            const std::string & output_base = std::string("test"),
            IntersectionMeshingMethod MeshingMethod = IntersectionMeshingMethod::CGAL,
            double Min_Inter_Volume = 1E-15,
            bool  bDoPerf_log = true,
            bool  bDebugOutput = false) :
    m_Mesh_A { mesh_A },
    m_Mesh_B { mesh_B },
    m_Mesh_Coupling { mesh_Coupling },
    m_comm { m_Mesh_Coupling.comm() },
    m_nodes { m_comm.size() },
    m_rank { m_comm.rank() },
    m_local_comm { mesh_I.comm() },
    m_Patch_Constructor_A { Patch_construction(m_Mesh_A,m_local_comm)},
    m_Patch_Constructor_B { Patch_construction(m_Mesh_B,m_local_comm)},
    m_MeshingMethod { MeshingMethod },
    m_Mesh_Intersection { Mesh_Intersection(mesh_I,m_Mesh_A,m_Mesh_B,m_MeshingMethod)},
    m_bSaveInterData { true },
    m_bDidPreliminarySearch { false },
    m_bHavePreallocData { false },
    m_bIntersectionsBuilt { false },
    m_Min_Inter_Volume { Min_Inter_Volume },
    m_bSkipIntersectionConstruction { false },
    m_bSkipIntersectionPartitioning { false },
    m_Output_filename_base { output_base + "_r_" + std::to_string(m_rank) + "_n_" + std::to_string(m_nodes)},
    MASTER_bPerfLog_intersection_search {bDoPerf_log},
    m_perf_log { libMesh::PerfLog("Intersection search", MASTER_bPerfLog_intersection_search) },
    m_bPrintDebug { bDebugOutput },
    m_bPrintTimingData { false },
    m_bPrintIntersectionsPerPartData { false }
  {
    // Reserve space for the intersection multimap
    m_Nb_Of_Intersections_Elem_C.resize(mesh_Coupling.n_elem(),0);
  };
```

Thanks!

**Comment by jwpeterson** [comment]
Presumably it refers to these two lines:
```
m_Patch_Constructor_A { Patch_construction(m_Mesh_A,m_local_comm)},
m_Patch_Constructor_B { Patch_construction(m_Mesh_B,m_local_comm)},
```
Your code seems to be constructing objects in place and then calling the move constructor rather than just passing the needed args to the constructor. So the fix is the same thing as before:
```
m_Patch_Constructor_A {m_Mesh_A, m_local_comm},
m_Patch_Constructor_B {m_Mesh_B, m_local_comm},
```
