### ISSUE TITLE
Experimental warning for all MeshBase users

### ISSUE THREAD

**Issue by jwpeterson** [libMesh/libmesh#2841]
We seem to have picked up a warning recently:
```
*** Warning, This code is untested, experimental, or likely to see future API changes: ./include/libmesh/mesh_base.h, line 1667, compiled Jan 15 2021 at 09:23:22 ***
```
In my version of libmesh, that line corresponds to this:
```
  const constraint_rows_type & get_constraint_rows() const
  { libmesh_experimental(); return _constraint_rows; }
```
but I don't explicitly call this anywhere in my code... so is it really experimental if I can't avoid it easily?

@roystgnr

**Comment by roystgnr** [comment]
*Use* of these is still experimental ... but now that we're doing automatic application of them in the library, "use" really needs to be interpreted as "the library found that container to be non-empty", not "the library checked whether that container was non-empty".  I'll fix it.
