### ISSUE TITLE
Fixes worth backporting for a 1.6.1 release?

### ISSUE THREAD

**Issue by roystgnr** [libMesh/libmesh#2854]
@jwpeterson is cherry-picking the bugfix in our Eigen interface from #2851, and wondering whether we should have a 1.6.1 release soon.  Looking over our PRs I see that there are quite a few other good candidates for backporting, probably enough to justify the update.

#2760
#2782 
#2790 
#2804 
#2807 
~~#2810 (I think; I'm testing to make sure this bug was introduced pre-1.6.0-branch)~~
#2814 
#2816 
#2821 
#2828 
#2849 (maybe with the libmesh_deprecated() line removed?)

**Comment by roystgnr** [comment]
#2810 seems to be irrelevant; I can do a --disable-metaphysicl build with 1.6.0 just fine.  I'll double-check before we tag a 1.6.1 in case any of the other fixes we backport was the one that introduced that bug.

**Comment by jwpeterson** [comment]
OK, I agree with all these suggestions so I'll just backport them all and let you know when it's done.

**Comment by jwpeterson** [comment]
OK @roystgnr I cherry-picked the commits listed above for the various PRs onto branch_v1.6.1. The only one that didn't work was #2782. I think there were other InfFE changes on master that went in before those fixes, so they don't apply cleanly on the 1.6.1 branch. It's up to you if you want to mess with that further, I'm OK with not including them.

**Comment by roystgnr** [comment]
Yeah, we can leave those out; looks like one was just to turn off warnings in a unit test and the other was a fix for an atavism in post-1.6.0-branch InfFE code.  Looks like we're good to put out a 1.6.1 after the branch is tested.

**Comment by jwpeterson** [comment]
> after the branch is tested.

OK, well we have the `make distcheck` testing that runs after I push the tag/make the release, but we could also do some independent testing prior to that if you want. I don't really expect to run into any issues, but doing some extra testing would also avoid us having to immediately tag a 1.6.2 in case anything unexpected comes up.

**Comment by roystgnr** [comment]
Can we just request Civet tests of a branch, the way we can request extra tests of a PR?  That'd actually be useful pretty often, for more than just releases - too often I upload an incomplete PR and have to tag it Do Not Merge just because that's the only way I know of to get CI to double-check the work in progress.

**Comment by jwpeterson** [comment]
AFAIK CIVET always needs a PR to be opened (or a release to be created) to trigger the testing, since those events are what trigger the payloads to be sent. For us that PR is usually into master, but I could imagine making a "dummy" branch which is basically the last commit before 1.6.x diverged, and then making a PR into that branch to trigger testing (but never actually merging). That sounds a little convoluted though, so maybe there's a simpler approach.

**Comment by roystgnr** [comment]
> That sounds a little convoluted though, so maybe there's a simpler approach.

I tried making a new branch from v1.6.0 itself, so the PR only has the last couple dozen commits, rather than the dozens of rc1/rc2/rc3 commits which preceded that tag.  But other than that, yeah, you had the right idea.

https://github.com/libMesh/libmesh/pull/2857

**Comment by jwpeterson** [comment]
Release 1.6.1 is [available now](https://github.com/libMesh/libmesh/releases/tag/v1.6.1).
