### ISSUE TITLE
Prism18-mesh with exodus-2

### ISSUE THREAD

**Issue by BalticPinguin** [libMesh/libmesh#2882]
Dear all,
I need some help for further analyzing a problem I just encountered:
I generate and write a mesh with
```  
  MeshTools::Generation::build_cube (mesh, /*nx= */5, /*ny=*/5, /*nz=*/3,
                                        /*xmin=*/ -5, /*xmax=*/5,
                                        /*ymin=*/ -5, /*ymax=*/5,
                                        /*zmin=*/ -3, /*zmax=*/3,
                                        PRISM18 /* this works*/           //PRISM18 /*THIS FAILS! */
                                    );

  ExodusII_IO(mesh).write ("finite_cube.e");
```
but when I open the `finite_cube.e` with ParaView, it looks quite odd: First, only one element in z-direction is present but also some elements overlap and some (e.g. element with id= 2) have weird shapes.

Unfortunately, I don't know how to further analyze the issue to see, e.g., if it is a problem with printing the file or if it is on ParaViews side!?
When using `PRISM15`, everything looks good. Also, according to `mesh.print_info()`, the generated mesh itself looks fine: It has the correct number of nodes and elements.
Has someone some experience with tools to analyze exodus-2 files or can give some other useful hints?
Many thanks in advance,
Hubert

**Comment by roystgnr** [comment]
Could you loop over the mesh and check whether each element is affine?  If the answer is yes then the problem has to be on our end or Paraview's; if no then we're doing something wrong in mesh generation.

**Comment by BalticPinguin** [comment]
>  check whether each element is affine? 

You mean to check for `elem->has_affine_map()`? yes, they are all affine. Also, if I generate the `PRISM18`-mesh and than convert all elements to first order, I get the same output as for `PRISM6`.

**Comment by roystgnr** [comment]
```has_affine_map()```, right.  Converting to first order could simply hide a bug, but unless we have an exactly-canceling-it-out bug in ```has_affine_map()```, that should have caught any problems in mesh generation.

Perhaps our libmesh-to-exodus node numbering conversion is broken for PRISM18?  Looking at exodusII_io_helper.C I don't actually see any node map; we seem to believe that their WEDGE18 numbering should match our PRISM18 numbering exactly.  Which ... maybe?

**Comment by BalticPinguin** [comment]
yes, that indeed is a very good hint.
It seems [this](https://gsjaardema.github.io/seacas-docs/html/element_types.html#wedge) is the official documentation where unfortunately the wedge18 is missing.
I will keep searching and update this if I know more.

**Comment by roystgnr** [comment]
Their HEX27 differs from ours, and our PRISM18 is constructed in an analogous fashion to our HEX27, so I wouldn't be surprised if their WEDGE18 differs in an analogous fashion.  I'm very surprised nobody caught it before now, though.

**Comment by jwpeterson** [comment]
It looks like we previously only ever employed an identity node mapping for the `PRISM18`. See for example, b6f96245fee, which was the commit where I updated things so that we did not need to store identity node mappings. That could have either always been wrong, or changed at some point in Exodus or even Paraview. I can try and take a look soon.

**Comment by BalticPinguin** [comment]
Finally, I found that at least the node-to-side map is correct: Having the wedge18 missing in what looks like the [official documentation](https://gsjaardema.github.io/seacas-docs/html/element_types.html#wedge), I found the map [in the source](https://gsjaardema.github.io/seacas-docs/html/element_types.html#wedge)...

**Comment by BalticPinguin** [comment]
update: 
   1. visit has a debug-mode which showed `For element type attribute text "WEDGE18" and num_nodes = 18, got vtk_celltype = -1` ; so it seems to be just not implemented there.
   2.  In Paraview I tried some things: One can reduce the problem further by setting `mesh, /*nx= */1, /*ny=*/1, /*nz=*/1,`; which results in a 2-element mesh.
   Having much simpler analysis, it becomes apparent that it is represented as two Prism6-elements where the first looks good, but the second seems to have the nodes 6-12 and a respectively strange shape.
   
   From this, I'd conclude that it is all fine from libMeshs side...

**Comment by roystgnr** [comment]
Thanks for looking into it!  I'm not as sanguine that we aren't doing anything wrong in our numbering, but in the absence of documentation to the contrary we'd just be blindly guessing if we tried to sync up with Paraview ...

**Comment by roystgnr** [comment]
Should we close this issue, until/unless we ever find some documentation to the contrary?

**Comment by jwpeterson** [comment]
@BalticPinguin, I took a look at the Exodus source code that you linked and compared it to our Prism18 numbering: 

Exodus:
```
/* wedge 18 */
  static int wedge18_table[5][9] = {
      {1, 2, 5, 4, 7, 11, 13, 10, 16}, /* Side 1 nodes -- quad     */
      {2, 3, 6, 5, 8, 12, 14, 11, 17}, /* Side 2 nodes -- quad     */
      {1, 4, 6, 3, 10, 15, 12, 9, 18}, /* Side 3 nodes -- quad     */
      {1, 3, 2, 9, 8, 7, 0, 0, 0},     /* Side 4 nodes -- triangle */
      {4, 5, 6, 13, 14, 15, 0, 0, 0}   /* Side 5 nodes -- triangle */
  };
```

libMesh:
```
const unsigned int Prism18::side_nodes_map[Prism18::num_sides][Prism18::nodes_per_side] =
  {
    {0, 2, 1,  8,  7,  6, 99, 99, 99}, // Side 0 (triangle)
    {0, 1, 4,  3,  6, 10, 12,  9, 15}, // Side 1
    {1, 2, 5,  4,  7, 11, 13, 10, 16}, // Side 2
    {2, 0, 3,  5,  8,  9, 14, 11, 17}, // Side 3
    {3, 4, 5, 12, 13, 14, 99, 99, 99}  // Side 4 (triangle)
  };
```

From which I was able to make the following table of equivalent numberings:

| libmesh side (0-based) | Exodus side (1-based) |
| ---------------------- | --------------------------- |
| 0                      | 4                     |
| 1                      | 1                     |
| 2                      | 2                     |
| 3                      | ???                   |
| 4                      | 5                     |

It seems to me that libmesh side 3 (0-based) should correspond to Exodus side 3 (1-based) numbering, but it does not? Maybe I am missing something, but I don't see how just one side could have a different numbering... I need to draw a picture and check.

**Comment by BalticPinguin** [comment]
oh, yes; I came across this as well today: They have rotated the side 3 for some reason! So if you draw it, you see that you get the 'correct' side-element, but looking at the graph [of libmeshs prism](http://libmesh.github.io/doxygen/classlibMesh_1_1Prism18.html), that side is rotated clock-wise.

But since this is the same for Prism15 (Wedge15), I don't think that this should cause these problems.

**Comment by jwpeterson** [comment]
OK, yes I agree, they numbered that one face with the opposite orientation, but the node ids otherwise make sense. (The libmesh faces are numbered so that, when viewed from "outside" the element, they all have a counter-clockwise orientation.) This is a little bit annoying since it makes things harder to check, but I guess it would not cause the issues you're seeing in Paraview. Especially if the same thing is done for Prism15 and those work fine...

**Comment by jwpeterson** [comment]
@BalticPinguin I tried a test in which I read in out a single Prism18 element from:

$LIBMESH_DIR/share/reference_elements/3D/one_prism18.xda

and wrote out an Exodus file. I then opened that Exodus file in Paraview and used the "Select Points Through" tool. As you can see in the screenshot, it looks almost correct. For example, the element is correctly identified as a WEDGE18, and it does not appear twisted. But note that only six vertices are being shown... none of the mid-edge/mid-face vertices show up in pink.

![prism18](https://user-images.githubusercontent.com/1775907/112210676-fb511280-8be8-11eb-9db9-f601ab368f67.png)

I suspect that this is because Paraview is not correctly using/displaying the higher-order nodes... it may even be only looking at the first 6 nodes in the list, and then once you add a second element, the numbering is all off.

**Comment by BalticPinguin** [comment]
yes, this is in very good agreement with my observation and interpretation.

Than I'll follow @roystgnr suggestion and close this for now.

Thanks to both of you for the ideas and support to go through this...

**Comment by jwpeterson** [comment]
I wonder if we can open an issue for the VTK/Paraview devs regarding this. @acbauer for example might be interested?

**Comment by jwpeterson** [comment]
For what it's worth, I see the same exact behavior for pyramids: both Pyramid5 and Pyramid13 (Quad8 base) seem to both work fine in Paraview, but Pyramid14 (Quad9 base) does the same thing as Prism18, where only the vertex nodes are recognized.

The Exodus source code shows an 18-node pyramid Interestingly, 
```
/* pyramid */
  static int pyramid_table[5][9] = {
      {1, 2, 5, 0, 6, 11, 10, 0, 15}, /* side 1 (tri) */
      {2, 3, 5, 0, 7, 12, 11, 0, 16}, /* side 2 (tri) */
      {3, 4, 5, 0, 8, 13, 12, 0, 17}, /* side 3 (tri) */
      {1, 5, 4, 0, 10, 13, 9, 0, 18}, /* side 4 (tri) */
      {1, 4, 3, 2, 9, 8, 7, 6, 14}    /* side 5 (quad) */
  };
```
which according to the docs:
```
/*
 * node count:  5 -- 4-node quad, 3-node tri
 *             13    8            6
 *             14    9            6
 *             18    9            7
 *             19    9            7  + volume center node.
 */
```
looks like it would support both our Pyramid13 and Pyramid14 with an identity node mapping, but doesn't work in Paraview.

**Comment by acbauer** [comment]
Any chance you could share the file here? I'd be happy to take a look at it in ParaView to try and see what's going on.

**Comment by jwpeterson** [comment]
> Any chance you could share the file here?

Sure, thanks!

[Prism6 (working)](https://drive.google.com/file/d/1sVeDURomhGREIVfbiQ2JtBy29uxbwqgG/view?usp=sharing)
[Prism15 (working)](https://drive.google.com/file/d/1qve47WDo9y4nIrRPEcktU5O6UxL4xxG2/view?usp=sharing)
[Prism18 (not working)](https://drive.google.com/file/d/1jxb_7UWGfVAyo-H3Np2p11XNvc3GE8LW/view?usp=sharing)

These are just Exodus files with a single element in them. They all open OK for me in Paraview but only the first two actually display all the nodes correctly, the last one only displays the vertex nodes, as discussed in the ticket. I assume it will be simplest to debug if you work with the files that have a single element, but I can also create files with more elements as necessary.

**Comment by acbauer** [comment]
It's getting read in as a 6-noded wedge. 
![6nodedcell](https://user-images.githubusercontent.com/2197741/112224336-8ccc7e80-8c01-11eb-98a2-627a9cc4640b.png)

I looked at the contents briefly with `ncdump` and it seems to be correct upon inspection (I'm not an ExodusII expert).

Is it okay to use this file in the VTK/ParaView public testing database? It's a standard question since it's your data and we don't make any assumptions about what can be done with it.

**Comment by jwpeterson** [comment]
> but certainly shouldn't be down-sampled to a 6 node wedge

OK. Note also that when there are 2 or more Prism18s in the mesh, there is some kind of indexing bug where the second Prism18 is using some nodes of the first one. In the screenshot below, the domain should be a cube split into two Prism18s, but as you can see from the edges, the elements are instead overlapped/twisted up.  

![two_prism18](https://user-images.githubusercontent.com/1775907/112318340-f0df5900-8c7a-11eb-9178-3821a97871a7.png)

[Two Prism18s](https://drive.google.com/file/d/1Y6VvlifSDycQenpecVOzKl5rZqszw4CM/view?usp=sharing)

> Is it okay to use this file in the VTK/ParaView public testing database? 

Sure, it's fine to use any of these files for any purpose.

**Comment by jwpeterson** [comment]
Regarding this:

>  I don't know by memory if there is an 18 node wedge in VTK 

The VTK writer in libmesh makes the following associations:
```
PRISM6 -> VTK_WEDGE
PRISM15 -> VTK_QUADRATIC_WEDGE
PRISM18 -> VTK_BIQUADRATIC_QUADRATIC_WEDGE
```
so, I think there is at least some support for this element type on the VTK side.

**Comment by acbauer** [comment]
As a side note, VTK and ParaView has had significant improvements for HO cells in recent years. Try using the `Unstructured Cell Types` source to check them all out. From there it looks like the 2nd order Lagrange Wedge is also a good fit (shown in the image below as well). Note that if you want to see the cell curvature you'll need to bump up the `Nonlinear Subdivision Level` if you haven't seen that option yet. I'll put in a bug report to get the ExodusII reader fixed.
![curvature](https://user-images.githubusercontent.com/2197741/112323221-f5f6d500-8c87-11eb-852e-c20b46982897.png)

**Comment by jwpeterson** [comment]
Thanks @acbauer, I did not know about the Nonlinear Subdivision Level option, that is really cool!

**Comment by roystgnr** [comment]
No kidding!  I've always either manually subdivided elements before output (when I really need to make an image for a presentation or paper, 1% of the time) or just put up with poorly-linearized output (when I'm feeling lazy, 99% of the time).  Doing that on the fly by just changing a slider is nice!

**Comment by acbauer** [comment]
Visualization tools are supposed to make your lives easier by doing what you want, not make you do hacky workarounds :)

I just wish I saw some path forward for HO cells for DG methods in VTK. Unfortunately it seems like we're stuck with one tuple per cell quantity or cells that just don't connect properly.

**Comment by acbauer** [comment]
Reported the issue here -- https://gitlab.kitware.com/vtk/vtk/-/issues/18160

**Comment by acbauer** [comment]
I *think* this is fixed in ParaView master now which means it will make it into the ParaView v5.10 release that will be out in the fall of 2021. If you're in a rush to try this out you can get the nightly ParaView installers at https://www.paraview.org/download/ (just change version to Nightly). Please let me know if you don't think this is working properly and we can revisit.
![one_prism18](https://user-images.githubusercontent.com/2197741/128248155-6d46ed6e-7f4b-4696-845f-3bbf30b45855.png)
![two_prism18](https://user-images.githubusercontent.com/2197741/128248171-66621a65-b9d5-4a6c-9454-682a530fe1e5.png)

Also, there are discussions with investigating HO cell data for DG methods in VTK and ParaView. It's very preliminary but a possibility that it could be supported.

**Comment by jwpeterson** [comment]
Awesome @acbauer thanks for following up on this! Everything looks good to me from your screenshots, the only thing I might want to check is whether a nodal variable is also displayed correctly on this element. I'll let you know if I have a chance to try out a nightly Paraview.
