### ISSUE TITLE
Request for deletion of extraneous write statements

### ISSUE THREAD

**Issue by ajamar1** [libMesh/libmesh#2913]
Hello Developers,

(hopefully this is the correct way to convey this request)

Thanks for all the continual development on this great library.  I had one (hopefully simple) request. In radial_basis_interplation.C in RadialBasisInterpolation::prepare_for_use(), there are libMesh::out statements that I need to delete every time I get a new revision of libMesh so that my terminal is not flooded.  Any way those could be removed on future releases?  I assume Ben? put these lines in during development and debugging, and I may be the only one using this function at this point.

The specific snippets are:

libMesh::out << "bounding box is \n"
               << _src_bbox.min() << '\n'
               << _src_bbox.max() << std::endl;

and 

libMesh::out << "bounding box is \n"
               << _src_bbox.min() << '\n'
               << _src_bbox.max() << '\n'
               << "r_bbox = " << _r_bbox << '\n'
               << "rbf(r_bbox/2) = " << rbf(_r_bbox/2) << std::endl;

on lines 88 and 101 of the v1.6.1 version of the file.

**Comment by roystgnr** [comment]
Yeah, that's been there since Ben's first commit of the class in 2013.  I even recall looking at them shortly thereafter, but they didn't seem to be in an inner loop so I guess it didn't bother me that they weren't in an `if (verbose)` sort of test either.  I'll clean it up.

**Comment by roystgnr** [comment]
Should I get rid of the `libmesh_experimental();` in the constructor while I'm at it?  If you've been using this 8-year-old class regularly then I'd say the experiment has succeeded.  :-D

**Comment by ajamar1** [comment]
Great question.  I’d say I have been using it regularly for about 6 months now, but its now a mainstay in CHAR.  I propose leaving it as experimental for now.  After a year or so when our users more broadly use the associated features and get sufficiently annoyed, then I’ll say its passed the experiment.  So I’ll get back to you in a year or so.

….and thanks for the help cleaning out those write statements.

From: roystgnr ***@***.***>
Reply-To: libMesh/libmesh ***@***.***>
Date: Thursday, April 29, 2021 at 7:43 AM
To: libMesh/libmesh ***@***.***>
Cc: "Amar, Adam J. (JSC-EG311)" ***@***.***>, Author ***@***.***>
Subject: [EXTERNAL] Re: [libMesh/libmesh] Request for deletion of extraneous write statements (#2913)


Should I get rid of the libmesh_experimental(); in the constructor while I'm at it? If you've been using this 8-year-old class regularly then I'd say the experiment has succeeded. :-D
