### ISSUE TITLE
Issue with z-displacement value in systems_of_equations_ex8

### ISSUE THREAD

**Issue by jwpeterson** [libMesh/libmesh#3000]
In this example, we set the z-displacement to -1 in the code:
```
  {
    std::set<boundary_id_type> clamped_boundaries;
    clamped_boundaries.insert(MAX_Z_BOUNDARY);

    std::vector<unsigned int> w;
    w.push_back(w_var);

    ConstFunction<Number> neg_one(-1.);

    system.get_dof_map().add_dirichlet_boundary
      (DirichletBoundary (clamped_boundaries, w, neg_one,
                          LOCAL_VARIABLE_ORDER));
  }
```
but it seems to be clamped to zero in the output:
![sys_ex8](https://user-images.githubusercontent.com/1775907/131514327-f1ab51eb-ec13-48d5-9484-5b35e363e90b.png)

**Comment by jwpeterson** [comment]
Apparently @dknez replied on the mailing list, but I didn't see it.

> Yes, you're right, there is a bug. We need to add:
> system.get_dof_map().enforce_constraints_exactly(system);
> 
> before:
> 
> libMesh::out << "Computing stresses..." << std::endl;
> 
> This imposes the non-zero Dirichlet constraints on the solution, which is what you need to do for plotting purposes. Note that this has no effect on the solve itself, it's just required for correct visualization.
> 
> I think we also need to add:
> system.update();
> 
> in the same place as well so that we also update system.current_local_solution, since that is what is used in the stress calculation. I tried that but the stress still seems a bit strange on the boundary, so not sure what is causing that. But anyway, my suggestion would be to update this example to have two new lines:
> 
> system.get_dof_map().enforce_constraints_exactly(system);
> system.update();
>

**Comment by rebpoli** [comment]
Thanks!
