### ISSUE TITLE
Xdr class: use of version_number

### ISSUE THREAD

**Issue by BalticPinguin** [libMesh/libmesh#3070]
I am currently stuck with proper reading of checkpoint-files. In particular, I'd say there is some error related to the `read_header` function:

The `Xdr` class has a member `version_number` which, as far as I can see, it is not in use except for the functions `set_version()` and `version` use it. Even  the [constructor](https://github.com/libMesh/libmesh/blob/2ddb0695b44f38f6936caab387be4b1666f069fd/src/utils/xdr_cxx.C#L100) doesn't initialize it.

Now, when reading  the `domain`, there is [this line](https://github.com/libMesh/libmesh/blob/2ddb0695b44f38f6936caab387be4b1666f069fd/src/systems/system_io.C#L186)
````
  if (io.version() >= LIBMESH_VERSION_ID(0,7,2))
````
which compares in my case to `-32336` (or other numbers, indicating that it indeed is not initialized).

Thus, my question is if I have some misconception related to this or just misuse this function when I call it from user-code?
(I have one function that handles read/write of the mesh and a separate function that read/writes systems. The latter reads/writes a header file with `system.read_header()` and than `system.read_parallel_data`.)

Otherwise, I'd expected that `version` should probably be initialized to the current `LIBMESH_VERSION_ID`? 

Best regards

**Comment by jwpeterson** [comment]
Hi @BalticPinguin I agree the missing initialization of `version_number` looks like a definite bug. It looks like we do indeed call:
```
    io.set_version(LIBMESH_VERSION_ID(LIBMESH_MAJOR_VERSION,
                                      LIBMESH_MINOR_VERSION,
                                      LIBMESH_MICRO_VERSION));
```
elsewhere (see e.g. equation_systems_io.C) which is based on defines set in libmesh_config.h, so it seems reasonable that we would do the same in the Xdr class constructor... I will put up a PR which does this and see if anything breaks.

**Comment by BalticPinguin** [comment]
Thank you @jwpeterson : #3077 fixed it.
