### ISSUE TITLE
libMesh 0.9.4 soon?

### ISSUE THREAD

**Issue by roystgnr** [libMesh/libmesh#308]
I'd like to tag a release after the nonlocal_stuff is merged and after that libHilbert regression is sorted out.  Anyone else have issues to fix or improvements to add before we make a new release?  Any votes for 0.9.4 over 1.0.0?

**Comment by jwpeterson** [comment]
0.9.4-rc2 has now been tagged on the 0.9.4 branch and a new release was created for it.

There are still a couple of possible outstanding bugs in this RC that @roystgnr is aware of (at least one of which he can't reproduce at the moment) but we'd like to set a definite date of *March 15, 2015* for the final 0.9.4 release (if not sooner).  The 0.9.4 branch is also frozen as far as new features are concerned, but any hotfixes that can be easily cherry-picked over are still allowed.

**Comment by roystgnr** [comment]
Released last month; thanks @jwpeterson for the help.
