### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by luchinsky** [libMesh/libmesh#3088]
Could you please help with the following issue?
I have the following installation error (the folder '/mnt/d/projects/moose/libmesh/build/contrib/netcdf/v4' ideed does not have Makefile):

make[2]: Leaving directory '/mnt/d/projects/moose/libmesh/build/contrib/gzstream'
Making all in netcdf/v4
make[2]: Entering directory '/mnt/d/projects/moose/libmesh/build/contrib/netcdf/v4'
make[2]: *** No rule to make target 'all'.  Stop.
make[2]: Leaving directory '/mnt/d/projects/moose/libmesh/build/contrib/netcdf/v4'
make[1]: *** [Makefile:1020: all-recursive] Error 1
make[1]: Leaving directory '/mnt/d/projects/moose/libmesh/build/contrib'
make: *** [Makefile:32531: all-recursive] Error 1

**Comment by jwpeterson** [comment]
Hmm... I think we'd need a lot more info to be able to figure out what's going on here. My guess is that something went wrong during configure that caused netcdf to not be configured, but then the Makefiles still tried to build it? Can you maybe attach your config.log file to this Issue so that we can take a closer look?

**Comment by luchinsky** [comment]
Hi John,
Thank you very much for your comments. I am trying to install moose on WSL2 in Windows 10.The moose installation went as usual. But libmesh folder was empty. Then I have found new instructions on moose guthub (I am coming back to moose after a couple of years break).So I followed the instructions. The configure went well without errors as far as I could see and all the folders were seemingly generated.  But make did not work for the reason that I have mentioned.
The config.log file is attached.
Looking forward to hearing from you.
Best regards,Dmitry 

    On Monday, November 15, 2021, 08:52:42 AM PST, John W. Peterson ***@***.***> wrote:  
 
 


Hmm... I think we'd need a lot more info to be able to figure out what's going on here. My guess is that something went wrong during configure that caused netcdf to not be configured, but then the Makefiles still tried to build it? Can you maybe attach your config.log file to this Issue so that we can take a closer look?

**Comment by roystgnr** [comment]
I don't think Github posts email attachments; in any case I can't see the config.log here.

**Comment by luchinsky** [comment]
Hi,
It looks like it did not configure properly last time, see the last lines of the config.log below. I tried to reconfigure and got an error that m4 was not installed. I installed m4 in WSL2 ubuntu.It did configure properly and asked to run make and make install. I apologize for the false alarm. Although the make (with -j) takes forever already a few hours on WSL2).
I did try to repeat installation on ubuntu 18.04 and there was an error related to "boost/system/read_code.hpp"I am currently installing it on ubuntu 20.04.

Thank you! Dmitry

    On Monday, November 15, 2021, 02:35:19 PM PST, roystgnr ***@***.***> wrote:  
 
 


I don't think Github posts email attachments; in any case I can't see the config.log here.

—
You are receiving this because you authored the thread.

Reply to this email directly, view it on GitHub, or unsubscribe.
++++++++++++++++++++  CONFIG.log ++++++++++++++++++++++

program_transform_name='s,x,x,'psdir='${docdir}'sbindir='${exec_prefix}/sbin'sharedstatedir='${prefix}/com'subdirs=' contrib/netcdf/v4 contrib/timpi'subdirs_extra=' contrib/metaphysicl'sysconfdir='${prefix}/etc'target='x86_64-pc-linux-gnu'target_alias=''target_cpu='x86_64'target_os='linux-gnu'target_vendor='pc'vtkbuild=''vtkmajor=''vtkversion=''
configure: exit 1

**Comment by roystgnr** [comment]
Thanks for the update!  I'm not sure we have anyone using libMesh via WSL2; I'd have hoped that the underlying Ubuntu system makes it relatively painless, but if that's not the case then I'd definitely want to fix that ASAP.

> Although the make (with -j) takes forever already a few hours on WSL2).

Are you giving a number of cores as an argument to `-j`?  If you just use -j without an argument IIRC `make` will try to compile every single file at once, and it can be a mess: contention for I/O, processes fighting for swap space, potentially much slower than a carefully-sized parallel make.

> I am currently installing it on ubuntu 20.04.

I'll close this issue then; feel free to reopen if you run into any other installation problems.
