### ISSUE TITLE
moose/test will not compile after libmesh installation Ubuntu 20.04

### ISSUE THREAD

**Issue by luchinsky** [libMesh/libmesh#3089]
I could install libmesh following instructions on this site (the log file is attached). However, I cannot compile tests following moose installation instructions (see below error):
cd ~/projects/moose/test
make -j 4

Please notice that on November the 1-st I was able easily to install MOOSE as usual and now I am struggling for two days with installation. I would really appreciate your help.  

Could it be that now I should use a different folder for tests? E.g. "make check" in libmesh/build does work.

Make is searching for missing files in the folder that does not exist, e.g. 
/bin/sh: 1: /home/dmitry/projects/moose/libmesh/installed/contrib/bin/libmesh-config: not found
There is folder 
/home/dmitry/projects/moose/libmesh/install/contrib/bin/
but it does not contain file
libtool

[config.log](https://github.com/libMesh/libmesh/files/7543876/config.log)

error in trying to make test
~/projects/moose/test$ make -j 8
/bin/sh: 1: /home/dmitry/projects/moose/libmesh/installed/contrib/bin/libmesh-config: not found
/bin/sh: 1: /home/dmitry/projects/moose/libmesh/installed/contrib/bin/libmesh-config: not found
/bin/sh: 1: /home/dmitry/projects/moose/libmesh/installed/contrib/bin/libmesh-config: not found
/bin/sh: 1: /home/dmitry/projects/moose/libmesh/installed/contrib/bin/libmesh-config: not found
/bin/sh: 1: /home/dmitry/projects/moose/libmesh/installed/contrib/bin/libmesh-config: not found
/bin/sh: 1: /home/dmitry/projects/moose/libmesh/installed/contrib/bin/libmesh-config: not found
/bin/sh: 1: /home/dmitry/projects/moose/libmesh/installed/contrib/bin/libmesh-config: not found
/bin/sh: 1: /home/dmitry/projects/moose/libmesh/installed/contrib/bin/libmesh-config: not found
/bin/sh: 1: /home/dmitry/projects/moose/libmesh/installed/contrib/bin/libmesh-config: not found
/bin/sh: 1: /home/dmitry/projects/moose/libmesh/installed/libtool: not found
/bin/sh: 1: /home/dmitry/projects/moose/libmesh/installed/libtool: not found
/bin/sh: 1: /home/dmitry/projects/moose/libmesh/installed/contrib/bin/libmesh-config: not found
/bin/sh: 1: /home/dmitry/projects/moose/libmesh/installed/contrib/bin/libmesh-config: not found
/bin/sh: 1: /home/dmitry/projects/moose/libmesh/installed/contrib/bin/libmesh-config: not found
Using HIT from /home/dmitry/projects/moose/framework/contrib/hit
make: python-config: Command not found
make: python-config: Command not found
/bin/sh: 1: /home/dmitry/projects/moose/libmesh/installed/contrib/bin/libmesh-config: not found
Compiling C++ (in opt mode) /home/dmitry/projects/moose/framework/build/unity_src/src_Unity.C...
/bin/sh: 1: /home/dmitry/projects/moose/libmesh/installed/libtool: not found
/bin/sh: 1: /home/dmitry/projects/moose/libmesh/installed/contrib/bin/libmesh-config: not found
make: *** [/home/dmitry/projects/moose/framework/build.mk:145: /home/dmitry/projects/moose/framework/build/unity_src/src_Unity..opt.lo] Error 127

**Comment by roystgnr** [comment]
If you're trying to install libMesh from the Moose submodule, did you use the Moose script to do so?  I got the impression from your previous issue that you were doing it manually.  Either way, you must not have finished `make install` if there's nothing in the install directory.  The relevant error is whatever led to that, not the later error when Moose can't find anything.

**Comment by luchinsky** [comment]
Hi,This time it was native Ubuntu 20.04 (the installation on WSL2 did not work but I made a mistake and will repeat installation on WSL2 latter)
On the native Ubuntu 20.04
   13  curl -L -O https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh   14  bash Miniconda3-latest-Linux-x86_64.sh -b -p ~/miniconda3   15  export PATH=$HOME/miniconda3/bin:$PATH   16  conda config --add channels conda-forge   17  conda config --add channels https://conda.software.inl.gov/public   18  conda install mamba   22  conda init bash   68  conda create --name moose -q -y   69  conda activate moose   70  conda install mamba
Then I was following MOOSE installationmamba install moose-toolsmamba install moose-libmeshmkdir ~/projectscd ~/projectsgit clone https://github.com/idaholab/moose.gitcd moosegit checkout master
then I was following libmesh installation from githubcd /moose/libmesh the folder is empty at this stage then    77  git submodule update --init --recursive   78  mkdir build   79  cd build   80  ../configure --prefix=/home/dmitry/projects/moose/libmesh/install
the folder is populated at this stage and instructions to run "make" and "make install" are printed. So I    81  make -j 12   82  make install
Is this is correct?
I will repeat from the scratch and let you know the outcome.

Best regards,Dmitry

    On Tuesday, November 16, 2021, 07:28:28 AM PST, roystgnr ***@***.***> wrote:  
 
 


If you're trying to install libMesh from the Moose submodule, did you use the Moose script to do so? I got the impression from your previous issue that you were doing it manually. Either way, you must not have finished make install if there's nothing in the install directory. The relevant error is whatever led to that, not the later error when Moose can't find anything.

**Comment by luchinsky** [comment]
Hi,
I was trying to repeat the whole installation from the scratch.
  169  bash Miniconda3-latest-Linux-x86_64.sh -b -p ~/miniconda3  170  export PATH=$HOME/miniconda3/bin:$PATH  171  conda create --name moose -q -y  172  conda activate moose  173  conda install mamba  174  mamba install moose-tools  175  mamba install moose-libmesh  176  cd projects/  177  git clone https://github.com/idaholab/moose.git  178  cd moose/  179  git checkout master  180  cd libmesh/  181  ls  182  git submodule update --init --recursive  186  mkdir build
  187  cd build  188  ../configure --prefix=/home/dmitry/projects/moose/libmesh/install  189  make -j 8

This time I get an error during "make -j 8", see below.
This is a new error I have not seen so far. I would really appreciate your help.
Best regards,Dmitry
PS. ++++++++++++++++++++++ error in make -j 8 for libmesh +++++++++++++++++++++  CXX      src/parallel/libmesh_devel_la-parallel_ghost_sync.lo  CXX      src/parallel/libmesh_devel_la-parallel_histogram.lo  CXX      src/parallel/libmesh_devel_la-parallel_node.lo  CXX      src/parallel/libmesh_devel_la-parallel_sort.lo  CXX      src/parallel/libmesh_devel_la-threads.lo  CXX      src/partitioning/libmesh_devel_la-centroid_partitioner.lo  CXX      src/partitioning/libmesh_devel_la-linear_partitioner.lo  CXX      src/partitioning/libmesh_devel_la-mapped_subdomain_partitioner.lo  CXX      src/partitioning/libmesh_devel_la-metis_partitioner.lo  CXX      src/partitioning/libmesh_devel_la-parmetis_partitioner.lo  CXX      src/partitioning/libmesh_devel_la-partitioner.lo  CXX      src/partitioning/libmesh_devel_la-partitioner_factory.lo  CXX      src/partitioning/libmesh_devel_la-sfc_partitioner.loIn file included from ../src/partitioning/parmetis_partitioner.C:33:./include/libmesh/parmetis_helper.h:88:41: error: static assertion failed: ParMETIS and libMesh ID sizes must match!   88 |   static_assert(sizeof(Parmetis::idx_t) == sizeof(dof_id_type),      |                 ~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~  CXX      src/partitioning/libmesh_devel_la-subdomain_partitioner.lo  CXX      src/physics/libmesh_devel_la-diff_physics.lomake[1]: *** [Makefile:21338: src/partitioning/libmesh_devel_la-parmetis_partitioner.lo] Error 1make[1]: *** Waiting for unfinished jobs....make[1]: Leaving directory '/home/dmitry/projects/moose/libmesh/build'make: *** [Makefile:32536: all-recursive] Error 1++++++++++++++++++++++++++++ END of make -j 8 ++++++++++++++++++++++++
+++++++++++++++++++++ head and end lines lines from config.log (total #of lines 7377) ++++++++++++++++++++++This file contains any messages produced by compilers whilerunning configure, to aid debugging if configure makes a mistake.
It was created by libmesh configure 1.7.0-pre, which wasgenerated by GNU Autoconf 2.69.  Invocation command line was
  $ ../configure --prefix=/home/dmitry/projects/moose/libmesh/install
## --------- #### Platform. #### --------- ##
hostname = dmitry-desktopuname -m = x86_64uname -r = 5.11.0-40-genericuname -s = Linuxuname -v = #44~20.04.2-Ubuntu SMP Tue Oct 26 18:07:44 UTC 2021
/usr/bin/uname -p = x86_64/bin/uname -X     = unknown

 ...................................................................#define HAVE_EXODUS_API 1#define DETECTED_EXODUS_VERSION_MAJOR 5#define DETECTED_EXODUS_VERSION_MINOR 22#define HAVE_NEMESIS_API 1#define HAVE_LIBHILBERT 1#define HAVE_FPARSER 1#define HAVE_FPARSER_DEVEL 0#define HAVE_FPARSER_JIT 1#define HAVE_NANOFLANN 1#define HAVE_METAPHYSICL 1#define BUILD_USER "dmitry"#define BUILD_ARCH "x86_64-pc-linux-gnu"#define BUILD_HOST "dmitry-desktop"#define BUILD_VERSION "62774ade899b871fb8acde2cc9373a34d3eb12f9"#define BUILD_DEVSTATUS "Development Build"#define BUILD_DATE __DATE__ " " __TIME__
configure: exit 0

++++++++++++++++++++ end of config.log file ++++++++++++++++++++++++++++++++++++++++++++++++++++++    On Tuesday, November 16, 2021, 09:42:36 AM PST, Dmitry Luchinsky ***@***.***> wrote:  
 
 Hi,This time it was native Ubuntu 20.04 (the installation on WSL2 did not work but I made a mistake and will repeat installation on WSL2 latter)
On the native Ubuntu 20.04
   13  curl -L -O https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh   14  bash Miniconda3-latest-Linux-x86_64.sh -b -p ~/miniconda3   15  export PATH=$HOME/miniconda3/bin:$PATH   16  conda config --add channels conda-forge   17  conda config --add channels https://conda.software.inl.gov/public   18  conda install mamba   22  conda init bash   68  conda create --name moose -q -y   69  conda activate moose   70  conda install mamba
Then I was following MOOSE installationmamba install moose-toolsmamba install moose-libmeshmkdir ~/projectscd ~/projectsgit clone https://github.com/idaholab/moose.gitcd moosegit checkout master
then I was following libmesh installation from githubcd /moose/libmesh the folder is empty at this stage then    77  git submodule update --init --recursive   78  mkdir build   79  cd build   80  ../configure --prefix=/home/dmitry/projects/moose/libmesh/install
the folder is populated at this stage and instructions to run "make" and "make install" are printed. So I    81  make -j 12   82  make install
Is this is correct?
I will repeat from the scratch and let you know the outcome.

Best regards,Dmitry

    On Tuesday, November 16, 2021, 07:28:28 AM PST, roystgnr ***@***.***> wrote:  
 
 


If you're trying to install libMesh from the Moose submodule, did you use the Moose script to do so? I got the impression from your previous issue that you were doing it manually. Either way, you must not have finished make install if there's nothing in the install directory. The relevant error is whatever led to that, not the later error when Moose can't find anything.

**Comment by jwpeterson** [comment]
Your messages have very strange formatting, I guess because you are replying via email) but I think the relevant error message here is:
```
static_assert(sizeof(Parmetis::idx_t) == sizeof(dof_id_type),  
```
We have seen this previously when a system Parmetis from /usr/include that uses an 8-byte index type is picked up accidentally by configure. But I think that should not happen when using the MOOSE instructions to build...

**Comment by luchinsky** [comment]
Hi John,
Thank you very much for the message!
Yes, this is exactly the error that was displayed:+++++++++++++++++++++++++++In file included from ../src/partitioning/parmetis_partitioner.C:33:./include/libmesh/parmetis_helper.h:88:41: error: static assertion failed: ParMETIS and libMesh ID sizes must match!   88 |   static_assert(sizeof(Parmetis::idx_t) == sizeof(dof_id_type),      |                 ~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~  CXX      src/partitioning/libmesh_devel_la-subdomain_partitioner.lo  CXX      src/physics/libmesh_devel_la-diff_physics.lomake[1]: *** [Makefile:21338: src/partitioning/libmesh_devel_la-parmetis_partitioner.lo] Error 1++++++++++++++++++++++++++++++
I am not sure what "using the MOOSE instructions to build..." means on the top of following your instructions on mooseframework and github.com/libMesh first I follow these instructions to build moose(https://mooseframework.inl.gov/getting_started/installation/conda.html) then I am using instruction from readme on (https://github.com/libMesh/libmesh)
I activated moose and run these commands from moose environment   
   - cd to location of libmesh clone.
   - git submodule update --init --recursive
   - mkdir build
   - cd build
   - ../configure --prefix=/path/to/libmesh/install
   - make
   - make install
The only thing I did not do was to update conda and moose.
Am I still missing something?
Best regards,Dmitry

    On Tuesday, November 16, 2021, 01:13:05 PM PST, John W. Peterson ***@***.***> wrote:  
 
 


Your messages have very strange formatting, I guess because you are replying via email) but I think the relevant error message here is:
static_assert(sizeof(Parmetis::idx_t) == sizeof(dof_id_type),  

We have seen this previously when a system Parmetis from /usr/include that uses an 8-byte index type is picked up accidentally by configure. But I think that should not happen when using the MOOSE instructions to build...

**Comment by jwpeterson** [comment]
Yeah I don't think you are supposed to run `configure` like that (with only a `--prefix`) when you are building libmesh for MOOSE... there are normally many options that MOOSE needs to pass to configure. This would also explain the error you are seeing, where a Parmetis from /usr/include is being picked up by configure.

**Comment by luchinsky** [comment]
OK, thank you. What instructions I should follow then? 
Also, please notice that compilations went through nicely a few times when I followed the path I have described. This is the first time I am seeing this error. 

    On Tuesday, November 16, 2021, 02:01:44 PM PST, John W. Peterson ***@***.***> wrote:  
 
 


Yeah I don't think you are supposed to run configure like that (with only a --prefix) when you are building libmesh for MOOSE... there are normally many options that MOOSE needs to pass to configure. This would also explain the error you are seeing, where a Parmetis from /usr/include is being picked up by configure.

**Comment by jwpeterson** [comment]
> What instructions I should follow then?

I think you should [follow the instructions that you linked to](https://mooseframework.inl.gov/getting_started/installation/conda.html) since you plan to use libmesh via MOOSE. It's possible for an expert to create and maintain a custom-built libmesh for use with MOOSE, but why bother when you could just do:
```
mamba install moose-libmesh
```
instead? I believe this will also guarantee that you get a version of libmesh that is not too old or too new to work with the version of MOOSE you are using.

**Comment by luchinsky** [comment]
Hi John,
That is exactly the problem. I do use these commands mamba install moose-toolsmamba install moose-libmeshAnd I did hope that this is itBut when I cd /moose/test and run make -j 4 I get these errors:/bin/sh: 1: /mnt/d/projects/moose/libmesh/installed/contrib/bin/libmesh-config: not found/bin/sh: 1: /mnt/d/projects/moose/libmesh/installed/contrib/bin/libmesh-config: not found
and in fact the folder /moose/libmesh is empty. This is why I thought that you have changed the procedure and I have to install libmesh separately. 
I would really appreciate your help.
Best regards,Dmitry

 

    On Tuesday, November 16, 2021, 02:32:05 PM PST, John W. Peterson ***@***.***> wrote:  
 
 



What instructions I should follow then?


I think you should follow the instructions that you linked to since you plan to use libmesh via MOOSE. It's possible for an expert to create and maintain a custom-built libmesh for use with MOOSE, but why bother when you could just do:
mamba install moose-libmesh

instead? I believe this will also guarantee that you get a version of libmesh that is not too old or too new to work with the version of MOOSE you are using.

**Comment by jwpeterson** [comment]
OK, I think this may be a question for the MOOSE Discussion boards, but one question is whether you somehow have a `LIBMESH_DIR` set in your environment that points the MOOSE Makefile to `/mnt/d/projects/moose/libmesh/installed` even though that is not the correct libmesh installation directory? (Maybe this is from an old .bashrc file, for example.)

In any event, the solution here is not to build your own libmesh by hand. Instead, you should try to figure out what is wrong with the mamba installation, and get that working. This will also make your next MOOSE/libmesh update much easier.

**Comment by luchinsky** [comment]
Hi John,
Thank you! No I do not have LIBMESH_DIR. I do not know why the Makefile points to "/mnt/d/projects/moose/libmesh/installed"I specify this path in "../configure --prefix=/mnt/d/projects/moose/libmesh/install" when trying to install libmesh separately.
But the Makefile points to the same path "/mnt/d/projects/moose/libmesh/installed" when I do not try to install libmesh separately and only use mamba install moose-toolsmamba install moose-libmesh
I am using two brand new ubuntu installations one on WSL2 and one native. I can delete and reinstall both from scratch because they were created intentionally for MOOSE. my .bashrc can be found below. As you can see it is almost empty. This is the case for both versions of ubuntu. It is really a good news that a separate installation of the libmesh is not required. I hope very much that a solution can be found. Are there any other files that could be useful to troubleshooting?
Best regards,DmitryPS. If needed I could try to install MOOSE one more time from Ubuntu 18.04. It worked many times in the past but not anymore so I tried to switched to 20.04 as recommended on your MOOSE site. By the way you have now impressive tutorials, thank you.  

    On Tuesday, November 16, 2021, 03:04:08 PM PST, John W. Peterson ***@***.***> wrote:  
 
 


OK, I think this may be a question for the MOOSE Discussion boards, but one question is whether you somehow have a LIBMESH_DIR set in your environment that points the MOOSE Makefile to /mnt/d/projects/moose/libmesh/installed even though that is not the correct libmesh installation directory? (Maybe this is from an old .bashrc file, for example.)

In any event, the solution here is not to build your own libmesh by hand. Instead, you should try to figure out what is wrong with the mamba installation, and get that working. This will also make your next MOOSE/libmesh update much easier.

—
You are receiving this because you authored the thread.

Reply to this email directly, view it on GitHub, or unsubscribe.

+++++++++++++++++++ .bashrc ++++++++++++++++++++++# ~/.bashrc: executed by bash(1) for non-login shells.# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)# for examples
# If not running interactively, don't do anythingcase $- in    *i*) ;;      *) return;;esac
# don't put duplicate lines or lines starting with space in the history.# See bash(1) for more optionsHISTCONTROL=ignoreboth
# append to the history file, don't overwrite itshopt -s histappend
# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)HISTSIZE=1000HISTFILESIZE=2000
# check the window size after each command and, if necessary,# update the values of LINES and COLUMNS.shopt -s checkwinsize
# If set, the pattern "**" used in a pathname expansion context will# match all files and zero or more directories and subdirectories.#shopt -s globstar
# make less more friendly for non-text input files, see lesspipe(1)[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"
# set variable identifying the chroot you work in (used in the prompt below)if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then    debian_chroot=$(cat /etc/debian_chroot)fi
# set a fancy prompt (non-color, unless we know we "want" color)case "$TERM" in    xterm-color|*-256color) color_prompt=yes;;esac
# uncomment for a colored prompt, if the terminal has the capability; turned# off by default to not distract the user: the focus in a terminal window# should be on the output of commands, not on the prompt#force_color_prompt=yes
if [ -n "$force_color_prompt" ]; then    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then    # We have color support; assume it's compliant with Ecma-48    # (ISO/IEC-6429). (Lack of such support is extremely rare, and such    # a case would tend to support setf rather than setaf.)    color_prompt=yes    else    color_prompt=    fifi
if [ "$color_prompt" = yes ]; then    PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ 'else    PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ 'fiunset color_prompt force_color_prompt
# If this is an xterm set the title to ***@***.***:dircase "$TERM" inxterm*|rxvt*)    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"    ;;*)    ;;esac
# enable color support of ls and also add handy aliasesif [ -x /usr/bin/dircolors ]; then    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"    alias ls='ls --color=auto'    #alias dir='dir --color=auto'    #alias vdir='vdir --color=auto'
    alias grep='grep --color=auto'    alias fgrep='fgrep --color=auto'    alias egrep='egrep --color=auto'fi
# colored GCC warnings and errors#export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'
# some more ls aliasesalias ll='ls -alF'alias la='ls -A'alias l='ls -CF'
# Add an "alert" alias for long running commands.  Use like so:#   sleep 10; alertalias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'
# Alias definitions.# You may want to put all your additions into a separate file like# ~/.bash_aliases, instead of adding them here directly.# See /usr/share/doc/bash-doc/examples in the bash-doc package.
if [ -f ~/.bash_aliases ]; then    . ~/.bash_aliasesfi
# enable programmable completion features (you don't need to enable# this, if it's already enabled in /etc/bash.bashrc and /etc/profile# sources /etc/bash.bashrc).if ! shopt -oq posix; then  if [ -f /usr/share/bash-completion/bash_completion ]; then    . /usr/share/bash-completion/bash_completion  elif [ -f /etc/bash_completion ]; then    . /etc/bash_completion  fifiexport DISPLAY=localhost:0
# >>> conda initialize >>># !! Contents within this block are managed by 'conda init' !!__conda_setup="$('/home/dmitry/miniconda3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"if [ $? -eq 0 ]; then    eval "$__conda_setup"else    if [ -f "/home/dmitry/miniconda3/etc/profile.d/conda.sh" ]; then        . "/home/dmitry/miniconda3/etc/profile.d/conda.sh"    else        export PATH="/home/dmitry/miniconda3/bin:$PATH"    fifiunset __conda_setup# <<< conda initialize <<<

**Comment by luchinsky** [comment]
Hi John,
Thank you!It was all mamba.
Best regards,Dmitry 

    On Tuesday, November 16, 2021, 03:04:08 PM PST, John W. Peterson ***@***.***> wrote:  
 
 


OK, I think this may be a question for the MOOSE Discussion boards, but one question is whether you somehow have a LIBMESH_DIR set in your environment that points the MOOSE Makefile to /mnt/d/projects/moose/libmesh/installed even though that is not the correct libmesh installation directory? (Maybe this is from an old .bashrc file, for example.)

In any event, the solution here is not to build your own libmesh by hand. Instead, you should try to figure out what is wrong with the mamba installation, and get that working. This will also make your next MOOSE/libmesh update much easier.
