### ISSUE TITLE
undefined reference to `libMesh::Parallel::MessageTag::~MessageTag()'

### ISSUE THREAD

**Issue by RikVoorhaar** [libMesh/libmesh#3096]
Whenever I include `libmesh/mesh.h` I get an undefined reference error. For example, this is my CMAKE build log:

```
[build] Starting build
[proc] Executing command: /usr/bin/cmake --build /home/rik/switchdrive/Notes/finite_element_methods/mesh_interpolation_2D/build --config Debug --target all -j 18 --
[build] [1/2  50% :: 1.339] Building CXX object CMakeFiles/main.dir/main.cpp.o
[build] [2/2 100% :: 1.428] Linking CXX executable main
[build] FAILED: main 
[build] : && /usr/bin/mpic++ -g -rdynamic CMakeFiles/main.dir/main.cpp.o -o main   && :
[build] /usr/bin/ld: CMakeFiles/main.dir/main.cpp.o: in function `__static_initialization_and_destruction_0(int, int)':
[build] /opt/vcpkg/installed/x64-linux/include/libmesh/message_tag.h:115: undefined reference to `libMesh::Parallel::MessageTag::~MessageTag()'
[build] /usr/bin/ld: /opt/vcpkg/installed/x64-linux/include/libmesh/message_tag.h:120: undefined reference to `libMesh::Parallel::MessageTag::~MessageTag()'
[build] collect2: error: ld returned 1 exit status
[build] ninja: build stopped: subcommand failed.
[build] Build finished with exit code 1
```

The problem seems to be with the destructor of `MessageTag`, but as far as I can see in `message_tag.h` in my include directory, the destructor is properly defined, so I have no idea why it does this. 

My `main.cpp` is just

```
#include <libmesh/mesh.h>

int main(){
     return 0;
}
```

I installed `libMesh` using `vcpkg`, and I add it to my `CMakeLists.txt` with `target_include_directories`.
I am fairly new to developing with C/C++, so I have no real clue how to approach this.

**Comment by jwpeterson** [comment]
I definitely can't reproduce this, so I suspect the problem is related to vcpkg/CMake some how. I'm curious what the full compile/link line is, though? If it's just this:
```
/usr/bin/mpic++ -g -rdynamic CMakeFiles/main.dir/main.cpp.o -o main
```
Then I would not expect it to work... you need to link against all the libmesh and other relevant libraries in order to avoid undefined reference errors like the one posted.

**Comment by RikVoorhaar** [comment]
That's it. Sorry for the stupid question. 

For posterity, this `CMakeLists` does the trick:
```
project(main VERSION 0.1.0)

link_directories("/opt/vcpkg/packages/libmesh_x64-linux/lib")
include_directories("/opt/vcpkg/packages/libmesh_x64-linux/include")
add_executable(${PROJECT_NAME} main.cpp)

target_link_libraries(${PROJECT_NAME} PRIVATE mesh_opt)
```
