### ISSUE TITLE
transfer_elem seems not transferring extra element integers

### ISSUE THREAD

**Issue by YaqiWang** [libMesh/libmesh#3105]
The `transfer_elem` in `unstructured_mesh.C` used by `UnstructuredMesh::all_second_order` seems not transferring extra element integers. Because of this, when converting a first order mesh with extra element integers to second order, we will lose these integers. This is a bug reported by @yjung-anl. Possibly care needs to be taken for nodes (not sure). Tag @roystgnr

**Comment by roystgnr** [comment]
You know, I thought we simply had overlooked extra integer support here, but on closer look it seems like the support is there but has a simple bug.  I can reproduce it by extending a unit test; if the fix actually is simple then I'll push the fix and the extended test shortly.
