### ISSUE TITLE
VTK support for IsoGeometric Analysis visualization

### ISSUE THREAD

**Issue by roystgnr** [libMesh/libmesh#3152]
Pinging @aeslaughter to get the Coreform guys in here.

Right now, our best option for IGA visualization is "output to Exodus, and wince as our ExodusII_IO output inappropriately turns RATIONAL_BERNSTEIN control points into LAGRANGE mid-edge/face/cell points"  This works fine as long as our mesh is so fine that there's little difference between the two ... which means that the more advantageous an IGA solve is, the worse our IGA visualization is going to be.

Our best option for quickly fixing that is probably to output the proper element data via VTKIO, using the relatively recent extensions to VTK that support those element types.

Right now, src/mesh/vtk_io.C has an element map from libMesh element types to VTK element types, and that won't be enough - in libMesh the same e.g. HEX27 may be a Lagrange element if it has one mapping_type() or a Rational Bernstein element if it has another mapping_type().  At the very least we'll need to be testing Elem::mapping_type() before deciding which VTK element type to output.  Hopefully this will be the only major complication (in particular, I don't *see* anything in get_local_node_values or node_values_to_vtk that I'd expect to change), but I'm unfamiliar with the VTK rational basis support so I can't swear to it.

Our best bet for testing this out would be to just add VTK output to at least one of the IGA unit tests in tests/mesh/mesh_input.C - possibly testExodusFileMappingsPlateWithHole?  I'm not sure how best to get such a test in CI (as opposed to "just look at it manually in Paraview"), though, not without VTK input as well as output support.

**Comment by aeslaughter** [comment]
Thanks @roystgnr
