### ISSUE TITLE
Nodeset info from MeshBase

### ISSUE THREAD

**Issue by adityaghantasala** [libMesh/libmesh#3193]
Hello everyone

When going through the implementation of `get_info `in the `mesh_base` I found something strange. 
When printing the info of the nodesets, `get_sideset_name_map` from the `boundary_info `is used instead of using `get_nodeset_name_map`.

Here is the link to the implementation. 

https://github.com/libMesh/libmesh/blob/db468db9da113600e05b37e0f68927975a0a19dc/src/mesh/mesh_base.C#L856

My question is, is this intended ?  If yes why ?

I also want to reffer the following PR here #2840, where this is implemented. 

Thank you in advance.

**Comment by roystgnr** [comment]
That sure looks like a bug to me.  @loganharbour ?

**Comment by loganharbour** [comment]
Yep - absolutely a bug.

**Comment by roystgnr** [comment]
Thanks for catching this!
