### ISSUE TITLE
compilation error: ‘ReplaceAlgebraicType’ is not a class template

### ISSUE THREAD

**Issue by BalticPinguin** [libMesh/libmesh#3242]
dear all,
after my recent update of libMesh (master-branch), I get the compilation error
````
In file included from ../include/libmesh/parsed_function.h:29,
                 from ../../master/tests/numerics/composite_function_test.C:5:
../include/libmesh/vector_value.h:270:8: error: ‘ReplaceAlgebraicType’ is not a class template
  270 | struct ReplaceAlgebraicType<libMesh::VectorValue<T>, U>
      |        ^~~~~~~~~~~~~~~~~~~~
make[2]: *** [numerics/unit_tests_devel-composite_function_test.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from ../include/libmesh/mesh_generation.h:26,
                 from ../../master/tests/mesh/mesh_stitch.C:2:
../include/libmesh/vector_value.h:270:8: error: ‘ReplaceAlgebraicType’ is not a class template
  270 | struct ReplaceAlgebraicType<libMesh::VectorValue<T>, U>
      |        ^~~~~~~~~~~~~~~~~~~~
In file included from ./include/libmesh/fe_abstract.h:26,
                 from ./include/libmesh/fe_base.h:26,
                 from ./include/libmesh/fem_context.h:27,
                 from ./include/libmesh/fem_function_base.h:26,
                 from ./include/libmesh/system.h:27,
                 from ./include/libmesh/solution_history.h:22,
                 from ./include/libmesh/memory_solution_history.h:25,
                 from ../master/src/solvers/memory_solution_history.C:19:
./include/libmesh/vector_value.h:270:8: error: ‘ReplaceAlgebraicType’ is not a class template
  270 | struct ReplaceAlgebraicType<libMesh::VectorValue<T>, U>
      |        ^~~~~~~~~~~~~~~~~~~~
In file included from ./include/libmesh/fe_abstract.h:26,
                 from ./include/libmesh/fe_base.h:26,
                 from ./include/libmesh/fe.h:24,
                 from ../master/src/fe/fe_side_hierarchic.C:22:
./include/libmesh/vector_value.h:270:8: error: ‘ReplaceAlgebraicType’ is not a class template
````
I'll leave the further repetitions due to other include-paths aside now, but there are quite many.

I am not sure about the cause of this issue; it seems I am the only one having it!?
Probably @lindsayad can help me here?

For completeness: I use gcc 11.2.0 and configure with
````
configure --prefix=/path/ \
  --enable-default-comm-world \
  --disable-reference-counting \
  --disable-second          \
  --disable-strict-lgpl     \
  --disable-unique-id       \
  --disable-maintainer-mode \
  --disable-nodeconstraint  \
  --disable-coverage        \
  --enable-werror         \
  --enable-petsc          \
  --enable-mpi            \
  --enable-complex        \
  --enable-tetgen         \
  --enable-ifem           \
  --enable-march          \
  --enable-everything
````
Best regards

**Comment by jwpeterson** [comment]
Did your submodule update via
```
git submodule update --init --recursive
```
succeed? `ReplaceAlgebraicType` is a metaphysicl thing, so if you are still on old metaphysicl branch that could be the issue.

**Comment by BalticPinguin** [comment]
Actually, I missed the `recursive`-option, but that doesn't change anything here. 
But still, the version of metaphysicl looks rather old:
` Package version............... : metaphysicl-1.3.3`
The last commit there is  `4be0df67e` from Nov. 29; is that correct?

**Comment by jwpeterson** [comment]
My metaphysicl submodule is on libMesh/MetaPhysicL@b296fe3, which is from 7 days ago. This is the commit that was updated to in libMesh/libmesh@a9815a6e721d2f2dd77aa4557b512db3c244ea57 from April 14th.

**Comment by jwpeterson** [comment]
Is it possible that your submodule still points to roystgnr/MetaPhysicL? If so, you can run `git submodule sync` to try and update the new remote.

**Comment by jwpeterson** [comment]
@roystgnr there don't seem to be any metaphysicl tags (at least I don't have any) since v1.3.3_bootstrapped which corresponds to the version that @BalticPinguin is stuck on. Are you no longer tagging metaphysicl commits that we update the libmesh submodule to?

**Comment by BalticPinguin** [comment]
hmm... I noticed that all my submodules point to some old versions; manually updating (git checkout master; git pull) solves that; but `git submodule sync` brings me back to these old versions.

**Comment by jwpeterson** [comment]
`sync` should not change the "version" of any code in a submodule as far as I know. According to the man page, it "Synchronizes submodules' remote URL configuration setting to the value specified in .gitmodules." so it only changes the URL, and you must run it after getting up-to-date e.g. with `git pull`, since you want your sync to be based on the most up-to-date version of .gitmodules.

**Comment by jwpeterson** [comment]
Also, just for completeness, any time you run `git pull` you may also need to run `git submodule update --init --recursive` to make sure the submodules are up-to-date. `pull` and `rebase` don't update the submodules to their "current" versions.

**Comment by BalticPinguin** [comment]
thank you very much, @jwpeterson . Now, I have fixed all the issues.

Actually, I managed to set the submodules into some state where also updates/sync. etc. didn't help; (e.g. the `metaphysicl/build-aux` was missing, but git didn't seem to bother).
Finally, with `git submodule deinit --recursive` and `git submodule update --init --recursive`,

**Comment by lindsayad** [comment]
Glad you got this worked out!

**Comment by jwpeterson** [comment]
OK, yeah I don't think every metaphysicl update needs to be to a tagged version or anything. It might be useful to have pairs of `vx.y.z` and `vx.y.z_bootstrapped` tags so that it's clear what the bootstrapped version of any tagged release is.
