### ISSUE TITLE
Abaqus mesh reader modifies nodesets when surface sets are present

### ISSUE THREAD

**Issue by jessecarterMOOSE** [libMesh/libmesh#3358]
hi @roystgnr - got another Abaqus mesh reader bug for you. If you look at the MOOSE examples [here](https://github.com/idaholab/moose/tree/next/test/tests/mesh/abaqus_input), maybe [this one](https://github.com/idaholab/moose/blob/next/test/tests/mesh/abaqus_input/testcube_elset_name_in.inp) in particular, you'll see there are no nodesets, but when you run the example, nodesets are created. Also if you explicitly add some nodesets, the presence of multiple surface sets will modify those nodesets. Doesn't seem like correct behavior.

**Comment by jessecarterMOOSE** [comment]
Nevermind, this is not a libmesh issue. From the [Moose docs](https://mooseframework.inl.gov/source/mesh/MooseMesh.html):

> By default, MOOSE will construct a node set corresponding to each side set within your mesh.

Not sure why it _overwrites_ existing nodesets, but that's another problem for a different day...

**Comment by roystgnr** [comment]
> Not sure why it overwrites existing nodesets, but that's another problem for a different day...

Probably worth copying my answer from Slack:

libMesh doesn't combine anything.  We store [side sets and node sets] in completely different data structures, independently indexed.  We do let higher level code try to convert a side set into a new node set, but IMHO turning that on by default was a mistake.  ... and the API Derek added for that treats ids as a primary key, not names, so when you create a new node set from sideset 4->"top" it'll just happily add the nodes on that side to nodeset 4->"anything else".

That code probably predates our support for nodeset and sideset names, come to think of it.

Needs to be updated to take an optional argument specifying whether we want to map by name or by id when deciding which set to add nodes to.
