### ISSUE TITLE
Not able to set MUMPs parameters

### ISSUE THREAD

**Issue by MPhysXDev** [libMesh/libmesh#3375]
Dear all,

when using libmesh/SLEPc/MUMPs, **it does not seem to be possible to set any of the MUMPs control parameters.** 

To illustrate the problem, when running eigenproblems_ex3.C (from your suite of examples) with the following set of options (either on the command line or in the .petsrc file):

-options_view
-options_left

-st_type sinvert
-st_ksp_type preonly
-st_pc_type lu
-st_pc_factor_mat_solver_type mumps 
-mat_mumps_icntl_2 1 

We get the following report on exit:

#PETSc Option Table entries:
-mat_mumps_icntl_2 1
-mesh_name ../data/meshes/unit_disk
-n_evals 20
-options_left
-options_view
-st_ksp_type preonly
-st_pc_factor_mat_solver_type mumps
-st_pc_type lu
-st_type sinvert
#End of PETSc Option Table entries
WARNING! There are options you set that were not used!
WARNING! could be spelling mistake, etc!
There are 3 unused database options. They are:
**Option left: name:-mat_mumps_icntl_2 value: 1**
Option left: name:-mesh_name value: ../data/meshes/unit_disk
Option left: name:-n_evals value: 20

**Same behavior is observed for any of the other -mat_mumps control parameters we tried to use.** However, MUMPs is clearly being used, and the program runs properly and gives the expected results.

**The installed versions of the libraries(spack installed) are:**
libmesh@1.7.1
petsc@3.17.3
slepc@3.17.1
mumps@5.4.1

**The system configuration is:**
Description:	Ubuntu 20.04.4 LTS
Release:	20.04
Codename:	focal
    description: Notebook
    product: Latitude 5480 (07A7)
    vendor: Dell Inc.
          description: CPU
          product: Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz
          description: System Memory
          size: 16GiB

Thanks in advance to let us know if you reproduce the problem, if this is a libmesh issue or if this is something we shall report to the PETSc and/or SLEPc team(s).

**Comment by jwpeterson** [comment]
I found the following example in the [SLEPc User Manual](https://slepc.upv.es/documentation/slepc.pdf):
```
$ ./ex2 -n 50 -eps_interval 0.4,0.8 -st_type sinvert
-st_ksp_type preonly -st_pc_type cholesky
-st_pc_factor_mat_solver_type mumps -st_mat_mumps_icntl_13 1
```
Can you try prepending `-st_` to your MUMPs-specific flag and see if that fixes the problem?

**Comment by MPhysXDev** [comment]
Feeling a bit stupid, I thought I tried a couple of prefixes along that line, but should have tried -st_pc_mat... :(
It works indeed! Thanks for your time and prompt help!
