### ISSUE TITLE
More permissive `index_range` function

### ISSUE THREAD

**Issue by dschwen** [libMesh/libmesh#3377]
Any reason `index_range` just has a limited set of (partial) specializations?

It would be useful to have something like

```
template <typename T>
auto
index_range(const T & sizable)
{
  return IntRange<decltype(sizable.size())>(0, sizable.size());
}
```

To allow iterating over e.g. Communicators and MooseArrays. Basically anything that has a `.size()` function.

**Comment by jwpeterson** [comment]
Sounds like a great idea to me... there is an `index_range` specialization for `NumericVector` that we would want to keep, but it looks to me that your version could replace the other three that we currently have.

**Comment by roystgnr** [comment]
Looks like a great idea to me.

**Comment by dschwen** [comment]
Ok, I'll open a PR.

**Comment by dschwen** [comment]
Oh, can we rely on C++17 in libMesh, or is that only MOOSE for now? (return type `auto`)

**Comment by jwpeterson** [comment]
libMesh requires a C++17 compatible compiler now.
