### ISSUE TITLE
Installation error - build error

### ISSUE THREAD

**Issue by XuanQuangPham91** [libMesh/libmesh#3416]
Hello, 

I have a problem with the installation.

I have downloaded and installed: petsc-3.18.0 and slepc-3.18.0. After that, I download and install libmesh-1.7.1 following instructions in the [link](https://libmesh.github.io/installation.html). I meet the error below while doing the "make" step before the "make install" step.

In file included from /opt/local/lib/petsc-3.18.0/include/petscsys.h:1189,
                 from /opt/local/lib/petsc-3.18.0/include/petscbag.h:5,
                 from /opt/local/lib/petsc-3.18.0/include/petsc.h:5,
                 from ./include/libmesh/petsc_macro.h:66,
                 from src/solvers/petscdmlibmeshimpl.C:20:
src/solvers/petscdmlibmeshimpl.C: In function ‘PetscErrorCode DMSetUp_libMesh(DM)’:
src/solvers/petscdmlibmeshimpl.C:904:120: error: ‘struct _p_PetscObject’ has no member named ‘type’
  904 |     LIBMESH_SETERRQ2(((PetscObject)dm)->comm, PETSC_ERR_ARG_WRONG, "DM of type %s, not of type %s", ((PetscObject)dm)->type, DMLIBMESH);      
|                                                                                                                        ^~~~
/opt/local/lib/petsc-3.18.0/include/petscerror.h:115:127: note: in definition of macro ‘SETERRQ’
  115 |     PetscErrorCode ierr_seterrq_petsc_ = PetscError(comm, __LINE__, PETSC_FUNCTION_NAME, __FILE__, ierr, PETSC_ERROR_INITIAL, __VA_ARGS__); \    
|                                                                                                                               ^~~~~~~~~~~
src/solvers/petscdmlibmeshimpl.C:904:5: note: in expansion of macro ‘LIBMESH_SETERRQ2’
  904 |     LIBMESH_SETERRQ2(((PetscObject)dm)->comm, PETSC_ERR_ARG_WRONG, "DM of type %s, not of type %s", ((PetscObject)dm)->type, DMLIBMESH);
      |     ^~~~~~~~~~~~~~~~
  CXX      src/systems/libmesh_devel_la-diff_context.lo
  CXX      src/systems/libmesh_devel_la-diff_system.lo
make[1]: *** [Makefile:21925: src/solvers/libmesh_devel_la-petscdmlibmeshimpl.lo] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/opt/local/src/libmesh-1.7.1'
make: *** [Makefile:32290: all-recursive] Error 1

**Comment by ehsanakrami** [comment]
I had the same problem. It seems that the current version of libMesh is not compatible with Petsc 3.18. It downgraded Petsc to the 3.17.4 version, and it is working smoothly.

**Comment by roystgnr** [comment]
We don't have any PETSc 3.18 modules yet in our Continuous Integration testing, so the branch in #3417 has only been properly tested on my own computer so far.  Would either of you be up to giving it a try?

**Comment by ehsanakrami** [comment]
> I had the same problem. It seems that the current version of libMesh is not compatible with Petsc 3.18. It downgraded Petsc to the 3.17.4 version, and it is working smoothly.

I have tested this branch and works perfectly with PETSc 3.18.

**Comment by roystgnr** [comment]
Thank you!
