### ISSUE TITLE
constexpr error in timpi/request.h with OpenMPI

### ISSUE THREAD

**Issue by boyceg** [libMesh/libmesh#3538]
In the current libMesh `master` branch, I am getting errors like:
```
../contrib/timpi/src/parallel/include/timpi/request.h:112:28: error: constexpr variable 'null_request' must be initialized by a constant expression
  static constexpr request null_request = MPI_REQUEST_NULL;
                           ^              ~~~~~~~~~~~~~~~~
../contrib/timpi/src/parallel/include/timpi/request.h:112:43: note: cast from 'void *' is not allowed in a constant expression
  static constexpr request null_request = MPI_REQUEST_NULL;
```
with OpenMPI. The reason appears to be that OpenMPI  intentionally defines `MPI_REQUEST_NULL` to be a `void*`.

**Comment by jwpeterson** [comment]
I think this has been fixed, see libMesh/TIMPI#122

**Comment by jwpeterson** [comment]
The libMesh TIMPI submodule hasn't been updated with the fix yet, unfortunately. @roystgnr

**Comment by roystgnr** [comment]
Yeah, I was going to wait to bring it downstream until the next MOOSE submodule update, but if we've got non-MOOSE users hitting this now too (with what compiler, can I ask?) then it's urgent enough to move sooner.

**Comment by boyceg** [comment]
Looks like that does the job --- thanks!

**Comment by boyceg** [comment]
> with what compiler, can I ask?

Apple clang version 14.0.3 (clang-1403.0.22.14.1)
Target: arm64-apple-darwin22.4.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

**Comment by roystgnr** [comment]
Well, that's embarrassing.  I saw the bug report from an nvc++ user, and I've already noticed that nvc++ is extra picky about certain classes of issues, so I thought this was just one of those.  Looks like I broke OpenMPI support for *everyone*.

**Comment by NamjaeChoi** [comment]
Interesting. I don't think I hit this problem with GCC + OpenMPI.
