### ISSUE TITLE
L2_HIERARCHIC on PRISM elements

### ISSUE THREAD

**Issue by zachmprince** [libMesh/libmesh#3557]
We are looking into performing p-refinement on discontinuous-Galerkin variables. `L2_HIERARCHIC` seems to be the most useful family for p-refinement as its formulation ensures a wide range of element types. The geometry we are looking uses extruded triangles, i.e. prisms. Currently, `L2_HIERARCHIC` is not supported with this element type.

**Comment by roystgnr** [comment]
This should have been fixed as of #3604
