### ISSUE TITLE
Cannot compile libmesh in dbg mode

### ISSUE THREAD

**Issue by adigc** [libMesh/libmesh#3591]
Hello everyone, 

I am trying to compile libmesh in dbg mode and the compilation produces the following error 

```
  CXX      src/apps/fparser_parse_dbg-fparser_parse.o
In file included from ./include/libmesh/mesh_communication.h:26,
                 from ./include/libmesh/checkpoint_io.h:28,
                 from ../src/apps/splitter.C:24:
./include/libmesh/mesh_tools.h: In function 'void libMesh::MeshTools::libmesh_assert_valid_procids(const libMesh::MeshBase&)':
./include/libmesh/mesh_tools.h:572:3: error: 'libmesh_assert_topology_consistent_procids' was not declared in this scope; did you mean 'libmesh_assert_parallel_consistent_procids'?
  572 |   libmesh_assert_topology_consistent_procids<DofObjectSubclass>(mesh);
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |   libmesh_assert_parallel_consistent_procids
./include/libmesh/mesh_tools.h:572:63: error: expected primary-expression before '>' token
  572 |   libmesh_assert_topology_consistent_procids<DofObjectSubclass>(mesh);

```

I **could** compile in opt, devel and pro. No prpblem
I am suspecting a misplaced #ifdef  but am not sure.  Is this issue known ? If not, am I missing something when compiling. 

Thank you in advance.

**Comment by roystgnr** [comment]
Is it possible you've got `NDEBUG` and `DEBUG` processor macros *both* defined at the same time somehow?  The former via your own `$CXXFLAGS` and the latter via our `METHOD=dbg` settings?  That's our only guess so far.

**Comment by roystgnr** [comment]
This definitely isn't a known issue; most of our CI recipes include `dbg` builds and I don't think anyone's ever reported this before.

**Comment by adigc** [comment]
Thank you very much for your reply. I will check with the flags. 

As an additional info: I am compiling libmesh using the following script of moose repo 
https://github.com/idaholab/moose/blob/next/scripts/update_and_rebuild_libmesh.sh

also with the following options: 

```
./scripts/update_and_rebuild_libmesh.sh \
  --enable-vtk-required \
  CC="$CC" \
  CXX="$CXX" \
  FC="$FC" \
  F77="$F77" \
  F90="$F90" \
  CPP="$CPP" \
  AR="$AR" \
  RANLIB="$RANLIB" \
  CFLAGS="$CFLAGS" \
  CXXFLAGS="$CXXFLAGS" \
  FFLAGS="$FFLAGS" \
  CPPFLAGS="$CPPFLAGS" \
  LDFLAGS="$LDFLAGS"
```

**Comment by roystgnr** [comment]
If I configure with `CXXFLAGS=-DNDEBUG` then I get exactly this error.

**Comment by roystgnr** [comment]
I'll look into a fix ... but I'll probably also put in some screaming `static_assert` to error out earlier, unless someone else can come up with a reason why anyone would ever *intentionally* build with both `DEBUG` (turn on all the ridiculously expensive error checking!) and `NDEBUG` (turn off all the somewhat affordable error checking!) at the same time.

**Comment by adigc** [comment]
#2518

**Comment by adigc** [comment]
Thank you for the pointers, I checked into the environment and found this 

`CPPFLAGS=-DNDEBUG -D_FORTIFY_SOURCE=2 -O2`

This is after activating the mamba environment for building moose. 

This means that this CPPFLAGS is used for all the build types of moose/libmesh, so there are both DEBUG and NDEBUG defined for debug builds. This I believe is where the problem is coming from.

I can delete NDEBUG from CPPFLAGS but then it will be deleted for all the builds. Is this ideal ?

**Comment by roystgnr** [comment]
We add back `-DNDEBUG` ourselves for `opt` and `oprof` builds; leaving it unspecified in your environment is ideal.

Surely that `$CPPFLAGS` isn't being set from one of the MOOSE mamba packages?  People would be hitting this error left and right.
