### ISSUE TITLE
PETSc 3.20 warnings

### ISSUE THREAD

**Issue by lindsayad** [libMesh/libmesh#3610]
I'll put these here as I run across them

### PetscValidPointer
```
../src/solvers/petscdmlibmeshimpl.C:183:13: warning: Use "PetscAssertPointer()" (since version 3.20.0) instead. Silence this warning (as well as all others for this version) by defining PETSC_SILENCE_DEPRECATION_WARNINGS_3_20_0.
  183 |   PetscValidPointer(n,2);
```

**Comment by roystgnr** [comment]
Do we have a PETSc 3.20.0 yet, or is this just a git head?  I'm only seeing v3.19.4 in freshly pulled tags.

**Comment by lindsayad** [comment]
No 3.20.0 release yet. But I can fix the warnings for users using PETSc main with https://github.com/libMesh/libmesh/pull/3615
