### ISSUE TITLE
netcdf-4.3.1 does not compile with hdf5-1.8.13

### ISSUE THREAD

**Issue by capitalaslash** [libMesh/libmesh#363]
this has been fixed in netcdf, see Unidata/netcdf-c#51

i tried to manually update netcdf to 4.3.3rc2 but the vanilla conf file do not work, what should i change?

**Comment by capitalaslash** [comment]
v4.3.3 is available from a couple of weeks.
today i was able to test it in libmesh and it is working with my mpi-enabled hdf5, i just had to run aclocal and automake v1.12

**Comment by jwpeterson** [comment]
Fixed by #1326.
