### ISSUE TITLE
PETSC_RELEASE_GREATER_EQUALS is wrong

### ISSUE THREAD

**Issue by BalticPinguin** [libMesh/libmesh#3669]
I think, this is a follow-up to #3589: 
Trying to link against a 3.19.0 variant, ( I followed the [recommended instruction](https://petsc.org/release/install/download/#recommended-obtain-release-version-with-git) to get 'the release from git'),
I get several errors of the type
````
../libmesh-src/src/solvers/petscdmlibmeshimpl.C:184:3: error: ‘PetscAssertPointer’ was not declared in this scope; did you mean ‘PetscHashPointer’?
  184 |   PetscAssertPointer(n,2);
      |   ^~~~~~~~~~~~~~~~~~
````

because the AssertPointer is valid only `#if PETSC_RELEASE_GREATER_EQUALS(3,20,0)`.
Looking at that macro (`petsc_macro.h`), it is the opposite to `PETSC_RELEASE_LESS_EQUALS`, which checks for version and `LIBMESH_DETECTED_PETSC_VERSION_RELEASE`.
Since I don't use a detected version, the "greater_equals"-check evaluates to true...

My suggested solution is
````
diff --git a/include/numerics/petsc_macro.h b/include/numerics/petsc_macro.h
index ab5eec578..8a51fb35f 100644
--- a/include/numerics/petsc_macro.h
+++ b/include/numerics/petsc_macro.h
@@ -246,14 +246,22 @@ const PetscReal * pPR(const T * ptr)
 #define PETSC_RELEASE_EQUALS(major, minor, subminor) \
   (PETSC_VERSION_EQUALS(major, minor, subminor) && LIBMESH_DETECTED_PETSC_VERSION_RELEASE)
 
+#define PETSC_RELEASE_LESS_EQUALS(major, minor, subminor) \
+  (LIBMESH_DETECTED_PETSC_VERSION_RELEASE && \
+  (PETSC_VERSION_LESS_THAN(major, minor, subminor) || PETSC_VERSION_EQUALS(major, minor, subminor)))
+
+#define PETSC_RELEASE_GREATER_EQUALS(major, minor, subminor) \
+  (0 == PETSC_VERSION_LESS_THAN(major, minor, subminor)  && LIBMESH_DETECTED_PETSC_VERSION_RELEASE)
+
+#define PETSC_RELEASE_GREATER_THAN(major, minor, subminor) \
+  (0 == PETSC_VERSION_LESS_EQUALS(major, minor, subminor) && LIBMESH_DETECTED_PETSC_VERSION_RELEASE)
+
 #else
 
 #define PETSC_RELEASE_LESS_THAN(major, minor, subminor) \
   (PETSC_VERSION_LESS_THAN(major, minor, subminor))
 #define PETSC_RELEASE_EQUALS(major, minor, subminor) (PETSC_VERSION_EQUALS(major, minor, subminor))
 
-#endif
-
 #define PETSC_RELEASE_LESS_EQUALS(major, minor, subminor) \
   (PETSC_RELEASE_LESS_THAN(major, minor, subminor) || PETSC_RELEASE_EQUALS(major, minor, subminor))
 
@@ -263,4 +271,7 @@ const PetscReal * pPR(const T * ptr)
 #define PETSC_RELEASE_GREATER_THAN(major, minor, subminor) \
   (0 == PETSC_RELEASE_LESS_EQUALS(major, minor, subminor))
 
+#endif
+
+
 #endif // LIBMESH_PETSC_MACRO_H
````
but I'd guess there is some case which I'd treat incorrect this way?

**Comment by lindsayad** [comment]
These new macros match the macros from petsc themselves. In the words of @jedbrown:

> You're not supposed to use no-release versions [of PETSc] after their lifetime is over. Versions aren't even linearly ordered in between releases.
>
> To clarify, the intent is that people use these version macros with main to test in anticipation of the next release, not as an ad-hoc long-term-support snapshot. Once a release comes out, use it or keep riding main's bleeding edge.

**Comment by lindsayad** [comment]
In my own words: use a release or use `main`

**Comment by BalticPinguin** [comment]
thank you @lindsayad for the answer.
I completely understand the point (and wasn't aware of it before). I just wasn't used to update my complete software-stack, and seemingly it was just by luck that I didn't have such issues before :-)

**Comment by lindsayad** [comment]
I was flummoxed by the PETSc macros myself at first, and only after complaining about them and having Jed explain the rationale did I accept them haha
