### ISSUE TITLE
Support mixed-order meshes in `find_neighbors()`, `stitch_meshes()`

### ISSUE THREAD

**Issue by roystgnr** [libMesh/libmesh#3738]
While working on the unit tests for #3706 I ran into an issue: a mixed-order mesh is currently a very fragile thing to play with, because `UnstructuredMesh::find_neighbors()` treats mixed-order neighbors as **non**-neighbors - the higher order element has more nodes on their shared side, those additional nodes create a different `elem.key(side)`, and those different keys don't get recognized as a side that should be shared.  `UnstructuredMesh::stitch_meshes()` has the same problem: it will happily handle merging of nodes along mixed-order shared sides, but then when it comes time to create the `neighbor_ptr()` links between those sides it'll use `key()` on each and fail to recognize the identity there.

I'm thinking this might be as easy to fix as creating a `low_order_key()` (to preserve the existing API's behavior) that only considers vertices, not mid-edge or mid-face nodes, and then using that instead in these two places.

Pinging @eshemon and @miaoyinb so they can keep track of progress here too.  IMHO they shouldn't wait on this before beginning to upgrade mesh generators to second-order, though; the inadequacy here only affects stitched-together mixed-order compositions, and it ought to be possible to make a lot of progress even while stuck only doing single-component-level testing.

**Comment by lindsayad** [comment]
@roystgnr if this is NEAMS work, please add it to the NEAMS project. Now that we've discovered we can add libMesh issues/pulls it would be great to keep those tracked in the same project as MOOSE tickets
