### ISSUE TITLE
make error src/base/libmesh_opt_la-libmesh.lo error 1

### ISSUE THREAD

**Issue by GreatPastafarian** [libMesh/libmesh#3893]
An error occurs when applying make and make check. The source code is synchronized via git clone. Further actions were according to the instructions. Build error logs and configuration file below
Makefile:1047: warning: Dependencies for defining a suffix rule are ignored
Makefile:1047: warning: Dependencies for defining a suffix rule are ignored
Makefile:1723: warning: Dependencies for defining a suffix rule are ignored
Makefile:1723: warning: Dependencies for defining a suffix rule are ignored
In file included from /opt/petsc/linux-c-opt/include/petscsys.h:65,
                 from /opt/petsc/linux-c-opt/include/petscbag.h:3,
                 from /opt/petsc/linux-c-opt/include/petsc.h:6,
                 from ./include/libmesh/petsc_macro.h:56,
                 from src/base/libmesh.C:69:
src/base/libmesh.C: In constructor 'libMesh::LibMeshInit::LibMeshInit(int, const char* const*, TIMPI::communicator, int)':
/opt/petsc/linux-c-opt/include/petscsys.h:276:25: error: invalid conversion from 'MPI_Comm' {aka 'ompi_communicator_t*'} to 'TIMPI::communicator' {aka 'int'} [-fpermissive]
  276 | #define PETSC_COMM_SELF MPI_COMM_SELF
      |                         ^~~~~~~~~~~~~
      |                         |
      |                         MPI_Comm {aka ompi_communicator_t*}
src/base/libmesh.C:490:28: note: in expansion of macro 'PETSC_COMM_SELF'
  490 |       this->_comm->get() = PETSC_COMM_SELF;
      |                            ^~~~~~~~~~~~~~~
In file included from /opt/petsc/linux-c-opt/include/petscsys.h:1124:
src/base/libmesh.C:497:28: error: invalid conversion from 'int' to 'MPI_Comm' {aka 'ompi_communicator_t*'} [-fpermissive]
  497 |       CHKERRABORT(libMesh::GLOBAL_COMM_WORLD,ierr);
      |                   ~~~~~~~~~^~~~~~~~~~~~~~~~~
      |                            |
      |                            int
/opt/petsc/linux-c-opt/include/petscerror.h:719:25: note: in definition of macro 'PetscCallAbort'
  719 |         (void)MPI_Abort(comm, (PetscMPIInt)ierr_petsc_call_abort_); \
      |                         ^~~~
src/base/libmesh.C:497:7: note: in expansion of macro 'CHKERRABORT'
  497 |       CHKERRABORT(libMesh::GLOBAL_COMM_WORLD,ierr);
      |       ^~~~~~~~~~~
/usr/include/mpi.h:1388:39: note:   initializing argument 1 of 'int MPI_Abort(MPI_Comm, int)'
 1388 | OMPI_DECLSPEC  int MPI_Abort(MPI_Comm comm, int errorcode);
      |                              ~~~~~~~~~^~~~
src/base/libmesh.C:517:32: error: invalid conversion from 'int' to 'MPI_Comm' {aka 'ompi_communicator_t*'} [-fpermissive]
  517 |           CHKERRABORT(libMesh::GLOBAL_COMM_WORLD,ierr);
      |                       ~~~~~~~~~^~~~~~~~~~~~~~~~~
      |                                |
      |                                int
/opt/petsc/linux-c-opt/include/petscerror.h:719:25: note: in definition of macro 'PetscCallAbort'
  719 |         (void)MPI_Abort(comm, (PetscMPIInt)ierr_petsc_call_abort_); \
      |                         ^~~~
src/base/libmesh.C:517:11: note: in expansion of macro 'CHKERRABORT'
  517 |           CHKERRABORT(libMesh::GLOBAL_COMM_WORLD,ierr);
      |           ^~~~~~~~~~~
/usr/include/mpi.h:1388:39: note:   initializing argument 1 of 'int MPI_Abort(MPI_Comm, int)'
 1388 | OMPI_DECLSPEC  int MPI_Abort(MPI_Comm comm, int errorcode);
      |                              ~~~~~~~~~^~~~
src/base/libmesh.C:521:76: error: invalid conversion from 'int' to 'MPI_Comm' {aka 'ompi_communicator_t*'} [-fpermissive]
  521 |       ierr = DMRegister(DMLIBMESH, DMCreate_libMesh); CHKERRABORT(libMesh::GLOBAL_COMM_WORLD,ierr);
      |                                                                   ~~~~~~~~~^~~~~~~~~~~~~~~~~
      |                                                                            |
      |                                                                            int
/opt/petsc/linux-c-opt/include/petscerror.h:719:25: note: in definition of macro 'PetscCallAbort'
  719 |         (void)MPI_Abort(comm, (PetscMPIInt)ierr_petsc_call_abort_); \
      |                         ^~~~
src/base/libmesh.C:521:55: note: in expansion of macro 'CHKERRABORT'
  521 |       ierr = DMRegister(DMLIBMESH, DMCreate_libMesh); CHKERRABORT(libMesh::GLOBAL_COMM_WORLD,ierr);
      |                                                       ^~~~~~~~~~~
/usr/include/mpi.h:1388:39: note:   initializing argument 1 of 'int MPI_Abort(MPI_Comm, int)'
 1388 | OMPI_DECLSPEC  int MPI_Abort(MPI_Comm comm, int errorcode);
      |                              ~~~~~~~~~^~~~
src/base/libmesh.C: In destructor 'virtual libMesh::LibMeshInit::~LibMeshInit()':
src/base/libmesh.C:777:30: error: invalid conversion from 'int' to 'MPI_Comm' {aka 'ompi_communicator_t*'} [-fpermissive]
  777 |         CHKERRABORT(libMesh::GLOBAL_COMM_WORLD, ierr);
      |                     ~~~~~~~~~^~~~~~~~~~~~~~~~~
      |                              |
      |                              int
/opt/petsc/linux-c-opt/include/petscerror.h:719:25: note: in definition of macro 'PetscCallAbort'
  719 |         (void)MPI_Abort(comm, (PetscMPIInt)ierr_petsc_call_abort_); \
      |                         ^~~~
src/base/libmesh.C:777:9: note: in expansion of macro 'CHKERRABORT'
  777 |         CHKERRABORT(libMesh::GLOBAL_COMM_WORLD, ierr);
      |         ^~~~~~~~~~~
/usr/include/mpi.h:1388:39: note:   initializing argument 1 of 'int MPI_Abort(MPI_Comm, int)'
 1388 | OMPI_DECLSPEC  int MPI_Abort(MPI_Comm comm, int errorcode);
      |                              ~~~~~~~~~^~~~
src/base/libmesh.C:781:34: error: invalid conversion from 'int' to 'MPI_Comm' {aka 'ompi_communicator_t*'} [-fpermissive]
  781 |             CHKERRABORT(libMesh::GLOBAL_COMM_WORLD, ierr);
      |                         ~~~~~~~~~^~~~~~~~~~~~~~~~~
      |                                  |
      |                                  int
/opt/petsc/linux-c-opt/include/petscerror.h:719:25: note: in definition of macro 'PetscCallAbort'
  719 |         (void)MPI_Abort(comm, (PetscMPIInt)ierr_petsc_call_abort_); \
      |                         ^~~~
src/base/libmesh.C:781:13: note: in expansion of macro 'CHKERRABORT'
  781 |             CHKERRABORT(libMesh::GLOBAL_COMM_WORLD, ierr);
      |             ^~~~~~~~~~~
/usr/include/mpi.h:1388:39: note:   initializing argument 1 of 'int MPI_Abort(MPI_Comm, int)'
 1388 | OMPI_DECLSPEC  int MPI_Abort(MPI_Comm comm, int errorcode);
      |                              ~~~~~~~~~^~~~
src/base/libmesh.C:800:28: error: invalid conversion from 'int' to 'MPI_Comm' {aka 'ompi_communicator_t*'} [-fpermissive]
  800 |       CHKERRABORT(libMesh::GLOBAL_COMM_WORLD, ierr);
      |                   ~~~~~~~~~^~~~~~~~~~~~~~~~~
      |                            |
      |                            int
/opt/petsc/linux-c-opt/include/petscerror.h:719:25: note: in definition of macro 'PetscCallAbort'
  719 |         (void)MPI_Abort(comm, (PetscMPIInt)ierr_petsc_call_abort_); \
      |                         ^~~~
src/base/libmesh.C:800:7: note: in expansion of macro 'CHKERRABORT'
  800 |       CHKERRABORT(libMesh::GLOBAL_COMM_WORLD, ierr);
      |       ^~~~~~~~~~~
/usr/include/mpi.h:1388:39: note:   initializing argument 1 of 'int MPI_Abort(MPI_Comm, int)'
 1388 | OMPI_DECLSPEC  int MPI_Abort(MPI_Comm comm, int errorcode);
      |                              ~~~~~~~~~^~~~
make[1]: *** [Makefile:26520: src/base/libmesh_opt_la-libmesh.lo] Error 1
make: *** [Makefile:33743: all-recursive] Error 1
[config.log](https://github.com/user-attachments/files/16042109/config.log)

I use the manjaro system, which also supports installation from AUR. The alternative installation path leads to the error shown below. How to fix these errors and which installation method is preferable for use with openmc?
==> Making package: libmesh cpp03_final.r6839.g3e858a733-1 (Sat Jun 29 23:28:34 2024)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Updating libmesh git repo...
==> Validating source files with sha256sums...
    libmesh ... Skipped
==> Extracting sources...
  -> Creating working copy of libmesh git repo...
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (en_IE.UTF-8)
Switched to a new branch 'makepkg'
==> Starting prepare()...
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (en_IE.UTF-8)
Synchronizing submodule url for 'contrib/eigen/git'
Synchronizing submodule url for 'contrib/metaphysicl'
Synchronizing submodule url for 'contrib/nanoflann/nanoflann'
Synchronizing submodule url for 'contrib/netcdf/netcdf-c'
Synchronizing submodule url for 'contrib/poly2tri/poly2tri'
Synchronizing submodule url for 'contrib/timpi'
Synchronizing submodule url for 'm4/autoconf-submodule'
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (en_IE.UTF-8)
patch: **** Can't open patch file /home/vasilisiy/libmesh-petsc/src/netcdf.m4.patch : No such file or directory
==> ERROR: A failure occurred in prepare().
    Aborting...

**Comment by GreatPastafarian** [comment]
P.s. The make problem was solved when replacing from Petsc to Petsc-git from AUR

**Comment by roystgnr** [comment]
Thanks for the update; my apologies that nobody responded to you earlier.  I really ought to make sure my vacation dates aren't synched up with John's...
