### ISSUE TITLE
Assertion Failure in ExodusIO when reading TRI3 mesh

### ISSUE THREAD

**Issue by pbauman** [libMesh/libmesh#408]
Email me for the file if you want it - 6 elements.

I'm just meshing a circle in CUBIT (Trelis, whatever) using triangles (yes, I can use quads, yes I know I can generate a circle other ways - this is for testing/debugging before moving to more complex manifolds that may be possibly meshed with triangles).

Assertion failure is from get_side_map (it's getting called with 4 and side_map_size is 3). I'm going to try and dig into this, but was hoping someone else might've hit something similar to help accelerate things.

**Comment by jwpeterson** [comment]
I think this turned out to be a Cubit issue, but if it turns out there's something we can fix in libmesh's Exodus reader, please re-open.

**Comment by pbauman** [comment]
Sorry, I got derailed off this discussion with the csimsoft guys, but the current TL;DR from them is: There's no such thing as a 3D TRI3 - TRI3 is 2D and if 3D it's a shell. Which is entirely inconsistent with how they treat quads (or at least Cubit). So I still have to follow up with them. If that's the case, we might need to update the Exodus reader.
