### ISSUE TITLE
Several DofObject methods are O(n_var_groups)

### ISSUE THREAD

**Issue by roystgnr** [libMesh/libmesh#418]
Where they used to be O(1).

Obviously the variable groups refactoring was a big win for memory use, but there's a CPU cost that seems to show up in the n_var_groups>>1 case.  I'm trying to quantify the problem, but short of "give every DofObject a pointer to the DofMap" I can't figure out how to fix it.

**Comment by benkirk** [comment]
Definitely wasn't expecting n_var_groups>>1: what's >>1 exactly, and can it be addressed by reordering the variables to allow more variable groups to be identified?

**Comment by friedmud** [comment]
Interesting idea about reordering.  We could definitely reorder in MOOSE
before adding the variables to the system.  If that's the case then it's
hard to think of a scenario with more than about 4 or so groups... but of
course it is pathologically possible...

Derek

On Tuesday, January 13, 2015, Benjamin S. Kirk <notifications@github.com>
wrote:

> Definitely wasn't expecting n_var_groups>>1: what's >>1 exactly, and can
> it be addressed by reordering the variables to allow more variable groups
> to be identified?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/libMesh/libmesh/issues/418#issuecomment-69762282>.
>


-- 
Sent from my iPhone

**Comment by benkirk** [comment]
yep, of course the pathological possibility...

My expectation is that the n_var_groups would necessarily be <= # of FE families, which should be reasonable even for huge numbers of variables.  But yeah that breaks if the variables are added in an order that doesn't allow the 'packing'

The System could perhaps do a reordering internally to maximize the efficiency, but that's a fair amount of code and could be error prone, so if reordering the definition is possible that'd be great.

**Comment by roystgnr** [comment]
A System reordering option would be cool.  Is it really a fair amount of code?  I suspect "delete all variables and cache info about them in a local variable, then sort the local variable, then add them back" would do it.

**Comment by friedmud** [comment]
System reordering would kind of break some stuff though... because
add_variable() returns the variable number... so if people are depending on
that then you can't change it in the background.

I'd be all for automatic reordering though.  It would just also imply some
API changes...

Derek

**Comment by roystgnr** [comment]
Never mind me, then; Derek is right about us having to respect the add_variable() return value.  Off the top of my head I can't think of an efficient way to fix that without just as much app-level code as app-level reordering would require.

**Comment by pbauman** [comment]
Admittedly I haven't looked at the code, but why can't we do the O(n_groups) work when we `add_variable()`? If we do a search for an existing group and drop the variable in there, that'll be O(n_vars*log(n_groups)), but we only do it once at the beginning. Surely that can't be too painful?

**Comment by friedmud** [comment]
Because dof indexing is related to the variable number... and the variable
numbers are assigned at the point you call add_variable()

**Comment by roystgnr** [comment]
We currently assume that variable numbers within a group are contiguous, right?  Not sure how easy that would be to change, but we'd need to change it if we wanted to add variable N to any but the last variable group in the system.

**Comment by pbauman** [comment]
> We currently assume that variable numbers within a group are contiguous, right?

Derp, of course. Never mind, sorry.

**Comment by roystgnr** [comment]
Should we close this?  It looks like there's no room for further improvement without either reordering variables (which needs to be done at app level) or allowing discontiguous variable numbers (which might be an optimization in some cases but would almost certainly be a pessimization in others).
