### ISSUE TITLE
Adding new elements can cause old DOF indices errors

### ISSUE THREAD

**Issue by permcody** [libMesh/libmesh#435]
Working on his XFEM implementation, @bwspenc has seen cases where he receives error when adding new elements to the mesh.

@bwspenc - please provide more details or test cases for this issue.

**Comment by jwpeterson** [comment]
Related to #272

**Comment by jwpeterson** [comment]
I believe this very simple test code by Vasileios Vavourakis demonstrates the issue.

```
#include "libmesh/mesh.h"
#include "libmesh/equation_systems.h"
#include "libmesh/mesh_generation.h"

// Bring in the libmesh namespace
using namespace libMesh;

int main (int argc, char* argv[])
{
  LibMeshInit init(argc, argv);

  Mesh msh(init.comm(), 1);
  EquationSystems es(msh);

  es.add_system<System>("a_system");
  es.get_system<System>("a_system").add_variable("a_variable");

  MeshTools::Generation::build_line (msh, 10, 0., 1., EDGE2);
  msh.prepare_for_use();
  msh.print_info();
  msh.boundary_info->print_info();

  es.init();
  es.print_info();

  {
    Elem* e = Elem::build(EDGE2).release();
    e->set_id(msh.max_elem_id());
    e->set_node(0) = msh.node_ptr(2);
    e->set_node(1) = msh.node_ptr(8);
    msh.add_elem(e);
    msh.prepare_for_use();
    msh.print_info();
    msh.boundary_info->print_info();

    es.reinit();
    es.print_info();
  }

  return 0;
}
```

**Comment by roystgnr** [comment]
Yes, this works (by which I mean fails to work) perfectly.  Once I've got the library working with it I'll probably just add a ```e->processor_id() = 0;``` to get ParallelMesh compatibility and toss it wholesale into the unit tests.

**Comment by roystgnr** [comment]
This should be ready for @bwspenc to test; either it's working as of #559 or I'll need a more intricate test case to catch any deeper problems.

**Comment by bwspenc** [comment]
@roystgnr Sorry I haven't been really helpful here.  I'm in some meetings this week.  I'll try your fix out in the next day or so. Thanks for looking into this.

**Comment by bwspenc** [comment]
@roystgnr I just had a chance to test this, and it resolved my problems.  I can add and delete elements with no issues now. Thanks a ton for working on this! I'm super excited that this is working correctly now. Sorry I haven't been more helpful with providing you examples -- I've just been pulled a lot of directions lately. You can close this issue.

@permcody Now that this has been resolved, I need to sit down with you, look through my code, and figure out a plan for how it should be integrated into MOOSE. I won't have time until at least May 26th. In the mean-time, if you're curious and want to look at it, it's sitting on the xfem_phantom branch of my MOOSE fork.

**Comment by roystgnr** [comment]
@bwspenc Thanks for the testing!  I'll close this; feel free to reopen if further issues come up.
