### ISSUE TITLE
--disable-mpi fails with triangle support

### ISSUE THREAD

**Issue by rvetter** [libMesh/libmesh#483]
When configuring with --disable-strict-lgpl (for triangle support) and --disable-mpi, compilation fails with src/geom/elem_cutter.C:43:49: error: 'MPI_COMM_SELF' was not declared in this scope. It seems that this part of the code is not properly #ifdef'd.

**Comment by roystgnr** [comment]
Give that PR a try?  Thanks for catching this!

**Comment by rvetter** [comment]
Works for me, thanks.
