### ISSUE TITLE
Fix issue with --with-metis=PETSc

### ISSUE THREAD

**Issue by jwpeterson** [libMesh/libmesh#498]
As reported by @manavbhatia, apparently we are still passing contrib/metis include paths to the compiler when `--with-metis=PETSc` is specified, leading to inconsistent header file/linking situations.

**Comment by jwpeterson** [comment]
The problem is definitely in metis.m4.  We add the headers to the include paths if $enablemetis = yes, which is true whether or not Metis comes from PETSc.  @manavbhatia are the Metis/Parmetis headers installed by PETSc in $PETSC_DIR/include by any chance?

```
  dnl The METIS API is distributed with libmesh, so we don't have to guess
  dnl where it might be installed...
  if (test $enablemetis = yes); then
     METIS_INCLUDE="-I\$(top_srcdir)/contrib/metis/include"
     METIS_LIB="\$(EXTERNAL_LIBDIR)/libmetis\$(libext) \$(EXTERNAL_LIBDIR)/libGK\$(libext)"
     AC_DEFINE(HAVE_METIS, 1, [Flag indicating whether the library will be compiled with Metis support])
     AC_MSG_RESULT(<<< Configuring library with Metis support >>>)

     dnl look for thread-local storage
     AX_TLS
 else
     METIS_INCLUDE=""
     METIS_LIB=""
     enablemetis=no
  fi
```

**Comment by manavbhatia** [comment]
Yes, they are both in $PETSC_DIR/include

-Manav

On Fri, Mar 13, 2015 at 12:39 PM, John W. Peterson <notifications@github.com

**Comment by jwpeterson** [comment]
@manavbhatia would you mind trying out the [metis_m4](https://github.com/libMesh/libmesh/tree/metis_m4) branch, and see if that fixes the issue for you?

**Comment by dschwen** [comment]
I just encountered an issue where contrib/metis keeps getting used despite the `--with-metis=PETSc` option. Might be a separate issue though (I'm building with only distribution packages from Ubuntu 19.10, petsc-dev libmetis-dev etc.). Right now I can only build with` --disable-metis`

**Comment by jwpeterson** [comment]
What is the error message exactly? Note that in bcf8df72742aad48b892bd70f9af94d8725fc99d @roystgnr changed the conditions under which metis.h gets installed so if you are seeing a locally installed metis.h maybe it is related to that.
