### ISSUE TITLE
error building with VTK-6.2 from homebrew

### ISSUE THREAD

**Issue by canesin** [libMesh/libmesh#512]
Using a fresh OSX install with homebrew vtk:

checking /usr/local/opt/vtk/include/vtk-6.2/vtkConfigure.h usability... yes
checking /usr/local/opt/vtk/include/vtk-6.2/vtkConfigure.h presence... yes
checking for /usr/local/opt/vtk/include/vtk-6.2/vtkConfigure.h... yes
<<< Configuring library without VTK support >>>

args: --with-vtk-include=$VTK_INCLUDE --with-vtk-lib=/usr/local/opt/vtk/lib

**Comment by jwpeterson** [comment]
> On Mar 27, 2015, at 6:48 PM, Fábio César Canesin <notifications@github.com> wrote:
> 
> Using a fresh OSX install with homebrew vtk:
> 
> checking /usr/local/opt/vtk/include/vtk-6.2/vtkConfigure.h usability... yes
> checking /usr/local/opt/vtk/include/vtk-6.2/vtkConfigure.h presence... yes
> checking for /usr/local/opt/vtk/include/vtk-6.2/vtkConfigure.h... yes
> <<< Configuring library without VTK support >>>
> 
> args: --with-vtk-include=$VTK_INCLUDE --with-vtk-lib=/usr/local/opt/vtk/lib
> 

Something failed to link.  There's probably more info in config.log...

**Comment by canesin** [comment]
Undefined symbols for architecture x86_64:
  "vtkXMLPUnstructuredGridWriter::New()", referenced from:
      vtkSmartPointer<vtkXMLPUnstructuredGridWriter>::New() in conftest-eefd1e.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
configure:33968: $? = 1
configure: failed program was:
| /* confdefs.h */

**Comment by jwpeterson** [comment]
In VTK-6.1, vtkXMLPUnstructuredGridWriter::New() seems to have been in libvtkIOXML-6.1.dylib.

For example, I ran:
```
for i in /opt/moose/vtk-6.1/lib/*.dylib; do echo $i; nm $i | grep vtkXMLPUnstructuredGridWriter; done
```

And it printed (arrow marks added for emphasis):
```
/opt/moose/vtk-6.1/lib/libvtkIOXML-6.1.dylib
000000000006af90 t __Z47vtkInstantiatorvtkXMLPUnstructuredGridWriterNewv
000000000006b0d0 T __ZN29vtkXMLPUnstructuredGridWriter14GetDataSetNameEv
000000000006b0f0 T __ZN29vtkXMLPUnstructuredGridWriter23GetDefaultFileExtensionEv
000000000006b180 T __ZN29vtkXMLPUnstructuredGridWriter24FillInputPortInformationEiP14vtkInformation
000000000006b110 T __ZN29vtkXMLPUnstructuredGridWriter29CreateUnstructuredPieceWriterEv
000000000006b1f0 t __ZN29vtkXMLPUnstructuredGridWriter3IsAEPKc
==> 000000000006af10 T __ZN29vtkXMLPUnstructuredGridWriter3NewEv
000000000006b0b0 T __ZN29vtkXMLPUnstructuredGridWriter8GetInputEv
000000000006b230 t __ZN29vtkXMLPUnstructuredGridWriter8IsTypeOfEPKc
000000000006b070 T __ZN29vtkXMLPUnstructuredGridWriter9PrintSelfERNSt3__113basic_ostreamIcNS0_11char_traitsIcEEEE9vtkIndent
000000000006af70 T __ZN29vtkXMLPUnstructuredGridWriterC1Ev
000000000006afa0 T __ZN29vtkXMLPUnstructuredGridWriterC2Ev
000000000006b020 T __ZN29vtkXMLPUnstructuredGridWriterD0Ev
000000000006b000 T __ZN29vtkXMLPUnstructuredGridWriterD1Ev
000000000006afe0 T __ZN29vtkXMLPUnstructuredGridWriterD2Ev
000000000006b210 t __ZNK29vtkXMLPUnstructuredGridWriter19NewInstanceInternalEv
000000000006b1d0 t __ZNK29vtkXMLPUnstructuredGridWriter20GetClassNameInternalEv
00000000000e5000 S __ZTI29vtkXMLPUnstructuredGridWriter
00000000000d79e0 S __ZTS29vtkXMLPUnstructuredGridWriter
00000000000e4bd0 S __ZTV29vtkXMLPUnstructuredGridWriter
```

So, either VTK-6.2 changed the organization of the libs (again, after just changing them in 6.1) or maybe homebrew vtk's build is slightly non-standard?  If you could let me know where the symbol in question is found in your VTK, that would be helpful.

**Comment by jwpeterson** [comment]
> So, either VTK-6.2 changed the organization of the libs (again, after just changing them in 6.1)

Yes, that's what they did, the function in question is in libvtkIOParallelXML-6.2.dylib:
```
/opt/moose/vtk-6.2/lib/libvtkIOParallelXML-6.2.dylib
000000000001f380 T __ZN29vtkXMLPUnstructuredGridWriter14GetDataSetNameEv
000000000001f3a0 T __ZN29vtkXMLPUnstructuredGridWriter23GetDefaultFileExtensionEv
000000000001f430 T __ZN29vtkXMLPUnstructuredGridWriter24FillInputPortInformationEiP14vtkInformation
000000000001f3c0 T __ZN29vtkXMLPUnstructuredGridWriter29CreateUnstructuredPieceWriterEv
000000000001f4a0 t __ZN29vtkXMLPUnstructuredGridWriter3IsAEPKc
==> 000000000001f1d0 T __ZN29vtkXMLPUnstructuredGridWriter3NewEv
000000000001f360 T __ZN29vtkXMLPUnstructuredGridWriter8GetInputEv
000000000001f4e0 t __ZN29vtkXMLPUnstructuredGridWriter8IsTypeOfEPKc
000000000001f320 T __ZN29vtkXMLPUnstructuredGridWriter9PrintSelfERNSt3__113basic_ostreamIcNS0_11char_traitsIcEEEE9vtkIndent
000000000001f230 T __ZN29vtkXMLPUnstructuredGridWriterC1Ev
000000000001f250 T __ZN29vtkXMLPUnstructuredGridWriterC2Ev
000000000001f2d0 T __ZN29vtkXMLPUnstructuredGridWriterD0Ev
000000000001f2b0 T __ZN29vtkXMLPUnstructuredGridWriterD1Ev
000000000001f290 T __ZN29vtkXMLPUnstructuredGridWriterD2Ev
000000000001f4c0 t __ZNK29vtkXMLPUnstructuredGridWriter19NewInstanceInternalEv
000000000001f480 t __ZNK29vtkXMLPUnstructuredGridWriter20GetClassNameInternalEv
000000000002bd20 S __ZTI29vtkXMLPUnstructuredGridWriter
00000000000285e0 S __ZTS29vtkXMLPUnstructuredGridWriter
000000000002b8b0 S __ZTV29vtkXMLPUnstructuredGridWriter
```

We'll have to update vtk.m4 to fix this...
