### ISSUE TITLE
AMG preconditioning options are not passed from command-line options

### ISSUE THREAD

**Issue by YaqiWang** [libMesh/libmesh#546]
If you check out https://github.com/libMesh/libmesh/blob/master/src/numerics/petsc_preconditioner.C Line 252 to 258, you will see that the options for AMG is intentionally bypassed. Is there a particular reason for it? I'd like to remove that if statement because I want to pass some extra BoomerAMG options to the preconditioner through with my MOOSE app. For example, `-pc_hypre_boomeramg_print_statistics`. Thanks.

**Comment by jwpeterson** [comment]
Hmm... I found the commit where that line was added in SVN, but I don't remember why I did it.  I'd say it could probably be removed.

```
------------------------------------------------------------------------
r4798 | jwpeterson | 2011-08-11 16:08:46 -0600 (Thu, 11 Aug 2011) | 2 lines
Changed paths:
   M /trunk/libmesh/include/numerics/petsc_preconditioner.h
   M /trunk/libmesh/src/numerics/petsc_preconditioner.C

Requesting ILU/LU in parallel on the PetscPreconditioner now
sets block Jacobi parallel preconditioner + ILU/LU sub-preconditioner.
------------------------------------------------------------------------
```

**Comment by jwpeterson** [comment]
@YaqiWang did you try removing this to see if it allows you to pass Hypre flags on the command line?

**Comment by YaqiWang** [comment]
Yes, I did. It does. I believe you can use PhysicsBasedPreconditioner to try this out.

**Comment by jwpeterson** [comment]
OK, I will see if I can sneak that into the next libmesh update.
