### ISSUE TITLE
Add method to query field type for variable in ExodusII_IO

### ISSUE THREAD

**Issue by permcody** [libMesh/libmesh#551]
Have ExodusII_IO report back whether a field is elemental or nodal based on a variable name.
See https://github.com/idaholab/moose/issues/4974

Low Priority

**Comment by jwpeterson** [comment]
We currently expose vectors containing the elemental and nodal variables names in ExodusII_IO:
```
  const std::vector<std::string> & get_elem_var_names();
  const std::vector<std::string> & get_nodal_var_names();
```
that should be all you need.

**Comment by permcody** [comment]
Great thanks, I missed that. Closing...
