### ISSUE TITLE
echo -n is not POSIX

### ISSUE THREAD

**Issue by jwpeterson** [libMesh/libmesh#575]
http://www.etalabs.net/sh_tricks.html

Looks like 63873cf4 introduced an issue with some shells which causes them to print -n to the terminal.  A possible workaround is to use the printf shell built-in.  Reported by @karpeev.

**Comment by roystgnr** [comment]
Gah!  I remember trying to check if "-n" was POSIX, but I foolishly just checked it in dash rather than going to the standards.

printf is indeed the recommended solution.  http://pubs.opengroup.org/onlinepubs/007904875/utilities/printf.html
