### ISSUE TITLE
fem_system_ex3 is a bit too slow in DEBUG mode

### ISSUE THREAD

**Issue by jwpeterson** [libMesh/libmesh#599]
Since Moosebuild runs make check in this mode, this affects all PRs. The simplest way to speed it up is probably to reduce the number of timesteps from 25 to 5 if @pbauman is OK with that...

```
n_timesteps = 25
dbg mode: 219.59
opt mode: 14.50
```

```
n_timesteps = 5
dbg mode: 51.73
opt mode: 3.52
```

**Comment by pbauman** [comment]
Oiy, sorry. I think I only ran in devel model when I built that. 5 steps should be fine. It's easy enough for the user to change it, but the main thing I was going for was to show out of the box there was no numerical dissipation (25 steps went though about 3 periods of oscillation) if the user took a look at the results.

**Comment by jwpeterson** [comment]
I'll put a comment to that effect in the input file.
