### ISSUE TITLE
PetscMatrix::update_preallocation_and_zero () needs update

### ISSUE THREAD

**Issue by dknez** [libMesh/libmesh#605]
I guess the PETSc fix required for PetscMatrix::update_preallocation_and_zero () is now available in PETSc-3.6?

**Comment by jwpeterson** [comment]
I'm afraid not, the commit is petsc/petsc@cfb96d2, `git tag --contains cfb96d2` doesn't show it in 3.6.

**Comment by dknez** [comment]
ok, thanks for checking... feel free to close this issue then, or whatever you prefer.

**Comment by jwpeterson** [comment]
@karpeev what's up with your `mat-reset` branch in PETSc?  It doesn't appear to be merged anywhere...

**Comment by dknez** [comment]
@karpeev, it looks like this petsc branch was declined in April, is that right?

https://bitbucket.org/petsc/petsc/pull-requests/269/matreset-keeps-mattype-comm-sizes-but/activity

**Comment by karpeev** [comment]
Yes, we decided to do it differently (a "deeper" mat-type specific reset,
but we haven't gotten around to it yet). I will finally be back in Chicago
and at work next Monday and we can talk about how to proceed there. It just
needs some time put into it.

**Comment by dknez** [comment]
OK, cool, thanks for the update. I was just curious :)

**Comment by jwpeterson** [comment]
@dknez I'm not sure if this issue with `update_preallocation_and_zero()` will ever be fixed... 

@karpeev moved on from PETSc development quite some time ago, maybe he knows if someone else ever picked up the thread?

In any case, the guards which restrict the code to PETSc >= 3.5.0 are probably outdated.  Perhaps we should just throw an error from that function regardless of PETSc version?

**Comment by dknez** [comment]
OK, thanks for the update on this. We can just remove update_preallocation_and_zero() from PetscMatrix, if you like... we don't use it in the examples anymore. Also, perhaps it's better to just allocate a new PetscMatrix with a new nonzero pattern rather than trying to update an existing one, it seems like that's the easier approach.

**Comment by jwpeterson** [comment]
> We can just remove update_preallocation_and_zero() from PetscMatrix, if you like...

OK, I will do that.
