### ISSUE TITLE
automatic connect in figure

### ISSUE THREAD

**Issue by nemati456** [libMesh/libmesh#609]
hi!
I have a problem with tecplot
I want to plot 2 separate circule in one figure but.......
tecplot connect last node of first to first node of second circle automatically.
Its make problem for my other work
in the second figure this connect is between airfoil and circle
this is the code(or attached file)
with regad!

implicit none
integer::i,j
real::r1,teta,r2,r
real,dimension(0:361,2):: x, y
r1=2
r2=5

do j=1,2
teta=0
if(j==1)then
r=r1
j=1
else
r=r2
end if
do i=0,360
x(i,j)=rcos(teta)
y(i,j)=rsin(teta)
teta=3.1415/180+teta
!print*,i,teta,x(i,j)
end do
end do

OPEN(UNIT=10,FILE='RESULT circle.PLT')
WRITE(10,)'VARIABLES="X","Y"' 
WRITE(10,)'ZONE I=',361*2,'F=POINT'
do j=1,2

do i=0,360

WRITE(10,*)x(i,j),y(i,j)
END DO 
enddo

close(10)

end

![eliptic](https://cloud.githubusercontent.com/assets/12984799/8296830/fcf2db92-196a-11e5-8428-e585bd82c16b.jpg)
![export](https://cloud.githubusercontent.com/assets/12984799/8296831/fd2b6584-196a-11e5-879b-21f76a00b34f.jpg)

**Comment by canesin** [comment]
Virus spamming on github, this is a new.

**Comment by roystgnr** [comment]
This is a tecplot issue, not a libMesh issue, and definitely not a spam-half-a-dozen-unconnected-projects issue.
