### ISSUE TITLE
Xdr::is_eof() forget precompiler "#ifdef LIBMESH_HAVE_XDR" 

### ISSUE THREAD

**Issue by lw4992** [libMesh/libmesh#638]
The new member function, `is_eof` of class Xdr in libmesh\src\utils\xdr_cxx.C, forgot precompiler "#ifdef LIBMESH_HAVE_XDR", it may caused "undeclared fp" error in line 406.

**Comment by roystgnr** [comment]
Let me know if #639 works for you?  Thanks.

**Comment by lw4992** [comment]
Yes. I would close this issue.

**Comment by lw4992** [comment]
Yes. I would close this issue.
