### ISSUE TITLE
Add libmesh_cxx11 macros and functions

### ISSUE THREAD

**Issue by roystgnr** [libMesh/libmesh#655]
In cases where std::move(x) would leave more efficient code but where (x) would work, we should have a libmesh_move(x) inline function that compiles to the former when available and the latter otherwise.  Likewise for std::forward().

The "final" and "override" keywords are useful for efficiency and compile-time error checking, respectively, but they can be safely omitted too; we should have libmesh_final and libmesh_override macros that disappear when using C++98 but give us the C++11 features when they're supported.

We should eventually do the same with noexcept/throw().  Maybe with constexpr (we can't safely use that in C++98, but we can declare with it so that C++11 user code can take advantage).  Possibly with nullptr (or is that too risky due to differing overload selection?).

Any opportunities I'm missing?  I don't see any way to use lambdas, auto, or the other really interesting features while maintaining backward compatibility.

Edit to add checklist:
- [x] Add `libmesh_make_unique` wrapping `std::make_unique`
- [ ] Add `libmesh_move` wrapping `std::move`
- [x] Add `libmesh_final` wrapping `final` specifier
- [x] Add `libmesh_override` wrapping `override` specifier
- [x] Add `libmesh_delete` wrapping `delete` specifier for deleted functions
- [ ] Use `constexpr` where appropriate.  Not possible to [emulate in C++03](http://programmers.stackexchange.com/questions/142836/achieving-forward-compatibility-with-c11).
- [ ] Add `libmesh_noexcept` which expands to `noexcept` for C++11 compilers and `throw()` for older compilers.  Use this in place of `throw()` whereever it is currently in the library.
- [x] `nullptr`: There is a C++03 compatible `nullptr_t` example in [Effective C++, 2nd ed.](https://en.wikibooks.org/wiki/More_C%2B%2B_Idioms/nullptr#Solution_and_Sample_Code).
- [ ] Add `libmesh_default` wrapping the `=default` function specifier.

**Comment by friedmud** [comment]
This all sounds awesome @roystgnr !  Great idea!

**Comment by roystgnr** [comment]
After talking to the Dakota people recently I'm resigned to supporting C++98 (well, C++03 - if your compiler can't clear() an empty container then it can go to hell) for years to come, at least for our core features.

But I'm not sure that support has to be *first class*.  Suppose we switch from a "pass const reference, copy into member variable" constructor idiom (1 copy) to a "pass value, libmesh_move into member variable" idiom (2 copies with C++98, 1 copy with an lvalue in C++11, 0 copies with an rvalue in C++11).  As long as the latter still *compiles* with C++98, I'm comfortable with making old compilers' output slower if that's the cost of making new compilers' output faster.

(*probably* just a hypothetical example; we have lots of this sort of construction, but the only one I can see which might end up in an inner loop is the DenseVector-from-std::vector constructor, and I don't think we use that much)

@friedmud, are MOOSE users building with C++11 typically now?

**Comment by jwpeterson** [comment]
On Fri, Sep 18, 2015 at 9:54 AM, roystgnr <notifications@github.com> wrote:

> In cases where std::move(x) would leave more efficient code but where (x)
> would work, we should have a libmesh_move(x) inline function that compiles
> to the former when available and the latter otherwise. Likewise for
> std::forward().
>

I'm curious how you are going to use libmesh_move and libmesh_forward
without also having corresponding library functions that take rvalue
reference parameters?

Also, I could see things getting weird with overloads maybe?

f(libmesh_move(x))

could potentially call a different function in C++03 and C++11.


The "final" and "override" keywords are useful for efficiency and
> compile-time error checking, respectively, but they can be safely omitted
> too; we should have libmesh_final and libmesh_override macros that
> disappear when using C++98 but give us the C++11 features when they're
> supported.
>
Agree, this has been on my "to do but not high priority" list for a while.


> We should eventually do the same with noexcept/throw(). Maybe with
> constexpr (we can't safely use that in C++98, but we can declare with it so
> that C++11 user code can take advantage). Possibly with nullptr (or is that
> too risky due to differing overload selection?).
>
> Any opportunities I'm missing? I don't see any way to use lambdas, auto,
> or the other really interesting features while maintaining backward
> compatibility.
>
I believe there is also an "=delete;" specifier for functions you want to
disallow (that in 03 we handled with private constructors, etc).

-- 
John

**Comment by roystgnr** [comment]
libmesh_delete on those private constructors is a great idea.

libmesh_move would be useful in a few places because standard library objects have rvalue constructors and we use standard library containers under the hood.  I don't think there's any obvious places to use it in our library (since our APIs for e.g. DenseVector usually "fill" a target reference rather than returning a new object), but I might have missed something.

**Comment by roystgnr** [comment]
Things getting weird with overloads is a theoretical possibility, but if it happens in practice, the bug is with f, not with our invocation of it.  It's certainly possible to write a function with e.g. an lvalue overload that does foo and an rvalue overload that does bar, but what the rvalue overload is *supposed* to do is foo-more-efficiently.

**Comment by roystgnr** [comment]
We should add a wrapper to std::make_unique() - it ought to be possible to replace half of our invocations of new with that...

**Comment by jwpeterson** [comment]
`std::make_unique()` is [C++14 only](http://en.cppreference.com/w/cpp/memory/unique_ptr/make_unique).

**Comment by roystgnr** [comment]
Yeah, but we'll need to write the tedious case of the wrapper anyway.  Oh, hell, but even writing it ourselves would require variadic templates, which are C++11 only...

**Comment by permcody** [comment]
I edited the master list in this issue and added `libmesh_make_unique` to the list. I'm not sure exactly how this will work with C++11 disabled unless we already have the pieces we need from boost. At any rate we could use this immediately in MOOSE so I'd like to see it in libMesh soon! A link to the full implementation with variadic templates can be found in this thread: http://stackoverflow.com/questions/7038357/make-unique-and-perfect-forwarding

**Comment by jwpeterson** [comment]
A configure test for this can be added pretty easily, but I don't think the Boost subset we provide, which is based on 1.55.0 (Nov. 2013) , has a `make_unique` implementation. [One was added](http://www.boost.org/doc/libs/1_59_0/libs/smart_ptr/make_unique.html) in 1.56.0 (Jan. 2014), however.

What syntax would you want `libmesh_make_unique` to have? If you use `__VA_ARGS__`, then it should be pretty easy (haven't actually tried this yet) to have 
```
libmesh_make_unique(Type, arg1, arg2, arg3);
```
expand to either:
```
new Type(arg1, arg2, arg3);
```
in the C++11/14 disabled case, or a call to the templated function: 
```
template<typename T, typename... Args>
std::unique_ptr<T> make_unique(Args&&... args)
{
    return std::unique_ptr<T>(new T(std::forward<Args>(args)...));
}
```
given in the SO example.  But I feel like at least half the point of `std::make_unique` is that it provides a nice syntax, so hiding that behind a macro defeats the point.  

The other option would be a lightweight macro (no `__VA_ARGS__`) that calls one of
* `std::make_unique`, in the C++14 case
* `stack_overflow_make_unique`, in the C++11 but not 14 case
* `libmesh_error` or a `#error` if none of the above.

**Comment by permcody** [comment]
I guess I'll need @roystgnr to weigh in here as he indicated he'd like this in libMesh. Depending on his thoughts, we could also consider adding it to MOOSE so that we don't have to consider the non-C++11 case. That way we can keep the nicer syntax since we don't have to fall back to a C++03 compatible version.

**Comment by roystgnr** [comment]
I'd also prefer the lightweight C++11+ version, even if that means we can't use it in libMesh proper for a while.

**Comment by roystgnr** [comment]
__VA_ARGS__ is a non-C++03-standard extension too, isn't it?  It's in gcc, but it's only standard in C99 and C++11?  If we could get a nice-looking pure-C++03 case then I'd be tempted, but if we're going outside the old standard then I'd much rather get a nicer result from it.

**Comment by jwpeterson** [comment]
> VA_ARGS is a non-C++03-standard extension too, isn't it?

Technically yes, but we already use them, unguarded, in other parts of the library.


> If we could get a nice-looking pure-C++03 case

I think by definition the macro versions of anything are not "nice-looking."

**Comment by friedmud** [comment]
I'm really starting to wonder if all of this work is worth it.  What real reason does libMesh have in needing to support C++98?

Now that MOOSE has moved on and we've had very little problems from our user base... it seems like continuing to support C++98 in libMesh is just unnecessary work.  It's holding us back from using all of the power of C++11 (like range-based for, lambdas and auto).

Is there a real need / driving force behind keeping C++98 compatibility?  Maybe the thing to do is make a "final" release of libMesh with C++98 capability and then just move to C++11...

**Comment by jwpeterson** [comment]
I think a big difference is that MOOSE provides a binary package of C++11-compatible compilers which eased the transition for MOOSE users.  The main issues reported on moose-users have been on clusters that use the Intel compiler with an older GCC.  It's my feeling that a larger number of libmesh users will be in this latter situation, but I don't have any numbers to base that on.

**Comment by roystgnr** [comment]
The only driving force for me is that we've got some users' users' users who don't have full C++11 compiler support on their systems yet, and the users' users supporting them pay part of my salary.  I promise to keep jiggling elbows about when they're ready to step up their requirements, but honestly if everyone else gets sick of waiting before then I'll understand and I'll just take over the "backporting fixes to 1.0" task as long as necessary.

**Comment by friedmud** [comment]
Nah - if you have paying customers that don't want to upgrade... that's a valid reason to keep the support!

I was just double-checking that that really is still the case and we weren't arbitrarily limiting ourselves here...

**Comment by roystgnr** [comment]
Closing this issue; we should be ready to upgrade.
