### ISSUE TITLE
Make partition virtual

### ISSUE THREAD

**Issue by snschune** [libMesh/libmesh#676]
fyi @jwpeterson. 
I want to make ```Partitioner::partition()``` virtual. This would make it easier to 
incorporate already existing libmesh partitioner as ```MooseObject``` into ```Moose```. 

Background is explained here idaholab/moose#5776.

**Comment by jwpeterson** [comment]
I'm in favor of this, as long as we get some better documentation for `Partitioner::partition()` along the lines of "If you are implementing a new type of Partitioner, you probably want to override `_do_partition().  The partition() member may be overridden, especially in library code which wraps `Partitioner` objects, but be careful that you don't omit any of the necessary setup/shutdown code in `Partitioner::partition()` when doing so. `, etc., etc.
