### ISSUE TITLE
Backwards API compatibility vs new default arguments

### ISSUE THREAD

**Issue by roystgnr** [libMesh/libmesh#681]
Our common "let's add an argument to a method but give it a default for backwards compatibility" trick does not actually ensure backwards compatibility: only backwards compatibility with code that does not take a pointer to that method.

I never thought about this until I got stung (with a pointer internal to libMesh in code that's not yet in master, thankfully) by it.

I still find such changes acceptable (taking pointers to functions, especially pointers to member functions, is done rarely and only by sophisticated users who ought to be able to figure out the problem) but definitely not ideal (if you're bitten in user code, it creates the same sort of "you have to upgrade libMesh in perfect tandem with your own application" and "bisecting is much harder" problems that any other API change does), so I'd like to hear others' thoughts.

**Comment by jwpeterson** [comment]
By "not backwards compatible", you just mean it doesn't compile right?  Not that the function pointer is called with some weird arguments you weren't expecting?

I guess my thoughts would be to remove/deprecate APIs that take function pointers as much as possible, switching them over to Functor interfaces?

**Comment by pbauman** [comment]
> I guess my thoughts would be to remove/deprecate APIs that take function pointers as much as possible, switching them over to Functor interfaces?

+1

This has been a source of confusion many times, particularly with training new students to use the library.

**Comment by roystgnr** [comment]
I mean it doesn't compile.  I'd be much less optimistic if there was any possibility of runtime error.

But I think I've misconveyed the problem.  The trouble isn't our APIs taking function pointers from the user (although I agree we should have functor alternatives to all of them and we should deprecate the pointer versions).  If someone changes the signature of a function pointer argument then that's an obvious API change.

The trouble is our APIs *providing* function pointers to the user, which can't be deprecated because it's a low level feature of C++.  (a similar problem exists with virtual functions, where "overridden" can turn into "hidden" with a new base class default argument, but I think we've always been careful in those cases)

Take a look at the SyncRefinementFlags class in mesh_refinement.C for an example of what I mean.  It takes a pointer-to-member for the getter and setter method, so the same code works to sync both h refinement and p refinement flags.  Sexy, right?  And the kind of thing we want users to be able to do too, without us creating a shim functor for every imaginably useful function?

But if we change Elem::set_refinement_flag and Elem::set_p_refinement_flag to take an additional default argument "bool do_something_new = false", then although every old invocation of those methods will work, old code like SyncRefinementFlags which takes *pointers* to those methods will fail.

I think this is just a theoretical problem for now.  A quick ```srcgrep '::\*'``` turned up pointer-to-member only being used once in GRINS, not at all in FIN-S, and once in MOOSE, and each of the uses was internal-to-app-code where it would be easy to modify signatures of both the function and the function pointer in the same commit.

**Comment by roystgnr** [comment]
Closing this; we're never going to maintain *that* level of API compatibility, and relying more on functors makes the problem less critical.
