### ISSUE TITLE
libtool refresh

### ISSUE THREAD

**Issue by benkirk** [libMesh/libmesh#713]
We've been using libtool 2.4.2 for a while now; 2.4.6 includes a number of bugfixes.  I'll open a branch to update our bundled version.  This will also touch all the built sources, so will produce a large derived file changeset.

**Comment by jwpeterson** [comment]
:+1: Do you have to update automake and autoconf at the same time or are they fairly independent in that regard?

**Comment by roystgnr** [comment]
In theory the different autotools' versions are very independent.  In practice I've seen weird (although IIRC not badly broken) behavior when accidentally combining a new automake with an ancient libtool.

Large file changesets are fine; just keep them limited to a bootstrap-only commit (or two, if you decide to bump our automake from 1.12.5 to 1.12.6 while you're at it) so the other commits' changesets aren't drowned.

**Comment by benkirk** [comment]
the libtool change can go on by itself no problem.

As for automake, if we upgrade it I’d say we go all the way to 1.15, using the ‘legacy test harness’ for now to keep current behavior when running make check.

Thoughts?


On Nov 9, 2015, at 1:40 PM, roystgnr <notifications@github.com<mailto:notifications@github.com>> wrote:


In theory the different autotools' versions are very independent. In practice I've seen weird (although IIRC not badly broken) behavior when accidentally combining a new automake with an ancient libtool.

Large file changesets are fine; just keep them limited to a bootstrap-only commit (or two, if you decide to bump our automake from 1.12.5 to 1.12.6 while you're at it) so the other commits' changesets aren't drowned.

**Comment by jwpeterson** [comment]
> Thoughts?

Moving to 1.15 sounds good, apparently they [fixed a bug](https://lists.gnu.org/archive/html/automake/2015-01/msg00005.html) with "make distcheck" in that version...  Not sure exactly what you are referring to as far as the test harness goes, possibly this:
```
The default test-driver used by the Automake-generated testsuites
    now appends the result and exit status of each "plain" test to the
    associated log file (automake bug#11814).
```

**Comment by jwpeterson** [comment]
In case anyone was curious, you can blow away the old libmesh autotools by doing:
```
cd contrib/autotools && rm -rf bin include lib share
```
And rerun `bootstrap` to rebuild them.  This worked for me on OSX, no diffs in any of the generated files after updating.
