### ISSUE TITLE
Use setprecision(max_digits10) for ASCII I/O

### ISSUE THREAD

**Issue by roystgnr** [libMesh/libmesh#725]
I fixed some gross failures a few months ago where we'd inadvertently been outputting doubles using only 6 decimal places, but there's still subtle failures throughout the library where we're either hard-coding double (and thus no extended) precision, or where we're using digits10 (and so potentially losing a tiny bit of precision).

max_digits10 only exists in C++11, so we'll need a shim that either reimplements it (or falls back on digits10 and suffers a tiny roundoff) in the C++98 cse.

**Comment by jwpeterson** [comment]
Just FYI, @dschwen ended up writing a custom `max_digits10` implementation in MOOSE (idaholab/moose#6749, idaholab/moose#6761) since there is a [trivial formula](http://en.cppreference.com/w/cpp/types/numeric_limits/max_digits10) for computing it based on C++03 `numeric_limits<T>::digits`.
