### ISSUE TITLE
Issue with node deletion, allow_renumbering(), and prepare_for_use()

### ISSUE THREAD

**Issue by jwpeterson** [libMesh/libmesh#753]
While debugging something yesterday, @permcody came up with a simple test case that surprised me by not working.  The test code below produces the wrong mesh connectivity (see image).  We found three different ways of "fixing" the problem (lines 1, 2, and 3 in the comments below) but it seems like the code as written should "just work" :tm:.

Method 3 *may* cause it to work since it introduces a call to `renumber_nodes_and_elements()` that is otherwise avoided in `prepare_for_use()`... I haven't dug into it closely enough yet to know for sure.  One easy fix might be to always call `contract()` in `prepare_for_use()`.  It should be a fairly inexpensive operation if there are no NULL Elems in the Mesh.

```
#include "libmesh/mesh.h"
#include "libmesh/mesh_generation.h"
#include "libmesh/elem.h"
#include "libmesh/getpot.h"

using namespace libMesh;

// Test behavior of prepare_for_use() when elements are deleted.
int main (int argc, char** argv)
{
  LibMeshInit init(argc, argv);

  // Create a GetPot object to parse the command line
  GetPot command_line (argc, argv);

  // Read the number of elements on a side from the command line.
  int N = 2;
  if (command_line.search(1, "-N"))
    N = command_line.next(N);

  Mesh mesh(init.comm());
  MeshTools::Generation::build_square (mesh,
                                       /*nx=*/N, /*ny=*/N,
                                       /*xmin=*/0, /*xmax=*/1.,
                                       /*ymin=*/0, /*ymax=*/1.,
                                       QUAD4);

  // Delete element 0 and node 0, disallow numbering, and call
  // prepare_for_use().  This results in the incorrect connectivity in
  // the resulting file.
  mesh.delete_elem(mesh.elem(0));
  mesh.delete_node(mesh.node_ptr(0)); // 1.) Comment out this line and it works fine!
  mesh.allow_renumbering(false);      // 2.) Set this to true and it works fine!
  // mesh.contract();                 // 3.) Uncomment this line and it works fine!
  mesh.prepare_for_use();
  mesh.write("test_contract.e");

  return 0;
}
```

![connectivity](https://cloud.githubusercontent.com/assets/1775907/11845451/3b4d557a-a3d1-11e5-9f20-b5ab1e05490c.png)

**Comment by roystgnr** [comment]
Does it fail the same way with both SerialMesh and ParallelMesh?

Does ExodusII require consecutive numbering of its output?
---
Roy

**Comment by permcody** [comment]
One more piece of information:

I was under the impression that the user was responsible for deleting orphaned nodes, but as Derek pointed out here, https://github.com/idaholab/moose/issues/3080#issuecomment-164985137 libMesh should be deleting these nodes for me. Either way, why does **not** deleting the orphaned node work, while deleting it explicitly fail?

**Comment by jwpeterson** [comment]
> Does it fail the same way with both SerialMesh and ParallelMesh?

ParallelMesh also fails, although possibly in a slightly different way:

![parallelmesh](https://cloud.githubusercontent.com/assets/1775907/11846301/4a064cc6-a3d5-11e5-808a-2818ac52bd4e.png)


> Does ExodusII require consecutive numbering of its output?

I don't think the *format* itself requires it, but we may have something in our writer that assumes this is the case.  That's a good suggestion.

**Comment by permcody** [comment]
Whoa - I'm pretty sure I can build a ship with those pieces... hang on!

**Comment by jwpeterson** [comment]
> Whoa - I'm pretty sure I can build a ship with those pieces... hang on!

Yes, and for bonus points, can you arrange them into a kitty?
