### ISSUE TITLE
Build error: [libdbg_la-fpoptimizer.lo] Error 1

### ISSUE THREAD

**Issue by dhzhao** [libMesh/libmesh#755]
Hi,
In the process of building Libmesh, it got stuck here, see the error message below. I use Cygwin64, by the way.
Can someone please advise what to do to fix it?
Thanks a lot!
dhzhao

Error message:
make[4]: Entering directory '/home/dzhao/libraries/libmesh-0.9.5-rc1/contrib/fpa                                                                                                                                                 rser'
  CXX      libdbg_la-fpoptimizer.lo
fpoptimizer/bytecodesynth.cc: In instantiation of 'void FPoptimizer_ByteCode::By                                                                                                                                                 teCodeSynth<Value_t>::AddFunctionOpcode(unsigned int, FPoptimizer_ByteCode::Byte                                                                                                                                                 CodeSynth<Value_t>::Specializer<false, false>) [with Value_t = double]':
fpoptimizer/bytecodesynth.hh:293:17:   required from 'void FPoptimizer_ByteCode:                                                                                                                                                 :ByteCodeSynth<Value_t>::AddFunctionOpcode(unsigned int) [with Value_t = double                                                                                                                                                  '
fpoptimizer/bytecodesynth.hh:282:30:   required from 'void FPoptimizer_ByteCode:                                                                                                                                                 :ByteCodeSynth<Value_t>::AddOperation(unsigned int, unsigned int, unsigned int)                                                                                                                                                  [with Value_t = double]'
fpoptimizer/makebytecode.cc:150:21:   required from 'void FPoptimizer_CodeTree::                                                                                                                                                 CodeTree<Value_t>::SynthesizeByteCode(FPoptimizer_ByteCode::ByteCodeSynth<Value_                                                                                                                                                 t>&, bool) const [with Value_t = double]'
// many many lines here......................
.....................//
Makefile:1657: recipe for target 'libdbg_la-fpoptimizer.lo' failed
make[4]: *** [libdbg_la-fpoptimizer.lo] Error 1
make[4]: Leaving directory '/home/dzhao/libraries/libmesh-0.9.5-rc1/contrib/fpar                                                                                                                                             ser'
Makefile:2441: recipe for target 'all-recursive' failed
make[3]: *** [all-recursive] Error 1
make[3]: Leaving directory '/home/dzhao/libraries/libmesh-0.9.5-rc1/contrib/fpar                                                                                                                                                 ser'
Makefile:1032: recipe for target 'all' failed
make[2]: *** [all] Error 2
make[2]: Leaving directory '/home/dzhao/libraries/libmesh-0.9.5-rc1/contrib/fpar                                                                                                                                                 ser'
Makefile:912: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/dzhao/libraries/libmesh-0.9.5-rc1/contrib'
Makefile:28674: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

**Comment by dschwen** [comment]
Try configuring with --disable-fpoptimizer. But honestly with cygwin you
are on your own. Godspeed!

**Comment by dhzhao** [comment]
Thank you, dschwen. But do you mean --disable-fparser? I checked ./configure --help, there is no --disable-fpoptimizer.

**Comment by dhzhao** [comment]
ok, I think the problem is this unction in fparser.cc:
template<typename Value_t>
inline void FunctionParserBase<Value_t>::AddFunctionOpcode(unsigned opcode)

My compiler (g++) complains: unused parameter, unused variable.
What compiler do you use? 
Thank you.

**Comment by roystgnr** [comment]
On Thu, 17 Dec 2015, dhzhao wrote:

> My compiler (g++) complains: unused parameter, unused variable.

Those are both warnings, not errors.  Post the error lines?

> What compiler do you use?

gcc 4.9 and 5.2, intel 16, currently.  There is an internal compiler
bug in intel icpc 15.0 that gets triggered by fparser, but I've never seen
any other compiler (not even icpc 13 or 16) have a problem with it.
---
Roy

**Comment by dhzhao** [comment]
It's very long, but something like this:
fpoptimizer/bytecodesynth.cc: In instantiation of 'void FPoptimizer_ByteCode::By                                                                                                                                                 teCodeSynth<Value_t>::AddFunctionOpcode(unsigned int, FPoptimizer_ByteCode::Byte                                                                                                                                                 CodeSynth<Value_t>::Specializer<false, false>) [with Value_t = double]':
fpoptimizer/bytecodesynth.hh:293:17:   required from 'void FPoptimizer_ByteCode:                                                                                                                                                 :ByteCodeSynth<Value_t>::AddFunctionOpcode(unsigned int) [with Value_t = double                                                                                                                                                  '
fpoptimizer/bytecodesynth.hh:282:30:   required from 'void FPoptimizer_ByteCode:                                                                                                                                                 :ByteCodeSynth<Value_t>::AddOperation(unsigned int, unsigned int, unsigned int)                                                                                                                                                  [with Value_t = double]'
fpoptimizer/makebytecode.cc:150:21:   required from 'void FPoptimizer_CodeTree::                                                                                                                                                 CodeTree<Value_t>::SynthesizeByteCode(FPoptimizer_ByteCode::ByteCodeSynth<Value_                                                                                                                                                 t>&, bool) const [with Value_t = double]'
./fpoptimizer/instantiate_for_ad.hh:10:5:   required from here
fpoptimizer/bytecodesynth.cc:40:13: warning: unused variable 'mStackPtr' [-Wunus                                                                                                                                                 ed-variable]
         int mStackPtr=0;
             ^
fpoptimizer/bytecodesynth.cc:37:61: warning: unused parameter 'opcode' [-Wunused                                                                                                                                                 -parameter]
     void ByteCodeSynth<Value_t>::AddFunctionOpcode(unsigned opcode,

**Comment by roystgnr** [comment]
That's still just warnings...

Can you run "make 2>&1 | grep -i error | tee justerrors.txt" and just
post those lines to the list?

Or better, run "make 2>&1 | tee everything.txt" and send that to my
email address?  The libMesh mailing list filters long messages.
---
Roy

**Comment by dhzhao** [comment]
Hi Roy,
This is the .txt file following your | tee everything.txt.
Thank you very much for help.
Donghui

On Thu, Dec 17, 2015 at 10:23 PM, roystgnr <notifications@github.com> wrote:

>
> That's still just warnings...
>
> Can you run "make 2>&1 | grep -i error | tee justerrors.txt" and just
> post those lines to the list?
>
> Or better, run "make 2>&1 | tee everything.txt" and send that to my
> email address? The libMesh mailing list filters long messages.
> ---
> Roy
>
> On Thu, 17 Dec 2015, dhzhao wrote:
>
> >
> > It's very long, but something like this:
> > fpoptimizer/bytecodesynth.cc: In instantiation of 'void
> FPoptimizer_ByteCode::By teCodeSynth::AddFunctionOpcode(unsigned int,
> > FPoptimizer_ByteCode::Byte CodeSynth::Specializer) [with Value_t =
> double]':
> > fpoptimizer/bytecodesynth.hh:293:17: required from 'void
> FPoptimizer_ByteCode: :ByteCodeSynth::AddFunctionOpcode(unsigned int) [with
> Value_t =
> > double '
> > fpoptimizer/bytecodesynth.hh:282:30: required from 'void
> FPoptimizer_ByteCode: :ByteCodeSynth::AddOperation(unsigned int, unsigned
> int, unsigned
> > int) [with Value_t = double]'
> > fpoptimizer/makebytecode.cc:150:21: required from 'void
> FPoptimizer_CodeTree::
> CodeTree::SynthesizeByteCode(FPoptimizer_ByteCode::ByteCodeSynth&,
> > bool) const [with Value_t = double]'
> > ./fpoptimizer/instantiate_for_ad.hh:10:5: required from here
> > fpoptimizer/bytecodesynth.cc:40:13: warning: unused variable 'mStackPtr'
> [-Wunus ed-variable]
> > int mStackPtr=0;
> > ^
> > fpoptimizer/bytecodesynth.cc:37:61: warning: unused parameter 'opcode'
> [-Wunused -parameter]
> > void ByteCodeSynth::AddFunctionOpcode(unsigned opcode,
> >
> > —
> > Reply to this email directly or view it on
> GitHub.[ACQfck8I7q4bb2UobD91eWiyPIwhQqpUks5pQ3LugaJpZM4G3z3l.gif]
>
> >
> >
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/libMesh/libmesh/issues/755#issuecomment-165659496>.
>

Making all in include
make[1]: Entering directory '/home/dzhao/libraries/libmesh-0.9.5-rc1/include'
make  all-recursive
make[2]: Entering directory '/home/dzhao/libraries/libmesh-0.9.5-rc1/include'
Making all in libmesh
make[3]: Entering directory '/home/dzhao/libraries/libmesh-0.9.5-rc1/include/libmesh'
make  all-am
make[4]: Entering directory '/home/dzhao/libraries/libmesh-0.9.5-rc1/include/libmesh'
make[4]: Nothing to be done for 'all-am'.
make[4]: Leaving directory '/home/dzhao/libraries/libmesh-0.9.5-rc1/include/libmesh'
make[3]: Leaving directory '/home/dzhao/libraries/libmesh-0.9.5-rc1/include/libmesh'
make[3]: Entering directory '/home/dzhao/libraries/libmesh-0.9.5-rc1/include'
make[3]: Leaving directory '/home/dzhao/libraries/libmesh-0.9.5-rc1/include'
make[2]: Leaving directory '/home/dzhao/libraries/libmesh-0.9.5-rc1/include'
make[1]: Leaving directory '/home/dzhao/libraries/libmesh-0.9.5-rc1/include'
Making all in contrib
make[1]: Entering directory '/home/dzhao/libraries/libmesh-0.9.5-rc1/contrib'
Making all in unique_ptr
make[2]: Entering directory '/home/dzhao/libraries/libmesh-0.9.5-rc1/contrib/unique_ptr'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/dzhao/libraries/libmesh-0.9.5-rc1/contrib/unique_ptr'
Making all in eigen/eigen
make[2]: Entering directory '/home/dzhao/libraries/libmesh-0.9.5-rc1/contrib/eigen/eigen'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/dzhao/libraries/libmesh-0.9.5-rc1/contrib/eigen/eigen'
Making all in gmv
make[2]: Entering directory '/home/dzhao/libraries/libmesh-0.9.5-rc1/contrib/gmv'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/dzhao/libraries/libmesh-0.9.5-rc1/contrib/gmv'
Making all in netcdf/v4
make[2]: Entering directory '/home/dzhao/libraries/libmesh-0.9.5-rc1/contrib/netcdf/v4'
make  all-recursive
make[3]: Entering directory '/home/dzhao/libraries/libmesh-0.9.5-rc1/contrib/netcdf/v4'
Making all in include
make[4]: Entering directory '/home/dzhao/libraries/libmesh-0.9.5-rc1/contrib/netcdf/v4/include'
make[4]: Nothing to be done for 'all'.
make[4]: Leaving directory '/home/dzhao/libraries/libmesh-0.9.5-rc1/contrib/netcdf/v4/include'
Making all in libdispatch
make[4]: Entering directory '/home/dzhao/libraries/libmesh-0.9.5-rc1/contrib/netcdf/v4/libdispatch'
make[4]: Nothing to be done for 'all'.
make[4]: Leaving directory '/home/dzhao/libraries/libmesh-0.9.5-rc1/contrib/netcdf/v4/libdispatch'
Making all in libsrc
make[4]: Entering directory '/home/dzhao/libraries/libmesh-0.9.5-rc1/contrib/netcdf/v4/libsrc'
make[4]: Nothing to be done for 'all'.
make[4]: Leaving directory '/home/dzhao/libraries/libmesh-0.9.5-rc1/contrib/netcdf/v4/libsrc'
Making all in liblib
make[4]: Entering directory '/home/dzhao/libraries/libmesh-0.9.5-rc1/contrib/netcdf/v4/liblib'
make[4]: Nothing to be done for 'all'.
make[4]: Leaving directory '/home/dzhao/libraries/libmesh-0.9.5-rc1/contrib/netcdf/v4/liblib'
Making all in ncgen3
make[4]: Entering directory '/home/dzhao/libraries/libmesh-0.9.5-rc1/contrib/netcdf/v4/ncgen3'
make[4]: Nothing to be done for 'all'.
make[4]: Leaving directory '/home/dzhao/libraries/libmesh-0.9.5-rc1/contrib/netcdf/v4/ncgen3'
Making all in ncgen
make[4]: Entering directory '/home/dzhao/libraries/libmesh-0.9.5-rc1/contrib/netcdf/v4/ncgen'
make[4]: Nothing to be done for 'all'.
make[4]: Leaving directory '/home/dzhao/libraries/libmesh-0.9.5-rc1/contrib/netcdf/v4/ncgen'
Making all in ncdump
make[4]: Entering directory '/home/dzhao/libraries/libmesh-0.9.5-rc1/contrib/netcdf/v4/ncdump'
make  all-recursive
make[5]: Entering directory '/home/dzhao/libraries/libmesh-0.9.5-rc1/contrib/netcdf/v4/ncdump'
Making all in cdl4
make[6]: Entering directory '/home/dzhao/libraries/libmesh-0.9.5-rc1/contrib/netcdf/v4/ncdump/cdl4'
make[6]: Nothing to be done for 'all'.
make[6]: Leaving directory '/home/dzhao/libraries/libmesh-0.9.5-rc1/contrib/netcdf/v4/ncdump/cdl4'
Making all in expected4
make[6]: Entering directory '/home/dzhao/libraries/libmesh-0.9.5-rc1/contrib/netcdf/v4/ncdump/expected4'
make[6]: Nothing to be done for 'all'.
make[6]: Leaving directory '/home/dzhao/libraries/libmesh-0.9.5-rc1/contrib/netcdf/v4/ncdump/expected4'
make[6]: Entering directory '/home/dzhao/libraries/libmesh-0.9.5-rc1/contrib/netcdf/v4/ncdump'
make[6]: Nothing to be done for 'all-am'.
make[6]: Leaving directory '/home/dzhao/libraries/libmesh-0.9.5-rc1/contrib/netcdf/v4/ncdump'
make[5]: Leaving directory '/home/dzhao/libraries/libmesh-0.9.5-rc1/contrib/netcdf/v4/ncdump'
make[4]: Leaving directory '/home/dzhao/libraries/libmesh-0.9.5-rc1/contrib/netcdf/v4/ncdump'
Making all in man4
make[4]: Entering directory '/home/dzhao/libraries/libmesh-0.9.5-rc1/contrib/netcdf/v4/man4'
Making all in images
make[5]: Entering directory '/home/dzhao/libraries/libmesh-0.9.5-rc1/contrib/netcdf/v4/man4/images'
make[5]: Nothing to be done for 'all'.
make[5]: Leaving directory '/home/dzhao/libraries/libmesh-0.9.5-rc1/contrib/netcdf/v4/man4/images'
make[5]: Entering directory '/home/dzhao/libraries/libmesh-0.9.5-rc1/contrib/netcdf/v4/man4'
make[5]: Nothing to be done for 'all-am'.
make[5]: Leaving directory '/home/dzhao/libraries/libmesh-0.9.5-rc1/contrib/netcdf/v4/man4'
make[4]: Leaving directory '/home/dzhao/libraries/libmesh-0.9.5-rc1/contrib/netcdf/v4/man4'
Making all in examples
make[4]: Entering directory '/home/dzhao/libraries/libmesh-0.9.5-rc1/contrib/netcdf/v4/examples'
Making all in C
make[5]: Entering directory '/home/dzhao/libraries/libmesh-0.9.5-rc1/contrib/netcdf/v4/examples/C'
make[5]: Nothing to be done for 'all'.
make[5]: Leaving directory '/home/dzhao/libraries/libmesh-0.9.5-rc1/contrib/netcdf/v4/examples/C'
Making all in CDL
make[5]: Entering directory '/home/dzhao/libraries/libmesh-0.9.5-rc1/contrib/netcdf/v4/examples/CDL'
make[5]: Nothing to be done for 'all'.
make[5]: Leaving directory '/home/dzhao/libraries/libmesh-0.9.5-rc1/contrib/netcdf/v4/examples/CDL'
make[5]: Entering directory '/home/dzhao/libraries/libmesh-0.9.5-rc1/contrib/netcdf/v4/examples'
make[5]: Nothing to be done for 'all-am'.
make[5]: Leaving directory '/home/dzhao/libraries/libmesh-0.9.5-rc1/contrib/netcdf/v4/examples'
make[4]: Leaving directory '/home/dzhao/libraries/libmesh-0.9.5-rc1/contrib/netcdf/v4/examples'
make[4]: Entering directory '/home/dzhao/libraries/libmesh-0.9.5-rc1/contrib/netcdf/v4'
make[4]: Leaving directory '/home/dzhao/libraries/libmesh-0.9.5-rc1/contrib/netcdf/v4'
make[3]: Leaving directory '/home/dzhao/libraries/libmesh-0.9.5-rc1/contrib/netcdf/v4'
make[2]: Leaving directory '/home/dzhao/libraries/libmesh-0.9.5-rc1/contrib/netcdf/v4'
Making all in exodusii/v5.22/exodus
make[2]: Entering directory '/home/dzhao/libraries/libmesh-0.9.5-rc1/contrib/exodusii/v5.22/exodus'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/dzhao/libraries/libmesh-0.9.5-rc1/contrib/exodusii/v5.22/exodus'
Making all in nemesis/v5.22/nemesis
make[2]: Entering directory '/home/dzhao/libraries/libmesh-0.9.5-rc1/contrib/nemesis/v5.22/nemesis'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/dzhao/libraries/libmesh-0.9.5-rc1/contrib/nemesis/v5.22/nemesis'
Making all in qhull/qhull
make[2]: Entering directory '/home/dzhao/libraries/libmesh-0.9.5-rc1/contrib/qhull/qhull'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/dzhao/libraries/libmesh-0.9.5-rc1/contrib/qhull/qhull'
Making all in libHilbert
make[2]: Entering directory '/home/dzhao/libraries/libmesh-0.9.5-rc1/contrib/libHilbert'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/dzhao/libraries/libmesh-0.9.5-rc1/contrib/libHilbert'
Making all in metis
make[2]: Entering directory '/home/dzhao/libraries/libmesh-0.9.5-rc1/contrib/metis'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/dzhao/libraries/libmesh-0.9.5-rc1/contrib/metis'
Making all in parmetis
make[2]: Entering directory '/home/dzhao/libraries/libmesh-0.9.5-rc1/contrib/parmetis'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/dzhao/libraries/libmesh-0.9.5-rc1/contrib/parmetis'
Making all in fparser
make[2]: Entering directory '/home/dzhao/libraries/libmesh-0.9.5-rc1/contrib/fparser'
make  all-recursive
make[3]: Entering directory '/home/dzhao/libraries/libmesh-0.9.5-rc1/contrib/fparser'
Making all in extrasrc
make[4]: Entering directory '/home/dzhao/libraries/libmesh-0.9.5-rc1/contrib/fparser/extrasrc'
make  all-am
make[5]: Entering directory '/home/dzhao/libraries/libmesh-0.9.5-rc1/contrib/fparser/extrasrc'
make[5]: Nothing to be done for 'all-am'.
make[5]: Leaving directory '/home/dzhao/libraries/libmesh-0.9.5-rc1/contrib/fparser/extrasrc'
make[4]: Leaving directory '/home/dzhao/libraries/libmesh-0.9.5-rc1/contrib/fparser/extrasrc'
make[4]: Entering directory '/home/dzhao/libraries/libmesh-0.9.5-rc1/contrib/fparser'
  CXX      libdbg_la-fpoptimizer.lo
fpoptimizer/bytecodesynth.cc: In instantiation of 'void FPoptimizer_ByteCode::ByteCodeSynth<Value_t>::AddFunctionOpcode(unsigned int, FPoptimizer_ByteCode::ByteCodeSynth<Value_t>::Specializer<false, false>) [with Value_t = double]':
fpoptimizer/bytecodesynth.hh:293:17:   required from 'void FPoptimizer_ByteCode::ByteCodeSynth<Value_t>::AddFunctionOpcode(unsigned int) [with Value_t = double]'
fpoptimizer/bytecodesynth.hh:282:30:   required from 'void FPoptimizer_ByteCode::ByteCodeSynth<Value_t>::AddOperation(unsigned int, unsigned int, unsigned int) [with Value_t = double]'
fpoptimizer/makebytecode.cc:150:21:   required from 'void FPoptimizer_CodeTree::CodeTree<Value_t>::SynthesizeByteCode(FPoptimizer_ByteCode::ByteCodeSynth<Value_t>&, bool) const [with Value_t = double]'
./fpoptimizer/instantiate_for_ad.hh:10:5:   required from here
fpoptimizer/bytecodesynth.cc:40:13: warning: unused variable 'mStackPtr' [-Wunused-variable]
         int mStackPtr=0;
             ^
fpoptimizer/bytecodesynth.cc:37:61: warning: unused parameter 'opcode' [-Wunused-parameter]
     void ByteCodeSynth<Value_t>::AddFunctionOpcode(unsigned opcode,
                                                             ^
fpoptimizer/bytecodesynth.cc: In instantiation of 'void FPoptimizer_ByteCode::ByteCodeSynth<Value_t>::AddFunctionOpcode(unsigned int, FPoptimizer_ByteCode::ByteCodeSynth<Value_t>::Specializer<false, false>) [with Value_t = float]':
fpoptimizer/bytecodesynth.hh:293:17:   required from 'void FPoptimizer_ByteCode::ByteCodeSynth<Value_t>::AddFunctionOpcode(unsigned int) [with Value_t = float]'
fpoptimizer/bytecodesynth.hh:282:30:   required from 'void FPoptimizer_ByteCode::ByteCodeSynth<Value_t>::AddOperation(unsigned int, unsigned int, unsigned int) [with Value_t = float]'
fpoptimizer/makebytecode.cc:150:21:   required from 'void FPoptimizer_CodeTree::CodeTree<Value_t>::SynthesizeByteCode(FPoptimizer_ByteCode::ByteCodeSynth<Value_t>&, bool) const [with Value_t = float]'
./fpoptimizer/instantiate_for_ad.hh:10:5:   required from here
fpoptimizer/bytecodesynth.cc:40:13: warning: unused variable 'mStackPtr' [-Wunused-variable]
         int mStackPtr=0;
             ^
fpoptimizer/bytecodesynth.cc:37:61: warning: unused parameter 'opcode' [-Wunused-parameter]
     void ByteCodeSynth<Value_t>::AddFunctionOpcode(unsigned opcode,
                                                             ^
fpoptimizer/bytecodesynth.cc: In instantiation of 'void FPoptimizer_ByteCode::ByteCodeSynth<Value_t>::AddFunctionOpcode(unsigned int, FPoptimizer_ByteCode::ByteCodeSynth<Value_t>::Specializer<false, false>) [with Value_t = long double]':
fpoptimizer/bytecodesynth.hh:293:17:   required from 'void FPoptimizer_ByteCode::ByteCodeSynth<Value_t>::AddFunctionOpcode(unsigned int) [with Value_t = long double]'
fpoptimizer/bytecodesynth.hh:282:30:   required from 'void FPoptimizer_ByteCode::ByteCodeSynth<Value_t>::AddOperation(unsigned int, unsigned int, unsigned int) [with Value_t = long double]'
fpoptimizer/makebytecode.cc:150:21:   required from 'void FPoptimizer_CodeTree::CodeTree<Value_t>::SynthesizeByteCode(FPoptimizer_ByteCode::ByteCodeSynth<Value_t>&, bool) const [with Value_t = long double]'
./fpoptimizer/instantiate_for_ad.hh:10:5:   required from here
fpoptimizer/bytecodesynth.cc:40:13: warning: unused variable 'mStackPtr' [-Wunused-variable]
         int mStackPtr=0;
             ^
fpoptimizer/bytecodesynth.cc:37:61: warning: unused parameter 'opcode' [-Wunused-parameter]
     void ByteCodeSynth<Value_t>::AddFunctionOpcode(unsigned opcode,
                                                             ^
fpoptimizer/bytecodesynth.cc: In instantiation of 'void FPoptimizer_ByteCode::ByteCodeSynth<Value_t>::AddFunctionOpcode(unsigned int, FPoptimizer_ByteCode::ByteCodeSynth<Value_t>::Specializer<true, false>) [with Value_t = long int]':
fpoptimizer/bytecodesynth.hh:293:17:   required from 'void FPoptimizer_ByteCode::ByteCodeSynth<Value_t>::AddFunctionOpcode(unsigned int) [with Value_t = long int]'
fpoptimizer/bytecodesynth.hh:282:30:   required from 'void FPoptimizer_ByteCode::ByteCodeSynth<Value_t>::AddOperation(unsigned int, unsigned int, unsigned int) [with Value_t = long int]'
fpoptimizer/makebytecode.cc:150:21:   required from 'void FPoptimizer_CodeTree::CodeTree<Value_t>::SynthesizeByteCode(FPoptimizer_ByteCode::ByteCodeSynth<Value_t>&, bool) const [with Value_t = long int]'
./fpoptimizer/instantiate_for_ad.hh:10:5:   required from here
fpoptimizer/bytecodesynth.cc:63:13: warning: unused variable 'mStackPtr' [-Wunused-variable]
         int mStackPtr=0;
             ^
fpoptimizer/bytecodesynth.cc:60:61: warning: unused parameter 'opcode' [-Wunused-parameter]
     void ByteCodeSynth<Value_t>::AddFunctionOpcode(unsigned opcode,
                                                             ^
fpoptimizer/bytecodesynth.cc: In instantiation of 'void FPoptimizer_ByteCode::ByteCodeSynth<Value_t>::AddFunctionOpcode(unsigned int, FPoptimizer_ByteCode::ByteCodeSynth<Value_t>::Specializer<false, true>) [with Value_t = std::complex<double>]':
fpoptimizer/bytecodesynth.hh:293:17:   required from 'void FPoptimizer_ByteCode::ByteCodeSynth<Value_t>::AddFunctionOpcode(unsigned int) [with Value_t = std::complex<double>]'
fpoptimizer/bytecodesynth.hh:282:30:   required from 'void FPoptimizer_ByteCode::ByteCodeSynth<Value_t>::AddOperation(unsigned int, unsigned int, unsigned int) [with Value_t = std::complex<double>]'
fpoptimizer/makebytecode.cc:150:21:   required from 'void FPoptimizer_CodeTree::CodeTree<Value_t>::SynthesizeByteCode(FPoptimizer_ByteCode::ByteCodeSynth<Value_t>&, bool) const [with Value_t = std::complex<double>]'
./fpoptimizer/instantiate_for_ad.hh:10:5:   required from here
fpoptimizer/bytecodesynth.cc:87:13: warning: unused variable 'mStackPtr' [-Wunused-variable]
         int mStackPtr=0;
             ^
fpoptimizer/bytecodesynth.cc:84:61: warning: unused parameter 'opcode' [-Wunused-parameter]
     void ByteCodeSynth<Value_t>::AddFunctionOpcode(unsigned opcode,
                                                             ^
fpoptimizer/bytecodesynth.cc: In instantiation of 'void FPoptimizer_ByteCode::ByteCodeSynth<Value_t>::AddFunctionOpcode(unsigned int, FPoptimizer_ByteCode::ByteCodeSynth<Value_t>::Specializer<false, true>) [with Value_t = std::complex<float>]':
fpoptimizer/bytecodesynth.hh:293:17:   required from 'void FPoptimizer_ByteCode::ByteCodeSynth<Value_t>::AddFunctionOpcode(unsigned int) [with Value_t = std::complex<float>]'
fpoptimizer/bytecodesynth.hh:282:30:   required from 'void FPoptimizer_ByteCode::ByteCodeSynth<Value_t>::AddOperation(unsigned int, unsigned int, unsigned int) [with Value_t = std::complex<float>]'
fpoptimizer/makebytecode.cc:150:21:   required from 'void FPoptimizer_CodeTree::CodeTree<Value_t>::SynthesizeByteCode(FPoptimizer_ByteCode::ByteCodeSynth<Value_t>&, bool) const [with Value_t = std::complex<float>]'
./fpoptimizer/instantiate_for_ad.hh:10:5:   required from here
fpoptimizer/bytecodesynth.cc:87:13: warning: unused variable 'mStackPtr' [-Wunused-variable]
         int mStackPtr=0;
             ^
fpoptimizer/bytecodesynth.cc:84:61: warning: unused parameter 'opcode' [-Wunused-parameter]
     void ByteCodeSynth<Value_t>::AddFunctionOpcode(unsigned opcode,
                                                             ^
fpoptimizer/bytecodesynth.cc: In instantiation of 'void FPoptimizer_ByteCode::ByteCodeSynth<Value_t>::AddFunctionOpcode(unsigned int, FPoptimizer_ByteCode::ByteCodeSynth<Value_t>::Specializer<false, true>) [with Value_t = std::complex<long double>]':
fpoptimizer/bytecodesynth.hh:293:17:   required from 'void FPoptimizer_ByteCode::ByteCodeSynth<Value_t>::AddFunctionOpcode(unsigned int) [with Value_t = std::complex<long double>]'
fpoptimizer/bytecodesynth.hh:282:30:   required from 'void FPoptimizer_ByteCode::ByteCodeSynth<Value_t>::AddOperation(unsigned int, unsigned int, unsigned int) [with Value_t = std::complex<long double>]'
fpoptimizer/makebytecode.cc:150:21:   required from 'void FPoptimizer_CodeTree::CodeTree<Value_t>::SynthesizeByteCode(FPoptimizer_ByteCode::ByteCodeSynth<Value_t>&, bool) const [with Value_t = std::complex<long double>]'
./fpoptimizer/instantiate_for_ad.hh:10:5:   required from here
fpoptimizer/bytecodesynth.cc:87:13: warning: unused variable 'mStackPtr' [-Wunused-variable]
         int mStackPtr=0;
             ^
fpoptimizer/bytecodesynth.cc:84:61: warning: unused parameter 'opcode' [-Wunused-parameter]
     void ByteCodeSynth<Value_t>::AddFunctionOpcode(unsigned opcode,
                                                             ^
/usr/lib/gcc/x86_64-pc-cygwin/5.2.0/../../../../x86_64-pc-cygwin/bin/as: .libs/libdbg_la-fpoptimizer.o: too many sections (48609)
/tmp/cce04Kiu.s: Assembler messages:
/tmp/cce04Kiu.s: Fatal error: can't write .libs/libdbg_la-fpoptimizer.o: File too big
/usr/lib/gcc/x86_64-pc-cygwin/5.2.0/../../../../x86_64-pc-cygwin/bin/as: .libs/libdbg_la-fpoptimizer.o: too many sections (48609)
/tmp/cce04Kiu.s: Fatal error: can't close .libs/libdbg_la-fpoptimizer.o: File too big
Makefile:1657: recipe for target 'libdbg_la-fpoptimizer.lo' failed
make[4]: *** [libdbg_la-fpoptimizer.lo] Error 1
make[4]: Leaving directory '/home/dzhao/libraries/libmesh-0.9.5-rc1/contrib/fparser'
Makefile:2441: recipe for target 'all-recursive' failed
make[3]: *** [all-recursive] Error 1
make[3]: Leaving directory '/home/dzhao/libraries/libmesh-0.9.5-rc1/contrib/fparser'
Makefile:1032: recipe for target 'all' failed
make[2]: *** [all] Error 2
make[2]: Leaving directory '/home/dzhao/libraries/libmesh-0.9.5-rc1/contrib/fparser'
Makefile:912: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/dzhao/libraries/libmesh-0.9.5-rc1/contrib'
Makefile:28674: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

**Comment by dschwen** [comment]
For real?! The error is
/tmp/cce04Kiu.s: Fatal error: can't write .libs/libdbg_la-fpoptimizer.o:
File too big

How big can it possibly be? And more importantly how big is too big on your
system? Sorry about the configure option, I thought we had that one.

>

**Comment by dhzhao** [comment]
Hi Dan,
I couldn't locate either cce04Kiu.s or libdbg_la-fpoptimizer.o on my disk.
I searched all, but I don't think they are there.
My computer seems to have large enough storage.
I have no idea what else to try. Let me know if you have some advice.
Thank you.
Donghui

**Comment by dschwen** [comment]
Quite frankly my advice would be to install this on a Linux system. But let's not give up quite yet I'll try to find a windows machine to replicate the issue. Might take a while though.

**Comment by dhzhao** [comment]
Thank you, Dan. Let me know if you figure out something. 
Installing a Linux on my computer could be a painful job since I have most of my stuff in Windows. Hopefully this can be resolved.
Thank you again. 
Donghui

**Comment by dschwen** [comment]
Ok, according to a web search the reason is that by default the windows object format is limited to 2^16 sections. Heavy use of templates in fpoptimizer can break that barrier. Please check if your compiler supports the ` -Wa,-mbig-obj`  flag. That would raise the limit to 2^32 using a modified object format.

**Comment by dhzhao** [comment]
Dan,
I use gcc-g++ 5.2.0-1. It has no -mbig-obj flag. Should I use other compiler, like cygwin32-gcc-g++?
Being curious, if I do ./configure --disable-fparser, what functionality will Libmesh lose if built without fparser?
Thanks a lot!

**Comment by dhzhao** [comment]
Dan, you are right that it is because of the limitation of object file in windows.
This "too many sections" problem was finally solved by changing the optimization level in CXXFLAGS_DBG in /contrib/fparser/Makefile :
CXXFLAGS_DBG =  -std=gnu++11 -O
Using -O2 finally got around this problem.

**Comment by dschwen** [comment]
Nice, please keep us posted on your progress.
