### ISSUE TITLE
Build error: In file included from src/base/libmesh.C

### ISSUE THREAD

**Issue by dhzhao** [libMesh/libmesh#757]
Hi, please see the error message below in build libmesh.C. It seems some place misses #include <math.h>?
Please advise how to fix it. Thank you!

 CXX      src/base/libmesh_dbg_la-libmesh.lo
In file included from src/base/libmesh.C:22:0:
./include/libmesh/getpot.h: In member function 'std::__cxx11::string GetPot::_DBE_expand(const string&)':
./include/libmesh/getpot.h:2932:55: error: no matching function for call to 'asinh(double&)'
               return _convert_from_type(std::asinh(arg));
                                                       ^
In file included from ./include/libmesh/libmesh_common.h:46:0,
                 from ./include/libmesh/libmesh.h:25,
                 from src/base/libmesh.C:20:
/usr/lib/gcc/x86_64-pc-cygwin/5.2.0/include/c++/complex:1769:5: note: candidate: template<class _Tp> std::complex<_Tp> std::asinh(const std::complex<_Tp>&)
     asinh(const std::complex<_Tp>& __z)
     ^
/usr/lib/gcc/x86_64-pc-cygwin/5.2.0/include/c++/complex:1769:5: note:   template argument deduction/substitution failed:
In file included from src/base/libmesh.C:22:0:
./include/libmesh/getpot.h:2932:55: note:   mismatched types 'const std::complex<_Tp>' and 'double'
               return _convert_from_type(std::asinh(arg));
                                                       ^
./include/libmesh/getpot.h:2941:55: error: no matching function for call to 'acosh(double&)'
               return _convert_from_type(std::acosh(arg));
                                                       ^
In file included from ./include/libmesh/libmesh_common.h:46:0,
                 from ./include/libmesh/libmesh.h:25,
                 from src/base/libmesh.C:20:
/usr/lib/gcc/x86_64-pc-cygwin/5.2.0/include/c++/complex:1730:5: note: candidate: template<class _Tp> std::complex<_Tp> std::acosh(const std::complex<_Tp>&)
     acosh(const std::complex<_Tp>& __z)
     ^
/usr/lib/gcc/x86_64-pc-cygwin/5.2.0/include/c++/complex:1730:5: note:   template argument deduction/substitution failed:
In file included from src/base/libmesh.C:22:0:
./include/libmesh/getpot.h:2941:55: note:   mismatched types 'const std::complex<_Tp>' and 'double'
               return _convert_from_type(std::acosh(arg));
                                                       ^
./include/libmesh/getpot.h:2950:55: error: no matching function for call to 'atanh(double&)'
               return _convert_from_type(std::atanh(arg));
                                                       ^
In file included from ./include/libmesh/libmesh_common.h:46:0,
                 from ./include/libmesh/libmesh.h:25,
                 from src/base/libmesh.C:20:
/usr/lib/gcc/x86_64-pc-cygwin/5.2.0/include/c++/complex:1813:5: note: candidate: template<class _Tp> std::complex<_Tp> std::atanh(const std::complex<_Tp>&)
     atanh(const std::complex<_Tp>& __z)
     ^
/usr/lib/gcc/x86_64-pc-cygwin/5.2.0/include/c++/complex:1813:5: note:   template argument deduction/substitution failed:
In file included from src/base/libmesh.C:22:0:
./include/libmesh/getpot.h:2950:55: note:   mismatched types 'const std::complex<_Tp>' and 'double'
               return _convert_from_type(std::atanh(arg));
                                                       ^
Makefile:13245: recipe for target 'src/base/libmesh_dbg_la-libmesh.lo' failed
make[1]: *** [src/base/libmesh_dbg_la-libmesh.lo] Error 1
make[1]: Leaving directory '/home/dzhao/libraries/libmesh-0.9.5-rc1'
Makefile:28674: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

**Comment by roystgnr** [comment]
On Fri, 18 Dec 2015, dhzhao wrote:

> Hi, please see the error message below in build libmeshC It seems some place misses #include ?
> Please advise how to fix it Thank you!

It's not a missing include; it looks like a lying compiler.
std::asinh and others are defined in the cmath header in C++11, and
we only use them if your compiler defined __cplusplus > 199711L (which
implies C++11 support)

As a workaround, you can comment out the lines

#define HAVE_INVERSE_HYPERBOLIC_SINE

#define HAVE_INVERSE_HYPERBOLIC_COSINE

#define HAVE_INVERSE_HYPERBOLIC_TANGENT

in include/base/getpot.h

If you want to help us find a proper fix then I'd appreciate it
(you're using Cygwin, IIRC, and I don't have a windows machine handy
to replicate with) but if you just want to get things working ASAP I
understand.  I'm technically already on vacation myself...
---
Roy

**Comment by jwpeterson** [comment]
We already #include "libmesh_common.h" in getpot.h if `USE_LIBMESH` is defined.  The right solution is probably to write configure tests for these functions and set `HAVE_INVERSE_HYPERBOLIC_SINE` based on that...

**Comment by dhzhao** [comment]
I did a little search, and found out for GNU gcc-g++, those inverse hyperbolic functions, asinh etc, are actually in the library of Complex, not cmath...
Certainly this is not a Cygwin-related issue...
Thank you guys for replying even in holiday/vacation... really appreciate!

**Comment by jwpeterson** [comment]
According to the [standard](http://en.cppreference.com/w/cpp/numeric/math/asinh), they are defined in `<cmath>`.

**Comment by dhzhao** [comment]
It depends on compiler... Different compiler has different implementation.
For gnu gcc, the asinh(), acosh() etc, are not in cmath:

https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a01042.html

But instead they are in complex:
https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a01050.html

**Comment by pbauman** [comment]
What version of the GCC are you using with cygwin? How was it built? 

GCC puts those functions in `<cmath>`. E.g. from the cmath header in GCC 4.8.5 installed on my laptop:

<pre>
 constexpr float
  asinh(float __x)                                                                                                                                                                                                                         
  { return __builtin_asinhf(__x); }

  constexpr long double
  asinh(long double __x)
  { return __builtin_asinhl(__x); }

  template<typename _Tp>
    constexpr typename __gnu_cxx::__enable_if<__is_integer<_Tp>::__value,
                                              double>::__type
    asinh(_Tp __x)
    { return __builtin_asinh(__x); }
</pre>

**Comment by dschwen** [comment]
The specializations for std::complex types are in <complex>, which may be
what dhzhao is seening. But the regular floating point versions should be
in <cmath>.
Daniel

**Comment by jwpeterson** [comment]
Taking a second look at this, it does appear that you have to `#include <complex>` to specifically get the `std::complex`-enabled versions of the various inverse hyperbolic functions, e.g. [asinh(std::complex)](http://en.cppreference.com/w/cpp/numeric/complex/asinh).

What I don't know is why this error would be triggered by these functions' use in getpot.h, since there they are only called with real-valued arguments.  Nevertheless, I think adding configure tests is a good addition, but I'm curious: @dhzhao do these compiler errors go away if you simply `#include <complex>` somewhere at the top of getpot.h?

**Comment by dhzhao** [comment]
@jwpeterson, John, adding #include <complex> in getpot.h does not solve the problem, the same error message comes out...

**Comment by jwpeterson** [comment]
Well... that just means that your compiler claims `__cplusplus > 199711L` but doesn't something isn't quite right with it's hyperbolic inverse trig function implementation.

Try updating to the latest master?  I recently added more comprehensive configure tests for the inverse hyperbolic functions, they should hopefully be gracefully disabled on your system now.

**Comment by dhzhao** [comment]
@jwpeterson , John, "updating to the latest master" means downloading the "cxx.m4", and reconfigure?

**Comment by jwpeterson** [comment]
Do you have a clone of the repo?  If so, with the master branch checked out, try `git pull --rebase`.  If not, clone the repo by doing `git clone https://github.com/libMesh/libmesh.git`.

**Comment by dhzhao** [comment]
@jwpeterson , so I did the git clone, then configure, then make, but the following error:
$ make
CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/sh /home/dzhao/libmesh/build-aux/missing aclocal-1.15 -I m4
/home/dzhao/libmesh/build-aux/missing: line 81: aclocal-1.15: command not found
WARNING: 'aclocal-1.15' is missing on your system.
         You should only need it if you modified 'acinclude.m4' or
         'configure.ac' or m4 files included by 'configure.ac'.
         The 'aclocal' program is part of the GNU Automake package:
         <http://www.gnu.org/software/automake>
         It also requires GNU Autoconf, GNU m4 and Perl in order to run:
         <http://www.gnu.org/software/autoconf>
         <http://www.gnu.org/software/m4/>
         <http://www.perl.org/>
Makefile:5446: recipe for target 'aclocal.m4' failed
make: *** [aclocal.m4] Error 127

**Comment by jwpeterson** [comment]
You need to either run `./bootstrap` once from the top-level directory, or `./configure --disable-maintainer-mode`.

**Comment by dhzhao** [comment]
@jwpeterson , thanks John, with ./bootstrap, it went well. But another error comes out in making, can you please advise?
make[2]: Leaving directory '/home/dzhao/libmesh/contrib/parmetis'
Making all in fparser
make[2]: Entering directory '/home/dzhao/libmesh/contrib/fparser'
mpicxx -std=gnu++11    util/bytecoderules_parser.cc   -o util/bytecoderules_parser
Creating system-specific Bytecode in extrasrc/fp_opcode_add.inc ...
Makefile:2817: recipe for target 'extrasrc/fp_opcode_add.inc' failed
make[2]: *** [extrasrc/fp_opcode_add.inc] Error 127
make[2]: Leaving directory '/home/dzhao/libmesh/contrib/fparser'
Makefile:977: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/dzhao/libmesh/contrib'
Makefile:28909: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

**Comment by jwpeterson** [comment]
Hmm... I replied by email but it looks like it never made it to the issue?  Anyway, this issue might be fixed by configuring with ---disable-fparser.

**Comment by jwpeterson** [comment]
I think this issue has been fixed, but feel free to reopen...
