### ISSUE TITLE
Compilation error with --disable-second

### ISSUE THREAD

**Issue by salazardetroya** [libMesh/libmesh#763]
In the [uniform_refinement_estimator.C](https://github.com/libMesh/libmesh/blob/master/src/error_estimation/uniform_refinement_estimator.C#L624) the variable ```H2seminormsq``` is declared inside the ```LIBMESH_ENABLE_SECOND_DERIVATIVES``` compilation flags and makes the compilation fail if we pass --disable-second. Should that ```H2``` summation enclosed with the same compilation flags or the declaration of ```H2seminormsq``` declared outside the flags?

**Comment by roystgnr** [comment]
On Sat, 2 Jan 2016, salazardetroya wrote:

> In the uniform_refinement_estimatorC the variable H2seminormsq is declared inside the LIBMESH_ENABLE_SECOND_DERIVATIVES compilation flags and
> makes the compilation fail if we pass --disable-second Should that H2summation enclosed with the same compilation flags or the declaration
> ofH2seminormsq` declared outside the flags?

The summation should be enclosed.  Looks like there's a couple other
errors that have crept in since the last time we built with
--disable-second, though; I'll try to prepare a patch fixing them all.
---
Roy

**Comment by jwpeterson** [comment]
> On Jan 2, 2016, at 4:39 PM, roystgnr <notifications@github.com> wrote:
> 
> 
> On Sat, 2 Jan 2016, salazardetroya wrote:
> 
> > In the uniform_refinement_estimatorC the variable H2seminormsq is declared inside the LIBMESH_ENABLE_SECOND_DERIVATIVES compilation flags and
> > makes the compilation fail if we pass --disable-second Should that H2summation enclosed with the same compilation flags or the declaration
> > ofH2seminormsq` declared outside the flags?
> 
> The summation should be enclosed. Looks like there's a couple other
> errors that have crept in since the last time we built with
> --disable-second, though; I'll try to prepare a patch fixing them all.

Thanks.  Also sounds like a good candidate for the 0.9.5 branch.

**Comment by roystgnr** [comment]
@salazardetroya, let me know if #764 works for you?

**Comment by salazardetroya** [comment]
It works. Thank you.
