### ISSUE TITLE
Allow for "Biased" Meshing With Internal Mesh Generator

### ISSUE THREAD

**Issue by stimpsonsg** [libMesh/libmesh#767]
This issue began on the BISON issues board, but the BISON developers have informed me that this is a LibMesh issue, so I am submitting the issue here.

The BISON internal mesh generator, which is based on LibMesh, is currently restricted to uniform meshes.  An internal report from the BISON team demonstrated the benefits of using a "biased" mesh (with nonuniform regions), which they obtained by using a mesh generated by Cubit.  If possible, allowing the internal mesh generator to create biased meshes would be very useful.  

Thank you for your time!

**Comment by pbauman** [comment]
I agree this would be a nice feature to have (but I'd say low on the priority list, IMHO, since such things are easily done in the mesh generators, as you pointed out). In the meantime, there is some limited capability. I'm not sure what interface is exposed in BISON, but there is at least an option to bias the elements towards the boundary (based on Gauss-Lobatto points). You set, e.g. in [build_cube](http://libmesh.github.io/doxygen/namespacelibMesh_1_1MeshTools_1_1Generation.html#adc26f45af62fb628158c7585d4171d01), the last argument to `true`.

**Comment by stimpsonsg** [comment]
It's understandable that this is lower priority.  

I'm also unsure of what interface is exposed in BISON.  I've included a link to this issue on the ticket I made on the BISON site, so hopefully a BISON developer can shed some light on it.

Thanks for the quick response...and hopefully we can use this pre-existing option.

**Comment by permcody** [comment]
An alternative idea which is already on the TODO list for BISON this year
is to start using mesh adaptivity with BISON. I believe most of the
application is ready for adaptivity with just a few remaining issues
surrounding some of the contact algorithms. Once you have the ability to
robustly run a simulation with adaptivity you may not need biasing in your
initial meshes at all.

**Comment by roystgnr** [comment]
There is one thing that a non-uniform mesh grading can give you that
libMesh adaptive mesh refinement can't: anisotropic grading.
(Anisotropic element refinement has been on our would-be-nice list for
half a decade but won't make it to our TODO list for the near future;
IMHO contrary assumptions are too baked into libMesh.)

I use MeshTools::MeshModification::redistribute() as a workaround in
other applications.  In particular, passing a parsed function into
that gives a lot of flexibility from the input file.

I don't see any interface from MOOSE to redistribute(), though.  We
should probably fix that.

**Comment by permcody** [comment]
Interesting, I've never looked at that method before. We should be able to
create a MeshModifier object to redistribute nodes right now. We don't
believe we'll need to modify any existing APIs to add that capability.

**Comment by jwpeterson** [comment]
On Wed, Jan 6, 2016 at 9:06 AM, roystgnr <notifications@github.com> wrote:

>
> There is one thing that a non-uniform mesh grading can give you that
> libMesh adaptive mesh refinement can't: anisotropic grading.
> (Anisotropic element refinement has been on our would-be-nice list for
> half a decade but won't make it to our TODO list for the near future;
> IMHO contrary assumptions are too baked into libMesh.)
>
> I use MeshTools::MeshModification::redistribute() as a workaround in
> other applications. In particular, passing a parsed function into
> that gives a lot of flexibility from the input file.
>
> I don't see any interface from MOOSE to redistribute(), though. We
> should probably fix that.


Huh, I've either never used that or forgot about it.  The Gauss-Lobatto
grading in build_cube should probably be reimplemented in terms of that.

-- 
John

**Comment by friedmud** [comment]
+1 for a MeshModifier that can use `redistribute`

**Comment by jwpeterson** [comment]
I've opened issue idaholab/moose#6129 for this instead.
