### ISSUE TITLE
mesh_dimension in build_sphere

### ISSUE THREAD

**Issue by BalticPinguin** [libMesh/libmesh#790]
[mesh_gen.patch.txt](https://github.com/libMesh/libmesh/files/95857/mesh_gen.patch.txt)
I think there is a bug in build_sphere() concerning the dimension. 
Starting from miscellaneous_ex6 and changeing
 MeshTools::Generation::build_cube(...)
to
const libMesh::Real radius = 2;
MeshTools::Generation::build_sphere(cube_mesh, radius, 2, HEX8, 2, true);
I always get the error "Unknown dimension 0".
I think it is due to the mesh.clear() in that function where the dimension is removed as well.
At least for me, the patch in supplement made it working for me. 
Best,
Hubert

**Comment by jwpeterson** [comment]
Thanks for sending the patch.  I'll take a closer look/merge it today hopefully.
