### ISSUE TITLE
pthreads may be broken in libMesh

### ISSUE THREAD

**Issue by permcody** [libMesh/libmesh#801]
OK, I've spent a few hours trying to nail down some bad threading behavior and I still don't understand enough to solve the problem but I'll report what I think I've learned. I started running "helgrind" on MOOSE and it repeatedly prints out an issue with a recursive mutex on one that doesn't support it here:
https://github.com/libMesh/libmesh/blob/master/src/parallel/threads.C#L40

I started digging to see why it may be getting called and it looks like it's "first" locked here:
https://github.com/libMesh/libmesh/blob/master/include/parallel/threads.h#L552-L554

There are several odd things happening here, I may as well start with the first glaring issue. According to the POSIX standard. "Thread identifiers should be considered opaque: any attempt to use a thread ID other than in pthreads calls is nonportable and can lead to unspecified results."
http://man7.org/linux/man-pages/man3/pthread_self.3.html

So even though the type pthread_t is defined on our platforms, using it in a map probably isn't the best idea (but we do it anyway):
https://github.com/libMesh/libmesh/blob/master/src/parallel/threads.C#L32

Assuming that it works for a given platform (maybe), we move onto what's happening with this odd "recursive mutex" error. Again, according to the POSIX standard: "Unless real-time scheduling policies are being employed, after a call to pthread_create(), it is indeterminate which thread, the caller or the new thread will next execute."
http://man7.org/linux/man-pages/man3/pthread_create.3.html

The order in which things happen are this:
 1. lock the `_pthread_unique_id_mutex`
 2. create the thread
   1. thread: might ask for its id which takes us back to `Threads.C`
   2. thread: lock the `_pthread_unique_id_mutex` again  (possibly the source of the helgrind error)
   3. thread: return the thread id from the map which of course violates the POSIX recommendation (also, the bracket operators are being used here so we may also have an accidental insertion into the map if the id doesn't exist for some reason, or worse yet if the comparison operator is unreliable?).
 3. record the thread's unique id by using the buffer space as a key in the map (yikes)

This at least helps me to understand why this code was written the way it was. If a user desires a thread id for thread identification purposes and possibly indexing (i.e. everything in MOOSE) then we'd need to make sure we have a lock on the map before inserting into it it. Also, we'd need to make sure nobody else had a lock before accessing the thread id too. Logically, these two locks seem to make sense to me...

There are too many problems to fully understand the cause of the helgrind error. I could use another pair of eyes on this. I think the best way to resolve this would be to engineer a way to pass the thread id as an argument when we create the thread. In that world we wouldn't need any locks at all and we wouldn't have all this crazy logic to create a thread id through this weird mapping scheme. Since we have all these layers of abstraction anyway, it should be possible to reserve the first location in the threads args vector to hold the integer id. We'd then peel that off before passing control to the user thread routine.

**Comment by jwpeterson** [comment]
How does any of this :hankey: work?

**Comment by permcody** [comment]
BTW - Adding the following error check in Threads::pthread_unique_id() shows that there is definitely a problem

```
std::map<pthread_t, unsigned int>::iterator it = _pthread_unique_ids.find(pthread_self());
  if (it == _pthread_unique_ids.end())
    std::cerr << "Error retrieving ID for thread: " << pthread_self() << '\n'
```

**Comment by permcody** [comment]
I've been looking at this a little more today and still don't see a good way to fix the pthread issue. I wanted to see exactly what a pthread_t was on our macs and it's definitely not a simple type. If you comb through the system includes you'll eventually find a number of typdefs and structure: Here they are for your viewing pleasure:

```
typedef __darwin_pthread_t pthread_t;

typedef struct _opaque_pthread_t *__darwin_pthread_t;

struct _opaque_pthread_t {
	long __sig;
	struct __darwin_pthread_handler_rec  *__cleanup_stack;
	char __opaque[__PTHREAD_SIZE__];
};
```

So it's a pointer to a structure, which is why any of this code compiles at all. The current code uses `pthread_t` as a `std::map` key which is not portable (i.e. the type is not guaranteed to have `operator<()` defined. 

From reading several forums where other people would like to use thread ids for various things it looks like the only portable solution is to pass it as an argument in `pthread_create`. This leaves us with two scenarios:

1) Change the libMesh Threads API so that this "index" or id is passed as an argument to the thread body. Breaks lots of existing threaded code in libMesh and dependent libraries.

2) Don't change the libMesh API...  
We might be able to use wrap `pthread_key_create()`, `pthread_setspecific()` and the like to portably create an id.  ... or ... we figure out how to dump thread ids in MOOSE! I don't think that will be very easy (or even possible) with the architecture we've chosen to hide threading in the framework.

3) Stop supporting ids in pthreads, which means not supporting them in MOOSE!

ping @roystgnr, @friedmud

**Comment by permcody** [comment]
UPDATE: Before either of you even chime in I've already convinced myself that we cannot change the underlying thread API nor can we stop using thread IDs in MOOSE so I'm well on the path of finding a solution with the `pthread_[get|set]specific` calls to hold the ids for each thread. There's a fair amount of setup and bookkeeping to get it all right but I think it's the right solution. I even chatted it over with the other moose-devs and we don't think that dumping pthreads is the right choice here either (in favor of moving to C++11 std::thread). The reason for this is simple, Helgrind only support pthreads so this interface needs to work and it's arguably the most portable threading interface available. I'll be leaving on travel tomorrow so I don't know if I'll get a PR in for a few days or not but hopefully I'll have a solution to this whole mess soon.

**Comment by friedmud** [comment]
I remember writing that code. Looking back at it, I can see the issues
you're talking about.

Luckily, there is a pretty easy fix for MOOSE (which is what this code is
in there for... no one else uses it). Look here:

https://github.com/idaholab/moose/blob/5270d0cda43a579339ef4f82b84d19dc32b412ab/framework/include/utils/ParallelUniqueId.h

See all of the PTHREAD stuff? We just need to make that work without using
this stuff from libMesh. All it takes is a parallel queue object like the
one we use from TBB... a regular C++ queue with a lock around it will work
for now (just make a shim class that locks and unlocks the queue) and just
make it work just like the TBB stuff.

I only did pthreads this way because I thought we could get unique ids for
them easily... and it made switching between pthreads and OpenMP simple
(OpenMP really can give you a unique thread ID... it's the only threading
model we have that can really do that correctly).

Derek

**Comment by permcody** [comment]
@friedmud - I had already considered using the queue for pthreads but I'm not convinced this will work in MOOSE:

From the POSIX standard: 
       Unless real-time scheduling policies
       are being employed, after a call to pthread_create(), it is
       indeterminate which thread—the caller or the new thread—will next
       execute.

So using a queue to assign ids based on thread execution order does not guarantee consistent ids, and if we don't have consistent ids that may be used to index into a data structure in a well-defined way, I argue that we may not need an id for the purpose of unique identification. 

So this is really important, what is the design of thread ids in MOOSE supposed to be? Is it to keep threads operating on distinct copies of objects (thread 0 always operates on the zeroth copy of data and so on), or is it to uniquely identify threads such that I know that a given thread is working on a specific range?  Ugh... This is really tricky to make clear so let me see if I can come up with an example...

Lets say I run a simulation with two threads. In a particular threaded loop, let's say that the master process enters the parallel_for region, creates the two ranges and begins executing the `pthread_create()` loop. Now because the scheduling is not defined, it's possible for the master thread to create both of the pthreads and have the second thread begin executing first. If we use the queue option to assign ids, the second thread (which is working on the second half of the range due to the parallel_for loop construction) will be assigned thread id zero for this loop. Inside of MOOSE that ID will be used to grab the zeroth copy of any data structures it needs like MooseVariable. If the id is just there to make sure that the threads don't step on each other, that's fine. I bring this all up because of that PR that @aeslaughter tried to put in the other day and what @dschwen was messing with. If users think that thread *n* can access any *nth* copy of data and MOOSE and have predictable results in that copy of the data they are mistaken. I know better but it's why ids can be dangerous if incorrectly used.

**Comment by roystgnr** [comment]
We definitely shouldn't be trying to use pthread_t in a map, but all we're doing when we initialize that first vector of pthread_t is we're assigning an int to it.  So if we need per-thread ids then we ought to just be keeping vectors and maps of int.

"thread n can access any nth copy of data" isn't a mistake exactly, the way it's phrased; the whole distinction between threads and processes is that threads can run wild in each other's RAM.  But if users think that we're going to nicely chop elements (or nodes, whatever we're divvying up into ranges) into the exact same subsets each time and hand the nth subset to thread n, then that's definitely a no-no.

**Comment by friedmud** [comment]
Consistent IDs are not important. We don't care if the "first" thread gets
tid zero or not. Even in the case of Daniel's stuff... all he needs is to
get the unique "helper" object for _this_ thread ID... Which ID it is does
not matter.

Trust me, it will work (it does now with TBB!).

Derek

**Comment by permcody** [comment]
I'm just saying that the design needs to be documented (our job moving
forward). It's easy for users to build this assumption in and find
themselves in hot water later. It might be worthwhile to add some debugging
logic that can prescribe in-order and out-of-order id generation to make
sure people don't sneak in bad code at higher levels.

**Comment by friedmud** [comment]
Ok - but that's always been the design... since the beginning. It's not a
change or anything.

Derek

**Comment by permcody** [comment]
OK - this passes libMesh and MOOSE testing with TBB (no surprises there). I'd say merge it if you guys are happen with it.
