### ISSUE TITLE
Add TypeVector::norm(), norm_sq(), deprecate size(), size_sq()

### ISSUE THREAD

**Issue by jwpeterson** [libMesh/libmesh#813]
The original name has always been confusing and a mistake.  Let's phase it out.

**Comment by pbauman** [comment]
+1

**Comment by roystgnr** [comment]
Great idea.  Let's phase it out *slowly*, though; not just one release for an API that everyone's code is riddled with.

**Comment by friedmud** [comment]
The reason not to use "norm" is: _which_ norm? If you're doing this for
clarity then I would say make the new function `l2norm()`...

As for rollout: I would suggest:

1. Add norm()
2. Remove size()
3. Let everyone get size() completely out of their applications.
4. Add size() back in with the new definition (presumably the length,
right? That's what this whole thing is about?)

Giving #3 a decent amount of time will ensure less "hidden" bugs...

**Comment by jwpeterson** [comment]
On Fri, Jan 29, 2016 at 1:12 PM, Derek Gaston <notifications@github.com>
wrote:

> The reason not to use "norm" is: _which_ norm? If you're doing this for
> clarity then I would say make the new function `l2norm()`...
>

Well, that cat is already out of the bag, as there is already a
TensorTools::norm == the Euclidean norm for quite a while.  I think this
can be handled fine with documentation...


> As for rollout: I would suggest:
>
> 1. Add norm()
> 2. Remove size()
> 3. Let everyone get size() completely out of their applications.
> 4. Add size() back in with the new definition (presumably the length,
> right? That's what this whole thing is about?)
>

No, I don't want to add size() back in.  TypeVector is always LIBMESH_DIM
in length so it's not necessary.

-- 
John

**Comment by friedmud** [comment]
In that case... I would say: why change it?  Arguably `size()` is clearer than `norm()` .  It at least gives you some indication that it's going to do a Euclidean norm ;-)

**Comment by jwpeterson** [comment]
> Arguably size() is clearer than norm()

Well, the argument is that the STL has already made `size()` the de-facto way to get the number of items in a container, TypeVector::size() has nothing to do with that and is therefore confusing.

**Comment by pbauman** [comment]
> In that case... I would say: why change it? 

IMHO, I think it's always better to make changes to better adhere to the what's expected.

> Arguably size() is clearer than norm() .

I don't agree. In the vast majority of C++ containers, `size()` refers to the number of elements in the container, where as here we are computing the norm.

>  It at least gives you some indication that it's going to do a Euclidean norm ;-)

Again, I don't agree. But, I agree that either `norm()` should take an `enum` (or something) to select the norm, or we implement `l2_norm`, `l1_norm`, etc. as you suggested.

**Comment by jwpeterson** [comment]
Merged in 562caee.
