### ISSUE TITLE
Remove PETSc 2.x code paths

### ISSUE THREAD

**Issue by jwpeterson** [libMesh/libmesh#823]
The last PETSc 2.x release was 2.3.3 on May 23, 2007.  Surely no one is still using this and these code paths have not been compiled in years.  They are just making the source code harder to read for humans, so I vote we remove them...

**Comment by pbauman** [comment]
+1

**Comment by dknez** [comment]
+1

**Comment by jwpeterson** [comment]
Merged in 5a491fd.
