### ISSUE TITLE
Fix new projection code, if possible

### ISSUE THREAD

**Issue by roystgnr** [libMesh/libmesh#831]
I've finally figured out why the bug here is so hard to trigger a regression failure with.  (instructions for triggering one via MOOSE are in https://github.com/idaholab/moose/pull/6236 )

The MOOSE failure simply manages to magnify the problem: a constant monomial field, written out to the restart file with a value of 2 on each element, is getting read back in with a value of 2-epsilon (1.9999999999999996) on a handful of those elements.  Obviously we're not going to notice a 1e-15 scale error on any numerics tests, but these particular values are being used as *refinement flags*, and are being cast to an enum, and in C++ casting a floating point number to an integer (or a thinly disguised integer) truncates, not rounds.  Dropping the pre-cast value by 1e-15 drops the post-cast value by 1, which changes the flag from "refine" to "do_nothing".

Honestly, though, I'm not sure how this worked reliably before.  We've always done projection for non-lagrange elements, and that's always got a risk of floating point error.  I'll submit a PR to make MOOSE more robust once I'm done seeing if I can also get that last epsilon back on the libMesh side.

**Comment by roystgnr** [comment]
Ah, of course.  Before, if we detected an element was neither refined nor coarsened in either h or p, we went to a "just copy dof values" codepath.  Now we're only doing that for vertices and Lagrange dofs.  This is going to be hard to fix without losing the generality that was half the reason for refactoring to begin with...

**Comment by jwpeterson** [comment]
Just to clarify, are these values round-tripping through Exodus/NetCDF files or through the "custom" binary restart files that MOOSE writes?

It would be very frightening to me to learn that writing the floating point bit representation of "2.0" and then reading it back in would change the value.  But, from your second post I guess you are saying the 1.999999.... number is being computed as a result of projecting this solution vector in a slightly different way after it's been read in?

**Comment by roystgnr** [comment]
They're coming from xdr files.  The value gets read in as 2.0.  We then go through a projection call (there's some redundancy in libMesh here which dates back to ancient backwards compatibility we ought to drop, and it looks like there may be some redundancy in MOOSE too?).  The projection call dutifully solves integral(u*v) = integral(2*v), which after quadrature on this particular element boils down to something like "u = .142857... / .0714286", and at some point in the quadrature summation or the multiplications or the division an epsilon's error slipped in.

**Comment by permcody** [comment]
If you are referring to this gem:
https://github.com/idaholab/moose/blob/devel/framework/src/ics/InitialCondition.C#L86-L91,
then yes let's get rid of it! I can't believe we (no names mentioned here)
copied this code. We need to do this right and use callbacks or some other
mechanism to accomplish what we need.

**Comment by roystgnr** [comment]
No; that's redundancy of code which ought to be fixed.  I'm noticing what might be redundant calls to the non-redundant code, which ought to also be fixed.

And no blame to whoever's been copying-and-pasting-and-tweaking my projection code.  I'VE been copying-and-pasting-and-tweaking my projection code, and I let those copies float around in libMesh for years, because creating a GenericProjector that will handle every sort of projection imaginable in one place while remaining correct and efficient is so hard that here I am *still* trying to get it just right.

**Comment by roystgnr** [comment]
You know, I'm going to leave the projection code on in the p refinement/coarsening case.  Slightly slower if you know you're hierarchic, but much simpler code and it'll work for non-hierarchic FE too.
