### ISSUE TITLE
infinite elements: no initialisation of shape functions

### ISSUE THREAD

**Issue by BalticPinguin** [libMesh/libmesh#875]
Recently, I reallised that the infinite-element-part still seems to be erroneous: Adding the lines
```
if (elem->infinite()){
    out<<phi[i][qp]<<std::endl;
}
```
in the part, where the matrices Me and Ce are set up reveals, that the shape functions are 0 always.

I can try to fix it but I have not yet an idea what actually needs to be changed (except of course that I somewhere need to assign values to the shape functions; so far it seems they are just initialised).

**Comment by BalticPinguin** [comment]
I closed it since the patch #942 is merged.

**Comment by roystgnr** [comment]
Thank you much for this and for the fix!

I know beggars can't be choosers, but if you ever find yourself with too much free time, would you add some unit tests too?  (Or some asserts to miscellaneous_ex1?  How did this bug not leave that screaming and dying with a zero matrix?)

I don't think any of the current main developers are infinite elements people, and I'm afraid we'll just end up regressing that support again eventually unless it gets better test coverage.

**Comment by BalticPinguin** [comment]
I think, I will find time to prepare a respective example. Just might take some weeks.
I think, the point where  infinite elements were lost, when their were disabled in the example (see #830 ).
After this, of course,  any errors/incompatibilities were not found by the tests.
