### ISSUE TITLE
Add C++11 test for std::to_string

### ISSUE THREAD

**Issue by jwpeterson** [libMesh/libmesh#891]
This function removes the hassle of constructing a separate stringstream for doing formatted output.

[link](http://www.cplusplus.com/reference/string/to_string)

**Comment by dschwen** [comment]
Correct me if I'm wrong, but there is basically nothing that prevents us from declaring this function in the std namespace ourselves if the test comes back negative? That way the user wouldn't even have to know about the test.

**Comment by jwpeterson** [comment]
> declaring this function in the std namespace

One does not simply declare functions in the std namespace?

**Comment by roystgnr** [comment]
> One does not simply declare functions in the std namespace?

Right.  The only thing you're allowed to declare in std is overloads
of existing functions with your own data types.

**Comment by dschwen** [comment]
You're such a `[](Real d) { return x*x; }`!

**Comment by jwpeterson** [comment]
> You're such a [](Real d) { return x*x; }!

This won't compile, even in C++11.

**Comment by dschwen** [comment]
Sure it does!

```
#include <iostream>

typedef double Real;
const Real normal_person = 2;
const Real peterson = 4;

int main()
{
  auto square = [](Real x) { return x * x; };
  std::cout << (peterson == square(normal_person)) << '\n';
  return 0;
}
```

```
> clang++ --std=c++11 square.C`
> ./a.out`
1
```

**Comment by permcody** [comment]
lol - Nice demo program

**Comment by jwpeterson** [comment]
Your original version (before you corrected it) had "Real d", as in my quoted reply.  Nice try though.

**Comment by dschwen** [comment]
We must have barely crossed edits then. I updated that right away.

**Comment by jwpeterson** [comment]
Added in #894.
