### ISSUE TITLE
HDF5 Linking Error

### ISSUE THREAD

**Issue by friedmud** [libMesh/libmesh#910]
Something isn't quite right with the linking of HDF5 if you build the HDF5 C++ interface.

I get this:

```
ccache clang++ -DNDEBUG -std=gnu++11 -O2 -felide-constructors -Qunused-arguments -fopenmp  -L/opt/hdf5_clang_noparallel/lib -lhdf5 -Wl,-rpath,/opt/hdf5_clang_noparallel/lib -lz -L/opt/moose/petsc/mpich_petsc-3.6.1/clang-opt-superlu/lib -lpetsc -Wl,-rpath,/opt/moose/petsc/mpich_petsc-3.6.1/clang-opt-superlu/lib -lHYPRE -L/opt/moose/mpich/mpich-3.1.4/clang-opt/lib -L/opt/moose/clang_3.7.0/lib -lcmumps -ldmumps -lsmumps -lzmumps -lmumps_common -lpord -lscalapack -lsuperlu_dist_4.0 -lflapack -lfblas -lparmetis -lmetis -Wl,-rpath,/opt/X11/lib -L/opt/X11/lib -lX11 -lmpifort -Wl,-rpath,/opt/moose/gcc_5.2.0/lib/gcc/x86_64-apple-darwin15.0.0/5.2.0 -L/opt/moose/gcc_5.2.0/lib/gcc/x86_64-apple-darwin15.0.0/5.2.0 -Wl,-rpath,/opt/moose/gcc_5.2.0/lib -L/opt/moose/gcc_5.2.0/lib -lgfortran -lgomp -lgcc_ext.10.5 -lquadmath -lm -lmpicxx -lc++ -Wl,-rpath,/opt/moose/mpich/mpich-3.1.4/clang-opt/lib -lomp -lmpi -lpmpi -Wl,-rpath,/opt/moose/clang_3.7.0/lib -lSystem -ldl -Wl,-rpath,/Users/gastdr/projects/libmesh/lib -L/Users/gastdr/projects/libmesh/lib -lmesh_opt -I/Users/gastdr/projects/libmesh/include -I/opt/hdf5_clang_noparallel/include -D_THREAD_SAFE -pthread -I/opt/moose/petsc/mpich_petsc-3.6.1/clang-opt-superlu/include -I/opt/moose/petsc/mpich_petsc-3.6.1/clang-opt-superlu//include -I/opt/X11/include -I/opt/moose/mpich/mpich-3.1.4/clang-opt/include -I include -I contrib/mtwist/include -o simple-opt  src/main-opt.o 
Undefined symbols for architecture x86_64:
  "H5::FileAccPropList::DEFAULT", referenced from:
      _main in main-opt.o
  "H5::FileCreatPropList::DEFAULT", referenced from:
      _main in main-opt.o
  "H5::H5File::H5File(char const*, unsigned int, H5::FileCreatPropList const&, H5::FileAccPropList const&)", referenced from:
      _main in main-opt.o
  "H5::H5File::~H5File()", referenced from:
      _main in main-opt.o
ld: symbol(s) not found for architecture x86_64
```

Or I see a failure at runtime saying it can't find a similar symbol.

A test code is over here: https://github.com/friedmud/simple_libmesh_app/tree/hdf5_error  (note the branch)

Looking at the link line it's obvious that it's only picking up the "normal" HDF5 libraries... but completely missing the HDF5 C++ interface libraries.  On my system those are called:

```
libhdf5_cpp.11.dylib	libhdf5_cpp.a		libhdf5_cpp.dylib	libhdf5_cpp.la		libhdf5_hl_cpp.11.dylib	libhdf5_hl_cpp.a	libhdf5_hl_cpp.dylib	libhdf5_hl_cpp.la
```

Those came from configuring HDF5 with `--enable-cxx`

**Comment by friedmud** [comment]
Another, related issue I have is that `DEFAULT` is somewhere in the global namespace... and if it is defined before you `#include "H5Cpp.h"` then it causes a compile error.  I have to do `undef DEFAULT` before that `#include`.

Unfortunately - I wasn't able to reproduce this in the simple test from above.  I don't yet know if that means that it's some pollution coming from MOOSE (I'm seeing this when I try to do that `#include` in a MOOSE-based application) or if I simply don't have the right libMesh headers included to generate the issue in the simple example...

**Comment by jwpeterson** [comment]
> On Apr 24, 2016, at 6:35 PM, Derek Gaston <notifications@github.com> wrote:
> 
> Something isn't quite right with the linking of HDF5 if you build the HDF5 C++ interface.
> 
> I get this:
> 
> ccache clang++ -DNDEBUG -std=gnu++11 -O2 -felide-constructors -Qunused-arguments -fopenmp  -L/opt/hdf5_clang_noparallel/lib -lhdf5 -Wl,-rpath,/opt/hdf5_clang_noparallel/lib -lz -L/opt/moose/petsc/mpich_petsc-3.6.1/clang-opt-superlu/lib -lpetsc -Wl,-rpath,/opt/moose/petsc/mpich_petsc-3.6.1/clang-opt-superlu/lib -lHYPRE -L/opt/moose/mpich/mpich-3.1.4/clang-opt/lib -L/opt/moose/clang_3.7.0/lib -lcmumps -ldmumps -lsmumps -lzmumps -lmumps_common -lpord -lscalapack -lsuperlu_dist_4.0 -lflapack -lfblas -lparmetis -lmetis -Wl,-rpath,/opt/X11/lib -L/opt/X11/lib -lX11 -lmpifort -Wl,-rpath,/opt/moose/gcc_5.2.0/lib/gcc/x86_64-apple-darwin15.0.0/5.2.0 -L/opt/moose/gcc_5.2.0/lib/gcc/x86_64-apple-darwin15.0.0/5.2.0 -Wl,-rpath,/opt/moose/gcc_5.2.0/lib -L/opt/moose/gcc_5.2.0/lib -lgfortran -lgomp -lgcc_ext.10.5 -lquadmath -lm -lmpicxx -lc++ -Wl,-rpath,/opt/moose/mpich/mpich-3.1.4/clang-opt/lib -lomp -lmpi -lpmpi -Wl,-rpath,/opt/moose/clang_3.7.0/lib -lSystem -ldl -Wl,-rpath,/Users/
>  gastdr/p
>  rojects/libmesh/lib -L/Users/gastdr/projects/libmesh/lib -lmesh_opt -I/Users/gastdr/projects/libmesh/include -I/opt/hdf5_clang_noparallel/include -D_THREAD_SAFE -pthread -I/opt/moose/petsc/mpich_petsc-3.6.1/clang-opt-superlu/include -I/opt/moose/petsc/mpich_petsc-3.6.1/clang-opt-superlu//include -I/opt/X11/include -I/opt/moose/mpich/mpich-3.1.4/clang-opt/include -I include -I contrib/mtwist/include -o simple-opt  src/main-opt.o 
> Undefined symbols for architecture x86_64:
>   "H5::FileAccPropList::DEFAULT", referenced from:
>       _main in main-opt.o
>   "H5::FileCreatPropList::DEFAULT", referenced from:
>       _main in main-opt.o
>   "H5::H5File::H5File(char const*, unsigned int, H5::FileCreatPropList const&, H5::FileAccPropList const&)", referenced from:
>       _main in main-opt.o
>   "H5::H5File::~H5File()", referenced from:
>       _main in main-opt.o
> ld: symbol(s) not found for architecture x86_64
> Or I see a failure at runtime saying it can't find a similar symbol.
> 
> A test code is over here: https://github.com/friedmud/simple_libmesh_app/tree/hdf5_error (note the branch)
> 
> Looking at the link line it's obvious that it's only picking up the "normal" HDF5 libraries... but completely missing the HDF5 C++ interface libraries. On my system those are called:
> 
> libhdf5_cpp.11.dylib    libhdf5_cpp.a       libhdf5_cpp.dylib   libhdf5_cpp.la      libhdf5_hl_cpp.11.dylib libhdf5_hl_cpp.a    libhdf5_hl_cpp.dylib    libhdf5_hl_cpp.la
> Those came from configuring HDF5 with --enable-cxx
> 

OK, I don't think I've ever tested in that config, so not too surprised it doesn't work.  I am actually working on hdf.m4 on a branch because of other issues related to v. 1.8.13.  What version are you using?

**Comment by friedmud** [comment]
1.8.16 - just grabbed it this evening.

Derek

**Comment by jwpeterson** [comment]
> Another, related issue I have is that DEFAULT is somewhere in the global namespace... and if it is defined before you #include "H5Cpp.h" then it causes a compile error. I have to do #undef DEFAULT before that #include.

The culprit is in MOOSE:

framework/include/utils/XTermConstants.h:#define DEFAULT  "\33[39m"

**Comment by friedmud** [comment]
Doh!  That's a dumb thing to do (it is also dumb that this messes up HDF5 though!).

**Comment by jwpeterson** [comment]
The `DEFAULT` thing has been fixed in MOOSE, and hdf.m4 has been updated to link with the C++ libs, so I think this is fixed.
