### ISSUE TITLE
Build fails with --disable-mpi

### ISSUE THREAD

**Issue by dschwen** [libMesh/libmesh#923]
```
  CXXLD    unit_tests-dbg
parallel/unit_tests_dbg-packed_range_test.o: In function `PackedRangeTest::testNullAllGather()':
/home/moose/projects/moose/libmesh/build/tests/../../tests/parallel/packed_range_test.C:125: undefined reference to `void libMesh::Parallel::Communicator::allgather_packed_range<void, __gnu_debug::_Safe_iterator<__gnu_cxx::__normal_iterator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, std::__cxx1998::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >, std::__debug::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >, libMesh::null_output_iterator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >(void*, __gnu_debug::_Safe_iterator<__gnu_cxx::__normal_iterator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, std::__cxx1998::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >, std::__debug::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >, __gnu_debug::_Safe_iterator<__gnu_cxx::__normal_iterator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, std::__cxx1998::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >, std::__debug::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >, libMesh::null_output_iterator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >) const'
collect2: error: ld returned 1 exit status
```

**Comment by jwpeterson** [comment]
Thanks.  There is also a ticket about `--disable-amr` builds failing.  We should probably fix both and cherry-pick onto 1.0.0.  BTW, was this an accident, or were you really going for a no-MPI build?

**Comment by dschwen** [comment]
If I tell you @friedmud will get mad at me

**Comment by dschwen** [comment]
Just as an aside, MOOSE fails to build even if libmesh compiles (mooseError uses MPI_Abort without any guards. Not sure if that is by design...)

**Comment by roystgnr** [comment]
Can't have been by design, can it?  If there's a problem with the terminate handler (e.g. not calling MPI_Abort() in some case where it's supposed to) then we should fix that.  If there isn't then you should terminate().

**Comment by roystgnr** [comment]
I'll get these builds fixed ASAP, by the way.

**Comment by permcody** [comment]
We _never_ build MOOSE with MPI turned off or adaptivity turned off. I have
no doubt that we have several regressions for these modes. Generally none
of our users build this way so it's not a super high priority to fix them
but if somebody wants to, I'd be happy to accept those changes.

**Comment by dschwen** [comment]
@permcody while this is not the point of this issue I think it could be done relatively easy. At a quick glance it looks like only a few files (maybe 5 spots altogether) need to be edited (some multiapp stuff uses raw MPI calls). While I recognize that this is not a priority at all it would clean up the MOOSE code base. We use libmesh to wrap parallel communication everywhere else, so using the raw calls looks a bit iffy.

**Comment by roystgnr** [comment]
These are bugs in libMesh itself (and bugs in our testing at UT - I didn't realize until now that cppunit-devel wasn't installed on our new machines!); they need to be fixed for other users even if they're not a high priority for MOOSE, and I'm hoping to finish the fixes right away so backporting to 1.0.0 won't be a hassle.

**Comment by roystgnr** [comment]
Let me know if anything else crops up.

**Comment by friedmud** [comment]
Just to follow up on this... there is one very good reason to make sure our
stuff builds without MPI: Windows.

On Windows we don't really need MPI (threading is good enough)... and the
new UNIX stuff for Windows is going to mean we may start to "support" it....

**Comment by permcody** [comment]
We can certainly add a target. We have about 32 build boxes now! I suspect
there will be several regressions in MOOSE for building without MPI and AMR.

**Comment by dschwen** [comment]
See above. There are plenty of unprotected raw MPI calls in the MultiApp system.
