### ISSUE TITLE
Doxygen docs not generated for classes marked 'libmesh_final'

### ISSUE THREAD

**Issue by jwpeterson** [libMesh/libmesh#926]
Expanding the list of classes [here](http://libmesh.github.io/doxygen/annotated.html), you won't see Hex8/20/27, Prism6/15/18, `PetscVector`, etc.  `PetscMatrix` is there, but no docs show up for the [header file](http://libmesh.github.io/doxygen/classlibMesh_1_1PetscMatrix.html).

This could be fixable by simply removing the `libmesh_final` keyword before generating the docs (replacing it later), updating the version of Doxygen used, or some other approach.

**Comment by pbauman** [comment]
Doxygen has a `PREDEFINED` [option](https://www.stack.nl/~dimitri/doxygen/manual/config.html#cfg_predefined) where you can tell it to build the documentation with those macros predefined (regardless of configuration). In this case, you'd set `PREDEFINED = libmesh_final` in the doxygen. That's assuming, of course, Doxygen understands `final`.

**Comment by jwpeterson** [comment]
Interesting idea, will give that a try...

**Comment by borisboutkov** [comment]
:+1:  would be very useful! I just ran into this issue while trying implement some PetscMatrix stuff through GRINS.
