### ISSUE TITLE
--disable-cxx11 should actually disable C++11

### ISSUE THREAD

**Issue by roystgnr** [libMesh/libmesh#927]
Not just skip searching for it.

With libstdc++ from GCC 5.1 and up, -D_GLIBCXX_USE_CXX11_ABI=0 needs to be explicitly specified to use the pre-C++11-compatible ABI.

With g++ 6.1 and up, -std=c++03 needs to be explicitly specified to use the pre-C++11 standard.

This is an issue rather than a patch because I have no idea what needs to be done for non-gcc compilers.

**Comment by jwpeterson** [comment]
This would be nice to have... 

I'm not sure clang will support doing this at all.  They have enabled random C++11 features (creating iostreams from std::strings rings a bell) in the last several versions of the compiler, even when *not* compiling with -std=c++11.

**Comment by roystgnr** [comment]
Closing this issue, because it's time to just demand C++11 and stop supporting --disable-cxx11.
