### ISSUE TITLE
Can't compile libMesh with MPI support

### ISSUE THREAD

**Issue by jas02** [libMesh/libmesh#949]
Hi,

I am trying to compile libMesh with (Intel/Open) MPI support, but every time compilation fails with 

```
...
./.libs/libmesh_opt.so: undefined reference to `MPI_Barrier'
./.libs/libmesh_opt.so: undefined reference to `MPI_Type_commit'
./.libs/libmesh_opt.so: undefined reference to `MPI_Comm_rank'
make[1]: *** [meshavg-opt] Error 1
```

I tried to configure with option 

```
./configure --with-mpi=/apps/all/impi/5.1.2.150-iccifort-2016.1.150-GCC-4.9.3-2.25/lib64
```
I also tried it without lib64 at the end, both fails.

Any idea how can I compile it with MPI support?

**Comment by jas02** [comment]
Sorry, I just find your mailing list, sorry for this ticket.

**Comment by roystgnr** [comment]
Mailing list posts vs issues is a matter of your preference, in theory.  In practice I'd be curious as to which format ends up getting users more help.

Anyway, whichever you choose: post your configure.log somewhere we can take a look?  In particular it would be good to know whether we detected MPI directly or indirectly via PETSc.

**Comment by pbauman** [comment]
I was going to note:

If you're building with PETSc, it's usually "snooped" from PETSc. If not, assuming the Intel MPI is in your PATH, you can do

./configure CC=mpicc CXX=mpicxx

or, if you're wanting the Intel compilers underneath MPI,

./configure CC=mpiicc CXX=mpiicpc

**Comment by jwpeterson** [comment]
> post your configure.log

That's config.log, it will be located in your build directory.

**Comment by jas02** [comment]
Hi,

I solved problem with following:

```
./configure CC=mpiicc CXX=mpiicpc
```

Many thanks.

Lumír Jasiok
