### ISSUE TITLE
libMesh doesn't compile on Raspberry Pi

### ISSUE THREAD

**Issue by dschwen** [libMesh/libmesh#962]
I get errors such as these:

```
./include/libmesh/fe_type.h: In function ‘bool libMesh::operator>=(libMesh::Order, std::size_t)’:
./include/libmesh/fe_type.h:126:15: error: redefinition of ‘bool libMesh::operator>=(libMesh::Order, std::size_t)’
   inline bool operator>=(Order lhs, comparisontype rhs) \
               ^
./include/libmesh/fe_type.h:131:1: note: in expansion of macro ‘OrderWrapperOperators’
 OrderWrapperOperators(std::size_t)
 ^
./include/libmesh/fe_type.h:126:15: note: ‘bool libMesh::operator>=(libMesh::Order, unsigned int)’ previously defined here
   inline bool operator>=(Order lhs, comparisontype rhs) \
               ^
./include/libmesh/fe_type.h:130:1: note: in expansion of macro ‘OrderWrapperOperators’
 OrderWrapperOperators(unsigned int)
 ^
```

It seems to me the reason is that `sizeof(size_t) == 4` for the Arm archictecture toolchain of the Pi. This makes `size_t` equivalent to `unsigned int`, which cause the two declarations of the operators to be the same (on more common systems `sizeof(size_t) == 8` so this is not an issue).

Of course this issue is of **the utmost priority!!1!one!!eleven**

**Comment by roystgnr** [comment]
You think you're being sarcastic, but this does offend me.  Is there an easy way (Docker? Custom x86-32 gcc build? ARM cross-compiler?  QEMU?) to set up a sufficiently-similar test environment on CentOS7?

**Comment by dschwen** [comment]
And that's why you are awesome @roystgnr! Sarcasm is just a shield to protect my fragile personality. I'd really like to get MOOSE running on a Pi, if only for the LOLs. But ultimately it is a good test for "unexpected" architectures. For integer types the C++ standard only specifies a minimum size (so as far as I know `sizeof(unsigned int)` _could_ be 8 on some architectures (and again clash with `size_t`).

**Comment by dschwen** [comment]
I have used qemu before to crosscompile for arm, but that's been a while. I can get you a login on my Pi if you send me an ssh key. I'd also be happy to test any commits you make (or might even try to fix this myself).

**Comment by roystgnr** [comment]
There's another Pi geek here who's got QEMU set up on our Buildbot system.  "Raspbian" is what I should test with?

**Comment by dschwen** [comment]
Yes. I'm running Jessie. I'm working on a fix for this.

**Comment by dschwen** [comment]
Yay, it builds. FPOptimizer takes 850Mb RAM to build (out of the 1G on the Pi), so you can pretty much only compile in serial (or do `-j 4` until it fails with an _internal compiler error_ and then restart make in serial).

**Comment by jwpeterson** [comment]
Now that we have the "unobfuscated" version of that big FPOptimizer file, I wonder if it could be split up into multiple files to get around this issue.  Even on fast computers it's painful to compile. 

Also, you may want to fix your .gitconfig metadata on the Pi, your email address does not show up in the patch.

https://github.com/dschwen/libmesh/commit/384d8f177e612f4121f86de644100b16edd799bb.patch
