### ISSUE TITLE
Boundary id caches may not be accurate after BoundaryInfo::remove()

### ISSUE THREAD

**Issue by roystgnr** [libMesh/libmesh#965]
We remove ids from the maps, but not from the lists of IDs that are maintained alongside those maps.

**Comment by jwpeterson** [comment]
@roystgnr I think you've made some fixes in the vein of this Issue recently?  Can you be more specific about which lists of IDs are getting out of date?

**Comment by roystgnr** [comment]
The caches _boundary_ids, _side_boundary_ids, _edge_boundary_ids, _node_boundary_ids, and _shellface_boundary_ids are not updated when remove*() is called.

If the removed entry was the *last* entry with a particular id, then that id no longer exists in the mesh, and the corresponding 2 caches are now out of date.

I don't see how this is fixable without turning remove*() from O(1) into O(N) operations.  The only fix may be to document the failing and create some sort of rebuild_caches() method that a user can call after they're done with all their remove calls.

**Comment by roystgnr** [comment]
I've put in a BoundaryInfo fix or two but nothing related to this ticket.

**Comment by roystgnr** [comment]
Okay, now I've got a fix for this ticket.

**Comment by jwpeterson** [comment]
Pretty sure this was fixed by #1255.
