### ISSUE TITLE
Writing an ExodusII file with many subdomains and boundary_ids is very slow

### ISSUE THREAD

**Issue by dknez** [libMesh/libmesh#968]
I used mesh.write("mesh_name.exo") to write out a mesh with 547,532 elements, and with about 1,000 subdomains and boundary_ids. This took about 250 seconds. When I set all elements to be in the same subdomain, and cleared all boundary_ids, the writing took 2 seconds.

I'd be interested to see if we can optimize this "many subdomains/many boundary IDs" case.

**Comment by permcody** [comment]
What's the difference in file size? There's some amount of overhead for
creating a subdomain but it's probably not that big.

**Comment by dknez** [comment]
The difference in file size is 27MB with the subdomains and sidesets, and 26.3MB without.

**Comment by dknez** [comment]
Also, I tried this with the XdrIO writer, and the number of subdomains/boundary_ids did not affect the timing in that case.

**Comment by friedmud** [comment]
BoundaryIDs probably aren't the problem... but there is a LOT of shuffling
in the ExodusIIHelper to deal with subdomains.  It has to create separate
lists of elements that are in each subdomain and put everything in order,
etc...

You have to remember that "subdomains" mean more than just "a number for
each element" to Exodus... they are "blocks"... where each block is a
contiguous set of elements that all have the same element type.  XDR
doesn't care about this kind of thing... it just outputs elements and the
subdomain ID is simply a number that goes out with them...

Derek

**Comment by permcody** [comment]
While that's true, there's probably a simple change in the way we loop over
elements organizing them for output that could fix 90% of this slowdown.
It's worth a look.

**Comment by dknez** [comment]
Yeah, I figured this is primarily due to overhead from Exodus element blocks. If we can't optimize it further, that's not a big deal for me (switching to Xdr is a good way around this issue anyway). Nevertheless, the slowdown was larger than I would have expected so I thought it was worth bringing this up as an issue. 

FYI, here's some more timing info from the test case that I mentioned above, with different variations of including the subdomains and surfaces in the mesh that is written out:
ExodusII_IO (subdomains + surfaces): 165s
ExodusII_IO (subdomains only): 91s
ExodusII_IO (surfaces only): 66s
ExodusII_IO (neither): 0.8204s
XdrIO (subdomains + surfaces):  0.75s

Interestingly ExodusII_IO (surfaces only) still takes a while even though all elements are in one block in that case, so maybe there is some room for optimization here.

**Comment by friedmud** [comment]
Interesting!  There might be some low hanging fruit....

**Comment by rwcarlsen** [comment]
Does anyone have a good sample mesh/input file I could use to take a look at this?

**Comment by dknez** [comment]
I think the best option would be to recreate the case I described above with a simple mesh, e.g. via build_cube. I would suggest adding lots of subdomains and boundary_ids to the cube mesh and write it out. You could also compare writing out Xdr and ExodusII to see the speed difference.

I can set that up for you, if needed?

**Comment by rwcarlsen** [comment]
@dknez - If it's not too much trouble - that would be great.

**Comment by dknez** [comment]
The code below should be helpful for testing. You can view the libMesh logging output to see the timing for each mesh write. Change n_subdomains and n_boundary_ids if you want to modify the number of subdomains and sidesets. For me, the results I get with this test example as consistent with the timings I reported above. Let me know if you need anything more.

```
#include "libmesh/libmesh.h"
#include "libmesh/mesh.h"
#include "libmesh/mesh_generation.h"
#include "libmesh/exodusII_io.h"
#include "libmesh/xdr_io.h"
#include "libmesh/equation_systems.h"
#include "libmesh/elem.h"

using namespace libMesh;

int main (int argc, char** argv)
{
  // Initialize libMesh.
  LibMeshInit init (argc, argv);

  unsigned int n_elem = 750;
  Mesh mesh(init.comm());
  MeshTools::Generation::build_square (mesh,
                                       n_elem, n_elem,
                                       0., 1.,
                                       0., 1.,
                                       QUAD4);

  const unsigned int n_subdomains = 1000;
  const unsigned int n_boundary_ids = 1000;

  unsigned int next_subdomain_id = 0;
  unsigned int next_boundary_id = 0;

  MeshBase::element_iterator       el     = mesh.active_local_elements_begin();
  const MeshBase::element_iterator end_el = mesh.active_local_elements_end();

  for ( ; el != end_el; ++el)
    {
      Elem * elem = *el;

      if(next_subdomain_id < n_subdomains)
      {
        elem->subdomain_id() = next_subdomain_id;
        next_subdomain_id++;
      }

      for(unsigned int side=0; side<elem->n_sides(); side++)
        {
          if(elem->neighbor(side) == NULL)
          {
            if(next_boundary_id < n_boundary_ids)
            {
              mesh.get_boundary_info().add_side(elem, side, next_boundary_id);
              next_boundary_id++;
            }
          }
        }
    }

  mesh.print_info();

  std::cout << "Started writing xdr file" << std::endl;
  mesh.write("square.xdr");
  std::cout << "Finished writing xdr file" << std::endl;

  std::cout << "Started writing exo file" << std::endl;
  mesh.write("square.exo");
  std::cout << "Finished writing exo file" << std::endl;

  return 0;
}
```
