### ISSUE TITLE
Add contains_point specializations for simple elements

### ISSUE THREAD

**Issue by dschwen** [libMesh/libmesh#990]
Elements that are guaranteed to have flat sides, such as `TRI3` and `TET4` should have trivial geometric expressions to determine if a point is contained in them or not. Overloading `contains_point` for those should speed up this check (which is used heavily by `PointLocator`).

I'll push a draft for `TET3` that delivers a 2x speedup over the old method, which does BBOX + inverse map.

**Comment by jwpeterson** [comment]
*Ass*?

**Comment by jwpeterson** [comment]
I assume you mean `TRI3`... I was hoping it would be more than 2x.

**Comment by friedmud** [comment]
As long as you're going down this path... I would LOVE to have `volume()`
specializations for these "simple" elements as well... it's crazy just how
much time we spend calling `volume()`

**Comment by jwpeterson** [comment]
> As long as you're going down this path... I would LOVE to have `volume()`
> specializations for these "simple" elements as well... it's crazy just how
> much time we spend calling `volume()`

This has already been done.

**Comment by friedmud** [comment]
Really?  I still see `volume()` showing up a lot (like 6-7%) in my timing of my new code.  Maybe I'll take a closer look at it next time...

**Comment by jwpeterson** [comment]
> Really? I still see volume() showing up a lot (like 6-7%) in my timing of my new code. Maybe I'll take a closer look at it next time...

What type of element, and how often are you calling `volume()`?  Specializations of `volume()` for all the element types have been implemented, resulting in speedups of over 100x for some of the more expensive types.

**Comment by friedmud** [comment]
Quad4 and Hex8... I am calling it quite a bit.  I'll pay more attention next time I'm doing profiling.

Anyway - I'll quit polluting this Issue.  This particular issue gets a 👍 from me!  Should really help out a few things I'm working on right now!  (Just today I added a massive set of `contains_point()` searches to my code...)

**Comment by jwpeterson** [comment]
> Quad4 and Hex8

Those two are some of the most highly-optimized `volume()` comptations there are outside of the really simple ones like `TRI3` and `TET4`.  If they are still showing up in profiling, you might be better off caching values if possible... I don't think the actual calculations could be speeded up much more.

**Comment by friedmud** [comment]
Thanks @jwpeterson .  I've considered caching them and I might just need to do that...

**Comment by dschwen** [comment]
Looks more like a factor of 4 now.

**Comment by jwpeterson** [comment]
The original issue has been addressed for the guaranteed-affine elements, closing for now as I'm not aware of any other obvious simplifications.
